### ISSUE TITLE
Remove support for legacy encrypted private keys with 2-byte hashes

### ISSUE THREAD

**Issue by twiss** [openpgpjs/openpgpjs#1000]
There's an old format of encrypted secret keys, described at the bottom of https://tools.ietf.org/html/rfc4880#page-44, that has only a 2-byte hash instead of the usual SHA1 hash (or AEAD tag for V5 keys).

GPG has stopped exporting keys this way since 2002-04-16, unless using the `--simple-sk-checksum` option, according to its changelog. 

The spec also mentions:

> This checksum is deprecated; an implementation SHOULD NOT use it, but
> should rather use the SHA-1 hash denoted with a usage octet of 254.  The
> reason for this is that there are some attacks that involve undetectably
> modifying the secret key.

The issue is that vulnerabilities can arise not just from generating keys like this, but from accepting them as well. So, we would like to remove support for these keys.

When using OpenPGP.js to generate or encrypt keys, it has never generated these checksums. So, probably the main way someone could have keys like this is if they exported them a long time ago and stored them as-is.

This seems to me like it's probably rare. However, if someone knows that they or their users have keys like this, let me know and we can discuss some kind of migration plan.

---

As an aside, there's an even older format of encrypted keys that simply uses an unsalted MD5 hash to encrypt the key, described here: https://tools.ietf.org/html/rfc4880#page-13. As best I can tell, support for this in OpenPGP.js is already accidentally broken, and there are no test cases for this.

**Comment by larabr** [comment]
You need to use an older version of OpenPGP.js ([v4.7](https://github.com/openpgpjs/openpgpjs/tree/v4.7.2) or less) to decrypt & re-encrypt the key. The following code should work but is not tested:

```js
const passphrase = '...';
const armoredPrivateKey = '...';

const privateKey = (await openpgp.key.readArmored(armoredPrivateKey)).keys[0]
await privateKey.decrypt(passphrase);
// `privateKey` is now decrypted, re-encrypt with the same passphrase, but new encryption mechanism:
await privateKey.encrypt(passphrase);
// get armored key
console.log(privateKey.armor())
```
