### ISSUE TITLE
Use on React Native

### ISSUE THREAD

**Issue by poltak** [openpgpjs/openpgpjs#1007]
Hi there.

Has anyone had success getting this lib to work on React Native?

Adding it straight into the RN project I'm working on immediately crashes the app at load, saying it can't resolve the `crypto` module.

Looking deeper into this package I found that both the use of `crypto` and `streams` APIs seem to not be available on RN.

For `crypto`, there is a RN port here: https://github.com/tradle/react-native-crypto
For `streams`, `readable-stream` seems RN-compatible: https://github.com/nodejs/readable-stream

I ended up creating a fork of this repo, replacing the importing of the above libs with the RN-compatible ones. 

This got me past some of these errors, however I realized the `react-native-crypto` leads to an error when running the NPM `build` script, which I presume is something to do with the current grunt setup:

```
$ grunt build --compat copy:openpgp_compat && grunt build --lightweight copy:openpgp_lightweight clean:js && grunt build
Running "build" task

Running "browserify:openpgp" (browserify) task
>> Error: Parsing file ~/Documents/github/openpgpjs/node_modules/react-native-crypto/index.js: 'import' and 'export' may appear only with 'sourceType: module' (3:0)
Warning: Error running grunt-browserify. Use --force to continue.
```

I also saw some of the code to switch between using certain deps depending on whether or not it is being run in node or the browser. Perhaps adding proper support for React Native would also need an update to this code to factor in a environment.

I will add to this with further findings.

What else does anyone know that is stopping this from just working with React Native?

**Comment by poltak** [comment]
I ended up getting past the build error by adding `react-native-crypto` to the `browserify.openpgp.options.external` array so that package doesn't get bundled in the build. Also using NPM rather than yarn fxied a follow-up build issue (#926).

I'm now however stuck with the importing of the `buffer` package crashing the app at runtime. I ended up updating the `getNodeBuffer` function in `util.js` to return `undefined`, however the issue persists with that build. May be it's also be required by another dep. I've also tried adding in https://github.com/feross/buffer, without any luck

**Comment by twiss** [comment]
Hey @poltak :wave: I don't know much about React Native, but if it behaves more like a browser than like Node.js, you might have better luck trying to convince OpenPGP.js that it's running in a browser rather than that it's running in Node.js. Probably you could do this by replacing `window` with `global` everywhere in OpenPGP.js (PR welcome), or creating a fake `global.window = global` variable before loading OpenPGP.js.

**Comment by poltak** [comment]
From what I understand, it behaves different to both node and browser. You're missing lots of APIs that are available in both/either node and browsers. There seem to be lots of ports of certain APIs available for React Native, like with the streams, crypto, and buffer libs that I've linked. Unfortunately I haven't got those all working properly with this implementation of OpenPGP.

There are some other implementations of OpenPGP available for React Native, though they don't seem to be up to this project's standard of being tried-and-true. So far I've found these ones:
- https://github.com/jerson/react-native-fast-openpgp
- https://github.com/orhan/react-native-openpgp

> Probably you could do this by replacing window with global everywhere in OpenPGP.js (PR welcome), or creating a fake global.window = global variable before loading OpenPGP.js.

Unfortunately this didn't have any effect, but thanks for the suggestion.

**Comment by gabidi** [comment]
Hey @poltak , Did you ever manage to resolve this issue ?
Like you said other libs are available but non come close to the level of this one.
Would appreciate your thoughts, thanks.

**Comment by ken0x0a** [comment]
@poltak @gabidi  First of all, as I know, you will end up with 1 binary (index.bundle or something else) if you are using React Native, and the license of this library is LGPL, so it will be required to open source all of your js code with LGPL.

Could you let me know if you know any workaround for this.

I also wanted to use this functionality in RN, but I couldn't as the license.

**Comment by ken0x0a** [comment]
@openpgpjs
Thank you for this great library!

I want to use this library at React Native, but as above reason, I cannot use right now.

Is there any chance for you to change LICENSE?
Is it impossible?

**Comment by gabidi** [comment]
@ken0x0a Open sourcing the application is part of our product roadmap and is not an issue for me. Thank you for taking the time to raise that flag.

**Comment by chesnokovilya** [comment]
The library LGPL license is not preventing it from using inside proprietary software:
"A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a "work that uses the Library". Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License."

**Comment by ken0x0a** [comment]
@chesnokovilya Thank you for your answer!

Can I ask further more about it?

What you told me means:
- a work will be LGPL, if that is similar with this library;
- a work will not be LGPL, if that using this library for only some functionality of that work, and not the main functionality;

Is it correct?

**Comment by chesnokovilya** [comment]
I think it is not correct. 
Here is good explanation from wikipedia [https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License]
Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable shared library mechanism for linking". Alternatively, a statically linked library is allowed if either source code or linkable object files are provided.

**Comment by ken0x0a** [comment]
@chesnokovilya Thank you for the reply!

As I understand, I can use this library for my work.
But also, I understand that the definition of ["derivative work"](https://en.wikipedia.org/wiki/Derivative_work) differs for each person, and it's not clear whether it's safe to use for non-public work or not.

As I found another libraries with clear license, so I should use them.

Thank you so much for your help and time 🙏
