### ISSUE TITLE
Uncaught Error: Cannot find module 'stream'

### ISSUE THREAD

**Issue by dabit1** [openpgpjs/openpgpjs#1008]
Hi guys,

Inside of a service worker I import openpgp thorugh `this.importScripts('/openpgp.min.js');`. However when the service worker initiates it throws an error: `Uncaught Error: Cannot find module 'stream'`

- Create-react-app
- Chrome 78

Does anybody know why it happens?
Thanks

**Comment by chesnokovilya** [comment]
Could you provide code snippets? There is a worker implemented in the library, openpgp.worker.js has you tried to use it?

**Comment by twiss** [comment]
OpenPGP.js only does `require('stream')` if it thinks that it's in Node.js. Could you, in the browser console of your Service Worker, type `process` and see whether that object exists? Maybe your build process is polyfilling it for some reason, making OpenPGP.js believe that it's in Node.js.

**Comment by gabidi** [comment]
might be related to #1007

**Comment by twiss** [comment]
Hi :wave: We've made a prerelease of v5: https://github.com/openpgpjs/openpgpjs/releases/tag/v5.0.0-0
We now have browser-specific and Node-specific builds, and the browser build no longer ever tries to `require('stream')`. You can grab a build here: http://unpkg.com/openpgp/dist/
Let me know if this works for you :blush:
