### ISSUE TITLE
Question: How to save to a binary file?

### ISSUE THREAD

**Issue by ardimaunahan** [openpgpjs/openpgpjs#1014]
How can I save the return of the **signed** variable in a binary file?

Here's my code:
![image](https://user-images.githubusercontent.com/673492/70709175-3e021a80-1d17-11ea-9efd-240b672eeddd.png)

Here's the browser's console:
![image](https://user-images.githubusercontent.com/673492/70709256-6d188c00-1d17-11ea-8cfe-7226538eb6b8.png)

Note that I'm using Chrome browser environment and not Node.js. Would that be possible?

**Comment by twiss** [comment]
Hey :wave: The code you commented out seems like a good start.
Do you want the binary signature to contain the message itself, or not? Right now it won't, I'm guessing since you wrote `detached: false` that you want it to.
To achieve that, change `openpgp.cleartext.fromText` to `openpgp.message.fromText`, and `message.signature.packets.write()` to `message.packets.write()`.
Let me know if that's not what you want or if you have any other issues.

**Comment by ardimaunahan** [comment]
Thanks for the quick response. I applied the changes and here's what I got now:
![image](https://user-images.githubusercontent.com/673492/70715000-4ca2fe80-1d24-11ea-9e1d-14d80611dd2f.png)

What should I do next? I would like to save it to `file.pgp`. Another question though: does the `signature` contain both data and signature? That is what we need so let me know if there is a different property to look at.

**Comment by ardimaunahan** [comment]
Here's a sample signed file that we're expecting:
![image](https://user-images.githubusercontent.com/673492/70717190-cdfc9000-1d28-11ea-8a4c-743d331f2645.png)

Is this possible to be done on the browser side only?

**Comment by twiss** [comment]
> What should I do next? I would like to save it to file.pgp.

Take a look at [download.js](http://danml.com/download.html). You can make a `Blob` from a `Uint8Array`.

> Another question though: does the signature contain both data and signature?

Hard to tell, could you post your full new code again?

**Comment by ardimaunahan** [comment]
Thanks a lot, it worked! I was able to verify the signed file. 

I guess my next question would probably be is there another way aside form `download.js` to save the file? We have our own API to create file and it requires a plain text I believe. I guess what's the best practice for converting Uint8Array to string.

**Comment by twiss** [comment]
There's a deprecated FileSystem API in Chrome, and some efforts to replace it, but nothing generally supported, I believe.

> I guess what's the best practice for converting Uint8Array to base64?

`openpgp.util.Uint8Array_to_b64` should work :)

**Comment by ardimaunahan** [comment]
It all works now! Thanks a lot, really great help!
