### ISSUE TITLE
hash algorithm for signing

### ISSUE THREAD

**Issue by rushglen** [openpgpjs/openpgpjs#1015]
What is the default hash algorithm for signing? Can this be changed?
and if it is an option is this be auto-determined when checking a signature?

thanks.

**Comment by chesnokovilya** [comment]
Hey!
You could look and change it in src/config/config.js 
```
 prefer_hash_algorithm: enums.hash.sha256,
```
when you verify signature, hash algorithm would be determined from signature packet.

**Comment by rushglen** [comment]
Thanks, I thought it might have been sha1, good to know it's sha256.
