### ISSUE TITLE
Can't verify the signature, that was generated via gpg.

### ISSUE THREAD

**Issue by lurzhan** [openpgpjs/openpgpjs#1016]
Can't verify the signature, that was generated via gpg.
You could find the setup in openpgp-case.tar.gz archive.

Keys were generated using `gpg --full-generate-key` command.
Options are RSA 2048bit only for signature, no passphrase.
gpg version is:
gpg (GnuPG) 2.2.4

You can find the private key in key/test-key.asc and pub key in key/test-key.pub in the archive.
They were exported using next commands:
`gpg --armor --openpgp --output key/test-key.asc --export-secret-keys 7F690406B147E4362F7962E833A6A4E5BB711968`
`gpg --armor --openpgp --output key/test-key.pub --export 7F690406B147E4362F7962E833A6A4E5BB711968`

Also, there is a text and text.sig files.
text.sig was generated using this command:
`gpg --armor --openpgp --default-key 7F690406B147E4362F7962E833A6A4E5BB711968 --output text.sig --detach-sign text`

Finally, code itself is written in index.html in a script tag.
Could you please review this problem?
[openpgp-case.tar.gz](https://github.com/openpgpjs/openpgpjs/files/3964442/openpgp-case.tar.gz)

**Comment by chesnokovilya** [comment]
Hello, I will look at it.

**Comment by chesnokovilya** [comment]
Hey!
you could try creating message this way:
```
 const message = openpgp.message.fromBinary(openpgp.util.encode_utf8(plaintext);
 var options = {
              message: message,
              signature: await(openpgp.signature.readArmored(sig)), // parse detached signature
              publicKeys: (await(openpgp.key.readArmored(pubkey))).keys     // for verification
          };
```
it should work.

**Comment by lurzhan** [comment]
Applied your way of message creation to the code, but it still doesn't work.
You can check the diff in `openpgp.diff.txt` file
You can apply the patch to existing index.html file this way:
`patch -p0 -i openpgp.diff.txt`

[openpgp.diff.txt](https://github.com/openpgpjs/openpgpjs/files/3978656/openpgp.diff.txt)

**Comment by chesnokovilya** [comment]
Ah, It is because you are missing newline in text, it should be something like
```
      var text = `This string should be signed btw.
`;
```

**Comment by lurzhan** [comment]
Could you please, explain more?
The original message was without newline (i.e. 'This string should be signed btw.')
Is that some of OpenPGP's library requirement?

**Comment by chesnokovilya** [comment]
this is whole function doThings()
```
        async function doThings() {
          // Trying to verify gpg's detached signature .. it should work now
          var options = {
              message: openpgp.message.fromBinary(openpgp.util.encode_utf8(text)),        // CleartextMessage or Message object
              signature: await(openpgp.signature.readArmored(sig)), // parse detached signature
              publicKeys: (await(openpgp.key.readArmored(pubkey))).keys     // for verification
          };

          openpgp.verify(options).then(function(verified) {
            validity = verified.signatures[0].valid; // true
            if (validity) {
              console.log('signed by key id ' + verified.signatures[0].keyid.toHex());//should work now
            } else {
              console.log('error: could not verify text!');
            }
          });

          // Trying to verify openpgpjs's detached signature .. it works
          var options = {
              message: openpgp.cleartext.fromText(text),        // CleartextMessage or Message object
              signature: await(openpgp.signature.readArmored(detachedSig)), // parse detached signature
              publicKeys: (await(openpgp.key.readArmored(pubkey))).keys     // for verification
          };

          openpgp.verify(options).then(function(verified) {
            validity = verified.signatures[0].valid; // true
            if (validity) {
              console.log('signed by key id ' + verified.signatures[0].keyid.toHex());
            } else {
              console.log('error: could not verify text!');
            }
          });
      };```

**Comment by lurzhan** [comment]
Thanks for the help, the newline is definitely helped. It works now.
Could you, please, explain why the newline is needed considering the fact, that the original message didn't have it?

**Comment by chesnokovilya** [comment]
There is a new line in the file **text**. You could verify it by running `od -a text` in linux console, or in node
 ```var text = await fs.readFileSync('./text', 'utf8');
      lines = text.split("\n");
      console.log(lines);```

**Comment by lurzhan** [comment]
Thanks for the help!
