### ISSUE TITLE
generateKey() with compression type "none"

### ISSUE THREAD

**Issue by thjco** [openpgpjs/openpgpjs#1018]
I would like to exchange encrypted messages with someone using PGPDesktop(?). According to him the public key I sent is compressed with "ZLIB". Unfortunatelly I cannot find an option to set the compression type when using the generateKey() function. Does anyone has an idea how to turn off key compression in openpgp.js? Many thanks!

**Comment by bartbutler** [comment]
AFAIK, there is no key compression in OpenPGP so I'm not certain this diagnosis of the problem makes sense.

**Comment by tomholub** [comment]
My best guess is that the someone refers to preferred encryption algorithm setting in the pubkey sig.

https://tools.ietf.org/html/rfc4880
```
5.2.3.1.  Signature Subpacket Specification
5.2.3.9.  Preferred Compression Algorithms
9.3.  Compression Algorithms

       ID           Algorithm
       --           ---------
       0          - Uncompressed
       1          - ZIP [RFC1951]
       2          - ZLIB [RFC1950]
       3          - BZip2 [BZ2]
       100 to 110 - Private/Experimental algorithm
```
Does that mean his implementation only supports `Uncompressed`?

We set it to `zip` OR `zlib` as possible options (`uncompressed` is implicitly assumed at the end):
```js
signaturePacket.preferredCompressionAlgorithms = createdPreferredAlgos([
  enums.compression.zlib,
  enums.compression.zip
], config.compression);
```
It may be worth considering to add a third option, `enums.compression.uncompressed` at the end. Reasonable implementations should pick one of the first two (or first which fits their abilities), and lousy implementations could still fall back to the third option (most reasonable implementations would have assumed `Uncompressed` implicitly at the end, but..).

I'm reading the spec hastily. I don't see anything that would suggest that we SHOULD NOT be adding `Uncompressed` at the end explicitly. I don't know if this could have other implications, or exactly how our own implementation handles this.

@thjco can you please find out exactly which software and which version are they using?

**Comment by twiss** [comment]
Regarding symmetric algorithm preferences, the (draft) spec states

```
   Since AES-128 is the MUST-implement algorithm, if it is not
   explicitly in the list, it is tacitly at the end.  However, it is
   good form to place it there explicitly.
```
(non-draft says something similar).

And then

```
13.3.  Other Algorithm Preferences

   Other algorithm preferences work similarly to the symmetric algorithm
   preference
```

So, we definitely could (and probably should) include it. PR welcome.

**Comment by thjco** [comment]
Thanks for your feedback! The software used is "Symantec PGP Encryption Desktop" (unfortunatelly no version mentioned). The "PGP Key Generation Assistant" has "Advanced Key Settings". There you can select allowed compression types (Bzip2, ZLIB, ZIP, None) and a preferred compression (set to "No compression"). - Would be great if somebody could implement "uncompressed" :-)

**Comment by tomholub** [comment]
@thjco try to make a new key using latest version
