### ISSUE TITLE
Incorrect keyID at encrypted message

### ISSUE THREAD

**Issue by catap** [openpgpjs/openpgpjs#1021]
Hey,

I guess I found a bug that encrypted message has incorrect keyID for that it is encrypted.

I've tested it in my browser: Safari 13.0.4 (15608.4.9.1.3) with OpenPGP.js 4.7.1

Test case:
```js
let generateKeyOptions = {
    userIds: [{ name:'Jon Smith', email:'jon@example.com' }],
    rsaBits: 4096,
    passphrase: ''
};

let keyPair = await openpgp.generateKey(generateKeyOptions);

let publicKeys = await openpgp.key.readArmored(keyPair.publicKeyArmored);

if (publicKeys.keys[0].getKeyId().toHex() !== keyPair.key.getKeyId().toHex()) {
    throw "keyID at keyPair != publicKeys";
}

let encryptOptions = {
    message: openpgp.message.fromText('Hello, World!'),
    publicKeys: publicKeys.keys,
    armor: false
};

let ciphertext = await openpgp.encrypt(encryptOptions);

if (keyPair.key.getKeyId().toHex() !== ciphertext.message.getEncryptionKeyIds()[0].toHex()) {
    throw "keyID at keyPair != ciphertext";
}
```

Expected behaviour: it shouldn't throw at all.

How it works at my browser:
<img width="1280" alt="Screenshot 2019-12-20 11 54 51" src="https://user-images.githubusercontent.com/37775/71250315-a35d9900-231f-11ea-9b99-1c1f7defd39a.png">

**Comment by chesnokovilya** [comment]
Well, inside pgp key, there is a special keys for encryption and signing. Have you checked
```keyPair.getEncryptionKey().getKeyId().toHex() == ...```

**Comment by catap** [comment]
@chesnokovilya, thanks!

I forgot about dedicated key for encryption and signing.
