### ISSUE TITLE
NodeJS Compatibility Issue

### ISSUE THREAD

**Issue by NicoBougrand** [openpgpjs/openpgpjs#1035]
Hello,
In the official office platform, we are still using NodeJS 8.
But some dependencies of openpgp seems to not be compatible with this node.

Is there a way to use openpgp in nodeJs 8? 

Regards
Nicolas

**Comment by twiss** [comment]
Hey :wave: We still run our CI tests on Node.JS 8 among others: https://travis-ci.org/openpgpjs/openpgpjs/jobs/637005324#L208
So it should be possible to use OpenPGP.js there. What issue are you having?

**Comment by NicoBougrand** [comment]
I have the following error trace.
npm ERR! C:\Users\NG838E1\AppData\Local\Programs\Git\mingw64\bin\git.EXE ls-remote -h -t ssh://git@github.com/openpgpjs/asmcrypto.git
npm ERR!
npm ERR! ssh_exchange_identification: read: Connection reset by peer
npm ERR! fatal: Could not read from remote repository.

Happening only on Node8. (Node 8.9.4).
Not happening on Node10 (10.16.0)

**Comment by twiss** [comment]
You could try adding OpenPGP.js as a dependency of another project, and then installing that, or running `npm install --only=production` (since asmcrypto.js is only listed as a devDependency).

**Comment by NicoBougrand** [comment]
Ok I have to see that.
Because I am not sure I have the possibility to change the configuration in production.
The build is done with openshift, by mounting a pod, and I think I can't change the way npm is launch...
I will check.
Many thanks

**Comment by NicoBougrand** [comment]
But locally running the --only=production still fails :(

**Comment by twiss** [comment]
With the same error? That's strange.

You could just copy+paste the `dist/openpgp.js` file and `require()` that. You'll probably need to manually install the `asn1.js` dependency but the other things you don't really need.

**Comment by NicoBougrand** [comment]
OK thanks I will try to do that

**Comment by twiss** [comment]
This should be fix v4.10.2, I think.
