### ISSUE TITLE
Native ReadableStream can not be decrypted on Firefox

### ISSUE THREAD

**Issue by nwtgck** [openpgpjs/openpgpjs#1037]
Hi, developers. Thank you very much for your great project!

## Problem
Decryption of `ReadableStream` has an error "Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format." on Firefox. In Google Chrome, it works well.

## Reproducible code
Here is a reproducible code.

```js
(async ()=>{
  // GET "hello.txt.gpg"
  const res = await fetch("https://gist.githubusercontent.com/nwtgck/4d43a34ec27143f423ee653c77e9c854/raw/18b48917bbbfd2138add83f532ac7b9abd1d80a5/hello.txt.gpg");
  // Decrypt
  const rawStream = await (async () => {
    const options = {
      message: await openpgp.message.read(res.body),
      passwords: ['mypassword'],
      format: 'binary'
    };
    openpgp.config.allow_unauthenticated_stream = true;
    const plaintext = await openpgp.decrypt(options);
    return plaintext.data;
  })();
  
  // Read decrypted data
  const decrypted = [];
  const reader = rawStream.getReader();
  while(true) {
    const {done, value} = await reader.read();
    if (done) break;
    decrypted.push(...value);
  }
  // Show decrypted data
  console.log(decrypted);
  // expectation: [104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 10]
  // (it means "hello, world\n")
})();

```

### CodePen
You can try it on CodePen on Chrome and Firefox.
https://codepen.io/nwtgck/pen/yLyGwmj?editors=1011

### Chrome

In Chrome (79.0.3945.117 on macOS), the output is my expectation. It means "hello, world\n" as binary.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/10933561/72896770-cc7ca980-3d63-11ea-920a-17993447419b.png">

### Firefox

In Firefox (72.0.1 (64-bit) on macOS), I had the following error.
<img width="721" alt="image" src="https://user-images.githubusercontent.com/10933561/72896857-fc2bb180-3d63-11ea-9207-1edf358100f6.png">

The version of OpenPGP.js is the latest: 4.8.0.

**Comment by nwtgck** [comment]
In my experiment, `await reader.peekBytes(2)` in `openpgp/src/packet/packet.js` returns `[object ReadableStream]`, not `Uint8Array`. 

<img width="721" alt="e7eb19adac126c7035dc0ac61976b6ac" src="https://user-images.githubusercontent.com/10933561/72897785-1c5c7000-3d66-11ea-8be2-60ad10158107.png">

**Comment by twiss** [comment]
Hey :wave:

For now, you could use https://github.com/MattiasBuelens/web-streams-adapter to convert from a native stream to a polyfilled stream.

In the future, we should probably do that inside OpenPGP.js, in order to support native streams directly.

**Comment by nwtgck** [comment]
@twiss Thanks! I didn't know web-streams-adapter. I hope OpenPGP.js supports native streams directly because this project is essential!

**Comment by nwtgck** [comment]
@twiss I confirmed `@mattiasbuelens/web-streams-adapter` works for me in my project. Thanks.

---

For future visitors, here is my changes to support stream decryption for Firefox: <https://github.com/nwtgck/piping-ui-web/commit/81b0949ec2602c4399e24037e59e9c8265e9d63e>. I hope it help you.
