### ISSUE TITLE
readArmored throws "Error: Improperly formatted armor header"

### ISSUE THREAD

**Issue by JustusL** [openpgpjs/openpgpjs#1038]
Hello, 

I'm currently trying to implement a simple encrypt function using openpgp.js. When trying to set the publicKeys variable in the options for the encrypt function I get the following error:

![Bildschirmfoto 2020-01-24 um 12 32 08](https://user-images.githubusercontent.com/34372092/73066212-af4ff400-3ea5-11ea-9857-d4ed3cea325c.png)

Logging the result of readArmored shows that there has happened the following error:

![Bildschirmfoto 2020-01-24 um 12 32 25](https://user-images.githubusercontent.com/34372092/73066267-d1497680-3ea5-11ea-8eac-88b2fc6148fe.png)

My code currently looks like this and the given public key was generated before using the openpgp.js generateKey function.

![Bildschirmfoto 2020-01-24 um 12 34 54](https://user-images.githubusercontent.com/34372092/73066631-d529c880-3ea6-11ea-8079-cdd7a415e733.png)

Thanks in advance and I hope to be able to find a solution as fast as possible.

**Comment by twiss** [comment]
Hey :wave: It's a bit hard to tell but is your code indented, perhaps? There needs to be no leading whitespace.

**Comment by JustusL** [comment]
Thanks for your response. I followed the example from the ReadMe and put the key string into backticks (``) to avoid errors caused by spaces or tabs so I think that shouldn't be a problem.

**Comment by twiss** [comment]
Yeah, some examples in the readme make the same mistake, they are wrong.

**Comment by JustusL** [comment]
Thank you so much. So the solution really was to put every line in normal quotes and add a linebreak at the end. Now everything is working like it should :)

Example of the solution:
```
var pubkey = 
"-----BEGIN PGP PUBLIC KEY BLOCK-----"+"\n"+
"Version: OpenPGP.js v4.8.0"+"\n"+
"Comment: https://openpgpjs.org"+"\n"+
""+"\n"+
"xsFNBF4um0kBEADaOlS5ggdV8GrIGaFT+53c1ZntOVwFKyQhvl0L5sHFNccl"+"\n"+
...
```
