### ISSUE TITLE
How to use file streams properly

### ISSUE THREAD

**Issue by kirbyfu** [openpgpjs/openpgpjs#1039]
I'm trying to use use openpgp with read/write streams to address memory limitations in our system. I'm not well versed with streams and would like some pointers.

I tried copying [this example](https://github.com/openpgpjs/openpgpjs/blob/master/README.md#streaming-encrypt-uint8array-data-with-a-password) in your docs as much as possible but found that `ciphertext.message.packets.write()` was returning an Uint8 Array instead of a ReadableStream.

In the v2 function, I changed `armor` to true and using `ciphertext.data` instead to get a ReadableStream but when I pipe it to my WriteStream, I end up going from a 160MB input file to a 861 byte file so I'm clearly missing something here.

```javascript
const fs = require('fs');
const openpgp = require('openpgp');
const util = require('util');

const readFileAsync = util.promisify(require('fs').readFile);

const encryptFilev1 = async (inputFile, outputFile) => {
  await openpgp.initWorker({});
  const readableStream = fs.createReadStream(inputFile);
  const writeStream = fs.createWriteStream(outputFile);

  const pubKey = await readFileAsync('./pgp/public_key.txt');
  const options = {
    message: openpgp.message.fromBinary(readableStream),
    publicKeys: (await openpgp.key.readArmored(pubKey)).keys,
    armor: false,
  };

  const ciphertext = await openpgp.encrypt(options);
  const encrypted = ciphertext.message.packets.write(); // get raw encrypted packets as ReadableStream<Uint8Array>

  encrypted.pipe(writeStream);
};

const encryptFilev2 = async (inputFile, outputFile) => {
  await openpgp.initWorker({});
  const readableStream = fs.createReadStream(inputFile);
  const writeStream = fs.createWriteStream(outputFile);

  const pubKey = await readFileAsync('./pgp/public_key.txt');
  const options = {
    message: openpgp.message.fromBinary(readableStream),
    publicKeys: (await openpgp.key.readArmored(pubKey)).keys,
    armor: true,
  };

  const ciphertext = await openpgp.encrypt(options);
  const encrypted = ciphertext.data;

  encrypted.pipe(writeStream);
};

encryptFilev1('./input.zip', './output.pgp');
// TypeError: encrypted.pipe is not a function

encryptFilev2('./input.zip', './output.pgp');
// input file: 159.9MB zip file
// output file: 861 bytes
```

**Comment by twiss** [comment]
Hey :wave: For your first example, the issue is not that it's returning a Uint8Array, but that it's returning a Web Stream instead of a Node Stream. Try doing:
```js
const nodeStream = openpgp.stream.webToNode(ciphertext);
```
and piping that. (openpgp.encrypt does that automatically for streams that it returns directly, as in your second function.)

For your second function, I think it's working fine, but probably it's stopping too soon because of the error thrown by the first function? Does it work if you run the second function by itself?

**Comment by kirbyfu** [comment]
Thanks, the first example does work once I convert it to a Node Stream. As you suspected, the second function was stopping too soon because I needed to wrap my streams in a Promise in both functions.

So the final result was this:
```javascript
const encryptFilev1 = async (inputFile, outputFile) => {
  const readableStream = fs.createReadStream(inputFile);
  const writeStream = fs.createWriteStream(outputFile);

  const pubKey = await readFileAsync('./public.asc');
  const options = {
    message: openpgp.message.fromBinary(readableStream),
    publicKeys: (await openpgp.key.readArmored(pubKey)).keys,
    armor: false,
  };

  const ciphertext = await openpgp.encrypt(options);
  const encrypted  = ciphertext.message.packets.write();

  const stream = await openpgp.stream.webToNode(encrypted);
  return new Promise((resolve, reject) => {
    stream.once('error', reject);
    writeStream.once('finish', resolve);
    writeStream.once('error', reject);
    stream.pipe(writeStream);
  });
};

const encryptFilev2 = async (inputFile, outputFile) => {
  await openpgp.initWorker({});
  const readableStream = fs.createReadStream(inputFile);
  const writeStream = fs.createWriteStream(outputFile);

  const pubKey = await readFileAsync('./public.asc');
  const options = {
    message: openpgp.message.fromBinary(readableStream),
    publicKeys: (await openpgp.key.readArmored(pubKey)).keys,
    armor: true,
  };

  const encrypted = await openpgp.encrypt(options);
  const ciphertext = encrypted.data;

  return new Promise((resolve, reject) => {
    ciphertext.once('error', reject);
    writeStream.once('finish', resolve);
    writeStream.once('error', reject);
    ciphertext.pipe(writeStream);
  });
};
```

So many thanks, I think everything is working now!

But if you have time, I have a few more small questions:

Regarding the variable names `encrypted` and `ciphertext`, I noticed that in [this example](https://github.com/openpgpjs/openpgpjs#streaming-encrypt-uint8array-data-with-a-password)
```javascript
const ciphertext= await openpgp.encrypt(options)
const encrypted = ciphertext.message.packets.write()
```

whereas in the [next example](https://github.com/openpgpjs/openpgpjs#streaming-encrypt-and-decrypt-string-data-with-pgp-keys), we have:
```javascript
const encrypted = await openpgp.encrypt(options);
const ciphertext = encrypted.data;
```

Was swapping the variable names around like that intentional given the different options passed into `openpgp.encrypt`? I wasn't sure so I mimicked the example's names in my functions above.

Finally, I'm also curious if it's possible to use `web-stream-tools` to `await` the pipeline instead of returning a Promise. For the first function, I tried this which didn't write anything to my output file:
```javascript
  await openpgp.stream.pipe(encrypted, writeStream);
```

and this which says that `getWriter` is not a function despite it being mentioned [here](https://openpgpjs.org/web-stream-tools/global.html#getWriter)
```javascript
  const writer = openpgp.stream.getWriter(writeStream);
  await openpgp.stream.pipe(encrypted, writer);
```

**Comment by twiss** [comment]
Are you sure that, if you run only one of the functions, without the `return new Promise` but just a plain `encrypted.pipe(writeStream)`, that it doesn't work? That works for me.

Regarding the naming, I think it wasn't intentional. To me, the second example makes more sense. Alternatively, you could do
```js
const { data: encrypted } = await openpgp.encrypt(options);
encrypted.pipe(writeStream);
```
to sidestep the issue :)
I'll try to clean up the examples in the readme a bit.

**Comment by kirbyfu** [comment]
I tried again today without returning a Promise and using the plain pipe and it did indeed output the correct file. But since I was trying to await my `encryptFile` function before doing other things to the encrypted file, I needed to make sure the pipe completed its operation so I thought wrapping it in a Promise was the way to go.

**Comment by twiss** [comment]
I see. No, the openpgp stream util functions can't really help with that, since mostly they're meant to be used with Web Streams, not Node Streams. So I think your solution is the way to go, then.

**Comment by kirbyfu** [comment]
Sorry to bother, I noticed that I an input ~150MB file was outputting a small file (~532 bytes) again even when returning the Promise. After questioning my sanity, it seems the output file behaviour changes depending on which Public Key file I used.

When I used a Public Key that I generated just for testing this, it output the file correctly. However, when I used the actual Public Key for my service, it was outputting the small file.

I would imagine my actual Public Key is valid since it was being used to encrypt files before correctly without filestreams. I also checked the file permissions of both and they're the same so I'm not sure what to do now.

Testing Public Key
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Keybase OpenPGP v1.0.0
Comment: https://keybase.io/crypto

xo0EXjD0QwEEAKt3jnsAlAi+kW/BPmcFqwLCTMKitxoQdYyCOyz1QoatWL+9SdSm
HfwQd1p33Lef5xDB7kaYfY/H9iep8vDOf2XRvvQtZaxq0CsSVig/sasuAVya+qPc
5TMfd0kDPC8xQ1danSclts+2Cz+/0mSQKPzPXDCKjM6FgMVhCB7YDstfABEBAAHN
EVNVcCA8U3VwQHN1cC5jb20+wq0EEwEKABcFAl4w9EMCGy8DCwkHAxUKCAIeAQIX
gAAKCRBdzcEI0c4Fo2VzBACnhYXFuYTV2r2I4GRIozQDDf9qmfKXVRqP01atom6h
OHkDPl9coPVIBLtca2CoPMWYez2GDGE9oME1Mq12ONEmaYyfGNuTqop2DJ3Q3qDn
rX6brZ7++Vp+VtHf1IGzeVRv1SaeA3VV+YKSO/97tFd1UupW0MY/mKkWy3TLdPmW
us6NBF4w9EMBBAC94Shc52pvxZVK0bKxhxg7zTeJbAihXEdLKrk9+3qwyxVtDbJ5
8RDKvq9D2d85G+z53FsRCnCT6sxAocBVWkzvnvsWX+o2ATxbLf3eMg7ka+Z+pQjh
74w43rH3X9ew1RC4cltm9jisu8b2rfaWsfHipXeFOl+EqMqWq/cBfEO8UQARAQAB
wsCDBBgBCgAPBQJeMPRDBQkPCZwAAhsuAKgJEF3NwQjRzgWjnSAEGQEKAAYFAl4w
9EMACgkQ/PBv9IQB82ovtwP/WjIAsz2d1iLiib2md6tb5QHZPesvl9VYO1wB7pKN
skvN50GqzXZvgKjrGCPMomqpsG0dOlmS4rwmo6hajp729iM0iRz6Xq4Z+0Qy8Evr
juymCH1PJNWd9AUVdXymRyTx66gqtIgRxUDT3Lw8PW4wE3KEDI00cLEuagPzZ7Gj
xWaBnwP8CdMkbdoQ4OB040JXr2Tt2BRnpYhXpGULAReSTBP0VsGEOWpY3BGyz+/9
T3w6hejx63xvSapLvAXWdnV81bvVG3DLLvhQnL1b9xazKQSyj3qbKmHUdyIkXuZo
F9INxo0mAJOVhDZakX35TabNWEsB3WD1JSZqmesTwkjmSKZQCOzOjQReMPRDAQQA
wCxU5qHllcJfWwx6wC7JVlQrt3dNCEZzoK8WKqBgCJP1HT6C6t9MzJNmEARzTcT+
PTCVpQGLUWIQ+F6TN2U1oY+wgysFD+hcNw1m+KSfPR+UAsW0b+CDRGoCNSbyCOb9
ARKcWg9ZEm78tDZqzYqTBwJUnG7dXxJYNPNA6Tp47ssAEQEAAcLAgwQYAQoADwUC
XjD0QwUJDwmcAAIbLgCoCRBdzcEI0c4Fo50gBBkBCgAGBQJeMPRDAAoJEFMoOfen
sGixT08D/1MNbOzrJAH3XnKk9lHmCW40dgMyMlR4tH01ocsT0RT+bVF9QHQVron2
yK0wOCzSO+vrgdh9JRp5KlwWzShuG99yKksOc1uhPDtj17NG9MHYf7wP4uEmFR0C
mkmT+Oyg8RXLOnPCGIcdE4znrxUA9sektO5Cc5y/0qQ7Zj2gehagyt4D/jYn6oge
mLm+6mXngbZMgj6KgyiBrhcoWODTW32IOZFy7xfMICfPU0LK2ryBwukeKcsWnDN5
7zaQwVM1Mmj/3wLbYAL20p5wm+plNXTftygBszUC6LUgtMpVXyVS3wx82l/n64pV
cRXrdA62FuilZc6mfAiJemAPqwDRynCVWCTS
=ev60
-----END PGP PUBLIC KEY BLOCK-----

```

Actual Public Key
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: PGP Personal Privacy 6.5.8

mQGiBD5CaFsRBADQ35cnqJrHuT6jkVnmohuGaM8CBoIKZM1Oa1kLPKqKmOb+S5IP
gZKl4d3BKO8c7P3oJJmsg9EfplE0yvIlZlBdhkP1bDw0RRPvfJ/Ow9i2w3WfDU72
LygRz2J+l/83Yf4KP11+0uAZian1aTv0XU3661jyew9vRdeahOsu4DOmBQCg/+UZ
FKkr7RqzX1YtMqrEmn+SYW0EAL6SoY2qhbkp5w0O1WkSXnMKEdFKaKOrMHJ0YcpI
u+zbKybT+jzSzxFIJjL88QB8qhsZ5IkZcrZZfW4Z96YQbVfJw6blsquqU0TDONbJ
WIbHcP8nWqTbu5kLhuxAXlyq8dUFhjCroYyPkg7u7xgIDuJvrKXv7I2jB/v6lM16
wRq5A/0bDAvl/5oVp9wZ9F51abd5Z9on29C5qKLzBhT5O63yRounMGF8Zz5jyeUR
Du2BfV+ZK0co7nIFQuWRLDc1vsZyF4gJgOlRxrwR2w4vNARoSo/V9f1OoJA2vCWQ
ucyD8VBt64DHGgBs5nzDaCf/ByGhrm1/0nDp/OwV5vtKVhyd0LQRQ29tcHV0ZXJz
aGFyZSBGVFCJAE4EEBECAA4FAj5CaFsECwMCAQIZAQAKCRCFrG2zxuCQgcgmAKDw
Xrj1AdXig1yRk6oEnoiQsWrNZQCg/TFtmwBvsTCWilkqo8Av6Y1Rs7O5Ag0EPkJo
WxAIAPZCV7cIfwgXcqK61qlC8wXo+VMROU+28W65Szgg2gGnVqMU6Y9AVfPQB8bL
Q6mUrfdMZIZJ+AyDvWXpF9Sh01D49Vlf3HZSTz09jdvOmeFXklnN/biudE/F/Ha8
g8VHMGHOfMlm/xX5u/2RXscBqtNbno2gpXI61Brwv0YAWCvl9Ij9WE5J280gtJ3k
kQc2azNsOA1FHQ98iLMcfFstjvbzySPAQ/ClWxiNjrtVjLhdONM0/XwXV0OjHRhs
3jMhLLUq/zzhsSlAGBGNfISnCnLWhsQDGcgHKXrKlQzZlp+r0ApQmwJG0wg9ZqRd
QZ+cfL2JSyIZJrqrol7DVekyCzsAAgIIANQH/jaoSYoJkPb+R5EGF7k42v8VasT7
C/8owSZdAMn4yqcpjkW3sLGteEduvYbZd/VjWRLBj/mpIDukoObvKAq1Pr0RraFd
SKiKSiI3MCnEe8t5xme9q79nMmSQs0kqcbzn41/0IN7LSzvEfTQIWeOncPnfKiEf
KclwxMV9fztkU5Su2KC/NRJTUBN+W0YHbdCnzrX7bJ3Yu6JCIvkOYgBwLfvnkxPm
X0mgGSI8ytR4xSAdblFizdiH2GBxaRsp+5VZrTCsZtssC16pHjk4Pk/YTz9FYMvG
2W7E0nCCi+WMf+P9nhIT4sfuk6dbG+TdTFGleOCX247V8e1DjV3SDSmJAEYEGBEC
AAYFAj5CaFsACgkQhaxts8bgkIEVPwCgoWHL0lUt0BTAkegKJzFlZDLlJM8An01j
oaDUwMnF0I2H6+5SQapMmS+T523
=RaRO
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by kirbyfu** [comment]
If it helps you reproduce this behavior, I uploaded this:
[openpgp_test.zip](https://github.com/openpgpjs/openpgpjs/files/4133147/openpgp_test.zip)

Inside `app.js`, I have 2 functions that I was testing:
- `encryptFileInMemoryBinary` - encryption in memory
- `encryptFileStreamBinary` - encryption with streams

First I check these 2 functions with my RSA keys and manage to encrypt a file and decrypt it successfully.

I then use the DSA key and find that `encryptFileInMemoryBinary` outputs a file of a reasonable size while `encryptFileStreamBinary` outputs an impossibly small file.

**Comment by twiss** [comment]
Yeah, this is a bug. The issue is that the DSA key specifies `CAST5, 3DES, IDEA` as its preferred symmetric algorithms (no AES). So, OpenPGP.js tries to stream-encrypt with CAST5, but this was never implemented. We'll fix that.

Alternatively, the draft version of the spec says that AES128 must be implemented, and should be considered as always implicitly included in the preferred algorithms, so we may, in the future, take that as license to use AES128 anyway in this case.

To do so now, you could:
```js
    const pubKeyObj = (await openpgp.key.readArmored(pubKey)).keys[0];
    pubKeyObj.users[0].selfCertifications[0].preferredSymmetricAlgorithms = [];

    // ...
        publicKeys: [pubKeyObj],
    // ...
```

Could you perhaps let me know whether the software that you'll use to decrypt the message accepts the message (encrypted with AES128), if you try that?

But actually, even if it works, I would recommend to create a new key - this is a 1024-bit DSA key, it is not very secure. Also

> Version: PGP Personal Privacy 6.5.8

this software is very old, I would recommend to switch to something newer, like GnuPG 2.

**Comment by kirbyfu** [comment]
Can confirm that the new version works. Can't thank you enough for such a fast response over the weekend.

Unfortunately, the public key belongs to another vendor who have let us know they don't have much bandwidth to do things at the moment. The key is for an SIT environment so I'll see if I can convince them to create a more secure key before we reach production.
