### ISSUE TITLE
Update lodash to 4.17.15 for security

### ISSUE THREAD

**Issue by nwtgck** [openpgpjs/openpgpjs#1045]
Hi,

Could you update lodash in npm-shrinkwrap.json? lodash currently used in this project has vulnerabilities. I think you can just run `./update_deps.sh`.

https://github.com/openpgpjs/openpgpjs/blob/de6ab1db49b2ab3fb169c0995b355eb301ce53e9/npm-shrinkwrap.json#L5251-L5256

Here are details.
<p><em>Sourced from The GitHub Security Advisory Database.</em></p>
<blockquote>
<p><strong>Critical severity vulnerability that affects lodash, lodash-es, lodash-amd, lodash.template, lodash.merge, lodash.mergewith, and lodash.defaultsdeep</strong>
Affected versions of lodash are vulnerable to Prototype Pollution.
The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.</p>
<p>Affected versions: &lt; 4.17.12</p>
</blockquote>
<p><em>Sourced from The GitHub Security Advisory Database.</em></p>
<blockquote>
<p><strong>Moderate severity vulnerability that affects lodash</strong>
lodash prior to 4.7.11 is affected by: CWE-400: Uncontrolled Resource Consumption. The impact is: Denial of service. The component is: Date handler. The attack vector is: Attacker provides very long strings, which the library attempts to match using a regular expression. The fixed version is: 4.7.11.</p>
<p>Affected versions: &lt; 4.17.11</p>
</blockquote>
<p><em>Sourced from The GitHub Security Advisory Database.</em></p>
<blockquote>
<p><strong>High severity vulnerability that affects lodash, lodash-es, lodash-amd, lodash.template, lodash.merge, lodash.mergewith, and lodash.defaultsdeep</strong>
Affected versions of lodash are vulnerable to Prototype Pollution.
The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.</p>
<p>Affected versions: &lt; 4.17.13</p>
</blockquote>
<p><em>Sourced from <a href="https://github.com/nodejs/security-wg/blob/master/vuln/npm/493.json">The Node Security Working Group</a>.</em></p>
<blockquote>
<p><strong>Denial of Service</strong>
Prototype pollution attack (lodash / constructor.prototype)</p>
<p>Affected versions: &lt;4.17.11</p>
</blockquote>
<p><em>Sourced from The GitHub Security Advisory Database.</em></p>
<blockquote>
<p><strong>Low severity vulnerability that affects lodash</strong>
A prototype pollution vulnerability was found in lodash &lt;4.17.11 where the functions merge, mergeWith, and defaultsDeep can be tricked into adding or modifying properties of Object.prototype.</p>
<p>Affected versions: &lt; 4.17.11</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/lodash/lodash/commit/ddfd9b11a0126db2302cb70ec9973b66baec0975"><code>ddfd9b1</code></a> Bump to v4.17.15.</li>
<li><a href="https://github.com/lodash/lodash/commit/b185fcee26b2133bd071f4aaca14b455c2ed1008"><code>b185fce</code></a> Rebuild lodash and docs.</li>
<li><a href="https://github.com/lodash/lodash/commit/be87d303941222b97c482755afc0f4a77ce46c30"><code>be87d30</code></a> Bump to v4.17.14.</li>
<li><a href="https://github.com/lodash/lodash/commit/a6fe6b1e174fd02b5e60eb2664405f4c1262c300"><code>a6fe6b1</code></a> Rebuild lodash and docs.</li>
<li><a href="https://github.com/lodash/lodash/commit/e37182845f16715a0d1c391c8662d83c55609cee"><code>e371828</code></a> Bump to v4.17.13.</li>
<li><a href="https://github.com/lodash/lodash/commit/357e899e685872b4af5403ecc4b2a928f961ae63"><code>357e899</code></a> Rebuild lodash and docs.</li>
<li><a href="https://github.com/lodash/lodash/commit/fd9a062d57646450b61f74029315abd4cc834b08"><code>fd9a062</code></a> Bump to v4.17.12.</li>
<li><a href="https://github.com/lodash/lodash/commit/e77d68121ff00ba86b53eed5893d35adfe94c9dd"><code>e77d681</code></a> Rebuild lodash and docs.</li>
<li><a href="https://github.com/lodash/lodash/commit/629d1865793182cd967196716f4beff223aa4a91"><code>629d186</code></a> Update OpenJS references.</li>
<li><a href="https://github.com/lodash/lodash/commit/2406eac542b2a1282be8d812a6d8a45433ade80a"><code>2406eac</code></a> Fix minified build.</li>
<li>Additional commits viewable in <a href="https://github.com/lodash/lodash/compare/4.17.10...4.17.15">compare view</a></li>
</ul>

(source: https://github.com/nwtgck/piping-ui-web/pull/253#issue-374613410)

**Comment by chesnokovilya** [comment]
thanks! This will remove the vulnerability https://github.com/openpgpjs/openpgpjs/pull/1060

**Comment by nwtgck** [comment]
@chesnokovilya Thank you very much. 

Do you have a plan to use [Dependabot](https://dependabot.com/)? The bot can bump up dependencies and make pull requests.
