### ISSUE TITLE
Can i provide a raw key for AES256 encryption?

### ISSUE THREAD

**Issue by BobbyTable** [openpgpjs/openpgpjs#1050]
I see that i can symmetrically encrypt with a "passwords: []" parameter, but is there any method for using an array of raw bytes as the key for encryption/decryption?

**Comment by twiss** [comment]
Hey :wave: Yes, you can. One way of doing this is passing `sessionKey: { data: new Uint8Array([...]), algorithm: 'aes256' }` to `openpgp.encrypt`. For `decrypt`, the option is called `sessionKeys` (plural), and you can pass the same object or an array of them.

**Comment by BobbyTable** [comment]
Thanks for the promt reply! Great work on this library
