### ISSUE TITLE
Horizon 2020 Framework Programme funding?

### ISSUE THREAD

**Issue by terrafrost** [openpgpjs/openpgpjs#1051]
This isn't really a support request but I'm not sure where else to ask this lol.

Anyway, at the top right of https://openpgpjs.org/ it says "_This project is supported by the Horizon 2020 Framework Programme of the European Union_". I have an open source crypto library myself (in PHP). How do I get in on the 2020 Framework Programme of the European Union?

Thanks!

**Comment by twiss** [comment]
Hey :wave: OpenPGP.js is supported indirectly, via ProtonMail. My guess is that a crypto library by itself might be too low-level to receive funding. That being said, I can't really help you better than their own website can: https://ec.europa.eu/programmes/horizon2020/node/115.
