### ISSUE TITLE
Does key stretching occur when using 'passwords' option?

### ISSUE THREAD

**Issue by nin-o** [openpgpjs/openpgpjs#1055]
For example, should we use PBDKF2 on `secret stuff` before calling `encrypt()`? Or does openpgpjs do this for us already?

```
 const { message } = await openpgp.encrypt({
        message: openpgp.message.fromBinary(new Uint8Array([0x01, 0x01, 0x01])),
        passwords: ['secret stuff'],
        armor: false
    });
```

Thank you!

**Comment by twiss** [comment]
Hey :wave: Yes, some key stretching does occur, and can be configured to some extent, see [openpgp.config.s2k_iteration_count_byte](https://openpgpjs.org/openpgpjs/doc/module-config.html#.s2k_iteration_count_byte). However, if you can use the implementation of PBKDF2 provided by Web Crypto with a high iteration count, that probably provides more security per performance than the key stretching defined by OpenPGP, so I would still do so, anyway.
