### ISSUE TITLE
[Idea] Generate private/public key in different format (for example as a UInt8Array)

### ISSUE THREAD

**Issue by Asphiii** [openpgpjs/openpgpjs#1057]
I think it would be a great idea if OpenPGP could generate keys in different formats, not only as a PEM. I'm facing a lot of trouble with converting it to a different format, so it would be very helpful.

**Comment by twiss** [comment]
Hey :wave: Why do you want a different format? Do you want to avoid the overhead of base64, or?

Anyway, you can export a PGP key as a Uint8Array as follows:
```js
const { key } = await openpgp.generateKey({ ...options });
const binary = key.toPacketlist().write();
console.log(binary);
```

**Comment by Asphiii** [comment]
Thank you I will check it out!
