### ISSUE TITLE
Simple speed-up for Chrome in jsbn.js

### ISSUE THREAD

**Issue by maxtaco** [openpgpjs/openpgpjs#106]
There is some pretty ancient code in jsbn.js:

``` javascript
if(j_lm && (compat.get_navigator().appName == "Microsoft Internet Explorer")) {
       BigInteger.prototype.am = am2;
       dbits = 30;
}
else if ( j_lm && (compat.get_navigator().appName != "Netscape")) {
       BigInteger.prototype.am = am1;
       dbits = 26;
}
else { // Mozilla/Netscape seems to prefer am3
       BigInteger.prototype.am = am3;
       dbits = 28;
}
```

For modern browsers (Chrome/Safari/Mozilla), you wind up in the 2nd branch, but I find it faster in Chrome to wind up in the third (`dbits=28`).  For me, the fix is just to eliminate the first two branches. 
##

**Comment by mahrud** [comment]
Closing this, as we've removed jsbn in favor of bn.js: #654.
