### ISSUE TITLE
How to check if an encrypted message is encrypted with a specific public key?

### ISSUE THREAD

**Issue by SomaSomYT** [openpgpjs/openpgpjs#1066]
I tried to check the documentation but I am not succeeded finding the solution.
What i want to achive is:
- Check the encrypted message's recipient's fingerprint.

I tried to find the solution everywhere without success.

**Comment by tomholub** [comment]
Hello, this worked well:
```js
const msg = await openpgp.message.readArmored('-----BEGIN ...');
console.log(msg.getEncryptionKeyIds());
```

**Comment by SomaSomYT** [comment]
Thanks its working however i get this output:
`[ Keyid { bytes: 'M§\'\u001eL«Ke' } ]`
And how can I convert it into this?
`7192 D437 C8DD BA04 453A  3F6D 8288 58C8 4661 AEEB`

**Comment by tomholub** [comment]
`openpgp.util.str_to_hex(keyOrFingerprintOrBytes).toUpperCase()`

You'll get a long id (64 bits), not a fingerprint.

**Comment by SomaSomYT** [comment]
Umm I don't know whats the problem but the key id is not same.
I got this from the encrypted message:
`A5AA9E27780A8404`
And this from my public key:
`BD85C034E0F38957`

**Comment by tomholub** [comment]
You probably have a key that is a combination of two key packets:
```
primary: BD85C034E0F38957
subkey: A5AA9E27780A8404
```
In such situations, messages are typically encrypted for the subkey.

**Comment by SomaSomYT** [comment]
I dont know I encrypted two different messages for my public key and now i have this:
From message 1: A5AA9E27780A8404
From message 2: 4DA7271E4CAB4B65
From my pgp public key: BD85C034E0F38957
