### ISSUE TITLE
Extraneous packages

### ISSUE THREAD

**Issue by zbango** [openpgpjs/openpgpjs#1069]
After installing on `npm list` gets the following errors
![image](https://user-images.githubusercontent.com/9682684/77699613-b4522200-6f80-11ea-8db6-af4056912234.png)

I have 
node v10.17.0
npm 6.11.3

**Comment by chesnokovilya** [comment]
Those are dev dependencies, they are required for development and testing.

**Comment by twiss** [comment]
Hey @zbango :wave: This should be fixed in 4.10.2.
