### ISSUE TITLE
Request: ES6 Modules (importable using unpkg)

### ISSUE THREAD

**Issue by lastmjs** [openpgpjs/openpgpjs#1074]
It would be great if an ES modules build, suitable for browser and Node.js use, could be provided. It's important that this build not require bundlers like Webpack or Parcel to work correctly, it should be able to run in the browser (for example importing from the CDN unpkg) without modification.

**Comment by twiss** [comment]
Hey :wave: Yes, definitely. We hope to do this for v5. Also see #547.

**Comment by chesnokovilya** [comment]
Do you have a problem with unpkg? In theory it should run fine with script file reference.

**Comment by lastmjs** [comment]
I don't know if I've tried it with unpkg, I just know that if it works with unpkg it is likely to work with my build system, which is very minimal. Essentially I use ES modules everywhere, and rewrite bare specifiers to the actual paths so that the browser knows where they are. The important part for me is to load the source code written with es modules into the browser. I don't want to deal with just a script tag, I want to integrate openpgp perfectly into the standard module system that I'm already using.

**Comment by twiss** [comment]
This is fixed in #1047, and will be in the upcoming V5 release :)
