### ISSUE TITLE
How to read privatekey on Yubikey for decrypt PGP message ?

### ISSUE THREAD

**Issue by athlona64** [openpgpjs/openpgpjs#1077]
i need to decrypt PGP message with Yubikey 

How to read privatekey on Yubikey and fill password (PIN) for unlock Yubikey

Old Step
1. connect Yubikey
2. gpg --decrypt --armor pgp.key (terminal)
3. prompt PIN i fill PIN for unlock
4. (terminal) show message decrypt

How to use openpgpjs in above step ?

**Comment by tomholub** [comment]
OpenPGP.js does not currently (to my knowledge) include integration with hardware tokens, you'd have to go through gpg-agent or similar.
