### ISSUE TITLE
openpgp has a huge installation size in node_modules

### ISSUE THREAD

**Issue by Tilogorn** [openpgpjs/openpgpjs#1078]
Currently using `openpgp@4.9.0` in a Debian 10, Node.js-environment and installing all my dependencies with `npm install --no-optional --only=prod` to reduce the size of `node_modules` as much as possible, I get a **installation size of 152.9 MiB** just for openpgp.js!

This is by far the biggest package in my node_modules directory (big project), followed by some 10-12 MiB sized dependencies for processing PDFs and Office documents.

```
$ ncdu node_modules
```

![Bildschirmfoto vom 2020-04-15 07-53-09](https://user-images.githubusercontent.com/7524854/79303178-8c563e80-7eee-11ea-927a-7bddf977b843.png)

Digging deeper, it seems that the `node_modules` directory by the project itself is bloated. There is a lot of dev dependencies I do not need when just using the framework, e.g. compilers (`babel-*`), testing frameworks (`nyc`, `mocha`, `sinon`) and linters (`eslint`). 

![Bildschirmfoto vom 2020-04-15 08-05-39](https://user-images.githubusercontent.com/7524854/79303760-fd4a2600-7eef-11ea-8e71-9e980acc884d.png)

Would it be possible to keep this stuff out of the normal "ready-to-use" installations?

**Comment by chesnokovilya** [comment]
`npm install --only=prod` should install only 10 packages less than 500 kb in size.

**Comment by twiss** [comment]
I think this might be because of the npm-shrinkwrap.json file. I'll make a PR to remove it and see if that fixes things.

**Comment by twiss** [comment]
@Tilogorn 4.10.2 should fix this. Thanks for the report!

**Comment by Tilogorn** [comment]
@twiss Wow, thanks for the super fast reaction! Fix confirmed :thumbsup:
