### ISSUE TITLE
DomException in IE11: InvalidCharacterError when reading public key

### ISSUE THREAD

**Issue by sebastianhelbig** [openpgpjs/openpgpjs#1084]
Version 4.10.2
>Openpgp.key.readArmored(…)

=> In IE11 the error array is filled with a `DomException: InvalidCharacterError`
=> Same for dist/openpgp.js and dist/compat/openpgp.js

I tried the same with an older version (4.4.10). With this version it works fine.

**Comment by twiss** [comment]
Hey :wave:
IE11's atob is broken. The following monkey-patch should fix this:
```js
try {
    window.atob(' ');
} catch (e) {
    window.atob = (function(atob) {
        return function(string) {
            return atob(String(string).replace(/[\t\n\f\r ]+/g, ''));
        };
    })(window.atob);
}
```
Maybe we should add this to OpenPGP.js. But adding it to your code somewhere should fix it, for now.

**Comment by sebastianhelbig** [comment]
Thanks a lot. With your patch it is working fine.
