### ISSUE TITLE
Error encrypting message: No keys, passwords, or session key provided.

### ISSUE THREAD

**Issue by davidli3100** [openpgpjs/openpgpjs#1086]
For some reason, the code below returns an error even though I provide a publicKey and a message.

```
 let openpgp = window.openpgp
        await openpgp.initWorker({path: withPrefix("../js/openpgp.worker.min.js")})
        // firebase.storage().ref('public.asc').getDownloadURL().then((url) => {
        //     // encrypt stuff with the key
        //     console.log(url)
        // })
        const publicKey = `-----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: OpenPGP.js v4.6.2
        Comment: https://openpgpjs.org
        
        xsBNBF6c4EkBCAC3io7lVTPpEBSjllEmZtIyKlw270M+9nwqwJRrysGfQRGf...
        -----END PGP PUBLIC KEY BLOCK-----`
        const { data: encrypted } = await openpgp.encrypt({
            message: openpgp.message.fromText('Hello World'),
            publicKeys: openpgp.key.readArmored(publicKey).keys,
        })
        console.log(encrypted)
```
Any idea why? Could it be the Public PGP key header? I'm not providing a privateKey as I don't need signing. 

I don't see how I'm not providing a key or message, as it's explicitly defined in the options of the encrypt function. Quite honestly, I'm a little confused about how that's possible.

**Comment by chesnokovilya** [comment]
you need to use await as readArmored is async function.
```
const key = await openpgp.key.readArmored(armored);
const encrypted = await openpgp.encrypt({
    message: openpgp.message.fromText(data),
    publicKeys: key.keys[0]
})```

**Comment by arungithub1996** [comment]
This issue was solved by providing a *passwords* parameter with the *keyoptions*
```
    var keyOptions = {
      message: openpgp.message.fromText(fileToEncrypt),
      publicKeys: publickey ,
      passwords: "secret",
      armor : true
    }
```

**Comment by twiss** [comment]
That probably doesn't do what you think it does. That encrypts the message with a password and ignores the public key entirely.

In your code example, the key is indented, which causes leading spaces to break the parsing. In addition to what @chesnokovilya said, you have to unindent it, like this:
```js
        const publicKey = `-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v4.6.2
Comment: https://openpgpjs.org

xsBNBF6c4EkBCAC3io7lVTPpEBSjllEmZtIyKlw270M+9nwqwJRrysGfQRGf...
-----END PGP PUBLIC KEY BLOCK-----`
```
Try to inspect the result of `await openpgp.key.readArmored(publicKey)` to see if it worked or not.

**Comment by chesnokovilya** [comment]
Closing this as answered.
