### ISSUE TITLE
Documentation for openpgp.decrypt 'format' options

### ISSUE THREAD

**Issue by fluxquantum** [openpgpjs/openpgpjs#1089]
Is there a documented list of supported formats for the decryption? 

I dug through some examples and found instances of it being used in practice but if someone could direct me to a guide that shows what's the behavior and some additional use case examples, it will be very helpful.

For context I have the following code:

 options = {
        message: await openpgp.message.read(readableStream),
        privateKeys: [privKeyObj],
        format: 'binary'//TODO: Figure out what this does
    };

    console.log("****About to run file decryption******");
    const decrypted = await openpgp.decrypt(options);
    const plainText = decrypted.data;

As far as I have observed, the 'format' value hasn't impacted my ability to decrypt. I prefer to have a more intuitive understanding on what is happening.

Thank you for your time.

**Comment by twiss** [comment]
Hey :wave: The `format` parameter is documented here: https://openpgpjs.org/openpgpjs/doc/module-openpgp.html#.decrypt
If you pass `'binary'`, `plainText` will be a `Uint8Array`. If you pass `'utf8'` (the default), it will be a string. In essence, the latter has the same effect as:
```js
const plainText = openpgp.util.decode_utf8(decrypted.data).replace(/\r\n/g, '\n');
```

**Comment by fluxquantum** [comment]
@twiss Thank you for the quick follow up, I appreciate it.
