### ISSUE TITLE
Streaming decrypt Uint8Array data with a password

### ISSUE THREAD

**Issue by boby1975** [openpgpjs/openpgpjs#1096]
Hi guys,
And I'm trying to use openpgp.js with node.js.
Does anybody know how to do "Streaming decrypt Uint8Array data with a password"? 
There is no such example. 
But there is "Streaming encrypt Uint8Array data with a password"
https://github.com/openpgpjs/openpgpjs#streaming-encrypt-uint8array-data-with-a-password
I need vice versa example
Thanks a lot

**Comment by twiss** [comment]
Hey :wave: It is exactly the same as the [Encrypt and decrypt Uint8Array data with a password](https://github.com/openpgpjs/openpgpjs#streaming-encrypt-uint8array-data-with-a-password) example, except you pass and receive a stream. More instructions are here: https://github.com/openpgpjs/openpgpjs/releases/tag/v4.0.0

**Comment by boby1975** [comment]
Thanks. It works.
