### ISSUE TITLE
Can't read keys in IE11

### ISSUE THREAD

**Issue by shalenidze** [openpgpjs/openpgpjs#1101]
I have a problem with `openpgp.key.readArmored(key)` in IE11, it works well in Chrome or FF

I import compact version for old browsers
`openpgp/dist/compat/openpgp.min.js`

Backend return me key in base64, I decode it using `atob`( decoded string is the same as decoded in Chrome)

In IE11 call `openpgp.key.readArmored(key)` returns the object with property `err` and one error inside it.

Error is 
`DOMException: Invalid character error`

How can I solve this problem, or at least where is the problem

![Screenshot from 2020-05-25 12-37-33](https://user-images.githubusercontent.com/34502861/82801417-f49d2600-9e85-11ea-9150-582d4116ec4b.png)
![Screenshot from 2020-05-25 12-37-51](https://user-images.githubusercontent.com/34502861/82801410-f36bf900-9e85-11ea-8a38-387a8ca5d001.png)

![Screenshot from 2020-05-25 12-38-08](https://user-images.githubusercontent.com/34502861/82800821-fdd9c300-9e84-11ea-9097-fe50bfbfaaab.png)

**Comment by shalenidze** [comment]
sry I found the solution in previous issues

**Comment by le-thomas** [comment]
Hi, where did you find the solution?
Thanks

**Comment by le-thomas** [comment]
sry found it thanks
