### ISSUE TITLE
Wrong file name after decryption

### ISSUE THREAD

**Issue by GhsVilela** [openpgpjs/openpgpjs#1105]
I'm new to openpgp, I'm encrypting a file but them when i decrypt the file, the name is always "msg.txt", but the original file is for example 20200206111500.csv.

Can u guys help me? I tried everything that I know and no lucky so far

openpgp version 4.6.2

**Comment by twiss** [comment]
Hey :wave: If you want to record the filename, you have to pass it explicitly, as the second parameter of `openpgp.message.fromText`/`fromBinary`.

**Comment by GhsVilela** [comment]
> Hey  If you want to record the filename, you have to pass it explicitly, as the second parameter of `openpgp.message.fromText`/`fromBinary`.

Thanks, it was exactly what I was needing, working fine now. You saved me haha
