### ISSUE TITLE
Openpgp does not work on Electron after 4.5.4 due to node detection

### ISSUE THREAD

**Issue by ecamellini** [openpgpjs/openpgpjs#1106]
I am using `openpgp` in an Electron app -- up to version `4.5.3` everything worked as expected.

After upgrading from version `4.5.3` to version `4.5.4`, I get the following error:
![image](https://user-images.githubusercontent.com/6418684/84251697-ffa2b800-ab0d-11ea-99a0-a96152e2e1c9.png)

The error is slightly different if I try to update to version `4.5.5` instead, or any newer version:
![image](https://user-images.githubusercontent.com/6418684/84251956-57d9ba00-ab0e-11ea-99d0-e0bbfc5d2574.png)

Lookin in the changelog, it seems that versions [4.5.4](https://github.com/openpgpjs/openpgpjs/releases/tag/v4.5.4) and [4.5.5](https://github.com/openpgpjs/openpgpjs/releases/tag/v4.5.5) included some subsequent changes in the node detection mechanism: 

- https://github.com/openpgpjs/openpgpjs/pull/911/files was included in version `4.5.4`, and I think it is the cause of the error -- see below: 
- https://github.com/openpgpjs/web-stream-tools/pull/3/files was the only change from version `4.5.4` to `4.5.5`, and it's the reason why the error changes and refers to `stream` after that

These two PRs change the node detection mechanism and make `openpg` believe it is under Node when used in Electron.

## Node detection before these changes
```
detectNode: function() {
    return typeof window === 'undefined';
  }
```

This function is consistent between a web browser and electron: **it returns `false` in both cases**.

## Node detection after these changes
```
  detectNode: function() {
    return typeof global.process === 'object' &&
      typeof global.process.versions === 'object';
  }
```

This function returns **`true` when executed in Electron**.

## Chrome behavior before and after

![image](https://user-images.githubusercontent.com/6418684/84253450-3aa5eb00-ab10-11ea-83e1-b4b94eced096.png)

## Electron behavior before and after

![image](https://user-images.githubusercontent.com/6418684/84253501-4f827e80-ab10-11ea-9b7b-66d23c69e4e9.png)

**Comment by twiss** [comment]
Hey :wave: That's a bit strange, I thought Electron was supposed to provide access to the Node.js APIs? If not, why is it exposing `global.process`? Which version of Electron is this?

**Comment by ecamellini** [comment]
Thanks for your answer.
I will try to solve it as you say in the meantime, and wait for a stable v5 release!

**Comment by twiss** [comment]
Hi :wave: We've made a prerelease of v5: https://github.com/openpgpjs/openpgpjs/releases/tag/v5.0.0-0
You can grab a browser or Node.js build here, whichever works best: http://unpkg.com/openpgp/dist/
Let me know if this works for you :blush:

**Comment by larabr** [comment]
v5 has been released and should fix this problem. Feel free to open a new issue if needed.
