### ISSUE TITLE
Trying to make website from scratch with ability to post and an encrypted private chatting option.

### ISSUE THREAD

**Issue by LilPump99** [openpgpjs/openpgpjs#1107]
Good evening, I am trying to make a website from scratch with the ability to post media (photos and videos) and has an encrypted private chatting feature where multiple people can chat. I am having trouble with the coding for that and instructions or resources, or tips would be most helpful.

**Comment by twiss** [comment]
Hey :wave: This is a very big question. Making it secure is very difficult. Also, OpenPGP is probably not the best protocol for chat. The Signal protocol might be more appropriate for your use case.
