### ISSUE TITLE
keyStatus returned by Key.verifyPrimaryKey() is undefined

### ISSUE THREAD

**Issue by mwaeckerlin** [openpgpjs/openpgpjs#1110]
I have a strange problem: I create a new key, but key status is `undefined`:

In a mocha test:

```
const assert = require("assert");
const openpgp = require("openpgp");

var alice = null;

describe("simulate mail clients", function () {
  it("should initialize alice", async function () {
    alice = await openpgp.generateKey({
      userIds: [{ name: "Alice", email: "alice@example.com" }],
      curve: "ed25519",
      passphrase: "secret",
    });
    alice.key.getExpirationTime().then(console.log);
    assert.ok(alice.privateKeyArmored);
    assert.ok(alice.publicKeyArmored);
    assert.ok(alice.revocationCertificate);
    const keyStatus = await alice.key.verifyPrimaryKey();
    assert.equal(keyStatus, 3);
  });
});
```

Returns:
```
$ node_modules/.bin/mocha --bail


  simulate mail clients
Infinity
    1) should initialize alice


  0 passing (442ms)
  1 failing

  1) simulate mail clients
       should initialize alice:
     AssertionError [ERR_ASSERTION]: undefined == 3
      at Context.<anonymous> (test/test.js:19:12)
```

`alice.key.getExpirationTime()` returns `Infinity`, which is exactly the expected value. According to the documentation, that's from the primary key, so I assume, a primary key has been created correctly. Then why does `await alice.key.verifyPrimaryKey()` return `undefined`?

I'd expect the key status to be `3`.

**Comment by mwaeckerlin** [comment]
According to [the documentation](https://openpgpjs.org/openpgpjs/doc/module-key.Key.html), method `verifyPrimaryKey` should return `module:enums.keyStatus`:

```
(async) verifyPrimaryKey(date, userId) → {Promise.<module:enums.keyStatus>}
```

But when debugging, in the code, I see a completely different behaviour:
```
/**
 * Verify primary key. Checks for revocation signatures, expiration time
 * and valid self signature. Throws if the primary key is invalid.
 * @param {Date} date (optional) use the given date for verification instead of the current time
 * @param  {Object} userId (optional) user ID
 * @returns {Promise<true>} The status of the primary key
 * @async
 */
Key.prototype.verifyPrimaryKey = async function (date = new Date(), userId = {}) {
  const primaryKey = this.keyPacket;
  // check for key revocation signatures
  if (await this.isRevoked(null, null, date)) {
    throw new Error('Primary key is revoked');
  }
  // check for at least one self signature. Self signature of user ID not mandatory
  // See {@link https://tools.ietf.org/html/rfc4880#section-11.1}
  if (!this.users.some(user => user.userId && user.selfCertifications.length)) {
    throw new Error('No self-certifications');
  }
  // check for valid, unrevoked, unexpired self signature

  var _ref = await this.getPrimaryUser(date, userId);

  const selfCertification = _ref.selfCertification;
  // check for expiration time

  if (helper.isDataExpired(primaryKey, selfCertification, date)) {
    throw new Error('Primary key is expired');
  }
};
```

In fact, it throws an exception when the key is revoked or expired, and it returns nothing in case of success. That explains, why I get `undefined`.

So, what's wrong now, the implementation or the documentation?

I'd prefer getting a return value instead of having to catch exceptions, so I'd prefer the behaviour in the documentation.

I'm using OpenPGP.js 4.10.4, installed from https://registry.npmjs.org/openpgp/-/openpgp-4.10.4.tgz

**Comment by twiss** [comment]
Hey :wave: Yeah, we changed the code, and the documentation is wrong. The reason we changed it is because most calling locations inside the library were throwing on invalid keys anyway, so this made it shorter. You shouldn't really need to call this function in application code, as OpenPGP.js checks key validity before using a key.

**Comment by mwaeckerlin** [comment]
@twiss, ok, I understand.

A question: How do I generate the documentation on my own? I tried `jsdoc -d=doc -r src`, but the result is very different from your documenation.

A suggestion: Would it be possible to automatically generate and update the documentation in the deployment process?

**Comment by twiss** [comment]
`grunt jsdoc` should do it.

And yes, something like this is the plan: https://github.com/twiss/openpgpjs/commit/e6b86941bccadc5c9440ba96b6b44b7f4a29be01. With that approach, old versions of the docs won't be available on that website, but they will be available locally when checking out an old version.

**Comment by mwaeckerlin** [comment]
Yes, `grunt jsdoc` works — after updating `requizzle` to `0.2.3`. Thank you.

Closing the ticket, since documentation will be automatically updated in future.

**Comment by tacerus** [comment]
Hi,

what is the new equivalent to `verifyprimarykey` ?

**Comment by twiss** [comment]
`verifyPrimaryKey` still exists, but you still don't have to call it before using the key, so yes, you can remove those calls unless you for some reason want to know whether the key is valid before (or without) using it.

**Comment by tacerus** [comment]
I received that it is undefined as in the issue title here when trying it with the new version and could not find it in the documentation. Maybe I need to call it on something other than the key?

In our case we use it for a keyserver, so it would make sense to verify keys before accepting them into the database.

**Comment by twiss** [comment]
The documentation is here: https://docs.openpgpjs.org/Key.html#verifyPrimaryKey.

As explained in this issue, the function throws on verification errors now, and returns undefined on success :)

**Comment by tacerus** [comment]
Ah, I must have missed that, apologies! Thank you very much!
