### ISSUE TITLE
How do you import a signature into a key?

### ISSUE THREAD

**Issue by JonathanWilbur** [openpgpjs/openpgpjs#1114]
If somebody else were to sign my PGP key, how would I import said signature into my PGP key using OpenPGP.js?

**Comment by twiss** [comment]
Hey :wave: If you have a signed copy of your key, you can use `key.update(signedKey)` to merge the signature into your key. If you just have a bare signature, you could add it manually (for inspiration, see [Key.prototype.applyRevocationCertificate](https://github.com/openpgpjs/openpgpjs/blob/6988fdfee1b057c5e16a0180137c410adc1ffd44/src/key/key.js#L687)).
