### ISSUE TITLE
Decrypt file using streams in chunks

### ISSUE THREAD

**Issue by oscarmorasu** [openpgpjs/openpgpjs#1117]
Hello,

I am trying to use this library to decrypt data being piped from a `PassThrough` stream. Upstream I have a connection to an SFTP server, which writes data in chunks to the `PassThrough` stream. The idea is to read in chunks from the PassThrough stream and do the PGP decryption chunk by chunk, on-the-fly.

Can I do that with this library?

This is my method in TypeScript:

```
export async function openPGPStream(passThroughStream: NodeJS.ReadWriteStream): Promise<NodeJS.ReadWriteStream> {
    const decryptResult = await openpgp.decrypt({
        message: await openpgp.message.read(passThroughStream),
        privateKeys: [await getPrivateKey()]
    });
    return decryptResult.data as NodeJS.ReadWriteStream;
}
```

If I understand right in the line:

```
message: await openpgp.message.read(passThroughStream),
```

Reads all the data in the `passThroughStream`, then does the decryption, then I get back another stream to read the decrypted data.

If that's the case then it looks like streaming/chunking is not possible.

Thanks in advance!

It reads the whole `passThroughStream`. That

**Comment by twiss** [comment]
Hey :wave: What you want is possible. `await openpgp.message.read(passThroughStream)` doesn't read all the data.

**Comment by andre-engelbrecht** [comment]
I need some help with this. I'm also getting a stream from an SFTP server. When doing this with an armored file, all is well, but when trying the same thing for a non-armored file, it just hangs, so I don't know what I'm doing wrong.

Here's my function:
`async function getDecryptStream(sftpStream) {

    openpgp.initWorker({ path: 'openpgp.worker.js' }) // set the relative web worker path

    // Construct public-key object
    const pubKey = `${environment.nissan_pgp.publicKey.join("\n")}`
    const pubkeyObj = await openpgp.key.readArmored(pubKey)

    // Construct and decrypt private-key object
    const privKey = `${environment.nissan_pgp.privateKey.join("\n")}`
    const privKeyObj = await openpgp.key.readArmored(privKey)

    if (privKeyObj.keys.length == 0 && privKeyObj.err) {
        throw new Error("Unable to construct and decrypt private-key object: " + privKeyObj.err.Error)
    }

    const privKeyObjKeys = privKeyObj.keys[0] // extract first valid key
    await privKeyObjKeys.decrypt(environment.nissan_pgp.passphrase) // decrypt key

    let encryptedMessage
    try {
        encryptedMessage = await openpgp.message.readArmored(sftpStream)
        console.log("Encrypted stream is armored")
    }
    catch (error) {
        encryptedMessage = await openpgp.message.read(sftpStream, true)
        console.log("Encrypted stream is not armored")
    }

    // Construct decrypt options
    const decryptOptions = {
        message: encryptedMessage,      // parse armored message
        publicKeys: pubkeyObj.keys,     // for verification (optional)
        privateKeys: [privKeyObjKeys]       // for decryption
    }

    // Get decryptor instance
    const decryptor = await openpgp.decrypt(decryptOptions);

    return decryptor.data // data is a ReadableStream
}`

If I could just understand what I'm doing wrong, that might already help a lot.
