### ISSUE TITLE
wetransfer.com like service implementing OpenPGP.js

### ISSUE THREAD

**Issue by starfrosch** [openpgpjs/openpgpjs#1118]
We're looking for a wetransfer.com like service that implements client side OpenPGP.js hosted and operated under Swiss Law. Any hints about a service like this? Your help is appreciated.

**Comment by steverecio** [comment]
@starfrosch I run a service that sounds like what you're looking for called Pipefile (pipefile.com). Feel free to send me a note if you have any questions.
