### ISSUE TITLE
FireFox: decrypt fetch body stream 

### ISSUE THREAD

**Issue by PaulTime** [openpgpjs/openpgpjs#1121]
Hello, I'm trying to decrypt the fetch stream body, using **lightweight** version of `openpgp` with worker enabled and 
`openpgp.config.allow_unauthenticated_stream = true;`

I do it like so 
```
const body$ = await fetch(url, { credentials: 'include' }).then(res => res.body);

    const { data: decrypted$ } = await openpgp.decrypt({
      message: await openpgp.message.read(body$, true),
      passwords: randomKey,
      format: 'binary',
      streaming: 'web',
    });
```
and it works well in chrome and edge
but in FireFox I see this message comes up
**_Error during parsing. This message / key probably does not conform to a valid OpenPGP format._**

where I am mistaken? I've also tried non lightweight version without worker and this `openpgp.config.allow_unauthenticated_stream = true;` config line, and the **Error** still there

**Comment by twiss** [comment]
Hey :wave: This is probably a bug in OpenPGP.js, combined with the fact that Firefox doesn't support the full Web Streams API, so we polyfill it there.

Could you try to use https://github.com/MattiasBuelens/web-streams-adapter to do the following (_after_ loading OpenPGP.js):

```js
import { createReadableStreamWrapper } from '@mattiasbuelens/web-streams-adapter';
const toPolyfillReadable = createReadableStreamWrapper(ReadableStream);

// before decrypting
body$ = toPolyfillReadable(body$);
```

**Comment by PaulTime** [comment]
It worked! Thanks a lot))

**Comment by drzraf** [comment]
Do you know the upstream bug tracking the missing part(s) of FF ReadableStream?
