### ISSUE TITLE
native-file-system-adapter integration

### ISSUE THREAD

**Issue by PaulTime** [openpgpjs/openpgpjs#1124]
Hello, I am using openpgp alongside with [native-file-system-adapter](https://github.com/jimmywarting/native-file-system-adapter/tree/master/src) download/decrypt/write to download folder files (all of these happens simultaneously)
my code looks like this: 
```
const openpgp = await getOpenpgp(); // this is just a dynamic import wrapped in helper func, nothing special 

    const { ReadableStream: PolyfillReadableStream } = await import(
      'web-streams-polyfill'
    );
    const { createReadableStreamWrapper } = await import(
      '@mattiasbuelens/web-streams-adapter'
    );
    const toPolyfillReadable = createReadableStreamWrapper(PolyfillReadableStream);
    const { chooseFileSystemEntries } = await import('services/native-file-system-adapter/src/es6');

    const fileHandle = await chooseFileSystemEntries({
      type: 'save-file',
      accepts: [
        { extensions: [name.split('.').pop()] },
        { mimeTypes: [type] },
      ],
      excludeAcceptAllOption: true,
      _preferPolyfill: false,
      _name: name,
    });

    const writable = await fileHandle.createWritable();

    const body$ = await fetch(url, { credentials: 'include' }).then(res => res.body);

    if (!body$) return;

    if (!isEncrypted) {
      await body$.pipeTo(writable);
      return;
    }

    const { data: decrypted$ } = await openpgp.decrypt({
      message: await openpgp.message.read(toPolyfillReadable(body$), true),
      passwords: randomKey,
      format: 'binary',
      streaming: 'web',
    });

    await decrypted$.pipeTo(writable);
```

what's interesting that `!isEncrypted` branch works pretty well and stable(it shows a chrome downloads bar and bytes been fetched and also I've tested the memory footprint of my tab and it stays on the low level, if to talk about downloading a 1GB file), but when I'm trying to download/decrypt the stream the download bar just doesn't appear until the whole file was fetched and decrypted till the end

Thank you !)

**Comment by twiss** [comment]
Hey :wave:

Setting `openpgp.config.allow_unauthenticated_stream = true` should fix this. For more info about streaming decryption, please see https://github.com/openpgpjs/openpgpjs/releases/tag/v4.0.0.

**Comment by PaulTime** [comment]
I forgot to mention this, but I already have this option enabled

**Comment by twiss** [comment]
Hmm. Are you setting the option before creating the worker? Could you try it without the worker?
If that doesn't help: could you try to remove the `toPolyfillReadable` again, or only use it when needed (when `!(body$ instanceof ReadableStream)` or something like that)?
And if that doesn't help: do you have any other options enabled? What software encrypted the message?

**Comment by PaulTime** [comment]
Hello
I've attached details in `console.log('file$', decrypted); // this log shows only after response body stream will be fully decrypted, so thats the problem` line in the middle of the example
```
const { showSaveFilePicker } = await import(
      // eslint-disable-next-line max-len
      'services/native-file-system-adapter/src/es6' /* webpackChunkName: "native-file-system-adapter" */
    );
    const { ReadableStream: PolyfillReadableStream } = await import(
      'web-streams-polyfill' /* webpackChunkName: "streams-polyfill" */
    );
    const { createReadableStreamWrapper } = await import(
      '@mattiasbuelens/web-streams-adapter' /* webpackChunkName: "streams-adapter" */
    );
    const toPolyfillReadable = createReadableStreamWrapper(PolyfillReadableStream);

    const body$ = await fetch(url, { credentials: 'include' }).then(res => res.body);

    console.log('body$', body$);

    if (!body$) return;

    const openPGP = await getOpenpgp();

    console.log('openPGP');

    const decrypted = await openPGP.decrypt({
      message: await openPGP.message.read(toPolyfillReadable(body$), true),
      passwords: randomKey,
      format: 'binary',
      streaming: 'web'
    });

    console.log('file$', decrypted); // this log shows only after response body stream will be fully decrypted, so thats the problem

    const fileHandle = await showSaveFilePicker({
      _preferPolyfill: false,
      _name: name,
      excludeAcceptAllOption: false,
      accepts: []
    });
    const writable = await fileHandle.createWritable({ size });
    // writer.releaseLock();

    console.log('fileStream', writable);

    await decrypted.data.pipeTo(writable);
```
this time I use worker and disabled `allow_unauthenticated_stream ` config property

**Comment by twiss** [comment]
> this time I use worker and disabled `allow_unauthenticated_stream` config property

I meant the other way around, could you try _without_ the worker but _with_ `allow_unauthenticated_stream = true`?

**Comment by PaulTime** [comment]
@twiss , I tried as you said and this is only way that it worked for me, but it works perfect!)
```
type WebStreamToolsReader<T> = ReadableStreamDefaultReader & {
  readBytes: (bytesToEmit?: number) => Promise<T>;
}
type WebStreamTools = {
  getReader: <T>(input: ReadableStream | ReadableStreamLike | Uint8Array | string) =>
    WebStreamToolsReader<T>;
}

export const getOpenpgp = async (): Promise<typeof openpgp & { stream: WebStreamTools }> => {
  const openpgp = await import(
    'openpgp' /* webpackChunkName: "openpgp" */
  );

  if (!openpgp.config.allow_unauthenticated_stream) {
    openpgp.config.allow_unauthenticated_stream = true;
  }

  // if (!openpgp.getWorker()) {
  //   await openpgp.initWorker({
  //     path: OPENPGP_WORKER_PATH,
  //     n: navigator.hardwareConcurrency
  //   });
  // }

  return await { ...openpgp.default, ...openpgp } as typeof openpgp & { stream: WebStreamTools };
};
```
but still, what would you recommend if I want to use workers ? Are there any workarounds you might know?

**Comment by twiss** [comment]
See my previous message :D 

> could you try to remove the toPolyfillReadable again, or only use it when needed (when !(body$ instanceof ReadableStream) or something like that)?

**Comment by PaulTime** [comment]
oh, sorry. I just tried as you said (without `toPolyfillReadable`) on latest stable Chrome (84) and got this message from `openpgp`:
`(in promise) Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.` 
also I checked instance of body stream and it logs that `body$ instanceof ReadableStream => false` maybe that is the reason for that message

**Comment by twiss** [comment]
Ah, I think it's because you're importing `web-streams-polyfill`. In Chrome, it's not needed (and in Firefox, openpgp.js does it for you, so you can just use `global.ReadableStream`).

**Comment by PaulTime** [comment]
It didn't worked(
but for now, I think, its enough for me, I just will destroy worker before decrypt starts and then enable it again if I need to
Thanks))
