### ISSUE TITLE
Session key decryption failed.

### ISSUE THREAD

**Issue by Chnovo28** [openpgpjs/openpgpjs#1126]
Session key decryption failed. from Version 4.10.5.
in V 4.10.4  working perfectly.

**Comment by twiss** [comment]
Hey :wave: Do you have an example message and private key that you're unable to decrypt with? Or, if you're unable to post that, the public key that corresponds to that private key?

**Comment by myrtleTree33** [comment]
Hi, another user here of your library.  I can confirm this is failing as of `v4.10.7`.  It works well in `v4.10.4`.

I am unable to disclose the keys, however traced the error to line #35703 in `openpgp.js`.

In `Message.decryptSessionKeys()`, there seems to be a condition that checks for the length of `keypackets`.  If the array is empty, condition falls through, leading to the default behavior of throwing an exception `Session key decryption failed`.

I think it may be looking at some public keys during decryption, when it should be just for private keys, though I am not sure if this is the case.

Can anyone help patch this? :P

**Comment by gilach** [comment]
Same issue here. This needs to be addressed.

**Comment by larabr** [comment]
Hi all,
in v4.10.5 we added some logic that verifies the binding signatures of decryption keys (https://github.com/openpgpjs/openpgpjs/blob/master/src/key/key.js#L351). This is needed to help guarantee the integrity of the keys.

Could you please check whether the decryption keys that you are using have been revoked? Or whether they are missing binding signatures?

**Comment by twiss** [comment]
@gilach and @myrtleTree33, could you please post a message that has this issue, and the public key it was encrypted with? We would like to know whether the above PR will fix this before merging it, as we suspect there are still other issues.

**Comment by vdabar** [comment]
Hi all, I have the exact same issue. I tracked down that it fails to meet this check:
https://github.com/openpgpjs/openpgpjs/blob/aa89893773c2ff97e85846ad5b0a184a89dc1688/src/key/helper.js#L356
which is called from here:
https://github.com/openpgpjs/openpgpjs/blob/aa89893773c2ff97e85846ad5b0a184a89dc1688/src/key/key.js#L336
and
where` signature.keyFlags[0] = 3 `
As I see it's only allowed to have `encrypt_communication` and  `encrypt_storage` flags, is there any reason behind it?

**Comment by twiss** [comment]
Hey :wave: `keyFlags = 3` means that the key may be used for signing and certification, but not encryption or decryption. We didn't use to respect this flag, but now we do, by default (we respect it for encryption since v0.4.0, and for decryption since v4.10.5). Since v4.10.8, you can set `openpgp.config.allow_insecure_decryption_with_signing_keys = true` to override this check for decryption, as per the linked PR above. Could you try that?

**Comment by vdabar** [comment]
@twiss Thanks for the quick answer! it works with the flag, however, we'll regenerate keys to respect those flags.

**Comment by ruipimentel** [comment]
Seems to be related to #878...?

I'm under the impression that by solving that other problem by the method I described [there](https://github.com/openpgpjs/openpgpjs/issues/878#issuecomment-858027368), the session key here was possibly automatically solved...?

Now my whole code seems to work!

**Comment by larabr** [comment]
@ruipimentel : session key decryption can fail for many reasons, but if the problem only pops up after updating from v4.10.4, then it shouldn't have anything to do with TextEncoders, and it's most definitely related to [this bug](https://github.com/openpgpjs/openpgpjs/issues/1126#issuecomment-683868831) with keys that were generated in the past.

**Comment by alan19031216** [comment]
Hi guys, I got a problem.

I try to decrypt PGP msg in my local and staging environment, it can be decrypted successfully. 

But when I move on to the production environment, it shows "Error decrypting message: Session key decryption failed."

These three environments are using the same passphrase, a public and private key but return different results.

Local:
node: v14.17.1
npm: 7.17.0
openpgp: 4.10.0

Staging:
node: v10.20.0
npm: 6.14.4
openpgp: 4.10.0

Production:
node: v10.15.2
npm: 5.8.0
openpgp: 4.10.0

Below is my coding

`
function decryptFunction(encrypted, callback) {
    openpgp.initWorker({ path: dbs_config.workerpath });
    openpgp.config.ignore_mdc_error = true 
    openpgp.config.allow_insecure_decryption_with_signing_keys = true

    var testPubKey = fs.readFileSync(dbs_config.serverPubPath, "ascii").trim();
    var testPriKey = fs.readFileSync(dbs_config.clientSecPath, "ascii").trim();

    var encWhole = (await openpgp.message.readArmored((encrypted)));

    var pubWhole = (await openpgp.key.readArmored(testPubKey));

    var pubInKey = pubWhole.keys;

    var priWhole = (await openpgp.key.readArmored(testPriKey));

    var priInKey = priWhole.keys[0];

    await priInKey.decrypt(dbs_config.cliPassphrase);

    const decoptions = {
        message: encWhole,
        publicKeys: pubWhole.keys,
        privateKeys: priInKey
    };

    var outMsg = openpgp.decrypt(decoptions).then(plaintext => {
        return plaintext.data;
    }).catch((e) => {
        console.log("error : " + e);
        throw e;
    });

    const outMsgTxt = await openpgp.stream.readToEnd(outMsg);
    msg = outMsgTxt;

    console.log("outMsgTxt-- " + outMsgTxt);
    callback(outMsgTxt);
}
`

**Comment by larabr** [comment]
Hi @lan19031216 , please open a new issue or discussion. v4.10.0 is not affected by the problem described here.

**Comment by alan19031216** [comment]
ok no problem

**Comment by Abhinav-vats** [comment]
Getting Session key decryption failed error on version 5.1.0 while decrypting the encrypted string even though message do not contain any sessionKeys or sessionAlgorithm, these values are null

**Comment by nabid-pf** [comment]
Try to add `config: { allowInsecureDecryptionWithSigningKeys: true }` in the decrypt function parameter object. Solved for me.
