### ISSUE TITLE
using a "openpgp_msg_privatekey" for "openpgp_msg_message.decryptAndVerifySignature" throws error

### ISSUE THREAD

**Issue by GameScripting** [openpgpjs/openpgpjs#113]
The documentation says the first paramter of `openpgp_msg_message.decryptAndVerifySignature` needs to be a `openpgp_msg_privatekey` which seems logical.
However that does not work.

Both `test\encryption.html` and the unit tests use the following structure, which does work but is not documented (or kind of "static typed") `{ key: [openpgp_msg_privatekey], keymaterial: [openpgp_packet_keymaterial]}` as the first paramter (for the `openpgp_msg_message.decryptAndVerifySignature` function)

See https://github.com/GameScripting/openpgpjs/blob/bug_decryptAndVerifySignatureBadParameter/bug_decryptAndVerifySignatureBadParameter/index.html for code showing the error.

**Comment by tanx** [comment]
Probably not relevant anymore.
