### ISSUE TITLE
Can it handle 2-keys for same email-adrs ? Using OpenPGP.js With Mailvelope For Browser Tab in Thunderbird

### ISSUE THREAD

**Issue by atErik** [openpgpjs/openpgpjs#1139]
Can "OpenPGP.js" handle 2-keys for same email-adrs, to send encrypted emails ?
I'm using "OpenPGP.js" with Mailvelope addon for browser tab inside Thunderbird.

when i have 2 or more keys for same email-adrs in Mailvelope, then sent email seems to be encrypted with none of the keys of destination email address , but instead source/sender's own key is used for encryption !!!

i have explained the problem here:
https://github.com/mailvelope/mailvelope/issues/743#issuecomment-670994286

is it something inside Mailvelope thats not working ? or is it a limitation of "OpenPGP.js" ? or is it something else inside my Thunderbird ?

my platform MacOS 10.15.6 Catalina (64bit-only), Thunderbird v68.11.0, Mailvelope v4.2.3.

**Comment by bartbutler** [comment]
To my knowledge this should not be an OpenPGP.js limitation--as far as the library is concerned, you can encrypt to any public keys you provide to it, it does no de-duplication or other operations based on User ID (email address). This sounds like a Mailvelope issue.

**Comment by atErik** [comment]
thank you @bartbutler , so in that case OpenPGP.js library is not part of this problem.

**Comment by bartbutler** [comment]
I highly doubt it, yes.

**Comment by atErik** [comment]
if user creates a single gpg key which has key-owner's multiple-IDs (for multiple email-address),
then Can "OpenPGP.js" use/handle the right key/subkey associated with a specific emal-address (out of multiple IDs) from that same key to decrypt/encrypt email received-from or sent-to a specific email-adrs ?

so in another word, Can "OpenPGP.js" use separate key for same email-adrs ? i think it can do this as its simple, & your previous answer clarified that,
but Can "OpenPGP.js" select+use specific-ID (associated with a specific email-address) from inside the single-key which has key-owner's multiple email-addresses ?

**Comment by bartbutler** [comment]
I'll have to defer this to @twiss for a definitive answer, but again I don't think OpenPGP cares about User ID, for decryption it'll use the correct encryption subkey to decrypt the message. For encryption, I don't think it's possible (or standard) to have different encryption subkeys associated with different users in the same key, I think what will happen is that only one of the encryption subkeys will be used. You can definitely have multiple user id packets but I think those are then associated with a key at large, not with specific parts of the key.

**Comment by twiss** [comment]
Yeah; different User IDs can have different preferences and such, but not different subkeys. In any case, this is highly unlikely to have anything to do with your issue, @atErik.

**Comment by atErik** [comment]
Thank you @twiss, for clarifying it.
i did not meant i want to use multi subkeys in a single key, just wanted to know if the multi-IDs/keys inside a single openpgp/gpg/pgp key will be handled properly by OpenPGP.js or not . i'm sorry for not-being very clear in my question/comments/senetences.
With your response, its assured+clear that OpenPGP.js itself can handle multi-ID based single/combined key , so OpenPGP.js will use the correct key/subkey, when a specific-ID (inside the multi-ID key) is used, to send a singed+encrypted email out, etc.

Also thanks to @bartbutler on contacting correct person.

Mailvelope problems in Thunderbird, the github-issue that was opened+submitted, still isn't addressed by Mailvelope project.
