### ISSUE TITLE
"openpgp_msg_message.decryptAndVerifySignature" with "openpgp_msg_publickey" parameter throws error

### ISSUE THREAD

**Issue by GameScripting** [openpgpjs/openpgpjs#114]
The documentation says the third paramter of `openpgp_msg_message.decryptAndVerifySignature` need to be a `openpgp_msg_publickey`. If you do that, it will throw.

When adding the publickey to keyring and not giving it as parameter everything works as expected.

Thats because the keyring does store the certificates using a structure which can be found here: https://github.com/openpgpjs/openpgpjs/blob/master/src/openpgp.keyring.js#L197
It looks like `{armored: [string], obj: [openpgp_msg_publickey], keyId: [openpgp_msg_publickey].getKeyId()}`

See https://github.com/GameScripting/openpgpjs/blob/bug_decryptAndVerifySignatureWith_openpgp_msg_publickey/bug_decryptAndVerifySignatureWith_openpgp_msg_publickey/index.html for code showing the error.

**Comment by tanx** [comment]
Probably not relevant anymore.
