### ISSUE TITLE
OpenPGP.js hide version

### ISSUE THREAD

**Issue by MalteKiefer** [openpgpjs/openpgpjs#1142]
I generate with openpgp.js a new key like this:

```javascript
		var createOptions = {
			numBits: keysize,
			userIds: [{name:user, email:email }],
			passphrase: createdString
		};

		openpgp.generateKey(createOptions).then(function(keypair) {
			var privkey = keypair.privateKeyArmored;
			var pubkey = keypair.publicKeyArmored;

			savekey(user, pubkey, "");
			savekey(user, privkey, createdString);

			if($("#inputKeyUpload").is(':checked'))
			{
				var keyserver = (loadval("pgpanywhere_keyserver",0)==1) ? "keys.openpgp.org" : loadval("pgpanywhere_keyserver",0);
				var upk = new openpgp.HKP('https://' + keyserver);
				upk.upload(pubkey).then(function() { alert(chrome.i18n.getMessage("publicKeyUploadOK")); });
			}

		}).catch(function(error) {
			alert(error);
		});
	});
```
Is there a way to tell openpgp not to put the version in the key like this:

    -----BEGIN PGP PRIVATE KEY BLOCK-----
    Version: OpenPGP.js v4.10.7
    Comment: https://openpgpjs.org

I will hide this:

    Version: OpenPGP.js v4.10.7
    Comment: https://openpgpjs.org

**Comment by tomholub** [comment]
You can change openpgp.config parameters to set any version you like, or none.

**Comment by MalteKiefer** [comment]
I don't find the parameter fo this.

**Comment by tomholub** [comment]
It's `versionstring` and `commentstring`. See:

![image](https://user-images.githubusercontent.com/6306961/90334568-1528d800-dfbe-11ea-8379-56c88a16df55.png)

**Comment by tomholub** [comment]
Plus the `show_comment` and `show_version`
