### ISSUE TITLE
Bugs in openpgp_encoding_deArmor()

### ISSUE THREAD

**Issue by encomiast** [openpgpjs/openpgpjs#115]
Hi openpgpjs team,

There are a few bugs in openpgp_encoding_deArmor(), messing up messages with double line breaks, trailing line breaks and more-than-double line breaks. This leads to signature verification failure.

----
1st:
https://github.com/openpgpjs/openpgpjs/blob/b94566a154d09bd63df963adb3bd515c729273e4/src/encoding/openpgp.encoding.asciiarmor.js#L79-L81
I suppose this was meant to strip the header line, leaving the original message text. Instead, it only returns the first paragraph of the original message text -- i.e. everything between the first and the second occurrence of a double \n character.

----
2nd:
After fixing above issue, triple/quadruple etc. line breaks all get rewritten to double line breaks due to a greedy Regex:
https://github.com/openpgpjs/openpgpjs/blob/b94566a154d09bd63df963adb3bd515c729273e4/src/encoding/openpgp.encoding.asciiarmor.js#L29

----
3rd:
The line break between the message text and the line starting with "-----" is not stripped even though it is not part of the original message text.

----
This should straighten it out:
https://github.com/encomiast/openpgpjs/commit/3282eda87f0b7005a018d436c35c9bc4928061c3

Issues #80 and #92 should also be fixed by this.

**Comment by tanx** [comment]
Probably not relevant anymore
