### ISSUE TITLE
openpgp.HKP CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by chenlhlinux** [openpgpjs/openpgpjs#1150]
I want import public key from HKP server, but browser tell me "CORS header'Access-Control-Allow-Origin' missing" and throw the error "TypeError: NetworkError when attempting to fetch resource". 
What should I do?

Thanks in advance.
code:
```
var hkp = new openpgp.HKP();
try {
	var publicKeyArmored = await hkp.lookup({
		query: email
	});
} catch (e) {
	alert(e);
}
```

**Comment by bartbutler** [comment]
This is usually a HKP server misconfiguration rather than an issue with the library.

**Comment by chenlhlinux** [comment]
When I changed the server to https://keys.openpgp.org, it work.

Thanks.
