### ISSUE TITLE
What version of the PGP standard does OpenPGP.js use?

### ISSUE THREAD

**Issue by seisvelas** [openpgpjs/openpgpjs#1154]
I noticed that there are multiple extant, incompatible versions of PGP. I was wondering what version of PGP this library uses?

Thanks!

**Comment by twiss** [comment]
Hi :wave: What incompatibilities are you referring to, specifically? Most additions to the spec are meant to be backwards compatible, except for deprecations of insecure algorithms.

In any case, we implement RFC4880, and most of RFC4880bis.

**Comment by seisvelas** [comment]
I didn't have any specific incompatibilities in mind, I had been told that and didn't double check. This answers my question perfectly, thanks!
