### ISSUE TITLE
Keyring tests are not independent

### ISSUE THREAD

**Issue by danrr** [openpgpjs/openpgpjs#1161]
Some tests in https://github.com/openpgpjs/openpgpjs/blob/v5/test/general/keyring.js rely on previous tests setting up variables. This means tests pass when run as a whole but fail when run individually (eg. when run with `npm run test -- --grep "removeKeysForId"`). This makes diagnosing issues with these tests harder. 

Tests should be independent and allow for successful partial runs when using the grep option.

**Comment by larabr** [comment]
Keyring support has been removed in 4a8fffdfdf94ca88f3624db6c7572611d1404eaf
