### ISSUE TITLE
Rare silent signature truncation on v3.1.3

### ISSUE THREAD

**Issue by danenania** [openpgpjs/openpgpjs#1164]
This is seemingly not reliably reproducible or deterministic, as our product runs thousands of `openpgp.sign` calls (including on messages up to 100kb and larger) without issue, but I have seen this pop up twice now within the last month, so thought I'd post and see if anyone has ideas on what could be going on.

In both cases, it seems that `openpgp.sign` signed a message (roughly 10kb) without issue, but upon further inspection, the signature was just a 4 character string beginning with an `=` character. It subsequently fails verification.

I unfortunately cannot share the message as it contains PII, but does anyone have any ideas as to what could possibly be causing this sort of behavior? For now, I'm planning to immediately verify after signing and implement a retry loop if verification fails.

**Comment by twiss** [comment]
Hey :wave: Could you post the code you're using to sign?

And - would it be possible to try OpenPGP.js v4 and see if it's fixed there? Even if we find the issue, this is unlikely to get fixed in v3, as it's no longer supported.

**Comment by larabr** [comment]
I'm closing this for now, if you are using a worker, that might be causing the problem. if you are still having issues feel free to reopen.
