### ISSUE TITLE
allow to pass config into functions

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#1166]
I digged this up in a conversation between @twiss and @wiktor-k and I thought it was a great idea, we'd definitely make a good use of this if it was available :) So I'm pulling it out to give it it's own issue (unless there already is one).

-------------------------------

_Yeah. Even more than that, sometimes you want to set a config option for one message/decryption only, which is a bit difficult right now with the async model. So I think it would be even nicer to add `config` options/parameters to all of the top-level functions. Then you could also do:_
```js
try {
  result = openpgp.decrypt({ message });
} catch (e) {
  warn("Insecure!");
  result = openpgp.decrypt({ message, config: { allow_insecure_decryption_with_signing_keys: true } });
}
```
_Or make it depend on the date of the email, et cetera.
And then there would also be no statefulness in the tests, potentially allowing us to run them in parallel, etc._

_Originally posted by @twiss in https://github.com/openpgpjs/openpgpjs/pull/1148#discussion_r480181580_

**Comment by tomholub** [comment]
Another possibility is something like - this way you don't have to change all of the signatures, but hard to say which is a larger change:

```ts
const laxOpenpgp = openpgp.configure({ config: { allow_insecure_decryption_with_signing_keys: true }});

// ...

try {
  result = openpgp.decrypt({ message });
} catch (e) {
  warn("Insecure!");
  result = laxOpenpgp.decrypt({ message });
}
```

**Comment by twiss** [comment]
Thanks for making an issue for this, @tomholub. I would like to do this in v5.

I would prefer the former option, because v5 allows you to import individual functions, so you'd have:

```js
import { decrypt } from 'openpgp';
try {
  result = decrypt({ message });
} catch (e) {
  warn("Insecure!");
  result = decrypt({ message, config: { allowInsecureDecryptionWithSigningKeys: true } });
}
```

I don't really see a way to make this work with the second option.

**Comment by tomholub** [comment]
Got it - sounds good :+1:
