### ISSUE TITLE
How to use the keyring?

### ISSUE THREAD

**Issue by nolash** [openpgpjs/openpgpjs#1168]
How do I add a key to keyring? I can't find example code in the README. THanks.

**Comment by larabr** [comment]
Hi @nolash, you can have a look at the tests: https://github.com/openpgpjs/openpgpjs/blob/v4/test/general/keyring.js#L109

**Comment by twiss** [comment]
Just to add - most examples in the README don't use keyrings, because they are often not really needed. You can just pass an array of keys to OpenPGP.js, and handle the keyring yourself. Good luck!
