### ISSUE TITLE
Key.prototype.isDecrypted() should check the subkeys as well

### ISSUE THREAD

**Issue by larabr** [openpgpjs/openpgpjs#1173]
`Key.prototype.isDecrypted()` currently returns whether the primary key packet is decrypted. Instead, the function should return `true` if any subkey is decrypted, regardless of the primary key status. 

This change is important to handle gnu-dummy keys correctly, as their primary key is unaffected by encryption/decryption.
Also, if `key.isDecrypted()` returns false, one will be sure that the key can be safely exported as no subkeys are left unencrypted.

Given this change, we can then settle on a constant value for `Key.prototype.isEncrypted` for gnu-dummy keys.

Related to #945.

**Comment by tomholub** [comment]
100% agree - we ended up monkey-patching our own methods when using OpenPGP.js exactly for this reason. If any of the secret packets are decrypted, isDecrypted should return true, else decrypted packets may slip through this check and end up getting exposed where you don't expect them to be when exporting the key.

In our case, for added clarity, we went with `Key.prototype.isFullyEncrypted` and `Key.prototype.isFullyDecrypted` which each handles the dummy keys appropriately based on which method was used.
