### ISSUE TITLE
Cannot Encrypt/Decrypt Excel Files

### ISSUE THREAD

**Issue by vinitsharswat** [openpgpjs/openpgpjs#1174]
Tried encrypting and decrypting excel files the same way I am doing for csv/txt files but I am not able to.

**Encryption**
var rawMessage= fs.readFileSync(path)
await openpgp.initWorker({ path: 'openpgp.worker.js' }); // set the relative web worker path
const publicKeyArmored = readFile(publicKeyPath);
const { data: encrypted } = await openpgp.encrypt({
    message: openpgp.message.fromBinary(new Uint8Array(rawMessage)),  // input as Message object
    publicKeys: (await openpgp.key.readArmored(publicKeyArmored)).keys, // for encryption
    armor: true,
    compression: openpgp.enums.compression.zip
});

**Decryption**
var rawMessage= fs.readFileSync(path)
const privateKeyArmored = readFile(privateKeyPath);
const { keys: [privateKey] } = await openpgp.key.readArmored(privateKeyArmored);
await privateKey.decrypt(passphrase);
const { data: decrypted } = await openpgp.decrypt({
  message: await openpgp.message.readArmored(encryptedData), //               // parse armored message
      privateKeys: [privateKey]                                           // for decryption
  });

Looking for quick resolution

**Comment by twiss** [comment]
Hey :wave: Try `format: 'binary'` when decrypting.
