### ISSUE TITLE
openpgp.message.read(stream, true) hangs

### ISSUE THREAD

**Issue by andre-engelbrecht** [openpgpjs/openpgpjs#1176]
I'm trying to decrypt a non-armored stream, and the code just seems to be hanging. Now, I'm propbably just doing something wrong, and I'll be happy to close this issue if that's the case, but I need some help here.

Here's my code:

	async function getDecryptStream(sftpStream) {

		openpgp.initWorker({ path: 'openpgp.worker.js' }) // set the relative web worker path

		// Construct public-key object
		const pubKey = `${environment.nissan_pgp.publicKey.join("\n")}`
		const pubkeyObj = await openpgp.key.readArmored(pubKey)

		// Construct and decrypt private-key object
		const privKey = `${environment.nissan_pgp.privateKey.join("\n")}`
		const privKeyObj = await openpgp.key.readArmored(privKey)

		if (privKeyObj.keys.length == 0 && privKeyObj.err) {
			throw new Error("Unable to construct and decrypt private-key object: " + privKeyObj.err.Error)
		}

		const privKeyObjKeys = privKeyObj.keys[0] // extract first valid key
		await privKeyObjKeys.decrypt(environment.nissan_pgp.passphrase) // decrypt key

		let encryptedMessage
		try {
			encryptedMessage = await openpgp.message.readArmored(sftpStream)
			console.log("Encrypted stream is armored")
		}
		catch (error) {
			encryptedMessage = await openpgp.message.read(sftpStream, true)
			console.log("Encrypted stream is not armored")
		}

		// Construct decrypt options
		const decryptOptions = {
			message: encryptedMessage,      // parse armored message
			publicKeys: pubkeyObj.keys,     // for verification (optional)
			privateKeys: [privKeyObjKeys]       // for decryption
		}

		// Get decryptor instance
		const decryptor = await openpgp.decrypt(decryptOptions);

		return decryptor.data // data is a ReadableStream
	}

Note 'sftpStream' is just a regular ReadableStream

Any help is greatly appreciated.

**Comment by twiss** [comment]
> ```
> 	try {
> 		encryptedMessage = await openpgp.message.readArmored(sftpStream)
> 		console.log("Encrypted stream is armored")
> 	}
> 	catch (error) {
> 		encryptedMessage = await openpgp.message.read(sftpStream, true)
> 		console.log("Encrypted stream is not armored")
> 	}
> ```
`readArmored` (and `read`) consumes (part of) the stream. After calling `readArmored`, some of the data will be "gone". You can't backtrack and try `read` instead.

Ideally, it would be best if you could figure out in advance what type of file it is (armored or unarmored), e.g. based on the file extension.

If there's no way for you to figure that out, you could try something like:

```js
const reader = openpgp.stream.getReader(sftpStream);
const firstBytes = await reader.peekBytes(27);
reader.close();
// check to see if firstBytes is '-----BEGIN PGP MESSAGE-----' ...
```

**Comment by andre-engelbrecht** [comment]
Thanks so much Daniel, this sounds like that tiny detail I was missing.
I'll try it out tomorrow morning.
Thank you very much!

André Engelbrecht
ajc.mfl@gmail.com

#Sent from my mobile#
