### ISSUE TITLE
how to adduid and revuid

### ISSUE THREAD

**Issue by Erriy** [openpgpjs/openpgpjs#1177]

**Comment by twiss** [comment]
Hey :wave: There are no very easy functions for this, at the moment. To add a user id, you could call `openpgp.reformatKey` with the updated list of users, or (if you don't want it to re-sign the existing user & subkey) only with the user you want to add, and then call key.update or simply `key.users.push(newKey.users[0])`. There is no function to revoke a user id at the moment; just a function to revoke the entire key. Feel free to send a pull request with one, if you need it (you could take inspiration from `key.revoke`).

P.S. Please send support questions to [gitter](https://gitter.im/openpgpjs/openpgpjs), instead.
