### ISSUE TITLE
how to add subkey and other users to an existing key? thanks

### ISSUE THREAD

**Issue by yaming042** [openpgpjs/openpgpjs#1180]

**Comment by twiss** [comment]
:wave: There is a `key.addSubkey` method. Adding users is a bit more involved, you could `openpgp.reformatKey` with the updated list of users, or (if you don't want it to re-sign the existing user & subkey) only with the user you want to add, and then call `key.update` or simply `key.users.push(newKey.users[0])`.

P.S. Please send support questions to [gitter](https://gitter.im/openpgpjs/openpgpjs), instead.
