### ISSUE TITLE
Cannot Decrypt Zip Files

### ISSUE THREAD

**Issue by mukeshswrkr** [openpgpjs/openpgpjs#1195]
I am getting incorrect zip file while trying to decrypt the zip file while this is working fine for csv files.
const options = {
    message: openpgp.message.fromText((await stream).Body.toString()),
    publicKeys: (await openpgp.key.readArmored(public_key.Value)).keys,
    armor: false
    };
  console.log(" options are ", options)
  const encrypted = await openpgp.encrypt(options);

**Comment by bartbutler** [comment]
You cannot use fromText() for ZIP files, as they aren't text. Look for a function called fromBinary() or similar.
