### ISSUE TITLE
Documentation related to "dist" broken

### ISSUE THREAD

**Issue by codigo-ergo-sum** [openpgpjs/openpgpjs#1240]
Documentation under the "Getting Started" section related to "dist" goes to a broken link. Specifically, where it says: "Or just fetch a minified build under dist." The link is to https://github.com/openpgpjs/openpgpjs/tree/master/dist but when clicking that link I get a 404. There are a couple of other places in the documentation that mention things like "dist/openpgp.min.js" and "dist/compat/openpgp.min.js", which don't seem to exist in the git repo.

For some context, I'm trying to do PGP decryption within a database, specifically Snowflake, in a UDF. https://docs.snowflake.com/en/user-guide/binary-examples.html#custom-decoding-with-javascript-udf. Hoping to basically have a javascript function that I can cut-and-paste to load as a UDF in Snowflake that will allow for PGP decryption of a given value in database (of course, when also given the appropriate private key for decryption.) It is pretty limited in terms of external libraries that it can rely on. I realize this may be ridiculously oversimplifying things, apologies if so.

**Comment by larabr** [comment]
We are in the process of releasing a new version, and the README is not updated yet. You'll find the `dist` files in the v4 releases: https://github.com/openpgpjs/openpgpjs/releases/tag/v4.10.10

**Comment by CMEONE** [comment]
@codigo-ergo-sum Yep, I ran into the exact same problem! Checking the `.gitignore`, they have purposefully removed the `dist/` directory from the repo.

You can also build yourself by seeing the instructions at the bottom of the `README` or fetch a prebuilt version from https://unpkg.com/browse/openpgp@4.10.10/dist/

**Comment by codigo-ergo-sum** [comment]
Thanks makes sense all. Closing issue.
