### ISSUE TITLE
How do I import/export key as bytes array?

### ISSUE THREAD

**Issue by CMEONE** [openpgpjs/openpgpjs#1242]
I would like to export the private key as an array of bytes and then import that into another private key. For this specific usecase, I would need an array of bytes, not an ascii-armored string. Additionally, I would want this array of bytes to be small, preferably under length 64 (which is why I cannot just convert the ascii-armored string to bytes). And, I want to be able to both export from a key and import this to create the identical key later.

Is this possible within openpgpjs? I have a feeling that it's somewhere in the `Key` class, but I'm not entirely sure which property it is and how to import it back into a new key object.

**Comment by tomholub** [comment]
Here's a snippet we use. It would be good to have this in the library :+1: 

```ts
  public static dearmor = async (text: string): Promise<{ type: OpenPGP.enums.armor, data: Uint8Array }> => {
    const decoded = await opgp.armor.decode(text);
    const data = await Stream.readToEnd(decoded.data);
    return { type: decoded.type, data };
  }
```

**Comment by CMEONE** [comment]
Ah, interesting, this is helpful... but I don't want to just convert the ascii-armored string to bytes. I would like a bytes array of under length 64. I guess that this would be the initial derivation bytes used to derive the key. I was thinking this might be the `Key.keyPacket.keyMaterial` array, but I'm not 100% sure and also I don't know how to use that to load an identical key later on.

**Comment by tomholub** [comment]
I didn't read your whole message. I was just referring to exporting it as unarmored bytes, nothing else. Sorry for confusion.

**Comment by CMEONE** [comment]
@twiss Do you know a solution? Is `Key.keyPacket.keyMaterial` the derivation bytes? And can these bytes be used to rederive the key using openpgpjs? If not, is there any other bytes array of under length 64 that can be used to export/import a key?

**Comment by CMEONE** [comment]
@larabr @twiss Any updates on whether `Key.keyPacket.keyMaterial` can be used to rederive a key, and if so, how?

**Comment by twiss** [comment]
Hey @CMEONE :wave: No, this isn't really possible, sorry. For one, to encrypt or decrypt messages, you also need the subkey material. Then, for it to be the same OpenPGP key, you also need a bunch of metadata (creation time, etc). If you want something short, it might be better to use a raw ECDH key. E.g. see https://github.com/dchest/tweetnacl-js. Obviously this won't be compatible with OpenPGP, though.
