### ISSUE TITLE
 Error generating keypair: TextEncoder is not defined

### ISSUE THREAD

**Issue by robertst-bitgo** [openpgpjs/openpgpjs#1253]
Using the 5.0.0 version, I get an exception when trying to generate keys in Node.js:
``` Error generating keypair: TextEncoder is not defined``` 

This is most likely the result of commit ab419179bcc37b1dd598b3cf041b7b200d6f9208 (https://github.com/openpgpjs/openpgpjs/commit/ab419179bcc37b1dd598b3cf041b7b200d6f9208)

**Comment by twiss** [comment]
Hi :wave: Yeah. Node.js 10 is about 2 months from being End-of-Life: https://nodejs.org/en/about/releases/. Please switch to a newer version. If you can't, you can keep using OpenPGP.js v4 for now, but Node.js 10 (and OpenPGP.js v4) will be unsupported soon.
