### ISSUE TITLE
Get public key from private key

### ISSUE THREAD

**Issue by kor3k** [openpgpjs/openpgpjs#1282]
this might be a stupid question, but how can i get/derive public key from private key?

```
const privKey = await openpgp.readKey('-----BEGIN PGP PRIVATE KEY BLOCK....')
const pubKey = getPubKeyFromPrivKey(privKey)
```
is it possible? is it the one in `subKeys` prop?

**Comment by twiss** [comment]
Hey :wave: `privKey.toPublic()` should work (and then `.armor()` if you want it armored).
