### ISSUE TITLE
decrypt binary file to string is failing

### ISSUE THREAD

**Issue by rafipiccolo** [openpgpjs/openpgpjs#1292]
I have an xml file. i encrypted it as binary. i then try to decrypt it
it worked yesterday.

Failing with version openpgp": "^5.0.0-2"
Was working on version openpgp": "^5.0.0-1"

```
    const text = await fs.promises.readFile('xxxxx'); // the file i try to decrypt
    const privateKeyArmored = await fs.promises.readFile('xxxxx');
    const passphrase = 'xxxx';

    const privateKey = await openpgp.decryptKey({
        privateKey: await openpgp.readKey({ armoredKey: privateKeyArmored.toString() }),
        passphrase,
    });

    // failing here
    const message = await openpgp.readMessage({
        'binaryMessage': text,
    });

    const { data: decrypted, signatures } = await openpgp.decrypt({
        message,
        privateKeys: privateKey, // for decryption
    });

    console.log(decrypted); // 'Hello, World!'

```

it fails on openpgp.readMessage

```
TypeError: Cannot read property 'Symbol(byValue)' of undefined
      at Object.read (node_modules/openpgp/dist/node/openpgp.min.js:2:22713)
      at Ko (node_modules/openpgp/dist/node/openpgp.min.js:2:304610)
      at /usr/app/node_modules/openpgp/dist/node/openpgp.min.js:2:304794
      at Qs (node_modules/openpgp/dist/node/openpgp.min.js:2:260529)
      at async /usr/app/node_modules/openpgp/dist/node/openpgp.min.js:2:304761
```

**Comment by larabr** [comment]
Hi @rafipiccolo, can you share the encrypted file? And how it was encrypted, if you have the code.

**Comment by rafipiccolo** [comment]
The bank send me a file everyday. like this one
[file.zip](https://github.com/openpgpjs/openpgpjs/files/6397853/file.zip)
you can try unzip it and try decrypting it.

i dont have acces to their code, but i can usually decrypt it with no problem.

do you have a clue as why it states : Cannot read property 'Symbol(byValue)' of undefined

The file is damaged ?

**Comment by larabr** [comment]
I can confirm there is a bug on our side, introduced in 5.0.0-2, that always causes reading errors if some unsupported packets are found in the message, thanks for reporting! Please use an earlier version for now :)

**Comment by rafipiccolo** [comment]
Thx, when should be released the new version on npm please ?

**Comment by rafipiccolo** [comment]
thanks for the work but its wtill failing. i opened another issue #1315
