### ISSUE TITLE
Introduce `PrivateKey` and `PublicKey` classes

### ISSUE THREAD

**Issue by larabr** [openpgpjs/openpgpjs#1293]
The current `Key` class could be extended to have `PrivateKey` and `PublicKey` subclasses, thus allowing TS to statically check key type. Also, given the changes proposed in https://github.com/openpgpjs/openpgpjs/pull/1205#issuecomment-772888464, having distinct subclasses would allow to easily document where passing a public key is sufficient.

**Comment by tomholub** [comment]
excellent - this will be a great improvement
