### ISSUE TITLE
`valid` property missing on type VerificationResult

### ISSUE THREAD

**Issue by alete89** [openpgpjs/openpgpjs#1313]
Docs [here](https://github.com/openpgpjs/openpgpjs/blame/master/README.md#L236) say that you can ask for `.valid` to type `VerificationResult` which is defined [here](https://github.com/openpgpjs/openpgpjs/blob/f0280262172ddc54910c056e2c8d8d42be5643c2/openpgp.d.ts#L119) but it doesn't define `valid` property.

```ts
interface VerificationResult {
  keyID: KeyID;
  verified: Promise<null | boolean>;
  signature: Promise<Signature>;
}
```

![image](https://user-images.githubusercontent.com/4999277/119597164-e2b2d380-bdb6-11eb-9ea1-f5ceaf91c80c.png)

**Comment by twiss** [comment]
Hey :wave: You can `await signatures[0].verified` instead, which is equivalent. I kind of think that we should remove the `.valid` property entirely (from the code and the docs), as it only works when not streaming, whereas `.verified` always works. If you feel like making a PR for that instead, it'd be welcome :)

**Comment by alete89** [comment]
@twiss Oh, allright! Actually that was a secondary question I had. I'll close the PR I drafted and start a new one with this in mind. Thanks!

**Comment by larabr** [comment]
@alete89 are you still interesting in making a PR for this?
