### ISSUE TITLE
npmjs.com documents out of date

### ISSUE THREAD

**Issue by bitslayer42** [openpgpjs/openpgpjs#1330]
The documentation on https://www.npmjs.com/package/openpgp still has old variable names in the examples:
        publicKeys: publicKey, // for verification (optional)
        privateKeys: privateKey // for decryption

**Comment by larabr** [comment]
Hi @bitslayer42 , this will be fixed with the next package release

**Comment by twiss** [comment]
This is fixed in [v5.0.0-4](https://www.npmjs.com/package/openpgp/v/5.0.0-4) :)
