### ISSUE TITLE
Anything imported is undefined or an empty object when using Browserify

### ISSUE THREAD

**Issue by lf94** [openpgpjs/openpgpjs#1346]
Hey!

So it appears when importing anything from openpgp, it's undefined or empty. My version is 5.0.0-3 and I'm using it with webpack. Any ideas?...

**Comment by lf94** [comment]
Going into the `package.json` and changing `main` to point to `dist/openpgp.mjs` fixes the issue.

**Comment by lf94** [comment]
The issue is things are pointing toward `dist/node`

**Comment by twiss** [comment]
If you're importing openpgp.js as a module, it's supposed to take the path from the `module` entry in package.json, and when building for the browser (such as when using webpack) it's supposed to use the replacements from the `browser` entry. This means that normally, it's supposed to use `dist/openpgp.min.mjs`. Is there anything in your webpack resolver's configuration that would change this?

**Comment by lf94** [comment]
Yeah it's because of how I'm using it with browserify. All good!

**Comment by lf94** [comment]
I'm re-opening because it appears openpgpjs is just broken under browserify. There seems to be missing a property: `"openpgp": "./dist/openpgp.min.mjs"` from `"browser"`.

**Comment by lf94** [comment]
So it appears browserify is resolving using the `main` property....

**Comment by twiss** [comment]
Browserify is meant to take modules that are meant for Node.js, and convert them to modules for the browser. That is not necessary for OpenPGP.js, as it already has a build for the browser. So the solution is simply to exclude it from being browserified.

**Comment by lf94** [comment]
So this creates a sort of paradox for me:

If the openpgp import statement is in myfile.ts, babel generates a file with a require statement, and browserify seems to keep that require statement in there despite using `-u openpgp` and `-x openpgp`...

If the openpgp import statement is not in myfile.ts, tsc fails.

Any ideas?

**Comment by twiss** [comment]
It might be that the require statement makes browserify think that it must be a Node.js module.

Are you using [babelify](https://github.com/babel/babelify)? Doing the babel and browserify in the same step might help somehow.

**Comment by lf94** [comment]
I'm actually using `esmify`... I'll keep trying.

**Comment by lf94** [comment]
> It might be that the require statement makes browserify think that it must be a Node.js module.

Which would make it use the `main` property, yeah, that sounds right.

**Comment by lf94** [comment]
Yeah so browserify presumes the modules using CJS will work in the browser as well by default. Since openpgpjs's `main` property points to a Nodejs-only variant, this is why it doesn't work.

I think there are two options for me:

1. I publish a variant of this package with a modified `main` property, pointing to the `dist/openpgp.mjs`.
2. I somehow reference "openpgp/dist/openpgp.mjs" from within my typescript file and somehow fix the type associations.

**Comment by lf94** [comment]
I'm reviewing https://www.typescriptlang.org/docs/handbook/module-resolution.html to see if option 2 is a possibility.

**Comment by lf94** [comment]
It was a success.

To anyone:

* Using TSC for type checking only
* Using babel for transpilation
* Using browserify for browser bundling

You *must* use a tsconfig.json file with the following:

```
"baseUrl": "./",
"paths": { "openpgp/dist/openpgp.mjs": ["node_modules/openpgp"] }
```

And in your `.ts` files you *must* specify: `import { readKey /* example */ } from "openpgp/dist/openpgp.mjs"`

This is so browserify can bundle the appropriate, browser variant of openpgpjs.
