### ISSUE TITLE
"export 'stream' (imported as 'openpgp') was not found in 'openpgp'

### ISSUE THREAD

**Issue by ehte92** [openpgpjs/openpgpjs#1363]
Getting a warning in the latest version when I am using the openpgp.stream and also getting a type error

`TypeError: Cannot read property 'readToEnd' of undefined`

I am using the following to read the stream to the end and store it in a variable.

`const plainStr = await openpgp.stream.readToEnd(decryptBlob.data);`

Is there any new changes in the new version?

**Comment by larabr** [comment]
Hi @ehte92 ,  `openpgp.stream` was unexported in 5.0.0-2, see https://github.com/openpgpjs/openpgpjs/pull/1291 .
