### ISSUE TITLE
SyntaxError: await is only valid in async function in using Sequalize ORM with ExpressJS for 2 databases Postgres & Cassandara

### ISSUE THREAD

**Issue by saurTarento** [openpgpjs/openpgpjs#1364]
const query = '**some sql query** WHERE param1=? AND param2=?  ALLOW FILTERING '; 
    const params = [ param1, param2];

        client.execute(query, params, function (err, result) 
        {
            if (err) throw err
                if(err) 
                { 
                    console.log(err)
                }
            
            console.log(result.rows.length) // giving 10 output

            for(let i=0; i<result.rows.length; i++) 
            {
              const result = await db.userReport.findOne({  where: { param1: result[0] }  });
              console.log(result)                    
            }    

        })

**Comment by larabr** [comment]
Wrong repo? :)
