### ISSUE TITLE
WebStream and async iterator

### ISSUE THREAD

**Issue by NickDarvey** [openpgpjs/openpgpjs#1370]
I was following the examples and tried to follow [streaming encryption with a password](https://github.com/openpgpjs/openpgpjs#streaming-encrypt-uint8array-data-with-a-password) but I get the error:
```
Type 'WebStream<Uint8Array>' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.ts(2504)
```

I think this might just be the [type definition](https://github.com/openpgpjs/openpgpjs/blob/ab22fe86da37f4056d4240e943fce7c3d558c360/openpgp.d.ts#L535) as it looks like the [polyfill for ReadableStreams does support it](https://github.com/MattiasBuelens/web-streams-polyfill/blob/36c08de41aa3a5699afab717b0e64af13dada56f/src/lib/readable-stream.ts). Should `asyncIterator` be added to the type definition? `WebStream<>` or `BaseStream<>`?

**Comment by twiss** [comment]
Hey :wave: Yeah, good catch. Apparently [Node streams support this as well](https://nodejs.org/api/stream.html#stream_readable_symbol_asynciterator), so I think this could be added to `BaseStream` :+1:
