### ISSUE TITLE
config.rejectPublicKeyAlgorithms missing from @types/openpgp

### ISSUE THREAD

**Issue by LucasLongarini** [openpgpjs/openpgpjs#1380]
- OpenPGP.js version: 5.0.0-3 
- @types/openpgp version: 4.4.17
- Affected platform (Browser or Node.js version): Node v12.22.3

The parameter `rejectPublicKeyAlgorithms` on the `config` type is missing

**Comment by larabr** [comment]
Hi @LucasLongarini , good point, we are actually missing all the `config.reject*` properties, and probably more. PR welcome :)

FYI v5 doesn't use @types/openpgp anymore, the definitions are in https://github.com/openpgpjs/openpgpjs/blob/master/openpgp.d.ts .

**Comment by LucasLongarini** [comment]
PR: [https://github.com/openpgpjs/openpgpjs/pull/1385](https://github.com/openpgpjs/openpgpjs/pull/1385)

**Comment by larabr** [comment]
Thanks @LucasLongarini :)
