### ISSUE TITLE
PGP Session key decryption failed

### ISSUE THREAD

**Issue by alan19031216** [openpgpjs/openpgpjs#1398]
Hi guys, I got a problem.

I try to decrypt PGP msg in my local and staging environment, it can be decrypted successfully. 

But when I move on to the production environment, it shows "Error decrypting message: Session key decryption failed."

These three environments are using the same public, private key, and passphrase but return different results.

Local:
node: v14.17.1
npm: 7.17.0
openpgp: 4.10.0

Staging:
node: v10.20.0
npm: 6.14.4
openpgp: 4.10.0

Production:
node: v10.15.2
npm: 5.8.0
openpgp: 4.10.0

Below is my coding

```js
function decryptFunction(encrypted, callback) {
    openpgp.initWorker({ path: dbs_config.workerpath });
    openpgp.config.ignore_mdc_error = true 
    openpgp.config.allow_insecure_decryption_with_signing_keys = true

    var testPubKey = fs.readFileSync(dbs_config.serverPubPath, "ascii").trim();
    var testPriKey = fs.readFileSync(dbs_config.clientSecPath, "ascii").trim();

    var encWhole = (await openpgp.message.readArmored((encrypted)));

    var pubWhole = (await openpgp.key.readArmored(testPubKey));

    var pubInKey = pubWhole.keys;

    var priWhole = (await openpgp.key.readArmored(testPriKey));

    var priInKey = priWhole.keys[0];

    await priInKey.decrypt(dbs_config.cliPassphrase);

    const decoptions = {
        message: encWhole,
        publicKeys: pubWhole.keys,
        privateKeys: priInKey
    };

    var outMsg = openpgp.decrypt(decoptions).then(plaintext => {
        return plaintext.data;
    }).catch((e) => {
        console.log("error : " + e);
        throw e;
    });

    const outMsgTxt = await openpgp.stream.readToEnd(outMsg);
    msg = outMsgTxt;

    console.log("outMsgTxt-- " + outMsgTxt);
    callback(outMsgTxt);
}
```

_Originally posted by @alan19031216 in https://github.com/openpgpjs/openpgpjs/issues/1126#issuecomment-897493087_

**Comment by larabr** [comment]
Hi @alan19031216 , this is not enough info for us to debug the problem. Can you share the message and keys (encrypted)?
Also, note that node v10 is EOL since April 2021, so you might want to try upgrading and see if that solves the issue.

**Comment by alan19031216** [comment]
All

**Comment by alan19031216** [comment]
The problem that I have is due to the Node js version. I had upgraded to Node 12 and everything ok.
