### ISSUE TITLE
not catchable unhandle promise rejection exception

### ISSUE THREAD

**Issue by sylarwang** [openpgpjs/openpgpjs#1403]
having issue to handle this exception, when run this code within try and catch block:
```
try
{
await openpgp.decrypt
}catch(error){
//can't catch this error here
}
```

```
(node:33164) UnhandledPromiseRejectionWarning: Error: Insecure message hash algorithm: SHA1
    at Qs.verify (/Users/swang/development/workspace/GBS/CDI/nodejs-cdi-ftp-watcher/node_modules/openpgp/dist/node/openpgp.min.js:2:272341)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/swang/development/workspace/GBS/CDI/nodejs-cdi-ftp-watcher/node_modules/openpgp/dist/node/openpgp.min.js:2:342097
```
I understand `sha-1` is not supported, but this will break the app, ending with crash the nodejs process, this is not good, can you suggest how to fix this?

**Comment by larabr** [comment]
Hi @sylarwang , the code you posted is invalid, as `openpgp.decrypt` is a function, not a promise.

**Comment by sylarwang** [comment]
sorry, it's typo, it should be this:
```
try
{
await openpgp.decrypt(decryptOptions);
}catch(error){
//can't catch this error here
}
```

**Comment by sylarwang** [comment]
there were something wrong in my code, I didn't call `await verified()` to verify the signature. closing this
