### ISSUE TITLE
Parsing a single revocation certificate does not succeed

### ISSUE THREAD

**Issue by pbrunschwig** [openpgpjs/openpgpjs#1419]
OpenPGP.js version: 5.0.0

I'm trying to parse/import a revocation certificate to a key. That is, given a revocation certificate, I need to find out to which key it belongs and then apply the certificate to that key. In OpenPGPjs 4.x, I could parse the cert using openpgp.message.parse(), and then iterate over the packets to find out if it's a signature -> key revocation packet.

However, now neither readKey() nor readSignature() would allow to process the revocation certificate. Any idea how to solve this?

**Comment by twiss** [comment]
Hey :wave: I think you could do something like:

```js
import { unarmor, PacketList, SignaturePacket } from 'openpgp';
const binary = await unarmor(revocationCertificate);
const packetlist = await PacketList.fromBinary(binary.data, new Map([[SignaturePacket.tag, SignaturePacket]]);
const revocationSignature = packetlist.findPacket(SignaturePacket.tag);
```

(Partially extracted from [`applyRevocationCertificate`](https://github.com/openpgpjs/openpgpjs/blob/3fa778abe2902e75ae5b1e7f6327467eef91a761/src/key/key.js#L568-L571), but otherwise untested.)

Admittedly, we could make this slightly easier (but `applyRevocationCertificate` assumes that you already know which key the revocation certificate applies to, indeed).

**Comment by pbrunschwig** [comment]
I already tried this method before creating this ticket. Unfortunately `PacketList.fromBinary()` throws the following error: 

`"Error: Error: Packet not allowed in this context: signature"`

**Comment by larabr** [comment]
The code posted by Daniel works for me, make sure you include the second argument when calling `PacketList.fromBinary` 👍

**Comment by pbrunschwig** [comment]
I did exactly what Daniel did. Did you try this with a single revocation certificate, or with a complete public key that contains a revocation certificate? 

I attached the revocation certificate I'm trying to read.
[dev-strike.txt](https://github.com/openpgpjs/openpgpjs/files/7253504/dev-strike.txt)

**Comment by twiss** [comment]
(The code I initially posted had a bug, so I edited it, did you try the new version? It's intended to work with a lone revocation certificate indeed.)

**Comment by pbrunschwig** [comment]
Oh, I see, I'll try that :-)

**Comment by pbrunschwig** [comment]
Thanks, the new version works :-)
