### ISSUE TITLE
Performance Issue During Signature Verification

### ISSUE THREAD

**Issue by theshh** [openpgpjs/openpgpjs#1424]
```
const readableStream = fs.createReadStream('enc.zip.pgp');
readableStream.setEncoding('UTF8')

const message = await openpgp.readMessage({
      armoredMessage: readableStream 
});

const { data: decrypted, signatures } = await openpgp.decrypt({
        message,
        verificationKeys: [senderPublicKey],
        decryptionKeys: [ privateKey],
        format: 'binary'
});

try {
        await signatures[0].verified;
 } catch (err) {
        console.log(err.message);
}
```

When performing decryption + signature verification for large files (e.g. 1GB in size) using `ReadableStream` , there seems to be a performance overhead where `await signatures[0].verified;` may take up to a couple of minutes to complete. Alternatively, adding `expectSigned: true` also results in UnhandledPromiseRejection thus preventing the error from being handled gracefully - for cases where message is signed with a mismatch verification key.

**Comment by twiss** [comment]
Hello :wave: Sorry for the delay. [v5.0.1](https://github.com/openpgpjs/openpgpjs/releases/tag/v5.0.1) should improve performance, let me know if it does for you. I've opened #1443 to remind myself to look at the `UnhandledPromiseRejection` issue.
