### ISSUE TITLE
Look into UnhandledPromiseRejection when using expectSigned: true with streaming

### ISSUE THREAD

**Issue by twiss** [openpgpjs/openpgpjs#1443]
See #1424.

**Comment by twiss** [comment]
@theshh I can't actually reproduce this issue. Please note that, when streaming, the signature verification error may end up in the data stream, so you need to consume the decrypted data stream (and properly catch errors there). Let me know if you still have issues.

**Comment by theshh** [comment]
All good, with the latest fix that seems to now work well. Thanks a lot! 

like you said, trade off using much more memory

**Comment by twiss** [comment]
:+1:

Yeah, I'll look into that :relaxed:
