### ISSUE TITLE
Error decrypting message: Session key decryption failed.

### ISSUE THREAD

**Issue by varsha123** [openpgpjs/openpgpjs#1521]
### Discussed in https://github.com/openpgpjs/openpgpjs/discussions/1520

<div type='discussions-op-text'>

<sup>Originally posted by **varsha123** May 16, 2022</sup>
Hi Team

we are facing below error : while decrypting signencrypted file generated using Bouncycastle library

Error decrypting message: Session key decryption failed.

Also same file we have tried with GPG tool: we received below detail: plz suggest what's wrong here in this file or our process

gpg: encrypted with rsa3072 key, ID ###############, created 2021-10-26
"Tazapay Devops (Tazapay SCB dev PGP) <#########>"
gpg: used key is not marked for encryption use.
File 'doc' exists. Overwrite? (y/N) n
Enter new filename: doc1
gpg: Signature made 12-May-22 11:31:45 AM India Standard Time
gpg: using RSA key ###################
gpg: issuer "##############"
gpg: Good signature from "###############" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg: There is no indication that the signature belongs to the owner.
Primary key fingerprint: #########################################
gpg: WARNING: message was not integrity protected
gpg: decryption forced to fail!

GPG version :
gpg (GnuPG) 2.3.6
libgcrypt 1.10.1
Copyright (C) 2021 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.

Please let us know how to fix this.

below is our decryption code

   const messagedecrypt:any =fs.readFileSync("TESTPGP_PGPOUT", "utf8");
    const message:any = await openpgp.readMessage({
        armoredMessage: messagedecrypt, // parse armored message       
    });
  
    const { data: decrypted, signatures } = await openpgp.decrypt({
        message,
        verificationKeys: publicKey, // optional
        decryptionKeys: privateKey1
    });
    console.log("decrypted-----");
    console.log(decrypted); // 'Hello, World!'
    console.log(message.packets[0].publicKeyId);

    try {
        await signatures[0].verified; // throws on invalid signature
        console.log('Signature is valid');
    } catch (e) {
        throw new Error('Signature could not be verified: ' + e.message);
    }

Thanks
Varsha</div>

**Comment by twiss** [comment]
Please don't create duplicate issues and discussions. It won't get you helped faster. You can ask on https://gitter.im/openpgpjs/openpgpjs instead.

**Comment by varsha123** [comment]
> Hi Team
> 
> we are facing below error : while decrypting signencrypted file generated using Bouncycastle library
> 
> Error decrypting message: Session key decryption failed.
> 
> Also same file we have tried with GPG tool: we received below detail: plz suggest what's wrong here in this file or our process
> 
> gpg: encrypted with rsa3072 key, ID ###############, created 2021-10-26 "Tazapay Devops (Tazapay SCB dev PGP) <#########>" gpg: used key is not marked for encryption use. File 'doc' exists. Overwrite? (y/N) n Enter new filename: doc1 gpg: Signature made 12-May-22 11:31:45 AM India Standard Time gpg: using RSA key ################### gpg: issuer "##############" gpg: Good signature from "###############" [unknown] gpg: WARNING: This key is not certified with a trusted signature! gpg: There is no indication that the signature belongs to the owner. Primary key fingerprint: ######################################### gpg: WARNING: message was not integrity protected gpg: decryption forced to fail!
> 
> GPG version : gpg (GnuPG) 2.3.6 libgcrypt 1.10.1 Copyright (C) 2021 g10 Code GmbH License GNU GPL-3.0-or-later https://gnu.org/licenses/gpl.html This is free software: you are free to change and redistribute it.
> 
> Please let us know how to fix this.
> 
> below is our decryption code
> 
> const messagedecrypt:any =fs.readFileSync("TESTPGP_PGPOUT", "utf8"); const message:any = await openpgp.readMessage({ armoredMessage: messagedecrypt, // parse armored message });
> 
> ```
> const { data: decrypted, signatures } = await openpgp.decrypt({
>     message,
>     verificationKeys: publicKey, // optional
>     decryptionKeys: privateKey1
> });
> console.log("decrypted-----");
> console.log(decrypted); // 'Hello, World!'
> console.log(message.packets[0].publicKeyId);
> 
> try {
>     await signatures[0].verified; // throws on invalid signature
>     console.log('Signature is valid');
> } catch (e) {
>     throw new Error('Signature could not be verified: ' + e.message);
> }
> ```
> 
> Thanks Varsha

ok sure.. I am waiting  for updates from last 2-3days so added new issue as earlier one was closed

**Comment by varsha123** [comment]
ok noted

**Comment by sshtel** [comment]
`await openpgp.decrypt({
            message,
            config: {
                allowInsecureDecryptionWithSigningKeys: true,
            },
            verificationKeys: publicKey,
            decryptionKeys: privateKey
        });`

try this config. this works for me
