### ISSUE TITLE
Documentation link on website leads to 404

### ISSUE THREAD

**Issue by smbkr** [openpgpjs/openpgpjs#1531]
The link to the documentation on the home page (https://openpgpjs.org) leads to https://docs.openpgpjs.org, however this URL leads to a Github pages 404 not found error.

**Comment by smbkr** [comment]
Looks like you can access the docs at https://openpgpjs.github.io/openpgpjs/ in case anyone else is searching for them

**Comment by twiss** [comment]
:+1: Thanks! Fixed.
