### ISSUE TITLE
Signature not found in a signed file

### ISSUE THREAD

**Issue by sambs** [openpgpjs/openpgpjs#1543]
- OpenPGP.js version: 5.3.1
- Affected platform: Node.js 16.6.1

I am trying to decrypt and verify a signed file. The `gpg` command line tool tells me the file signature is present and correct, however openpgpjs reports that a signature is not found:

```
await openpgp.decrypt({
    message,
    verificationKeys: theirPublicKey,
    decryptionKeys: ourPrivateKey,
    expectSigned: true,
})
// -> Error decrypting message: Message is not signed
```

I am able to decrypt without expecting a signature:

```
await openpgp.decrypt({
    message,
    verificationKeys: theirPublicKey,
    decryptionKeys: ourPrivateKey,
    expectSigned: false,
})
// -> Succesful decryption
```

Calling the message's verify method directly produces the following error:

```
await message.verify([theirPublicKey])
// -> Error: Can only verify message with one literal data packet
```

I'm not able to share the file itself but heres the output of `gpg --list-packets`:

```
# off=0 ctb=a8 tag=10 hlen=2 plen=3
:marker packet: PGP
# off=5 ctb=c1 tag=1 hlen=3 plen=268 new-ctb
:pubkey enc packet: version 3, algo 1, keyid XXXXXX
        data: XXXXXX
# off=276 ctb=d2 tag=18 hlen=2 plen=0 partial new-ctb
:encrypted data packet:
        length: unknown
        mdc_method: 2
# off=289 ctb=c8 tag=8 hlen=2 plen=0 partial new-ctb
:compressed packet: algo=1
# off=292 ctb=c4 tag=4 hlen=2 plen=13 new-ctb
:onepass_sig packet: keyid XXXXXX
        version 3, sigclass 0x00, digest 8, pubkey 1, last=1
# off=307 ctb=cb tag=11 hlen=2 plen=0 partial new-ctb
:literal data packet:
        mode b (62), created 0, name="file.name",
        raw data: unknown length
```

Ia surprised not to see a signature packet here, but as I say, somehow `gpg` is able to find and verify a signature:

```
❯ gpg --decrypt file.name > /dev/null

gpg: encrypted with rsa2048 key, ID XXXXXX, created 2022-03-31
      "XXXXX"
gpg: Signature made Mon  4 Jul 13:01:55 2022 BST
gpg:                using RSA key XXXXXX
gpg: Good signature from "XXXXXX" [unknown]
```

**Comment by larabr** [comment]
I think the missing signature packet in the gpg list-packets output might just be due to the fact that the tool cannot determine the literal packet size, due to a known limitation (see https://lists.gnupg.org/pipermail/gnupg-users/2006-May/028610.html).
It's hard to tell what's wrong with just this list-packet output.

Can you try to pass `config: { ignoreUnsupportedPackets: false }` as additional option to `decrypt`, and see if you get a different error? Perhaps the signature is of a legacy type.

**Comment by sambs** [comment]
Thanks @larabr, you're right. With `config: { ignoreUnsupportedPackets: false }` I get:

```
Error decrypting message: Version 3 of the signature packet is unsupported.
```

I guess that means I'll have to look for a different solution. Sadly I doubt I'll be able to get the sender to update their software.
