### ISSUE TITLE
Clarify usage of config.s2kIterationCountByte

### ISSUE THREAD

**Issue by redongh** [openpgpjs/openpgpjs#1565]
- OpenPGP.js version: 5.5.0
- Affected platform (Browser): 
  - Brave 1.43.89 (Chromium 105.0.5195.102)
  - Firefox 104.0.1 (64-bit)

loading the following content saved to a file `test.html` into one of the browsers listed above (others not tested)
```
<script src="openpgp.js"></script>                                                                                    
<h3>test s2kIterationCountByte 65011712</h3>
<script lang="JavaScript">                                                                                            
(async () => {                                                                                                        
  const { privateKey, publicKey, revocationCertificate } = await openpgp.generateKey({                                
    type: 'ecc',
    curve: 'curve25519',
    config: { s2kIterationCountByte: 65011712 },                                                                                                       
    userIDs: [{ name: '', email: 'test@foo.bar' }],                                
    passphrase: 'iloveyou',                                                                 
    format: 'armored'          
  });

    console.log(privateKey);   // '-----BEGIN PGP PRIVATE KEY BLOCK ... '
    console.log(publicKey);    // '-----BEGIN PGP PUBLIC KEY BLOCK ... '
    console.log(revocationCertificate);  // '-----BEGIN PGP PUBLIC KEY BLOCK ... '
})();
</script>
```

and copying the generated privkey from the browsers console and feeding it into either `pgpdump` or `gpg --list-packets` yields a (protect) count of **1024** (coded count 0) instead an expected value of **65011712**.
If the value given is diminished by one to 6501171**1**, the result actually after _pgpduming_ the privkey reads 6501171**2** so i suppose there is a minor flaw in the calculation of the value for the coded count which could have quite some security implications (render attacks more feasible and efficient) if not double checked.

**Comment by larabr** [comment]
The value needs to be of byte format, namely between 0-255. See [the spec](https://datatracker.ietf.org/doc/html/draft-ietf-openpgp-rfc4880bis-10#section-3.7.1.3) for more info about the value `c` (octect 10)
