### ISSUE TITLE
ReadableStream is no longer overwritten in OpenPGP.js >= 5?

### ISSUE THREAD

**Issue by nwtgck** [openpgpjs/openpgpjs#1566]
Thank you so much for the great library. It helps me a lot.

The current README.md says as follows.

> Please note that in those browsers, the global ReadableStream property gets overwritten with the polyfill version if it exists. 

https://github.com/openpgpjs/openpgpjs/tree/d0be98feb9ab3ca3a7e22e04d0603e39bf762bcb#platform-support

However, the 5.0.0 release note says as follows.

> The [web-streams-polyfill](https://github.com/MattiasBuelens/web-streams-polyfill) and [web-streams-adapter](https://github.com/MattiasBuelens/web-streams-adapter) libraries are only loaded when streaming is used, and only if TransformStreams aren't natively supported

https://github.com/openpgpjs/openpgpjs/releases/tag/v5.0.0

So I guess ReadableStream is no longer overrwitten in 5. I confirmed not overwritten in Firefox ESR 91 in which previously it is overwritten. Could we update the document?

**Comment by twiss** [comment]
Hey :wave: Yes, you're right, the document is outdated, thanks for catching that. Do you feel like making a PR, by any chance?

**Comment by nwtgck** [comment]
Hi!
I think the maintainers are the best people to maintain the own documents. But if noone do that, I'll make it.

**Comment by larabr** [comment]
This will likely get fixed sooner if you make a PR 😄

**Comment by larabr** [comment]
This is now clarified in the v6 README.

**Comment by nwtgck** [comment]
Thanks!
