### ISSUE TITLE
rawNotations Property Missing from SignaturePacket Type

### ISSUE THREAD

**Issue by LeoKotschenreuther** [openpgpjs/openpgpjs#1569]
- OpenPGP.js version: v5.5.0
- Affected platform (Browser or Node.js version): Node.js v14.17.5

The `rawNotations` property is missing from the `SignaturePacket` type in the projects [openpgp.d.ts](https://github.com/openpgpjs/openpgpjs/blob/v5.5.0/openpgp.d.ts#L477) file.

Consider the following function:
```
import openpgp from 'openpgp';

async function getNumberOfRawNotations(signature: openpgp.Key): Promise<number> {
  const primaryUser = await walletSignature.getPrimaryUser();
  return primaryUser.user.otherCertifications[0].rawNotations.length;
}
```

TypeScript errors on compilation with the error `TS2339: Property 'rawNotations' does not exist on type 'SignaturePacket'.` even though the [property exists on the implementation of the `SignaturePacket`](https://github.com/openpgpjs/openpgpjs/blob/v5.5.0/src/packet/signature.js#L79).

I can submit a PR to fix this myself if somebody is so kind and lets me know what type the `rawNotations` property is.

**Comment by larabr** [comment]
Hi, thanks for spotting this, it'd be great if you could open a PR.
The type of a `rawNotation` entry is `{ name: string; value: Uint8Array(); humanReadable: boolean }` -- `rawNotations` is an array of those. 🙂

**Comment by LeoKotschenreuther** [comment]
Here you go: https://github.com/openpgpjs/openpgpjs/pull/1571

**Comment by larabr** [comment]
Thanks for the fix!
