### ISSUE TITLE
Missing function declaration in SubKey type

### ISSUE THREAD

**Issue by FabienForestier** [openpgpjs/openpgpjs#1587]
The SubKey class has a `getExpirationTime` (https://github.com/openpgpjs/openpgpjs/blob/50ea1ac8890d3cf75c88330129e098951a48434e/src/key/subkey.js#L110) but the type definition of a SubKey in openpgp.d.ts does not declare this function.

Am I missing something or should the method be declared in the typings ?

**Comment by larabr** [comment]
Typings are not complete, feel free to open a PR :)

**Comment by FabienForestier** [comment]
Yup, here is the pull request: https://github.com/openpgpjs/openpgpjs/pull/1588

**Comment by larabr** [comment]
Fixed
