### ISSUE TITLE
Allow adding recipients retroactively

### ISSUE THREAD

**Issue by feefladder** [openpgpjs/openpgpjs#1605]
### Discussed in https://github.com/openpgpjs/openpgpjs/discussions/1604

<div type='discussions-op-text'>

<sup>Originally posted by **feefladder** February 23, 2023</sup>
I'm working on a way to share files in an end-to-end encrypted way, possibly using PGP. The files are rather big and therefore re-encrypting the file would take pretty long. What I'm looking to implement is something like this:
![E2E_add_recipient](https://user-images.githubusercontent.com/33122845/220954960-589df94a-08bc-47bc-905a-e192b5cf7eee.png)
It is important that files on the server are PGP encrypted, because it is a standard, and I would like to make a module that allows for decryption using hardware keys like so:
![E2E_decrypt](https://user-images.githubusercontent.com/33122845/220958416-c38d1132-9746-451e-a9f1-aeb0636a769b.png)
Now again, because these are large files, it would cost the Data Provider quite some bandwidth to: 

1. Download the data
2. re-encrypt the data with Data User's public key
3. re-upload the data that is encrypted using a different AES key

According to [this answer](https://security.stackexchange.com/a/244951/289735) it is technically possible, but not supported by tools. I would be willing to help work on this if possible :)</div>

**Comment by larabr** [comment]
I'll close this for now, to keep the conversation in one place (#1604). Based on the outcome of the discussion we can open specific issues or PRs directly :)
