### ISSUE TITLE
CI: update Mocha and Sinon to newer versions (using Node's native esm support)

### ISSUE THREAD

**Issue by Sanddrah** [openpgpjs/openpgpjs#1607]
![Screenshot (16)](https://user-images.githubusercontent.com/95150675/222578044-818297d0-e9e7-4cca-9204-879e34f7609d.png)

Hi
Some tests are failing in your package. Can you kindly fix them so we can integrate the changes in the Debian package.
Also, I will be very grateful if you can upgrade sinon dependency to at least version 14.0.2

**Comment by larabr** [comment]
The tests are passing on CI for node 14 to 18, as you can see here: https://github.com/openpgpjs/openpgpjs/actions/runs/4235637879
What version of node are you using?

Regarding sinon, what's the motivation for updating it? It'd be a breaking change, so not as simple as upgrading the dependency, and it's also dev only, so generally not a priority

**Comment by Sanddrah** [comment]
Thanks for your response!
For sinon, we only have version 14 in Debian, and unfortunately we don't maintain multiple versions of a package in Debian.
So I have to find a way to make openpgp package work with sinon 14.
It will be great relief if you can make this upgrade

**Comment by Sanddrah** [comment]
Here are the changes I made: https://salsa.debian.org/sandra_uwah/node-openpgp/-/blob/master/debian/patches/use-node-esm-support.patch
I attempted patching openpgp package to use NodeJs's in-build ECMAScript module support rather than depending on the esm package.

**Comment by Sanddrah** [comment]
> The tests are passing on CI for node 14 to 18, as you can see here: https://github.com/openpgpjs/openpgpjs/actions/runs/4235637879 What version of node are you using?
> 
> Regarding sinon, what's the motivation for updating it? It'd be a breaking change, so not as simple as upgrading the dependency, and it's also dev only, so generally not a priority

Thanks for your response!
For sinon, we only have version 14 in Debian, and unfortunately we don't maintain multiple versions of a package in Debian.
So I have to find a way to make openpgp package work with sinon 14.
It will be great relief if you can make this upgrade

**Comment by Sanddrah** [comment]
Here are the changes I made: https://salsa.debian.org/sandra_uwah/node-openpgp/-/blob/master/debian/patches/use-node-esm-support.patch
I attempted patching openpgp package to use NodeJs's in-build ECMAScript module support rather than depending on the esm package.

**Comment by larabr** [comment]
Could you post the error stack trace?
I think that patch might have unintended consequences. @twiss what do you think? If it works, maybe we could try and integrate that change in a minor release? It'd also be helpful to be able to update mocha (v9+ do not support esm).

**Comment by Sanddrah** [comment]
> > Here are the changes I made: https://salsa.debian.org/sandra_uwah/node-openpgp/-/blob/master/debian/patches/use-node-esm-support.patch
> > I attempted patching openpgp package to use NodeJs's in-build ECMAScript module support rather than depending on the esm package.
> 
> Could you post the error stack trace? I think patching imports might have unintended consequences. @twiss what do you think? If it works, maybe we could try and integrate those changes in a minor release? It'd also be helpful to be able to update mocha (v9+ do not support esm) and to start using TS.

Here are the logs: https://paste.debian.net/1272608/
