### ISSUE TITLE
verifyAllUsers() returns userID error for keys that contains image data

### ISSUE THREAD

**Issue by martgil** [openpgpjs/openpgpjs#1636]
- OpenPGP.js version: `"openpgp": "^5.8.0"`
- Affected platform (Browser or Node.js version): Node.js (I haven't tried for the Browser version/dist)

Description:

During my testing, OpenPGP.js `verifyAllUsers()` fails to work and returns `TypeError: Cannot read properties of null (reading 'userID')` when parsing a public key/key pair that contains image data. eg image added with gpg's `addphoto` command.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/46025304/234201824-c3d4a9bd-a5cc-4a75-ac58-11c6e81c16ef.png">

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/46025304/234200653-9694b35e-847d-4f3e-8367-37465239bc55.png">

File to use: 
[sample.pub.txt](https://github.com/openpgpjs/openpgpjs/files/11319793/sample.pub.txt)

Steps to reproduce:
```javascript
const key = `$armored_key`;
const k = openpgp.readKey({armoredKey: key});
const vk = (await k).verifyAllUsers(k);
console.log(vk);
```

**Comment by twiss** [comment]
Hey :wave: Thanks for the report! Indeed it seems like this function doesn't take User Attributes into account. We'd welcome a PR to fix this :)

**Comment by martgil** [comment]
Thank you! I attempt to fix this issue on https://github.com/openpgpjs/openpgpjs/pull/1637 based on the original issue. I'd love to contribute to OpenPGP.js as much as I'd like but if the fix requires more in-depth javascript - It's sad to say but I'm not really good at JS.
