### ISSUE TITLE
Getting error "No public key encrypted session key packet found" when decrypting

### ISSUE THREAD

**Issue by yashsinghvi3011** [openpgpjs/openpgpjs#1647]
- OpenPGP.js version: 5.9.0
- Affected platform (Browser or Node.js version): 12.16.1

I am using the openpgpjs version 5.9.0 and getting the error while decrypting the data. Below is the code. Can someone please help me out with it?

--------------------------------------------------------------------------------------------------------------------------------------------

const openpgp = require('openpgp');
const { readFileSync } = require('fs');

const fun3 = async () => {
    try {
        const passphrase = 'Admin@123';
        const privateKeyArmored = readFileSync('./private-key.asc', 'utf8');
        const privateKey = await openpgp.decryptKey({
        privateKey: await openpgp.readPrivateKey({ armoredKey: privateKeyArmored }),
        passphrase
        });
      
        const publicKeyArmored = readFileSync('./public-key.asc', 'utf8');
        const publicKey = await openpgp.readKey({ armoredKey: publicKeyArmored });
      
        const encryptedAndSignedMessage = readFileSync('./import.json.pgp', 'utf-8');
        var encryptedUint8 = new TextEncoder().encode(encryptedAndSignedMessage);
        const message = await openpgp.readMessage({
            binaryMessage: encryptedUint8
        });
        const { data } = await openpgp.decrypt({
            message,
            decryptionKeys: privateKey,
            verificationKeys: publicKey
        });
        console.log(data);
    } catch (e) {
        console.log('error', e);
    }
}

fun3();

**Comment by larabr** [comment]
Closing in favor of https://github.com/openpgpjs/openpgpjs/discussions/1646
