### ISSUE TITLE
Uint8Array - related issues in Firefox content script (sandboxed environment)

### ISSUE THREAD

**Issue by rrrooommmaaa** [openpgpjs/openpgpjs#1648]
- OpenPGP.js version: 5.9.0
- Affected platform: Firefox when loaded as a content script of web extension

In this setup we have 2 different Uint8Array types depending on where they were initialized: `openpgp.js` (Sandbox) or Web Cryptography API.

The sandboxed arrays are only recognizable as `globalThis.Uint8Array`, while the ones returned by Web Cryptography API are `(window.)Uint8Array`

So we currently need to patch `openpgp.js` for every occurrence of the pattern like `x instanceof Uint8Array`
replacing it with `x instanceof Uint8Array || x instanceof globalThis.Uint8Array`

I also found a helper function `is_bytes` in the codebase.
Can we fix it like this and call it from all the other places?
```
  function is_bytes(a) {
      return (a instanceof Uint8Array || a instanceof globalThis.Uint8Array);
  }
```
There are more details of this research: https://github.com/FlowCrypt/flowcrypt-browser/pull/5013#discussion_r1148343995

There is also an issue calling `subarray` and `slice` methods on `(window.)Uint8Array` in this setup -- permission denied.
It's better to not use these methods or create a sandbox copy of Uint8Array on arrays returned from  Web Cryptography API

**Comment by twiss** [comment]
Hello :wave: I'm a bit confused by this issue as the Web Crypto API does not return `Uint8Array`s, it returns `ArrayBuffer`s. We create `Uint8Array` views over them ourselves, for example here: https://github.com/openpgpjs/openpgpjs/blob/400b163f8411204f5de830b70e65fd86246cf933/src/crypto/hash/index.js#L63
I don't see any reason why taking a `subarray` or `slice` of such `Uint8Array`s would not be allowed - have you raised an issue with Firefox?

**Comment by rrrooommmaaa** [comment]
> I don't see any reason why taking a `subarray` or `slice` of such `Uint8Array`s would not be allowed - have you raised an issue with Firefox?

I can understand the mechanics of it -- when calling `subarray` or `slice`, the returned array is expected to be of the same class as the original one, that is an 'array with elevated privileges' (or an array belonging to a process with elevated privileges) should spawn an 'array with elevated privileges' as well, and this isn't allowed in the sandboxed environment -- `Permission denied` exception is raised. Perhaps, I can raise an issue with Firefox about it.

> I'm a bit confused by this issue as the Web Crypto API does not return Uint8Arrays, it returns ArrayBuffers.

If I remember, correctly it happened when serializing params in `uint8ArrayToMPI` (or `uint8ArrayBitLength`)-- `bin.subarray` call. I'll need to run the unpatched version again to reproduce this behavior, if needed. Can it be that Crypto API provides `Uint8Array`s in `CryptoKey` objects, e.g. `algorithm.publicExponent`
https://developer.mozilla.org/en-US/docs/Web/API/RsaHashedKeyGenParams
I didn't analyze that too deep, I guess you know where `bin` may be coming from.

**Comment by twiss** [comment]
> `stripped = bin.subarray(i);` caused this exception `Error: Permission denied to access property "constructor"`

Do you have a stack trace? This code comes from a helper functions so it's not entirely clear in which context this would break.

> Can it be that Crypto API provides `Uint8Array`s in `CryptoKey` objects, e.g. `algorithm.publicExponent`

As far as I can tell, we don't use this property anywhere. E.g. in the case of key generation we take the modulus from base64 and convert it to a Uint8Array ourselves, here: https://github.com/openpgpjs/openpgpjs/blob/bb0c1f8a08586ab83e0bdca57771e4c29c199b88/src/crypto/public_key/rsa.js#L181-L184.

**Comment by twiss** [comment]
Btw, a tangential thought; there is another API that we're using that does return Uint8Arrays, namely [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder). Though, normally we probably wouldn't call `subarray` or `slice` on those, except in the case of streaming. Is it possible that that's causing the issues you're seeing?

**Comment by rrrooommmaaa** [comment]
Yes, it is pretty much possible that these arrays are coming from `TextEncoder`. I didn't analyze the source code too deep, Crypto API was just my guess, as good as any other API. I noticed that these arrays have the mentioned peculiarities as opposed to those created inside OpenPGP.js (sandboxed) code with `new Uint8Array` statements.

**Comment by twiss** [comment]
Right. So - in that case, patching `TextEncoder` (e.g. by doing something like [this](https://github.com/openpgpjs/openpgpjs/discussions/1225#discussioncomment-354251)) might help (though that particular patch has a performance cost - patching the native `TextEncoder` to return "normal" `Uint8Array`s might be more efficient).

If that does help, I would indeed report an issue to Firefox as well :relaxed:
