### ISSUE TITLE
Import fails with web-stream-tools 0.0.14

### ISSUE THREAD

**Issue by IvanPizhenko** [openpgpjs/openpgpjs#1659]
OpenPGP.js version: 5.9.0
Affected Platform: Node 18

I have some unit tests written with AVA.
I have had
```
    "@openpgp/web-stream-tools": "^0.0.13",
    "openpgp": "^5.9.0",
```
in my package.json and all was working good.
Recetntly dependabot update came, which updated web-stream-tools to 0.0.14.
After this I started getting an error:
```
Error: Cannot find module '../../../../node_modules/@openpgp/web-stream-tools/lib/streams.js'
```
But I am not directly importing anything from web-stream-tools. It come through openpgp.js.

What I've found:
- in the web-stream-tools 0.0.14, their "main" file changed from "streams.js" to "index.js"
- openpgp.js seems to still use web-stream-tools 0.0.11

**Comment by larabr** [comment]
openpgpjs will update web-stream-tools in the v6 release, since v0.0.12 and above have some breaking changes.
If you have issues importing web-stream-tools, then please open an issue there: https://github.com/openpgpjs/web-stream-tools/issues
