### ISSUE TITLE
crypto-refresh branch inline signing produces OPS with salt that doesn't match signature

### ISSUE THREAD

**Issue by dkg** [openpgpjs/openpgpjs#1669]
https://tests.sequoia-pgp.org/v6.html#Inline_Sign_with_minimal_key_from_RFC9760_and_key__Alice___verify_with_key_from_RFC9760 shows that OpenPGP.js 5.7.0+crypto-refresh creates the following inline-signed message:

```
-----BEGIN PGP MESSAGE-----

xA0DAQoW8jFVDE9H444AxEYGAQobIAY4S2nzPlCh3VLXF8om0R0DILb9alp7
i2uIvIUTQiWiyxhsTwYJppfk1S36bHIrDB8eJ8GKVnCPZSXsJ7rZrMkByxR1
AGTnYPdIZWxsbyBXb3JsZCA6KcKYBgEbCgAAACkFgmTnYPcioQbLGGxPBgmm
l+TVLfpscisMHx4nwYpWcI9lJewnutmsyQAAAAAwiyCzv2nMwzCTbldk7n3L
sfv6hngz8VRhP9+aXYkDCi2qf2mpEhYy/aXLfYAFoGYi54cOH08VLvsVveVT
9uyzUZ2Ws1fENvp0MB3Tm4AEYxqhwSSaUDwVy2SInCfIMtw4YArCdQQBFgoA
JwWCZOdg9wmQ8jFVDE9H444WIQTrhbtfozp14V6UTmPyMVUMT0fjjgAA5fUB
AKYPXR+VnVolNN4zLjTvMLBFhHyKbnfqCDToMtN+E7KCAQC2cCkuGkw9jh/R
aMtvyNkyihUYpi7BrqPLqkIwX+0zBg==
-----END PGP MESSAGE-----
```

The leading one-pass signature (OPS) v6 packet contains this salt: `06384B69F33E50A1DD52D717CA26D11D0320B6FD6A5A7B8B6B88BC85134225A2`, but the actual v6 signature packet contains this salt: `B3BF69CCC330936E5764EE7DCBB1FBFA867833F154613FDF9A5D89030A2DAA7F`.

Non-streaming implementations might ignore the mismatched salts, but implementations that use a streaming interface are not going to work at all correctly.

**Comment by larabr** [comment]
Thanks for the report.
Fix included in #1630 and now published in the crypto-refresh branch too 👍
