### ISSUE TITLE
Handle closing the file descriptors in Node 20.x.x when work with streams

### ISSUE THREAD

**Issue by 10kc-svats** [openpgpjs/openpgpjs#1690]
- OpenPGP.js version: `5.5.0`
- Affected platform (Browser or Node.js version): > Node 20.x.x

When we switched from node 18 to node 20 we've encountered this problem, where `decrypt` method resolves the promise, but the `data` does not contain a decrypted stream.

The code reads a file using a stream with the `fs.createReadStream` method. If the stream isn't properly closed (either because of an error, or because the stream wasn't fully read), the file remains open. In the original code, we were passing the stream directly to `openpgp.readMessage`, and if `openpgp.readMessag`e didn't read the stream fully or there was an error in between, the stream was left open.

The piece of code:
```js
const stream = fs.createReadStream(filePath, 'utf-8');
const privateKey = await openpgp.decryptKey({
  privateKey: await openpgp.readPrivateKey({
    armoredKey: this.privateKeyASCII,
  }),
  passphrase: this.passPhrase,
});
const options: openpgp.DecryptOptions = {
  decryptionKeys: privateKey,
  message: await openpgp.readMessage({
    armoredMessage: stream,
  }),
};
const { data } = await openpgp.decrypt(options);
return data;
```
<img width="1271" alt="Screenshot 2023-10-05 at 3 18 43 PM" 
src="https://github.com/openpgpjs/openpgpjs/assets/112363847/f70453d8-0527-426a-ad0d-0e58cf14e19d">

Solution:
To resolve the issue, we explicitly close the stream using the `stream.destroy()` method after we're done processing it. This ensures that the file descriptor is closed and released appropriately, and it doesn't have to wait for the garbage collector to do it.

**Comment by 10kc-svats** [comment]
@larabr hi, unfortunately this does not work

**Comment by 10kc-svats** [comment]
@larabr if it can help you
<img width="587" alt="Screenshot 2023-10-11 at 5 29 37 PM" src="https://github.com/openpgpjs/openpgpjs/assets/112363847/9dc2671d-7d50-410b-bc51-cdf4c22d1d4d">

**Comment by 10kc-svats** [comment]
@larabr actually, stream.destroy() does not solve the problem, I accidentally switched to the prev node version and it works well (I thought I'm using node 20.x.x).

this [solution](https://github.com/openpgpjs/openpgpjs/issues/1512#issuecomment-1641879761) works for me

**Comment by larabr** [comment]
How are you testing for the issue? Passing a stream with data that triggers an OpenPGP.js error?

**Comment by 10kc-svats** [comment]
@larabr 
1. saving an encrypted file to the local directory 
2. creating a read stream from that file
3. Passing the stream to the decrypt method

```
const options: openpgp.DecryptOptions = {
  config: {
    allowInsecureDecryptionWithSigningKeys: true,
    allowUnauthenticatedMessages: true,
  },
  decryptionKeys: privateKey,
  message: await openpgp.readMessage({
    armoredMessage: readStream,
  }),
};
const { data } = await openpgp.decrypt(options);
```

**Comment by larabr** [comment]
I am not clear on the issue you are observing. Is this just about the warning in console? Have you confirmed that in Node 18 the file descriptor is properly closed, even if no warning is shown?

Also, are you reading out the `data` stream? If not, the decryption process doesn't even start (and neither does `readMessage` consume the input stream).
