### ISSUE TITLE
[@types]: TypeScript build error

### ISSUE THREAD

**Issue by vansergen** [openpgpjs/openpgpjs#1720]
### Description

- I cannot build my TypeScript project. I receive the following error

```
node_modules/openpgp/openpgp.d.ts:10:85 - error TS2307: Cannot find module '@openpgp/web-stream-tools' or its corresponding type declarations.
10 import type { WebStream as GenericWebStream, NodeStream as GenericNodeStream } from '@openpgp/web-stream-tools';
```

#### Possible workaround

1. Install `@openpgp/web-stream-tool@0.1.1` 

```sh
npm install @openpgp/web-stream-tool@0.1.1
```

2. Add the following declaration to your TS code

```ts
declare module "@openpgp/web-stream-tools" {
  export interface NodeStream<T extends Data> extends NodeWebStream<T> {}
}
```

### Extra info

- OpenPGP.js version: `v5.11.0`
- Affected platform (Node.js version): `v21.6.1`

**Comment by larabr** [comment]
Hi, indeed the web-stream-tools [need to be installed separately](https://github.com/openpgpjs/openpgpjs?tab=readme-ov-file#typescript) for TS to work. However, the version compatible with OpenPGP.js v5 is different (`0.0.11-patch-0`, or generally the latest below to v0.12). So you'll need to run:

```
npm install @openpgp/web-stream-tool@0.0.11-patch-0
```

And do not replace the TS declaration, as it's incorrect: NodeStreams in v5 are native Node streams, not Web Streams. The latter will change in the next major version only.

**Comment by dd-cardinal** [comment]
Hi. I'm keeping receiving that error in Angular 8.2.14 when I'm trying to compile

```
      ERROR in ../node_modules/openpgp/openpgp.d.ts:10:13 - error TS1005: '=' expected.

10 import type { WebStream as GenericWebStream, NodeStream as GenericNodeStream } from '@openpgp/web-stream-tools';
               ~
../node_modules/openpgp/openpgp.d.ts:10:85 - error TS1005: ';' expected.

10 import type { WebStream as GenericWebStream, NodeStream as GenericNodeStream } from '@openpgp/web-stream-tools';
```

I've already installed the @openpgp/web-stream-tools@0.0.11-patch-0

Here is my package.json

`{
  "name": "webapplication1",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:ssr": "ng run WebApplication1:server:dev",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/platform-server": "8.0.0",
    "@angular/router": "~8.2.14",
    "@ng-bootstrap/ng-bootstrap": "^5.1.4",
    "@nguniversal/module-map-ngfactory-loader": "8.0.0-rc.1",
    "@types/googlemaps": "3.39.12",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^4.4.1",
    "ngx-mask": "^8.1.6",
    "rxjs": "~6.4.0",
    "stream": "^0.0.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.20",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@openpgp/web-stream-tools": "^0.0.11-patch-0",
    "@storybook/angular": "^5.3.21",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^20.11.24",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "openpgp": "^5.11.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  },
  "optionalDependencies": {
    "node-sass": "^4.9.3",
    "protractor": "~5.4.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
}
`

**Comment by larabr** [comment]
The new error you posted is different from the one in the original report. Your TS version might be the reason why it's not working, try using TS v4?

**Comment by dd-cardinal** [comment]
The Angular Compiler of the version I'm using requires TypeScript >=3.4.0 and <3.6.0 but I can't update the Angular version. In this case, could I use a previous version of the library?

**Comment by dd-cardinal** [comment]
I used a previous version and worked well. Thanks a lot!
