### ISSUE TITLE
esm/cjs export config error

### ISSUE THREAD

**Issue by steven89** [openpgpjs/openpgpjs#1725]
- OpenPGP.js version:
`latest` & `4.10.11`

- Affected platform (Browser or Node.js version):
NodeJS

Both latest version & `4.10.11` are misconfigured for esm/cjs exports resulting in certain environments failing to properly load the module.
https://publint.dev/openpgp@4.10.11
https://publint.dev/openpgp@5.11.0

for my use case on version `4.10.11`, adding the following to `package.json` has fixed the loading issues for the `esm` version on NodeJS:
```json
  "type": "commonjs",
  "exports": {
    ".": {
      "require": "./dist/openpgp.js",
      "import": "./dist/openpgp.mjs"
    }
  },
```

I would expect the same change to work for the latest version as well

As a note, in my setup, `openpgp` is a dependency of a `crypto-lib` package and is not directly used by the main project
The error I got was (the "openpgp" comes from `import * as openpgp from 'openpgp'`):
```
TypeError: Cannot set properties of undefined (setting 'show_comment')
    at file:///.../node_modules/crypto-lib/dist/crypto.js:15:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

 error   Cannot set properties of undefined (setting 'show_comment')
  File:
    /.../node_modules/crypto-lib/dist/crypto.js:15:23
  Code:
    14 | }
    > 15 | openpgp.config.show_comment = !1;
         |                             ^
      16 | openpgp.config.show_version = !1;
      17 | function x(e) {
      18 |   return openpgp.message.fromText(e);
  Stacktrace:
TypeError: Cannot set properties of undefined (setting 'show_comment')
    at file:///.../node_modules/crypto-lib/dist/crypto.js:15:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by larabr** [comment]
Hi, please note that OpenPGP.js v4 is a legacy version, and it hasn't been tested with Node v14+.

As per v5, indeed we do not declare `exports` -- that will be done in the upcoming v6 release.
