### ISSUE TITLE
Chunk file upload and PGP

### ISSUE THREAD

**Issue by dogruis** [openpgpjs/openpgpjs#173]
Hi,

I'm trying to implement a PGP encryption for a chunk file upload.
I have to encrypt and upload data as a file stream using a BLOB object.

Is there any feature that will be soon implemented ?

Regards,

**Comment by tanx** [comment]
OpenPGP.js v2.x is much faster. See:

https://github.com/openpgpjs/openpgpjs#performance

Handling binary data like files is also supported:

https://github.com/openpgpjs/openpgpjs#encrypt-and-decrypt-uint8array-data-with-pgp-keys
