### ISSUE TITLE
Error decrypting message: Cannot destructure property 'c' of 'sessionKeyParams' as it is null

### ISSUE THREAD

**Issue by mlc** [openpgpjs/openpgpjs#1733]
- OpenPGP.js version: 5.11.1
- Affected platform (Browser or Node.js version): node.js

Steps to reproduce:
* Read a PGP private key `key` and a message `message` which is, for whatever reason, encrypted to that key's signing subkey instead of its encryption subkey.
* Call `decrypt({message, format: 'utf8', decryptionKeys: [key]})` and observe that a `Session key decryption failed` error is thrown.
* Try again, this time with `decrypt({message, format: 'utf8', decryptionKeys: [key], config: { allowInsecureDecryptionWithSigningKeys: true}})`

Expected result:
* Ideally decryption succeeds; at a minimum, an sensible error message is thrown.

Actual result:
* `TypeError: Error decrypting message: Cannot destructure property 'c' of 'i' as it is null.`
* Running with the un-minified version of the library gives `TypeError: Error decrypting message: Cannot destructure property 'c' of 'sessionKeyParams' as it is null.`, which is only marginally more useful.
```
TypeError: Error decrypting message: Cannot destructure property 'c' of 'sessionKeyParams' as it is null.
    at Object.publicKeyDecrypt (/Users/mlc/src/project/node_modules/openpgp/dist/node/openpgp.js:15624:15)
    at PublicKeyEncryptedSessionKeyPacket.decrypt (/Users/mlc/src/project/node_modules/openpgp/dist/node/openpgp.js:24853:37)
    at /Users/mlc/src/project/node_modules/openpgp/dist/node/openpgp.js:29996:35
    at Array.map (<anonymous>)
    at /Users/mlc/src/project/node_modules/openpgp/dist/node/openpgp.js:29949:50
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
```

**Comment by mlc** [comment]
Oh, I see, thank you! If this is as intended, then I guess I agree it's not a bug. Is it documented anywhere that `Message`s are stateful?

**Comment by larabr** [comment]
We are going to add a notice about this to `readMessage` -- thanks for bringing it up!
