### ISSUE TITLE
node:crypto error

### ISSUE THREAD

**Issue by b521f771d8991e6f1d8e65ae05a8d783** [openpgpjs/openpgpjs#1808]
Thank you for making openpgp.js available. I have encountered a bug when trying to use it that I have been unable to resolve.
`ERROR in ./node_modules/openpgp/dist/node/openpgp.mjs 4:0-39
Module not found: Error: Can't resolve 'module' in 'C:\Users\<User>\Documents\Projekte\mail-buddy\node_modules\openpgp\dist\node'
ERROR in node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.`

- OpenPGP.js version: 6
- Affected platform (Browser or Node.js version): Node v22.9.0

I installed the module via npm, and tries to use it (I am using the webpack bundler, if this is important).

**Comment by larabr** [comment]
Copying here for reference: [as reported in #1809](https://github.com/openpgpjs/openpgpjs/discussions/1809#discussioncomment-11339158), OpenPGP.js v6.0.0 uses an `exports` configuration that doesn't work as expected with Webpack; this is patched in [v6.0.1](https://github.com/openpgpjs/openpgpjs/releases/tag/v6.0.1) .

**Comment by RaenonX** [comment]
> Copying here for reference: [as explained in #1809](https://github.com/openpgpjs/openpgpjs/discussions/1809#discussioncomment-11339158), OpenPGP.js v6.0.0 uses an `exports` configuration that doesn't work as expected with Webpack with a web target; this is patched in [v6.0.1](https://github.com/openpgpjs/openpgpjs/releases/tag/v6.0.1) .

Although I haven't checked, the OP said it works so I assume it works now, will report if not in #1809 but thank you so much!
