### ISSUE TITLE
OpenPGP.js v6 Does Not Throw/Reject on Failed Armor Checksum

### ISSUE THREAD

**Issue by ioanmo226** [openpgpjs/openpgpjs#1810]
- OpenPGP.js version: 6
- Affected platform (Browser or Node.js version): Browser, Node.js

In OpenPGP.js v6, the library no longer throws/rejects on a failed armor checksum. This behavior was correctly handled in v5, where it would throw an error such as:  `Error: Ascii armor integrity check failed.`  

However, in v6, the same scenario incorrectly returns a success result.

### Steps to Reproduce

Using the following code, v6 returns the string `Hello world` instead of throwing the expected error:

```js
const openpgp = require('openpgp');

(async () => {
    const passphrase = `yourPassphrase`; // Password that private key is encrypted with
    const generateKeyResult = await openpgp.generateKey({type: 'rsa', rsaBits: 2048, passphrase, userIDs: [{email: 'test@email.com'}]});

    const publicKey = await openpgp.readKey({ armoredKey: generateKeyResult.publicKey });

    const privateKey = await openpgp.decryptKey({
        privateKey: await openpgp.readPrivateKey({ armoredKey: generateKeyResult.privateKey }),
        passphrase
    });


    const encrypted = await openpgp.encrypt({
        message: await openpgp.createMessage({ text: 'Hello world' }), // input as Message object
        encryptionKeys: publicKey,
        signingKeys: privateKey // optional
    });
    console.log('\n\noriginal msg:\n', encrypted);
    const badSumData = encrypted.replace(/\n=[a-zA-Z0-9/+]{4}/, '\n=aaaa');
    console.log('\n\nbadSumData msg:\n', badSumData);

    const message = await openpgp.readMessage({
        armoredMessage: badSumData // parse armored message
    });
    const decrypted = await openpgp.decrypt({
        message,
        verificationKeys: publicKey, // optional
        decryptionKeys: privateKey
    });
    const chunks = [];
    for await (const chunk of decrypted.data) {
        chunks.push(chunk);
    }
    const plaintext = chunks.join('');
    console.log(`\n\ndecrypted content:\n${plaintext}`);
})().catch(console.error);
```

### Expected Behavior

When the ASCII armor checksum fails, OpenPGP.js should throw/reject with an error like:  
`Error: Ascii armor integrity check failed`

### Actual Behavior

With v6, the above code does not throw or reject. Instead, it returns the success result `Hello world`.

### Related Issue

This issue was previously fixed in https://github.com/openpgpjs/openpgpjs/issues/924. However, it seems to have reappeared in v6.

**Comment by larabr** [comment]
Hi, this behavior is compliant with [RFC9580](https://www.rfc-editor.org/rfc/rfc9580.html#section-6.1-3):

> An implementation MUST NOT reject an OpenPGP object when the CRC24 footer is present, missing, malformed, or disagrees with the computed CRC24 sum.

**Comment by ioanmo226** [comment]
I see. Thank you for your explanation.
