### ISSUE TITLE
Private key is not decrypted

### ISSUE THREAD

**Issue by Messerjocke** [openpgpjs/openpgpjs#198]
Hi,

I’m trying to get some basic functionality working in my browser with openpgp.min.js.
Here are some lines of code to test encryption, decryption, signatures and validating these. I don’t get them to work properly.

// Creating the Keys seems to be working

var keypair = openpgp.generateKeyPair(1, 1024, "1234"); 
var privKeys = openpgp.key.readArmored(keypair.privateKeyArmored);
var publicKeys = openpgp.key.readArmored(keypair.publicKeyArmored);
var privKey = privKeys.keys[0];
var pubKey = publicKeys.keys[0];

// Encrypting messages works too

var enc_message = openpgp.encryptMessage([pubKey], 'test');
console.log(enc_message);

// ERROR : Private key is not decrypted

var msg = openpgp.message.readArmored(enc_message);
var dec_message = openpgp.decryptMessage(privKey, msg);
console.log(dec_message);

// ERROR : Private key is not decrypted

var enc_and_sign_message = openpgp.signAndEncryptMessage([pubKey],privKey,'test’);
console.log(enc_and_sign_message);

// ERROR : Private key is not decrypted

var msg = openpgp.message.readArmored(enc_and_sign_message);
var dec_and_sign_message = openpgp.decryptAndVerifyMessage(privKey, [pubKey], msg);
console.log(dec_and_sign_message);

// Problem : Signature is  =twTO every time no matter what key

var signedmessage = openpgp.signClearMessage(privKey,'test');
console.log(signedmessage);

var success = openpgp.verifyClearSignedMessage([pubKey],openpgp.cleartext.readArmored(signedmessage));
console.log(success.signatures[0]);

I would really appreciate some help or tips to get these lines working. I already read the tests in basic.js, but it didn’t help me.

Thank you and best regards,
Benjamin

**Comment by mchavarriae** [comment]
I have the same situation here, but the response didn't help me! Does somebody can help me? I can't run the basic example.
