### ISSUE TITLE
Handling of \r and EOL

### ISSUE THREAD

**Issue by toberndo** [openpgpjs/openpgpjs#211]
Instead of normalizing EOL to '\r\n' this also removes all '\r' from the text:
https://github.com/openpgpjs/openpgpjs/blob/master/src/packet/literal.js#L51
https://github.com/openpgpjs/openpgpjs/blob/master/src/cleartext.js#L45

**Comment by tanx** [comment]
Fixed in https://github.com/openpgpjs/openpgpjs/commit/68d1b5a35c9e2446ea2011b859d804ddfc5523a0
