### ISSUE TITLE
Ascii armor integrity check on message failed: '' should be 'PEFA'

### ISSUE THREAD

**Issue by edouard-lopez** [openpgpjs/openpgpjs#226]
Hi,
I'm trying to use Mailvelope, that use OpenPGP.js, during a cryptoparty and I can't import some of my friends key with the following error :
> Import Error! Unable to read one public key: Ascii armor integrity check on message failed: '' should be 'PEFA'

I don't find anything related to `PEFA` and `GPG` on Google. Does it means anything to you ?

[related issue on Mailvelope project](https://github.com/toberndo/mailvelope/issues/198).

**Comment by tanx** [comment]
See https://github.com/mailvelope/mailvelope/issues/198#issuecomment-43482681
