### ISSUE TITLE
API change documentation needs improved

### ISSUE THREAD

**Issue by kallisti5** [openpgpjs/openpgpjs#233]
Attepting to update an application using openpgpjs... a *lot* has changed.

Fixed:

     function parseMsg(msg) {
    -       return openpgp.read_message(msg);
    +       return openpgp.message.readArmored(msg);
     }

Now getting:

    TypeError: msg[0] is undefined
        if(msg[0].type === 2) {

Code

    var msg = parseMsg($("#messagebody div.message-part pre").html());
    // OpenPGP failed parsing the message, no action required.
    if(!msg) {
      return;
    }

    // msg[0].type: 2 == signed only
    // msg[0].type: 3 == encrypted only

    showKeyInfo(msg);

    if(msg[0].type === 2) {

I haven't been able to find any good API change documentation, is there a set of commits showing the major API changes?

**Comment by tanx** [comment]
See new 2.0 api docs
