### ISSUE TITLE
BigInteger to MPI  Bug/Inconsistency

### ISSUE THREAD

**Issue by secumundo** [openpgpjs/openpgpjs#240]
I might have found a bug in the BigInteger library. 

Assuming the bigInteger HEX  (generated with different library) = "9773838e13fdc32f398ad92747dd7ddbc28dd114092e7ccc5008e360d78ae1f44509ea41c26c4b70513b4efb1b93102dfd361ad41185f37df48375899096ec6b0af6e5d1b20d59d353fd9566efe2c34b43da27fe0e304c7f5895f02a49a0490d451761ef1d74e5dc606529d021296691a10d82416fda66c02c787cd52a713e353a9466bdf8da4e5e49d5b8791ca9aaf1dd8e3a5e4f5c810f1a2302ce004304efaba97f8bddd97d8c8e32505d78829abdf05d80cb4dfe2806994bceb625f796480d2753641b281e8f2568fbcf0f5f371676176a3df4a0515b208b3f5d091536e5415d4b95e9718fd02d2e6d072fdb1688998eeacf0f061f0424bbbb906fed4be9"

bi = new BigInteger(HEX,16);
bi.toString = 9773838e1 ...be9 // Correct
bi.toMPI = 0801009773838e .. be9

However, the correct result should IMHO be 08009773838e1 ... be9

gnupg verification for this keys fails accordingly.

Am I wrong? Or the code?

Michaela
##

**Comment by mahrud** [comment]
This is now fixed, probably with #654 . jsbn.js certainly had some unforgivable bugs. (try generating a biginteger from Uint8Array [127,127,127] and [129,129,129] ...)
