### ISSUE TITLE
Worker generateKeyPair failure

### ISSUE THREAD

**Issue by Warlone** [openpgpjs/openpgpjs#242]
1) Since version 6.0 this code:

var pgp_worker = new openpgp.AsyncProxy();
pgp_init();

pgp_worker.generateKeyPair(1, 1024, 'Ann Lee <ann@lee.com>', 'password', function(err, data){
...........

we are receiving this error: "Uncaught TypeError: number is not a function"

2) why  in  openpgp.min.js  we  are  including not minimal version of
worker:        "Worker(a||"openpgp.worker.js")"       instead       of
"Worker(a||"openpgp.worker.min.js")" ??? Is not critical of cause

**Comment by tanx** [comment]
See https://github.com/openpgpjs/openpgpjs#set-up
