### ISSUE TITLE
signClearMessage throws "TypeError: keyIntegers[2] is undefined"

### ISSUE THREAD

**Issue by jmizell** [openpgpjs/openpgpjs#244]
So I create my keys.
```
keypair = openpgp.generateKeyPair({numBits: 1024, userId: "somebody@somewhere.com"});
privKeys = openpgp.key.readArmored(keypair.privateKeyArmored);
console.log("privatekey \n\n"+ keypair.privateKeyArmored);
```
Seems good, so I test encrypt a message.
```
var armoredMessage = openpgp.encryptMessage(privKeys.keys,"Sample encrypted message.", null);
console.log("armoredMessage \n\n"+ armoredMessage);
```
So far so good, so now signing a message.
```
var clearSignedArmor = openpgp.signClearMessage(privKeys.keys, "Sample signed clear text message.");
console.log("clearSignedArmor \n\n"+ clearSignedArmor);
```
I receive this error, `TypeError: keyIntegers[2] is undefined`.   This is in Firefox 31.  In Google Chrome 35, I receive `Uncaught TypeError: Cannot read property 'toBigInteger' of undefined`.

**Comment by zartdinov** [comment]
I got same `TypeError: Cannot read property 'toBigInteger' of undefined` when forgot decrypt private key by passphrase.

P.S. Here I see that you encrypted message by **private key**
```javascript
var armoredMessage = openpgp.encryptMessage(privKeys.keys,"Sample encrypted message.", null);
```

**Comment by tanx** [comment]
Have you tried the recent v2.x release?

**Comment by zartdinov** [comment]
Yeah, v.2.x. When I tried sign signature packet with not decrypted private key.  But it's all right, just added
```javascript
if (!signingKeyPacket.isDecrypted) {
    throw new Error('Private key is not decrypted.');
}
```

This issue is outdated in my eyes. Previous comment was just for informativeness.

**Comment by tanx** [comment]
I could have sworn we throw an error in the Message object if the key is not decrypted. But maybe CleartextMessage does not inherit this behavior. Feel free to send a PR if you like 👍🏼

**Comment by tanx** [comment]
> This issue is outdated in my eyes. Previous comment was just for informativeness.

Ok. We check here anyway now:

https://github.com/openpgpjs/openpgpjs/blob/master/src/cleartext.js#L81
