### ISSUE TITLE
how to readArmord secret subkey?

### ISSUE THREAD

**Issue by buctyoyo** [openpgpjs/openpgpjs#255]
I need to readArmord a secret subkey and to sign a string. this my old version
```
var privateKey = openpgp.key.readArmored(fs.readFileSync('./privateSub').toString()).keys[0];
privateKey.decrypt('passphrase');
 openpgp.signClearMessage(privateKey,'hello', function (err, result) {
    console.log(err, result);
  })
```
this will give me a error `Error: Private key is not decrypted` when i give a correct passphrase;

Instead  I use command line import and sign with correct passphrase work well.

**Comment by tanx** [comment]
See the unit tests: https://github.com/openpgpjs/openpgpjs/blob/master/test/general/openpgp.js#L427-L447
