### ISSUE TITLE
Unable to use private key after passphrase change

### ISSUE THREAD

**Issue by fsievers** [openpgpjs/openpgpjs#263]
I'm trying to change a private keys passphrase and use the same private key with the new passphrase to decrypt a message. The private key passphrase change works, but I'm unable to decrypt messages after the change. If I change the passphrase back to the old passphrase, I'm able to decrypt messages again.

What is my mistake with the passphrase change?

Steps to recreate the problem:
1. Generate a keypair
2. Encrypt a message with the pub-key
3. Decrypt private-key (with "old-passphrase")
4. Encrypt private-key with new-passphrase
5. Decrypt private-key with new-passphrase
6. Try to decrypt the message (not working)
7. Encrypt private-key with old-passphrase
8. Decrypt private-key with old-passphrase
9. Try to decrypt the message (works)
##

**Comment by sanjanarajan** [comment]
The Key.encrypt function now encrypts all key packets - see https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L364
