### ISSUE TITLE
Support for multiple subkey binding signatures

### ISSUE THREAD

**Issue by toberndo** [openpgpjs/openpgpjs#266]
If a subkey has mulitple binding signatures (happens e.g. if you extend the expiration time of a key with GPG) then OpenPGP.js will only consider the last signature of the subkey. As a consequence the subkey could get the status invalid although there exists a valid binding signature.
##

**Comment by toberndo** [comment]
Multiple subkey binding signatures is implemented with:
https://github.com/openpgpjs/openpgpjs/pull/565

I think there is still an incompatibility with GnuPG in the way that the priority of multiple binding signatures is handled. RFC4880 says here:
```
An implementation that encounters multiple self-signatures on the
same object may resolve the ambiguity in any way it sees fit, but it
is RECOMMENDED that priority be given to the most recent self-
signature.
```
The implementation at https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L1030 just checks for existence of at least one valid subkey binding signature, but the implementation in GnuPG and RECOMMENDED according to RFC4880 would be to give priority to the most recent self-signature.
That way a more recent subkey binding signature can also be used to reduce a once given expiration time.

**Comment by tomholub** [comment]
That means we would keep an array of `bindingSingatures`, pick the one that is most recent by date created and only actually evaluate that one. Sounds OK to me if that's what GnuPG does.

At least it would remove ambiguity about which error to return when none is valid. Right now, I'm returning the reason of the "last" fail, which is not ideal.

**Comment by tomholub** [comment]
It would be faster, too.

**Comment by toberndo** [comment]
> At least it would remove ambiguity about which error to return when none is valid.
> Right now, I'm returning the reason of the "last" fail, which is not ideal.

This sounds like another advantage.

Here is an example key: [0xB18283F5.txt](https://github.com/openpgpjs/openpgpjs/files/1771687/0xB18283F5.txt)

With the following subkey:
```
:public sub key packet:
	version 4, algo 1, created 1410156217 (2014-09-08), expires 0
	keyid: D3376382176835CF
:signature packet: algo 1, keyid 8293FB81B18283F5
	version 4, created 1410156217, md5len 0, sigclass 0x18
	hashed subpkt 2 len 4 (sig created 2014-09-08)
	hashed subpkt 9 len 4 (key expires after 4y0d0h0m)
	subpkt 16 len 8 (issuer key ID 8293FB81B18283F5)
:signature packet: algo 1, keyid 8293FB81B18283F5
	version 4, created 1445067697, md5len 0, sigclass 0x18
	hashed subpkt 2 len 4 (sig created 2015-10-17)
	hashed subpkt 9 len 4 (key expires after 1y40d1h37m)
	subpkt 16 len 8 (issuer key ID 8293FB81B18283F5)
```
This subkey is displayed in GPGTools as expired on the 2015-10-18

**Comment by dd9jn** [comment]
Watch out for this extra gadget:  gpg does not consider encryption subkeys which are created in the future.  This allows to distribute future keys right away and as soon as the roll-over happens, gpg will use that new subkey.

**Comment by mahrud** [comment]
I think I can fix this, along with turning subKey.revocationSignature into an array and another bugfix. The strategy is similar to what we now do here to find the best primary user:
https://github.com/openpgpjs/openpgpjs/blob/2077d8487ff618d8f80546a55e3bbb7f59780f99/src/key.js#L524-L548
Except I need to make sure not to return future keys ... thanks @dd9jn!

**Comment by aviau** [comment]
> If a subkey has mulitple binding signatures (happens e.g. if you extend the expiration time of a key with GPG)

Hello! would you mind providing me with the steps to generate a key like this with openpgp and export it?

**Comment by tomholub** [comment]
@aviau you could use the failing key above. You can also inspect OpenPGP.js unit tests and re-use the key we have in tests.
