### ISSUE TITLE
Unclear Dependency on Web Workers

### ISSUE THREAD

**Issue by bantu** [openpgpjs/openpgpjs#269]
It is unclear whether Web Workers are an actual requirement or not. The Dependencies section in README.md (see below) makes it sound like Workers are not required when `window.crypto.subtle` is available. Even though subtle is available in my browser, I get an "You need to set the worker path!" error. I think this should be clearified.

> Dependencies
OpenPGP.js only supports browsers that implement window.crypto.getRandomValues. Also, if the browsers support native WebCrypto via the window.crypto.subtle api, this will be used. Though this can be deactivated by setting config.useWebCrypto = false. In this case the library will fall back to Web Worker operations if the initWorker(workerPath) is set.

**Comment by tanx** [comment]
Worker is purely optional. Please see the README and docs
