### ISSUE TITLE
Easier handling of messages with unknown type / (more) generic readArmored()

### ISSUE THREAD

**Issue by bantu** [openpgpjs/openpgpjs#270]
It looks like `openpgp.cleartext.readArmored()` is supposed to be used for reading signed cleartext messages and `openpgp.message.readArmored()` is supposed to be used for reading PGP messages (encrypted, and possibly signed).

If you do not know whether the message you've received is plaintext, signed, encrypted, encrypted and signed, e.g. when receiving e-mail messages, this seems to require quite some code to handle. Instead of having users reinvent the wheel over and over again, it would be useful to have some handling for this in opengpgjs. The `armor.getType()` method (see [0]) is related to that and can be used to identify the type of a given message. It however is private and it would probably also be useful to have a function that takes an unknown message and outputs the appropriate result/object.

Furthermore, extending this to `openpgp.key.readArmored()` might make sense.

[0] https://github.com/openpgpjs/openpgpjs/blob/master/src/encoding/armor.js#L29

**Comment by tanx** [comment]
See the new v2.x api in README and docs
