### ISSUE TITLE
Support for multiple recipients? 

### ISSUE THREAD

**Issue by daum** [openpgpjs/openpgpjs#271]
Does openpgpjs support multiple recipients from different public keys?  I saw #68 which has multiple keys from one armoredText, however is there a way to load more than one public key from different armoredText's for the encryption routine?  

Thanks!

**Comment by ashcs** [comment]
Please example for latest version

**Comment by avimar** [comment]
How do I do this? The link is no longer active.

I tried passing in an array of keys, that didn't work.

I tried putting both public keys in the same text for an import, and it encrypted it, but firebase.io said that it wasn't my key. Is that the only way? Is it just a bug with firebase.io?

**Comment by bartbutler** [comment]
An array of keys should work. Please look at the tests, there should be one or more examples in there of using multiple public keys.

**Comment by avimar** [comment]
I assume here https://github.com/openpgpjs/openpgpjs/blob/master/test/general/openpgp.js but despite the naming of `keys` it seems to only be one.

**Comment by bartbutler** [comment]
What happens when you try an array with multiple keys?

**Comment by avimar** [comment]
`(node:14700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error encrypting message: Cannot read property 'getPrimaryUser' of undefined`

Here's my code:

https://gist.github.com/avimar/b02c34a20d90d7476f615766b34246ed

**Comment by bartbutler** [comment]
FIrst, your keys are invalid. There needs to be a newline after the key headers that your keys lack. openpgp.key.readArmored has an 'err' field that will be an Error object if the key parsing fails.

Second, instead of '.key' you needs to use '.keys[0]' or merge the key array, as there can be (though there usually aren't) multiple keys inside an armored block.

With those changes your code worked for me.

**Comment by avimar** [comment]
Wow, `.keys` somehow worked fine -- that's what the getting started docs show: https://github.com/openpgpjs/openpgpjs/blob/master/README.md#encrypt-and-decrypt-string-data-with-pgp-keys

But when used in an array, it needs `[0]` specified.

So my code now seems to work fine, I just made that small change.
Thanks!

Code below for anyone who will need in the future:

```
options = {
    data: 'Hello, World!',                             // input as String (or Uint8Array)
    publicKeys: [                      // for encryption
	openpgp.key.readArmored(pubkey1).keys[0],
	openpgp.key.readArmored(pubkey2).keys[2]  
	]
   };
```

**Comment by bartbutler** [comment]
What is the 'keys[2]'? Do you have multiple keys in your armored block?

**Comment by avimar** [comment]
Woops, typo! Fixed it.

**Comment by waza123x** [comment]
thanks avimar, you saved my day.
