### ISSUE TITLE
RSA.generate calls atob

### ISSUE THREAD

**Issue by jcayzac** [openpgpjs/openpgpjs#279]
This code from `crypto/public_key/rsa.js` doesn't work in Node.js since it doesn't have `atob()`.
```js
      function toBigInteger(base64url) {
        var base64 = base64url.replace(/\-/g, '+').replace(/_/g, '/');
        var hex = util.hexstrdump(atob(base64));
        return new BigInteger(hex, 16);
      }
```

You should call

```js
new Buffer(base64, 'base64').toString('binary')
```

…when `atob` is not a function.

**Comment by tanx** [comment]
That code path is only executed in browser environments where native WebCrypto is available. In node the js fallback is used.
