### ISSUE TITLE
Handling keys without userid

### ISSUE THREAD

**Issue by alokmenghrajani** [openpgpjs/openpgpjs#282]
Some keys (e.g. http://pgp.mit.edu/pks/lookup?op=get&search=0x666b99d1320846ae) don't have a userid and currently can't be imported.

A quick fix would be to change https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L49 to initialize this.users to an empty array instead of null and update the error message on line 53.

**Comment by koto** [comment]
OpenPGP explicitly says that transferable public keys should have at least one UserID packet within: https://tools.ietf.org/html/rfc4880#section-11.1

**Comment by alokmenghrajani** [comment]
True. Weird that the key servers don't enforce this.
