### ISSUE TITLE
please add compiled and minificated version to use with bower

### ISSUE THREAD

**Issue by let4be** [openpgpjs/openpgpjs#283]

**Comment by mapmeld** [comment]
@let4be if you run ```grunt```, it will create a minified JS file at dist/openpgp.min.js - is this useful or would it still be helpful to include the minified JS file in the repo for bower?

**Comment by let4be** [comment]
The thing is if I use some library in a project I do not want to compile it(as I have 20 other libs), I just to want to use compiled version from my build system(gulp based) and currently it's impossible to do.
Pre-compiled version would help a lot in openpgp.js adoption.

**Comment by tanx** [comment]
Hi. There are prebuilt/minified releases here: https://github.com/openpgpjs/openpgpjs/releases

I have no idea how bower and gulp work. If you provide a PR that uses the files provided under github-releases, I'll be happy to review it.

We currently don't add prebuilt files to git, as this has caused confusion before when outside contributors send a PR that includes their local development build.

**Comment by evilaliv3** [comment]
the patch is correct @tanx, but it still miss to deliver a not compressed version that i think it's good to call openpgp.js

generally a package delivered with bower includes:
/src: sources
/dist: dists and generally the dist library distribute both the a bundled uncompressed version and a bundled minified version.

this way the library can be used both on development (uncompressed in order to see eventual debug errors) and on deployments (compressed).

**Comment by tanx** [comment]
Ok. I updated PR https://github.com/openpgpjs/openpgpjs/pull/290

 I linked all minified and unminified build artifacts in [here](https://github.com/openpgpjs/openpgpjs/blob/bower/bower.json#L9-L14)

I've also added a release shell script that will automatically patch the `package.json`/`bower.json` files, build, git tag, and publish to npm and bower. Please review if I did everything correctly for bower [here](https://github.com/openpgpjs/openpgpjs/blob/bower/release.sh#L35).

The `dist/` director is under .gitignore by default to prevent dev builds in the github repo. The files will be added in the upcoming v0.10.1 release.

**Comment by tanx** [comment]
Alright. Both minified and uncompressed builds are now available under [dist](https://github.com/openpgpjs/openpgpjs/tree/master/dist) and I've registered the bower package `openpgp`. Usage instructions [here](https://github.com/openpgpjs/openpgpjs#browser-support).
