### ISSUE TITLE
Ability to encrypt file content/message with a specified filename

### ISSUE THREAD

**Issue by reidan** [openpgpjs/openpgpjs#284]
While [Pull Request 176](https://github.com/openpgpjs/openpgpjs/pull/176) added the ability to specify a Filename for the literal data packets and there was mention of adding the ability to specify it in the higher level api at the message level, at this point I am not aware of a way to use that feature easily without modifying the library or copying the processes in the existing encryptMessage function.  

Would it be possible to add an optional filename parameter to the openpgp.encryptMessage function or were there security reasons for not exposing the filename at these higher interface layers?

I've modified my own repository to allow me to set the filename easily, however I want to make it easy to keep my implementation up to date with any updates that openpgp.js may have going forward.

Thanks in Advance!

**Comment by barrydegraaff** [comment]
Very interesting, would like to have this as well.
