### ISSUE TITLE
Invalid range check in DSA signature verification

### ISSUE THREAD

**Issue by koto** [openpgpjs/openpgpjs#286]
r and s parameters in DSA should satisfy the condition: `0 < r′ < q` and `0 < s′ < q`, see e.g. [FIPS 186-4](https://oag.ca.gov/sites/all/files/agweb/pdfs/erds1/fips_pub_07_2013.pdf) 4.7.

Instead you're checking  `0 <= r′ <= q` and `0 <= s′ <= q` (https://github.com/openpgpjs/openpgpjs/blob/master/src/crypto/public_key/dsa.js#L105-L111)

**Comment by koto** [comment]
Combined with the fact that the modular inverse implementation returns 0 when the inverse does not exist this allows for easy, universal DSA signature verification bypass.

**Comment by tanx** [comment]
Good catch @koto, thanks.

I spoke with @toberndo and we'll try to fix this asap.

**Comment by koto** [comment]
My suggested fix is to 
a) correct the ranges check and 
b) assert that the modular inverse is NOT 0.

**Comment by koto** [comment]
To note, this vulnerability was found by Daniel Bleichenbacher of Google, I'm merely reporting this.

**Comment by tanx** [comment]
Noted. Tell Daniel thanks and that he is owed a beer by whiteout :)

**Comment by koto** [comment]
I created a pull request with the fix. https://github.com/openpgpjs/openpgpjs/pull/288
