### ISSUE TITLE
Add boundled and minified version of openpgp.js library to repository

### ISSUE THREAD

**Issue by evilaliv3** [openpgpjs/openpgpjs#289]
Currently when one install openpgpjs via bower he gets only the source code of the application.

This makes difficult and not automatizable to include opepgp.js in other projects with a single Gruntfile.js as performed by quite all npm projects. Packaging openppg.js for bower would require to add to the git repo both the source code, the bundled library and the minified boundled library.

I found this problem when adding openpgp.js to the globaleaks project.

**Comment by tanx** [comment]
We have been using GitHub [releases](https://github.com/openpgpjs/openpgpjs/releases) up until now, but it seems several folks are having this issue (https://github.com/openpgpjs/openpgpjs/issues/283) we should do something.

I've added the minified files I released today to the repo: https://github.com/openpgpjs/openpgpjs/pull/290

As I'm not familiar with bowser, please verify that the PR is correct and advise on what I need to do to publish it for bower.

**Comment by evilaliv3** [comment]
ah right! thank you @tanx, i didn't find the other ticket.

as this is duplicated i'm closing it and continuing the discussion on the other one.
