### ISSUE TITLE
openpgpjs 0.11.0 does not include zlib.min.js.map in dist

### ISSUE THREAD

**Issue by hellais** [openpgpjs/openpgpjs#293]
When I include the latest build of openpgp.js as soon as openpgp.js loads I will get the following error:

```
GET http://localhost:9000/bower_components/openpgp/dist/zlib.min.js.map 404 (Not Found)
```

I am a bit puzzled as to why this would happen since the string "zlib.min.js.map" only appears in a comment here: https://github.com/openpgpjs/openpgpjs/blob/master/dist/openpgp.js#L949

**Comment by tanx** [comment]
It's just looking for the source maps file for zlib. This won't cause any runtime problems you will not not be able to debug the minified zlib code at debug time.

**Comment by hellais** [comment]
If it's not needed for a production release then it should not be doing that extra HTTP request when included from `dist/`.

**Comment by tanx** [comment]
> If it's not needed for a production release then it should not be doing that extra HTTP request when included from dist/.

This is something you browser does when the dev tools are open and if you activate source maps in the developer settings.

If it bugs you then patch ist welcome :)

**Comment by hellais** [comment]
Ah ok, it was unclear to me from your answer that this a behaviour of my browser when in the developer console and not that of the library. This is fine then, thanks!

**Comment by evilaliv3** [comment]
yep @tanx without talking with @hellais i was to open this issue few days ago.

for our project is really important to try to avoid/minimize unneded requests and also the loading of unneded libraries during production in order to minimize eventually attack surfaces.

is it possible to distribute a version without debug functionalities or with them disabled?

**Comment by tanx** [comment]
@evilaliv3 again, source maps are only requested by your browser if dev tools are open.

I'll just leave this here: http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

**Comment by evilaliv3** [comment]
ah ok thanks. i did't notice that comment as i started writing mine before.
