### ISSUE TITLE
Make possible by config to use only secure random generators

### ISSUE THREAD

**Issue by evilaliv3** [openpgpjs/openpgpjs#294]
By analyzing the implementation of the random sources used by OpenPGP.js it seem that as last resort random source OpenPGP.js uses an internal random generator that use the result of crypto operations to build a pseudo random source.

From far that i understand this is done in order to make possible for the library to work and perform well in a cross-compatible fashion where perfect random generators like window.crypto are not available.

I would find interesting if the library would accept a configuration variable with the action to "Enforce usage of window.crypto()" so that in case of window.crypto is not available no fallbacks are performed. This way softwares that highly rely on security could enforce this behaviour.

If the use case is clear and the ticket is accepted i would work on this by providing a clean patch.

**Comment by toberndo** [comment]
If you are referring to https://github.com/openpgpjs/openpgpjs/blob/master/src/crypto/random.js#L78 there are the following sources:
- window.crypto (Chrome, Firefox)
- window.msCrypto (IE)
- http://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback (node)
- randomBuffer (Web Worker) supplied by https://github.com/openpgpjs/openpgpjs/blob/master/src/worker/async_proxy.js#L121 with one of the 3 sources above

So there is no internal random number generator.

**Comment by evilaliv3** [comment]
hu @toberndo you are right. thanks for the clarification.

due to the strange loop in the the implementation i was trapped in this mistake where i was thinking you were using the encrypted message as input for the random source.
