### ISSUE TITLE
How to read encrypted, armored key that I just generated?

### ISSUE THREAD

**Issue by d33tah** [openpgpjs/openpgpjs#295]
As in the title - how can I  read encrypted, armored key that I just generated? Here's what I tried, but `gpg --list-packets < /tmp/key.asc` doesn't recognize that:

```
    var opt = {numBits: 512, userId: userId, passphrase: password1};               
    openpgp.generateKeyPair(opt).then(function(key) {                              
        var keyEncrypted = openpgp.armor.encode(openpgp.enums.armor.private_key,
                                                key.key.primaryKey.encrypted);  
    })
```

**Comment by toberndo** [comment]
https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L275

**Comment by d33tah** [comment]
Thanks, but ```key.key.armor()``` does not seem to be encrypted - ```gpg --import``` imported it with no problem.

**Comment by d33tah** [comment]
@toberndo:

Here's the test case:

```html
<script src="https://raw.githubusercontent.com/openpgpjs/openpgpjs/master/dist/openpgp.min.js"></script>
<pre id="key"></pre>
<script>var opt = {numBits: 512, userId: "a", passphrase: "a"};
openpgp.generateKeyPair(opt).then(function(key) {
    document.getElementById("key").innerHTML = (key.key.armor());
})</script>
```

Running this in the browser results in a key which can be saved as key.asc. Here's what an attempt to import it ends with:

```
$ gpg --import key.asc 
gpg: key 54CF22CCDB82CB8F: secret key imported
gpg: key 54CF22CCDB82CB8F: public key "a" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
```

**Comment by toberndo** [comment]
> Thanks, but key.key.armor() does not seem to be encrypted - gpg --import imported it with no problem.

Not sure what you expect here, GPG always imports the private key without asking for a password. You only need to unlock the private key material e.g. when decrypting a message.
