### ISSUE TITLE
Listing of encryption key IDs for an encrypted message

### ISSUE THREAD

**Issue by dbarski** [openpgpjs/openpgpjs#301]
I am currently working on a Firefox plugin using openpgpjs. Encryption works fine, but for decryption, it would be nice to be able to list the keys used for encryption to be easier be able to select the correct key from storage. How can this be most easily achieved?

Many thanks in advance
Best regards
Dmitri

**Comment by toberndo** [comment]
https://github.com/openpgpjs/openpgpjs/blob/master/src/message.js#L55

**Comment by dbarski** [comment]
Many thanks!

To bad it is not mentioned in the docs (http://openpgpjs.org/openpgpjs/doc/module-message.html) :)
