### ISSUE TITLE
General FAQ putting in the README

### ISSUE THREAD

**Issue by sgasser** [openpgpjs/openpgpjs#303]
If someone not master of encryption (like me) will start with this plugin there should be a FAQ or best practice part in the README.

To reply to answers like:
* Where I should save the private key? Localstorage or else where?
* Can the passphrase be the same for all users or how I should generate it?

I'm sure this will help users.

**Comment by tanx** [comment]
Please see the README and docs. Regarding your questions:

> Where I should save the private key? Localstorage or else where?

See localstorage module or use your own IndexedDB instance if you like.

> Can the passphrase be the same for all users or how I should generate it?

Never reuse passphrase for multiple users. It's best to let them choose.
