### ISSUE TITLE
Unknown ASCII Armor Type

### ISSUE THREAD

**Issue by ReturnOfTheBlack** [openpgpjs/openpgpjs#307]
I'm new here and am fairly new to using Javascript scripts so go easy on me.

When I try to get the public key from an armored block using: 
<code>var publicKey = openpgp.key.readArmored(keyString);</code>
it returns an error with the message Unknown ASCII Type.
Clearly I'm doing something wrong.

EDIT: Fixed, it was due to my poor formatting.

**Comment by crathermel** [comment]
I am getting the same error w/ the following code... This an encoding issue?  I have tried using my public key and a few others found online and they all seem to generate the same error.  What am I missing? 


var fs = require('fs');
var openpgp = require('openpgp');

var fs = require('fs');
fs.readFile('twi_key.txt', { encoding: 'utf-8' }, function (err, data) {
    var rawPublicKey = data;
    fs.readFile('message.txt', { encoding: 'utf-8' }, function (err, data) {
        var rawMessage = data;
        var publicKey = openpgp.key.readArmored(rawPublicKey).keys[0];
    });
});

**Comment by vnndi** [comment]
I have the same issue. Anyone knows a fix?

**Comment by crathermel** [comment]
@vnndi  my issue ended up being I was just coping the contents of the key into a file instead of using a key that was generated w/ an open pgp tool. It must write some header info or something that is required ..

**Comment by vnndi** [comment]
@crathermel thank you. i had to do the same thing. it's a work around but it shouldn't be like that.

**Comment by bartbutler** [comment]
What does your key look like?
