### ISSUE TITLE
Decryption with wrong private key throws exception, even when 'error' function is declared

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#310]
I am the developer of Zimbra OpenPGP Zimlet extenstion that adds PGP to Zimbra using OpenPGP.js.

For some time I have been ignoring a type error, that I believe may be a bug in OpenPGP.js.

The following type error is thrown when a user tries to decrypt a message with a wrong private key. For example when `Jeff` tries to decrypt a message encrypted to `Barry` barry@gocrazy.com with the private key of jeff@unbound.gov, this should not work and it isn't, but I cannot suppress the error thrown in the browsers console:
TypeError: Cannot read property 'isDecrypted' of null
    at Message.decrypt (deflate.js:13)
    at deflate.js:13
    at deflate.js:13
    at execute (deflate.js:13)
    at Object.decryptMessage (deflate.js:13)
    at DedicatedWorkerGlobalScope.self.onmessage (openpgp.worker.js:94)

Without worker.js the error is:
TypeError: Cannot read property 'isDecrypted' of null
    at Message.decrypt (deflate.js:13)
    at deflate.js:13
    at deflate.js:13
    at execute (deflate.js:13)
    at Object.decryptMessage (deflate.js:13)
    at decrypt-test1.html:175

This happens using the latest code on Github,

Example code:
var message = openpgp.message.readArmored(document.getElementById('message').value);
openpgp.decryptMessage(privKey, message).then(
// I cannot place a `try` statement here
   function(decrypted) {
      console.log(decrypted);
      document.write(decrypted);
   },
            function(err) {
               alert('Decryption failed!');
            }
   );

The function (err) is executed and I see an alert, but I also get the console TypeError.

Please handle the TypeError, at least when an error function is defined, or maybe explain how I should put a try...catch to avoid it.

I also created a test case for this issue. It can be git cloned from:
https://github.com/barrydegraaff/pgp-zimlet/blob/master/test/decrypt-test1.html

**Comment by barrydegraaff** [comment]
deflate.js indicate it's an error thrown my zlib.min.js.map, when I blank that file the error becomes, without worker:

TypeError: Cannot read property 'isDecrypted' of null
    at Message.decrypt (https://192.168.1.26/service/zimlet/_dev/tk_barrydegraaff_zimbra_openpgp/openpgp.js:11898:24)
    at https://192.168.1.26/service/zimlet/_dev/tk_barrydegraaff_zimbra_openpgp/openpgp.js:12323:15
    at https://192.168.1.26/service/zimlet/_dev/tk_barrydegraaff_zimbra_openpgp/openpgp.js:12441:18
    at execute (https://192.168.1.26/service/zimlet/_dev/tk_barrydegraaff_zimbra_openpgp/openpgp.js:12440:17)
    at Object.decryptAndVerifyMessage (https://192.168.1.26/service/zimlet/_dev/tk_barrydegraaff_zimbra_openpgp/openpgp.js:12321:10)

**Comment by barrydegraaff** [comment]
to get rid of the type error, we could:

replace:
if (!privateKeyPacket.isDecrypted) throw new Error('Private key is not decrypted.');
with:
  if (!privateKeyPacket) {
    throw new Error('Private key is not decrypted.');
  } else {
    if (!privateKeyPacket.isDecrypted) throw new Error('Private key is not decrypted.');
  }

Then the type error is suppressed, by I still am unable to catch or suppress the resulting error, not with a try-catch or with the error function.

**Comment by let4be** [comment]
Same here, can this already be fixed...?

TypeError: Cannot read property 'isDecrypted' of null
    at Message.decrypt (openpgp.js:11898)
    at openpgp.js:12310
    at openpgp.js:12459
    at execute (openpgp.js:12458)
    at Object.decryptMessage (openpgp.js:12309)
    at DedicatedWorkerGlobalScope.self.onmessage (openpgp.worker.js:94)

**Comment by barrydegraaff** [comment]
Also asked on the mailing list and there is *nothing* but silence here, I guess the dev priorities are not *fixing/reading* issues.

**Comment by let4be** [comment]
yup, just fork&&fix

**Comment by barrydegraaff** [comment]
I looked into the code, but it is a bit more complicated than it seems, but be my guest!

**Comment by Morgiver** [comment]
Got the same error, but my private key is the good one.
