### ISSUE TITLE
Trouble signing messages with whitespace at the end

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#311]
See also: https://github.com/mailvelope/mailvelope/issues/254

Creating a signed message with a trailing space results in a PGP Message that never has a good signature.

Found this in versions of OpenPGP as early as 0.8.

Steps to reproduce:
Download:
https://github.com/barrydegraaff/pgp-zimlet/blob/master/test/sign-test1.html

Change:

openpgp.signClearMessage(privKeys.keys, 'This is a signed message ').then(
Note the trailing space in 'This is a signed message '

The resulting PGP ASCII message ALWAYS fails signature verification.

PLEASE fix!!

**Comment by tanx** [comment]
Please retry with current v2.x release

**Comment by barrydegraaff** [comment]
I retried with the 2.0.0 release and the 2.3.0 release and the problem still exists.

clear-signing a message with a white space on the end, still generated a PGP message that always fails validation.

Steps to reproduce:
https://gist.githubusercontent.com/barrydegraaff/c42ab23821a756839ff76090d6f58d42/raw/91cc0b2a1bfcba03b67ec7de7c84ac67dec2b2d4/gistfile1.txt

I would say-> reopen

**Comment by sanjanarajan** [comment]
Fixed by ebeedd3

**Comment by barrydegraaff** [comment]
@sanjanarajan thanks for fixing all these old issues!
