### ISSUE TITLE
Implement cross-compatibility testing by means of SauceLabs

### ISSUE THREAD

**Issue by evilaliv3** [openpgpjs/openpgpjs#313]
It would be relevant to implement some cross-browser compatibility testing in order to validate the implementation of OpenPGP.js among a wide range of Browsers, Versions and OS.

A complete in-the-cloud solution for this is offered by [https://saucelabs.com/](Saucelabs) that offers free accounts for OpenSource projects so that OpenPGP.js could benefit of it.

given the fact that openpgp.js makes us of Grunt, relevant library that would be interesting to integrate is [grunt-saucelabs](https://github.com/axemclion/grunt-saucelabs)

**Comment by evilaliv3** [comment]
I've implemented what is was suggesting; now on every commit each test is executed on the relevant browsers (now selected randomly) and results are published through a badge inside the [Readme.md](https://github.com/evilaliv3/openpgpjs/tree/feature/unittesting)

![screenshot from 2015-05-06 01 32 54](https://cloud.githubusercontent.com/assets/217034/7484993/11fe3898-f390-11e4-99cf-d54053341a9e.png)
![screenshot from 2015-05-06 01 33 09](https://cloud.githubusercontent.com/assets/217034/7484995/1751ffc8-f390-11e4-97b6-c7dbdd940112.png)

**Comment by AlexanderWillner** [comment]
very nice!

**Comment by evilaliv3** [comment]
![screenshot from 2015-11-28 18 50 56](https://cloud.githubusercontent.com/assets/217034/11453441/12cd31ac-960b-11e5-829b-b38b0f9c7421.png)

bam, integrate in master! enjoy!
