### ISSUE TITLE
Put unit testing under code coverage monitoring with Coveralls

### ISSUE THREAD

**Issue by evilaliv3** [openpgpjs/openpgpjs#314]
Monitoring of code coverage is a valuable indicator of unit testing maturity and It would be relevant to put unit-tests for OpenPGP.js under coverage monitoring by means of [Coveralls](https://coveralls.io)

given the fact that tests are implemeneted by means of Mocha relevant tools are [coveralls](https://github.com/cainus/node-coveralls) combined with [grunt-mocha-istanbul](https://github.com/pocesar/grunt-mocha-istanbul)

**Comment by evilaliv3** [comment]
I've implemented what is was suggesting; now code coverage is under monitoring and shows that currently only 79% of the library is covered; Coveralls.io offers a useful interface to review what are the crytical parts no covered in order to evaluate what tests write in order to rise up the coverage fastly.

![screenshot from 2015-05-06 01 15 13](https://cloud.githubusercontent.com/assets/217034/7484896/ac618a5e-f38e-11e4-80ee-a6b111f0e5b7.png)
![screenshot from 2015-05-06 01 15 24](https://cloud.githubusercontent.com/assets/217034/7484899/b404f264-f38e-11e4-9a8b-027fcfcef62f.png)
![screenshot from 2015-05-06 01 16 24](https://cloud.githubusercontent.com/assets/217034/7484902/bfebf5f0-f38e-11e4-9d39-f9cd5882e63f.png)

**Comment by evilaliv3** [comment]
bam, implemented and integrated in master! enjoy!

https://coveralls.io/github/openpgpjs/openpgpjs

![screenshot from 2015-11-28 18 50 56](https://cloud.githubusercontent.com/assets/217034/11453453/77cab4a8-960b-11e5-83f7-01e5403ee694.png)

**Comment by tanx** [comment]
Congrats 😊👍🏼

**Comment by tanx** [comment]
I'm guessing only the travis tests are used as a hard quality gate for pull requests since not all sauce labs tests pass for all browsers?

That would be fine and definitely an improvement over the status quo with the results pic visibale in the github readme.

**Comment by bartbutler** [comment]
Yes, fantastic I'll try to find some time soon to work on typed array stuff.
