### ISSUE TITLE
Extend OpenPGP.js for use on Python under PyV8

### ISSUE THREAD

**Issue by fpietrosanti** [openpgpjs/openpgpjs#316]
Currently there is no complete, pure-python implementation in Python.

Trough V8 binding, using PyV8, it would be possible to use/execute Javascript code.

This ticket is to integrate/test/extend OpenPGP.js for use under PyV8, pushing it automated testing for Python, with a PyPi package that extend OpenPGP.js to the Python Community.

PyV8 links: https://code.google.com/p/pyv8/
PyPi PyV8 package: https://pypi.python.org/pypi/PyV8

**Comment by tanx** [comment]
Seems pretty out of scope to me. A python wrapper should definitely go into its own github repo.
