### ISSUE TITLE
Performance in Firefox and Internet Explorer is no good

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#318]
I apologize in advance for the lack of technical argumentation in this issue.

When decrypting messages especially ones that are not created by OpenPGP.js (eg GnuPGP with Thunderbird/Enigmail) I must say Firefox and Internet Explorer are slow.

Also in general, every PGP operation is slow in Firefox and Internet Explorer while all is rocket fast in Google Chrome.

I am not sure how we can improve this, but I am opening this report for reference.

**Comment by barrydegraaff** [comment]
At times the PGP stuff is just to slow to be useful in Firefox and Internet Explorer

**Comment by barrydegraaff** [comment]
Firefox 38 performs a LOT better, to a point that it is almost comparable to chrome,

Also Microsoft Spartan (Edge) performs better, but seems to have a few bugs...

So there is hope after all

**Comment by ba1020** [comment]
i teste firefox 38.3.0 and it is still slow to not functioning

**Comment by geokis** [comment]
I had tried Mailvelope last year with firefox and the performance was horrible. For everyday use not recommended. So, I uninstalled the plugin.
Now I give Mailvelope a new chance and with firefox 40 I have no performance problems. Message encryption and decryption is instantly.

I use my old keys. So I don't know how fast the main key is generated but you must do it only **once**.

**Comment by tanx** [comment]
Try new 2.x release https://github.com/openpgpjs/openpgpjs#performance
