### ISSUE TITLE
generateKeyPair not working in Chrome + CSS

### ISSUE THREAD

**Issue by kiaraRobles** [openpgpjs/openpgpjs#319]
I get the following error messenger using the firebug debugger in the chrome browser.
```
NotSupportedError: Only secure origins are allowed. http://goo.gl/lq4gCo {...}
Error generating keypair using native WebCrypto... falling back back to js!

TypeError: Cannot read property 'generateKeyPair' of null
    at http://www.blockchainme.com/js/openpgp.min.js:10:11161
```

Openpgp generateKeyPair is currently working fine in firefox, safari with CSS, but only working in Chrome w/o it. All browsers are updated to the most current version. 

Is any CSS or PHP known to interfere with openpgp.min.js?

**Comment by guguso** [comment]
Hi,

I get the same problem. I use the last version of Google Chrome : Version 43.0.2357.132 (64-bit).

```js
DOMException: Only secure origins are allowed. http://goo.gl/lq4gCo(anonymous function) @ openpgp.min.self.js?body=1:8
openpgp.min.self.js?body=1:8 Error generating keypair using native WebCrypto... falling back back to js!
openpgp.min.self.js?body=1:8 TypeError: Cannot read property 'generateKeyPair' of null
    at openpgp.min.self.js?body=1:8
```

Has anyone found a workaround?

**Comment by alax** [comment]
This is the same issue as #320. Check there for further information.

**Comment by tanx** [comment]
Works as intended
