### ISSUE TITLE
Support Keylookup on Facebook for PGP public keys

### ISSUE THREAD

**Issue by fpietrosanti** [openpgpjs/openpgpjs#322]
Facebook now do support importing a PGP public key, that's then being used for encrypting notifications.

If OpenPGP.js would support key lookup, it would be nice to support key lookup trough Facebook.
https://www.facebook.com/notes/protect-the-graph/securing-email-communications-from-facebook/1611941762379302
Asked about this also on Google's end-to-end https://github.com/google/end-to-end/issues/297 .

Inquiry and comments to followup also on on Facebook's notes

**Comment by tanx** [comment]
Not sure this is an OpenPGP lib feature. Seems more like an application level feature.

I made some comments here https://github.com/google/end-to-end/issues/297#issuecomment-110352404
