### ISSUE TITLE
Is the Signature validity in the roadmap?

### ISSUE THREAD

**Issue by tcz001** [openpgpjs/openpgpjs#323]
I'm contributing to Enigmail, It is now using GnuPG agent which is not easy for modularization. OpenPGP.js comes to my eyes, as it have a much better code organize and maybe portable for thunderbird, but it seems the Signature validity is not covered in current APIs, I'd like to help but not sure if it's already in the roadmap.

**Comment by AlexanderWillner** [comment]
Interesting. I think some while ago I proposed to use OpenPGP.js in Enigmail...

**Comment by tcz001** [comment]
umm... there can be some issues when it's using cryptography API and compared with the LocalStore openpgp.js is using, system pin-entry and key-chain seems safer for the time being. But there still be some reusable parts.

**Comment by fpietrosanti** [comment]
@tcz001 Wow, OpenPGP.js in Enigmail would be a super cool thing! 
Please consider that, for possibly biggest projects, we could also approach the friendly Open Technology Fund guys also to finance major missing implementations and/or integrations, especially now that OpenPGP.js is being used by either Mailvelope and GlobaLeaks projects, supported by OTF, and Enigmail is an actively used project by Security Advocacy project, supported by OTF.

**Comment by glamrock** [comment]
Agreed, OpenPGP.js in enigmail would be a big improvement :D OpenPGP.js checks inline signatures with `verifyClearSignedMessage` and `decryptAndVerifyMessage`.  

Verifying detached signatures would be super useful -- particularly for me, since it would enable easy software verification.

**Comment by shea256** [comment]
I'm currently playing around with "verifyClearSignedMessage" and as others have hinted, it doesn't seem to verify the validity of the messages. In the return response, I only get back "signatures" (which is an empty array) and "text" and not the "valid" boolean, which is what I would expect from the documentation:
http://openpgpjs.org/openpgpjs/doc/module-openpgp.html

Is this function just a placeholder? As @tcz001 asked, is an implementation on the roadmap? Or am I using this function wrong?

**Comment by shea256** [comment]
Never mind, there just isn't good documentation on this function.

For others, please reference this comment for information on how to use verifyClearSignedMessage properly: https://github.com/openpgpjs/openpgpjs/issues/278#issuecomment-68598266
