### ISSUE TITLE
Error replicating unit test function

### ISSUE THREAD

**Issue by nicwhitts** [openpgpjs/openpgpjs#332]
Im receiving the error:
openpgp.js, line 15789: Error: Not allowed to define cross-origin object as property on [Object] or [Array] XrayWrapper

When replicating the unit test function:

openpgp.getWorker().decryptKeyPacket(privKeyRSA, [privKeyRSA.primaryKey.getKeyId()], 'hello world').then(function(key) {

within a firefox add-on 

Using older version of firefox i get:

"permission denied to unwrap object"

**Comment by tanx** [comment]
Retry with v2.x
