### ISSUE TITLE
Tour/guide/examples for openpgp.js

### ISSUE THREAD

**Issue by shea256** [openpgpjs/openpgpjs#333]
Hi everyone, I made a code tour of openpgp.js that I thought might be useful.

Here it is:

https://github.com/shea256/openpgp.js-tour

Is there some place for this in the project? Could this be cleaned up and incorporated into documentation? Should I submit a pull request?

Thanks!

**Comment by tanx** [comment]
See README and unit tests for v2.x https://github.com/openpgpjs/openpgpjs#getting-started
