### ISSUE TITLE
Key.prototype.decrypt can't decrypt with valid passphrase

### ISSUE THREAD

**Issue by destan** [openpgpjs/openpgpjs#335]
Hi,

Although I provide a valid passphrase `Key.prototype.decrypt` returns false. When I inspect the code, this row https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L364 in the loop seems to be the problem.

At this point the keys array is like: `keys = [SecretKey, SecretSubkey, SecretSubkey]` and `keys[i].decrypt(passphrase)` on line 364 only fails for the `SecretKey` but it succeeds for both of the `SecretSubkey`s in the array.

Because of `if (!success) return false;` part the whole function returns false.

What could be the problem to cause SecretKey decryption to fail but SecretSubkey doesn't with the same passphrase?

PS: the key is usable on linux commandline with gpg and generated via gpg. I don't think the key is somehow broken but not sure.

**Comment by toberndo** [comment]
The Key class assumes that key and all subkey packets of a key share the same passphrase. Different passphrases here is rather an edge case. You would need to decrypt the key packets separately.
