### ISSUE TITLE
Unable to output gpg compatible binary

### ISSUE THREAD

**Issue by dheniges** [openpgpjs/openpgpjs#339]
I've been looking at the library and am unable to get binary output that can then be read by `message.fromBinary()` and correctly decrypted. If I use ascii armor it decrypts without issue.

Here's the gist of what I'm doing:

```
// Read armored keys
var publicKey = openpgp.key.readArmored(key);
var privateKey = openpgp.key.readArmored(privKey).keys[0];
privateKey.decrypt('secret');

// Encrypt
  var message = openpgp.message.fromText('test');
  message = message.encrypt(publicKey.keys);
// This is not binary decodable by fromBinary. How do I output that?
  var encryptedMessageBinary = message.packets.write();

// Decrypt
var message = openpgp.message.fromBinary(encryptedMessageBinary);
var decryptedMessage = message.decrypt(privateKey);
console.log(decryptedMessage.getText()); // Message not decrypted
```

My problem seems to be `message.packets.write()` outputting binary that is not functional with other pgp-compatible libs like gpg. The `fromBinary` function correctly interprets gpg generated binary messages.

**Comment by bartbutler** [comment]
Yep, you are using fromBinary incorrectly. fromBinary is to create a message from binary data, i.e. an image in binary string form, without any encoding. fromText, in contrast, converts Javascript UCS-2/UTF-16 to UTF-8, which is obviously not what you want form encrypting binary messages.

Try replacing fromBinary with something like (untested):
var message = new Message();
message.packets.read(encryptedMessageBinary);

**Comment by dheniges** [comment]
@bartbutler thanks for the quick response.

`fromBinary` does what I expect, that is, interpret a binary message (which could contain an image or just non-ascii-armored text).

If I run `gpg --encrypt -r "user@example.com" plaintext.txt` (where user@example.com has an associated public key) I get a `plaintext.txt.gpg` file. I can then use `fromBinary` to load that file, and then decrypt etc. This works great.

So my question is how do I generate the binary output the `gpg` command does by default with this library?

**Comment by bartbutler** [comment]
Hi @dheniges,

That's very strange, because that shouldn't work. fromBinary() -> encrypt() -> packets.write() should be the OpenPGP.js counterpart to your plaintext.txt.gpg. You can then decrypt with packets.read() -> decrypt() -> getLiteralData().

**Comment by evilaliv3** [comment]
@hellais it thnk this was also your issue. do you confirm it?

**Comment by hellais** [comment]
I believe I also ran into this issue. Quite some time as passed so I don't remember the exact details, but I believe it has something to do with not having the correct PGP headers present in the encrypted stream.

To create a binary payload equivalent to `gpg -e -r x@bar.com` I believe you must wrap it also inside a packlist like so: https://github.com/hellais/openpgpjs/blob/feature/streamedEncryption_fixes/test/stream/message.js#L108

**Comment by dheniges** [comment]
Thanks for the pointers. It sounds like the functionality isn't currently available to get the binary payload compatible with other PGP solutions. From my limited understanding I assume this would require a stream implementation like @hellais has worked on, or at least a way to get a Buffer object from a message.

Unfortunately I don't think I have the understanding to move this toward a PR, but I think this would be a sought after feature.

**Comment by bartbutler** [comment]
message.packets is a PacketList, message.packets.write() should do what you want. I verified basic interoperability with GnuPG a couple months ago in binary form and it worked. I'm not sure what the issue is here (I'll try to find the time to try it again), but it DOES work.

**Comment by dheniges** [comment]
FWIW here's the simplest use case I've been using to test, assuming you have keys configured in openpgp and gpg:
```
  var message = openpgp.message.fromText("test message");
  message = message.encrypt(publicKey.keys);
  fs.writeFileSync('output.txt.gpg', message.packets.write());
```
then switching to the command line:
```
gpg --output decrypted.txt --decrypt output.txt.gpg
```
The error I get is `packet(3) with unknown version 195`

I've tested with keys generated from the command line and openpgp. The keys seem to work fine in all cases.

**Comment by bartbutler** [comment]
message.packets.write() writes a binary string. This will be changing, but in the mean time, you cannot just write that to a file due to encoding. Try converting it to a Buffer first and writing that:

var buffer = new Buffer(binaryString, "binary");

**Comment by dheniges** [comment]
@bartbutler ah, thank you so much, that's it! 

Any interest in an updated README? I would be happy to PR that. Expanded documentation seems to be a popular request on this repo.

**Comment by bartbutler** [comment]
Glad to hear it! I'd hesitate a bit on updating the docs too much in this particular case because OpenPGP.js will be moving soon away from binary strings and towards typed arrays, which will make encoding issues like this moot.

**Comment by barrydegraaff** [comment]
Can someone elaborate how to do this on the 2.x release? That would  be most helpful thanks!
