### ISSUE TITLE
decryptMessage returns message without signature

### ISSUE THREAD

**Issue by ablankenship10** [openpgpjs/openpgpjs#342]
When decrypting a message, the function only returns the string of the message body, rather than the complete armored message. This provides no information on whether or not the message was signed and if it was, being able to run it through `verifyClearSignedMessage`. I realize the function `decryptAndVerifyMessage` exists but what if I'm not sure if the message is signed or not?

**Comment by tanx** [comment]
See getting started guide: https://github.com/openpgpjs/openpgpjs#encrypt-and-decrypt-uint8array-data-with-pgp-keys
