### ISSUE TITLE
msg.decrypt is not a function

### ISSUE THREAD

**Issue by Morgiver** [openpgpjs/openpgpjs#349]
I got this error when i try to decrypt a message : 

"TypeError: msg.decrypt is not a function
    at openpgp.js:12376
    at openpgp.js:12521
    at execute (openpgp.js:12520)
    at Object.decryptMessage (openpgp.js:12375)
    at Socket.<anonymous> (SecureSocketService.js:55)
    at Socket.9.Emitter.emit (socket.io.js:1335)
    at Socket.5.Socket.onevent (socket.io.js:879)
    at Socket.5.Socket.onpacket (socket.io.js:837)
    at Manager.8.module.exports (socket.io.js:1197)
    at Manager.9.Emitter.emit (socket.io.js:1335)"

"Uncaught (in promise) Error: Error decrypting message!"

there's my code : 

function on(eventName, callback) {
        socket.on(eventName, function() {
        var args = null;
        var privateKey = pgp.key.readArmored($cookies.get('clientPrivateKey')).keys[0];
        privateKey.decrypt(options.passPhrase);
        pgp.decryptMessage(privateKey, arguments).then(function(plaintext) {
               $rootScope.$apply(function() {
                       callback.apply(socket, plaintext);
               });
        });
 });

Did i miss something ?

Thx in advance

**Comment by atd-schubert** [comment]
I had the same issue, but found out that you have to **read the armored message** first.

Something like:
```js
openpgp.decryptMessage(secretKey, openpgp.message.readArmored(message))
    .then(function (plaintext) {
        // Do something with the plaintext...
    });
```

**Comment by tanx** [comment]
See getting started guide: https://github.com/openpgpjs/openpgpjs#getting-started
