### ISSUE TITLE
gpg -e --symmetric compatibilty

### ISSUE THREAD

**Issue by wzrdtales** [openpgpjs/openpgpjs#350]
Hello together,

I'm currently trying to use openpgp as fallback if gpg or gpg4win are not available at the users computer.

I searched through the docs but couldn't find anything about this topic...

The question is, is it possible to decrypt a file that was encrypted via

    gpg -e -r mail --symmetric -a input.file

The file gets decrypted, however, the resulting new file is about 25KiB greater than the original. In short, the decrypted result doesn't match the original.

**Comment by greensolid** [comment]
PGP is a combination of symmetric and asymmetric mechanisms. Thus, it lifts the restrictions of symmetric algorithms but with fair computing time and the possibility to encrypt large files. Especially on the Internet, for which OpenPGPJS is built to some extent, symmetric encryption would be useless if you don't have a secure channel to exchange the keys. Therefore, if you want to use PGP on the Internet, switch to asymmetric encryption. Otherwise, try to use AES or any other symmetric method. There are also several open source JS libraries for that on the Web.

**Comment by wzrdtales** [comment]
This is actually not an answer...

gpg --symmetric is a asymmetric, or better said hybrid encryption. It encrypts a passphrase asymmetric and the files itself get encrypted symmetric by this passphrase.

**Comment by greensolid** [comment]
According to my references (e.g., the official <a href="https://www.gnupg.org/gph/en/manual/x110.html">GnuPG handbook</a>, or this <a href="http://www.tutonics.com/2012/11/gpg-encryption-guide-part-4-symmetric.html">tutorial</a>) the <i>--symmetric</i> option, as the term indicates, is a symmetric encryption where you can choose various symmetric algorithms such as AES. Assymetric means that you have different keys for encryption and decryption which is not the case.

**Comment by wzrdtales** [comment]
Ok, my fault, I changed the title so this matches. But actually the problem persists. The decryption don't work, the output is malformed and way to big.

**Comment by wzrdtales** [comment]
Ok, I just digged a bit deeper and have maked a diff from the original to the new decrypted file. 

```
<U+0089>PNG
^Z
```

Seems to be an encoding issue

**Comment by wzrdtales** [comment]
Ok, for everyone else running into this issue.
You need to specify the encoding to be ascii when writing to a file and you also need to use the getLiteralData method instead of the getText (which `openpgp.decryptMessage` utilize).

## Example

```javascript
    var pgpMessage = openpgp.message.readArmored(data.toString());
    var msg = pgpMessage.decrypt(privateKey);


    fs.writeFile( file, msg.getLiteralData(), { encoding: 'ascii' }, function ( err ) {
      if (err) throw err;

      console.log('Successfully decrypted file %s', file);
    });
```
