### ISSUE TITLE
How to re-encrypt private key with new passphrase?

### ISSUE THREAD

**Issue by nategrover** [openpgpjs/openpgpjs#356]
I'd like to decrypt an existing private key using the existing passphrase for that key, then set a new passphrase and re-encrypt the key before exporting again.

**Comment by bartbutler** [comment]
Try something like this (no warranty):

        var _prKey = openpgp.key.readArmored(prKey).keys[0];
        var ok = _prKey.decrypt(oldMailPwd);
        if (ok) {
            _prKey.primaryKey.encrypt(newMailPwd);
            _prKey.subKeys[0].subKey.encrypt(newMailPwd);
            return _prKey.armor();
        } else return -1;
