### ISSUE TITLE
Browser won't execute script when trying to link to the dist on github.

### ISSUE THREAD

**Issue by spacebuilder2020** [openpgpjs/openpgpjs#358]
When I link to the github source by https://raw.githubusercontent.com/openpgpjs/openpgpjs/master/dist/openpgp.min.js for example, my browser in the debug panel reports that it refuses to execute script due to the mime type being plain text vs javascript.

**Comment by burzak** [comment]
Hi,

That mime type is what tells the browser how it should interpret the file. Sending the plain text header avoid the fact people using Github as a CDN.

Try hosting it yourself, you won't have any other problem.

**Comment by spacebuilder2020** [comment]
ok

**Comment by christianbundy** [comment]
Alternatively, use [RawGit](https://rawgit.com/).
