### ISSUE TITLE
Passing in private key as a string

### ISSUE THREAD

**Issue by joshterrill** [openpgpjs/openpgpjs#361]
I'm trying to pass in a private key as a string into a decrypt function. However I keep getting a `Cannot read property 'decrypt' of undefined` happens when I try to throw the whole key into a string, and I get `Unknown ASCII armor type` when I try to add `\n` to the end of each line.

**Comment by joshterrill** [comment]
I found out that this is happening because in my use case, the private key is ending up as a one line string. It would be awesome if `openpgp.js` could support being able to parse the keys as one line strings.

**Comment by tanx** [comment]
See getting started guide: https://github.com/openpgpjs/openpgpjs#getting-started
