### ISSUE TITLE
Support for keys stored on smartcards

### ISSUE THREAD

**Issue by jas4711** [openpgpjs/openpgpjs#362]
I have my private OpenPGP key on a YubiKey NEO and it would be nice to use it with OpenPGP.js.  

Thinking about how to implement this: Chrome has a USB API available from JavaScript, which is flexible enough to allow FIDO U2F to be implemented in JavaScript.  I would assume it is possible to implement support for CCID as well, and then on top off that, the OpenPGP Card Applet protocol in order to talk to the device.

Alternatively, call out to some host daemon to perform the private key operations for the browser.

**Comment by reuterbal** [comment]
+1

**Comment by tanx** [comment]
> Chrome has a USB API available from JavaScript, which is flexible enough to allow FIDO U2F to be implemented in JavaScript.

We're in the process of moving optional functionality to external modules and keeping the core crypto lib nice and lean. I'd recommend a seperate `openpgp-smartcard-storage` npm module for this feature.

**Comment by pbudzon** [comment]
Is there a timeline on this, or at least an open issue in another repo? Thanks!

**Comment by shuffle2** [comment]
Yea hm, closing this issue is fine if there is some other issue tracking the feature...but where would that be?

**Comment by phryneas** [comment]
Hi, I'm curryently trying to create a NativeMessagingHost application that uses the gpgme library for this kind of actions. 
I would like to provide such an external modules, do you offer any mechanisms to create a drop-in that would overwrite central functionality of openpgp.js?

**Comment by ecki** [comment]
WebCrypto could allow access to (PKCS11) hardware/software tokens for keystorage, but it is not fully specified, so I dont know if there are implementations. In any case that would not be a pure "key storage" module, as it also offloads the sign/verify/encrpt operations with that key. Anyway, if there is an implementation which can use a agent-side keystore (PKCS11/NSS) it just needs some additional slot management.

**Comment by Ulrar** [comment]
I was thinking of making an app using the Native messaging host too, @phryneas did you end up doing that ? Is this something you released somewhere by any chance ?

**Comment by phryneas** [comment]
yes, and I had something working but I never finished it, so take this repo with some warnings: https://github.com/phryneas/GnuPGHostApp
