### ISSUE TITLE
Can't decrypt openpgpjs (JS) encrypted pgp message with gnupg (Ubuntu GPG via PHP)

### ISSUE THREAD

**Issue by onetwoninea** [openpgpjs/openpgpjs#367]
I'm currently developing a pgp secured web-chat where the encryption is done on client side (Javascript using openpgpjs library) and is stored encrypted in a mysql DB.

In order to send the data to multiple user the server has to decrypt the stored message with PHP code (using gnupg PHP library which uses gpg on Ubuntu server) and re-encrypt it with the public keys of the users before he sends the document to them so that they can decrypt it with javascript.

The problem here: I can use openpgpjs to decrypt openpgpjs encrypted messages and I can use gnupg to decrypt gnupg encrypted messages. BUT I can not use openpgpjs to decrypt gnupg encrypted messages and other way round I can not use gnupg to decrypt openpgpjs encrypted messages.

After testing some scenarios I've compared the outputs of the encrypted text "Hallo!" which has been generated with the same public key but using the different libraries.

So the two outputs are:

"Hallo!" encrypted with openpgpjs library:

> -----BEGIN PGP MESSAGE----- Version: OpenPGP.js v1.3.0 Comment: http://openpgpjs.org wcFMA2jCJsaw5XYZAQ//Y84a7AI8JcFcqlWkIG3BNeOSTQowlPKS/TRIRT58 yTr0XHMriDRXeYoHsXEeaQA9aQAAKFnuD1Mi35MfGfGBB5MdFhJVLOZoIRBx 0a9U/bRQXgHcGMxoLjCUe20dzWl9cxQUNiWTcATCPlJwdYwk9Nr8ZDifgLxH 4yUxqtjS1Zcoc9Xaf89mTXlLedsjpLlwCv5t/hlE5QavEeN/l1aqFXE3WMVp CE GBDFQKqqKRfnPC3KUARoI8lv9tHfX58uuMXrf1kXBmHPsFAwb3mVIhC47 Pew4tJEjS9xB2aIJkO4pnFyH1mXroyqk6bEqRovv3SF I2Pztz3smJfLdPTy v7Sdi7zCbgQe50RkqYZ6zby1SrCmlu IVAKjdAaPz9GwmEzeMlRgmwyqozEv CifnWndWaDhwbUaSyO3GVjG8RlKEydLSzFTPXckdPV0l9oEHsP1O2/W0/XY4 nXMhwpG2bjhv5PoqvBAIPa9qGaPvW8SU1TrWUaSWKMbL7dWIv7Gs xeGQI m sI9aVmCd9fBNe5HEoMaSGPH6R/DJ/LzJQ6ZazVAivuYXkZyuJoc5wXR0lrGJ pPaJkQn0Oue3FDVW8Rhi8jPU0t/akGRTQO92xm9ZcSeJNCW17QB5owyzWFKO nMsTiM7Og7CHf8q07Vv80J8QwmvvtFEDbeRuuI qFrDSPgEa5FxWW/NEhx8d E1E97w7DqO8XMsORhDJCX54OoiFgXm65FvITGCPMUDZoPiKi3ssI1N42ajfP 7V8Gif F =4s5I -----END PGP MESSAGE-----

"Hallo!" encrypted with gnupg library:

> -----BEGIN PGP MESSAGE----- Version: GnuPG v2.0.22 (GNU/Linux) hQIMA2jCJsaw5XYZAQ/+IFsMFRuBlUNtUsm2w5uZ5Ty/XiFbhwprd9yvB3gQ4o2O N2n3/1EnZTdjW/JVl0oWU9E6juQvWbZPKzvttT3//XYwwPtsrCo4QPkUG7nCMyO9 smOwc3o2UKeyxVdYOa0kJXupvOydBLSb//cFfT2uTS8CnvCGCQFryPR553W1gY/9 A8FEnllO35V3Tj8Lt7YNci9UGVKsExMCaY12VR8QmaSUHmNevhxxMKoz06r2At9t S2gFEK70StcU+0uqJhbg8sm5EdTlW+q166GFGV848msQ9kFrmWKx7NTj6tpAwA8Q 57Icy77nCDhN6H5CiYoS0TFB3YmxN9oN4d5FRt68vwYGXe7WNqDf6I7W9Pzlu76F 7md9NKnhKHkae2FHECkEixEhuZmnFxVqdVqY9DdbHvmYbPaUSykm/q2AF6pIB4wf ydM9QN4ZKDjgw4zrE4BbNpMjgAzn5GYlRq6gJqQAcNVjvNYbdoxyyfdKyjerAnaq K85HZtD3FfFZ4+t2GMtwdkau46pnCFlazqA+Z1o+JdQFqmP1ROxzBheWup9cvpi/ n2mArxWgjik3T1VYYPHwNtj4JwTtqpBOJB2RGAauNNUinCT94cKUb3zaqDlAyCrG rCPwTvdq8Ri9ZIrvhz1K8kw1GK624dqn5CBPTo9ap/ACMmER19X5qVcoIQrBnOfS QQGR49e1aJZ4WeLf2FCLrumecb8s6HEYdiZppdWrnNkBVreEgeAD+2IsjoxZeKrD NDU1Uebhu7wTCgvZ/A6hkCP9 =R+YJ -----END PGP MESSAGE-----

as you can see they are clearly different.

So my question is: Is there a difference in the pgp algorithms/versions they are using? On openpgpjs.org it says that openpgpjs is using openpgp.. but this should be compatible to gnupgp, shouldn't it? AND: Is there a way (and what should I do for that?) to use openpgpjs and gnupg together in a compatible way so that I can encrypt and decrypt messages through another?

Thanks in advance!

**Comment by bartbutler** [comment]
You should read up a bit on the OpenPGP standard--the public key is used to encrypt a random key, and this random key is used with a symmetric algorithm (usually AES) to encrypt the message. So two encrypted messages with the same unencrypted content will be different. This is both a performance optimization (AES is faster than RSA) and more importantly a security feature, because non-randomized ciphertext is less secure for a number of reasons.

GnuPG and OpenPGPjs should be fully compatible between one another. I suggest you check formatting and line break conventions--looking at your quoted text, the line breaks seem to be stripped out, and line breaks do matter for ASCII-armored messages.

**Comment by onetwoninea** [comment]
"So two encrypted messages with the same unencrypted content will be different. "

But why is it always the same output in PHP and always the same output in JS? Its not like the output changes from encryption to encryption. They just differ between the libraries I've used.

But I've found another issue in my code. Im sending the pgp encrypted message with an AJAX POST request which turns "+" into whitespace and corrupts the message.

**Comment by alax** [comment]
> But why is it always the same output in PHP and always the same output in JS? Its not like the output changes from encryption to encryption. They just differ between the libraries I've used.

It definitely should not be the same-- PGP is not deterministic, and you definitely should not be getting identical outputs with identical inputs time after time. Like @bartbutler said, each message should have a unique session key, which will cause the output to always be different.

**Comment by bartbutler** [comment]
Like @alax said, If you are getting a deterministic output, something is wrong (probably your random number generator).

**Comment by gmontalvoriv** [comment]
+1
