### ISSUE TITLE
Inconsistency when decrypting images

### ISSUE THREAD

**Issue by larcohex** [openpgpjs/openpgpjs#369]
I have encrypted image using GnuPG, then I compared decrypted images from GnuPG and openpgp.js (need to convert it to base64 string and add to image in DOM).

openpgp.js produces an invalid image.

Used this code:

**popup.html**

    <!doctype html>
    
    <html>
    <head>
    	<title>Popup</title>
    	<script src="openpgp.js"></script>
    	<script src="popup.js"></script>
    </head>
    <body>
    	<p>Upload message: </p><input id="message" type="file"/><br>
    
    	<p>Upload secret key: </p><input id="secret" type="file"/><br>
    
    	<p>Secret key password: </p><input id="password" type="password"/><br><br>
    	<button id="decrypt">Decrypt</button>
    	<p id="output"></p>
    
    	<div id="loadingDiv"></div>
    </body>
    </html>

**popup.js**

    var message = "";
    var secret = "";
    
    
    function readMessage (e) {
    	var file = e.target.files[0];
    	if (!file) {
    		message = "";
    	}
    	var reader = new FileReader();
    	reader.onload = function (e) {
    		message = e.target.result;
    	};
    	reader.readAsText (file);
    }
    
    
    function readSecret (e) {
    	var file = e.target.files[0];
    	if (!file) {
    		secret = "";
    	}
    	var reader = new FileReader();
    	reader.onload = function (e) {
    		secret = e.target.result;
    	};
    	reader.readAsText (file);
    }
    
    
    
    
    function loadScript(url, callback)
    {
    	var head = document.getElementsByTagName ("head")[0];
    	var script = document.createElement ("script");
    	script.type = "text/javascript";
    	script.src = url;
    
    	script.onreadystatechange = callback;
    	script.onload = callback;

    	head.appendChild(script);
    }
    
    
    document.addEventListener ("DOMContentLoaded", function() {
    	document.getElementById ("message").addEventListener("change", readMessage, false);
    	document.getElementById ("secret").addEventListener("change", readSecret, false);
    	var gen = function() {
    		document.getElementById ("decrypt").addEventListener ("click", function() {
    			var output = document.getElementById ("output");
    			output.style.color = "black";
    			if (document.getElementById ("message").value == "") {
    				output.innerHTML = "No message provided";
    				output.style.color = "red";
    			}
    			else if (document.getElementById ("secret").value == "") {
    				output.innerHTML = "No secret key provided";
    				output.style.color = "red";
    			}
    			else if (document.getElementById ("password").value == "") {
    				output.innerHTML = "No password for secret key provided";
    				output.style.color = "red";
    			}
    			else {
    				var privateKey = openpgp.key.readArmored (secret).keys[0];
    				var isCorrect = privateKey.decrypt (document.getElementById ("password").value);
    				if (isCorrect) {
    					output.innerHTML = "";
    					output.style.color = "black";
    					var img = document.createElement ("img");
    					img.src = "loading.gif";
    					img.id = "loading";
    					document.getElementById ("loadingDiv").appendChild (img);
    					message = openpgp.message.readArmored (message);
    					openpgp.decryptMessage (privateKey, message).then (function (plaintext) {
                            output.innerHTML = plaintext;
                        }).catch (function(error) {
                            output.innerHTML = "Error while decrypting";
                            output.style.color = "red";
                        });
    				}
    				else {
    					output.innerHTML = "Incorrect password";
                        output.style.color = "red";
    				}
    			}
    		});
    	}
    	loadScript ("openpgp.js", gen);
    });

Compare `output` from `popup.js` and data from GPG-decrypted image.

**Comment by bartbutler** [comment]
decryptMessage converts text from UTF-8 to UTF-16/UCS-2. You need to use a binary mode otherwise it's going to corrupt your image.

**Comment by larcohex** [comment]
@bartbutler thank you for your response
as I have understood (sorry for noob question), i need to instead cast to `message = openpgp.message.fromBinary (message)`. is that the method that uses a binary mode?
i have tested like that, and it seems that i don't quite do the right thing since then decrypting fails with `Parameter "utf8" is not of type string`

**Comment by bartbutler** [comment]
That's actually the other direction (making a message from binary data). To get binary data from a message, you decrypt the message and then use getLiteralData:

msg = openpgp.message.readArmored( armoredMessage );
msg.decrypt(key);
var data = msg.getLiteralData();

This could and should be improved...it's not exactly straightforward, and doesn't use the WebWorker. This will be addressed in 2.0 when we have time to work on it and get it out.
