### ISSUE TITLE
KeyGeneration no useable subkey for encryption?

### ISSUE THREAD

**Issue by onetwoninea** [openpgpjs/openpgpjs#372]
Im currently building a pgp secured chat and want to store the publicKey of the keypair from the client inside a mysql database.  But when I try to encrypt some message with the ASCII armored public key from mysql (which i already imported into gpg keyring on ubuntu server) it says "gpg: [...] skipped: Unusable public key" and when I take a look on it it misses a subkey. 

So now I want to ask if it is

a) possible to generate the publicKey with a subkey which is useable for encryption 
b) possible to change the usage of gpg on ubuntu so that it is using the public key at all and not searching for a subkey..

This is my keypair generation code:

function generateKeyPair(inPassphrase, inUserID, inBits)
{
    inProgress = true;
    var options = {
        numBits: inBits,
        userId: inUserID,
        passphrase: inPassphrase
    };
    var keyP = openpgp.generateKeyPair(options).then(function(keypair) {
        privateKey = keypair.privateKeyArmored;
        publicKey = keypair.publicKeyArmored;
        inProgress = false;
    }).catch(function(error) {
        inProgress = false;
        alert(error);
    });
}

And im sending the text inside of "publicKey" to the server.

but on the server it doesn't shows a subkey...

Am I doing something wrong?

**Comment by sanjanarajan** [comment]
Please try this again with the latest version of the library - by default all keys are generated with a single encryption-enabled subkey.
