### ISSUE TITLE
IE9: No secure random number generator available

### ISSUE THREAD

**Issue by k-one-o-two** [openpgpjs/openpgpjs#378]
Hi!

There's a problem in ie9 - `getRandomValues` fails with the exception mentioned above.
Currently I'm found a workaround using this https://crypto.stanford.edu/sjcl/ and this https://github.com/rubycon/isaac.js and this code instead of throwing an exception
```
var sjcl = window.sjcl;
      if (sjcl.random.isReady()) {
        var buf = new Uint8Array(1);
        bytes = sjcl.random.randomWords(buf.length);
        buf.set(bytes);
      }else{
        var bytes = [];
        for (var i = 0; i < buf.length; i++) {
          bytes.push(isaac.rand());
          buf.set(bytes);
        }
      }
```

Maybe you can use it to add support for old browsers?

**Comment by tanx** [comment]
Nope. getRandomValues is a requirement. See readme.
