### ISSUE TITLE
Missing compression (zlib is default)

### ISSUE THREAD

**Issue by AlexanderWillner** [openpgpjs/openpgpjs#38]
Carsten wrote:

> To be compatible with GnuPG this library is missing compression (zlib is default). I was hoping that this is implemented before we even have key generation ;)
>
>
> The standard currently defines the following compression algorithms:
>
> ID      Algorithm       Req.
> --      ---------       ----
> 0     - Uncompressed    MUST
> 1     - ZIP [RFC1951 <http://tools.ietf.org/html/rfc1951>]   SHOULD
> 2     - ZLIB [RFC1950 <http://tools.ietf.org/html/rfc1950>]  MAY
> 3     - BZip2 [BZ2 <http://tools.ietf.org/html/rfc4880#ref-BZ2>]     MAY
> 100 to 110 - Private/Experimental algorithm

**Comment by tanx** [comment]
It seems this issue is ancient and not relevant anymore.
