### ISSUE TITLE
Unknown ASCII armor type

### ISSUE THREAD

**Issue by crathermel** [openpgpjs/openpgpjs#381]
@tanx @toberndo I am getting the error 'Unknown ASCII armor type' w/ the following code... This an encoding issue? I have tried using my public key and a few others found online and they all seem to generate the same error. What am I missing?

``` javascript
var fs = require('fs');
var openpgp = require('openpgp');

var fs = require('fs');
fs.readFile('twi_key.txt', { encoding: 'utf-8' }, function (err, data) {
     var rawPublicKey = data;
     fs.readFile('message.txt', { encoding: 'utf-8' }, function (err, data) {
          var rawMessage = data;
          var publicKey = openpgp.key.readArmored(rawPublicKey).keys[0];
     });
});
```

**Comment by mapmeld** [comment]
@crathermel can you ```console.log``` what rawPublicKey looks like right before you pass it to openpgp.key.readArmored? When I've had this issue, it's always been:

- I got a fs function, filename, or encoding wrong, so the string is unreadable
- the public key was not exported with the --armor option, so it looks like this ```Vg�ȞRK��/��|�{�```

**Comment by brycepj** [comment]
@mapmeld I'm having a similar issue to @crathermel (the same error is being thrown), but am confused. Maybe you can help me. 

From [the documentation for decrypting strings](https://github.com/openpgpjs/openpgpjs#encrypt-and-decrypt-string-data-with-pgp-keys), it seems that to decrypt a file, all I need to pass is a private key and an encrypted message. The public key is optional.

Even so, I've inspected both private and public keys and both look like your standard public/private key text blocks (strings). The message is being read correctly, and is encrypted. As far as I can tell, there aren't any errors with filepaths or encoding. But this seems like a pretty basic use case for this library --  I must be using this incorrectly. Any insight you can offer?

Here's a slightly simplified version of my code: 
```javascript
const fs = require('fs');
const openpgp = require('openpgp');

// Get pubkey and privKeys, both return strings

const privKey = fs.readFileSync('./keys/priv.txt', 'utf-8');
const pubKey = fs.readFileSync('./keys/pub.txt', 'utf-8');

// Get encrypted password

const encryptedMessage = fs.readFileSync('./tmp-pw/oak.txt.gpg', 'utf-8');

const decryptOptions = {
    message: openpgp.message.readArmored(encryptedMessage),
    privateKeys: openpgp.key.readArmored(privKey).keys[0]
};

openpgp.decrypt(decryptOptions)
  .then(function (plaintext) {
   return plaintext.data; // 'Hello, World!'
  })
  .catch(function (error) {
     // this is logged each time: `Error: Unknown ASCII armor type`
     console.log(error);
  });

```

**Comment by VTCAKAVSMoACE** [comment]
I found that using `.split("ARMORED FILE").join("MESSAGE")` on the ASCII-Armored string fixed this problem. Looking at the source, I found that the headers simply didn't match, and that replacing the peices of the header that were 'incorrect' with the 'correct' headers works just fine. This is non-destructive to the ASCII-armored text as well, since there are no spaces in these files except in the headers.

Hope this helps.

**Comment by evilaliv3** [comment]
Nice catch @VTCAKAVSMoACE

Would be nice if you could provide a patch by:
1) adding a unit test that proove that the bug exist
2) actually fixing the issue prooving that the test in 1 pass.

This way we could integrate the fix even by today!

**Comment by crathermel** [comment]
I was being a dummy - My problem was that I was just pasting in the contents of the key into a newly created file instead of using the actual file created

**Comment by VTCAKAVSMoACE** [comment]
@evilaliv3 I may or may not have forgotten that this was GitHub. I'll make a pull req later tonight.

**Comment by evilaliv3** [comment]
Perfect!  Looking forward for reviewing it!
