### ISSUE TITLE
error in using openpgpjs

### ISSUE THREAD

**Issue by aghamohammadi** [openpgpjs/openpgpjs#383]
i use your library but this error happen!!
please help me
![untitled](https://cloud.githubusercontent.com/assets/12841248/11998000/672cf844-aaa2-11e5-8a9e-ab4c73e3eb48.jpg)

**Comment by sctskw** [comment]
In order for anyone to answer this with any efficiency, you need to provide the full details of the problem. Including, but not limited to, the code you are using to produce this error, and any/all keys necessary to reproduce the problem.

**Comment by aghamohammadi** [comment]
thanks for replay
its solved, this was problem from key structure . deleted "\n" in key! this link https://github.com/openpgpjs/openpgpjs/blob/master/test/worker/api.js#L9
