### ISSUE TITLE
generateKeyPair is never solved

### ISSUE THREAD

**Issue by maxime1992** [openpgpjs/openpgpjs#386]
Hi, I'm trying to use openpgpjs into the browser (chrome 47).

I made an `npm install --save openpgp` then I just added `/node_modules/openpgp/dist/openpgp.min.js` to my script src.

When I run 
```
var options = {
    numBits: 2048,
    userId: 'Jon Smith <jon.smith@example.org>',
    passphrase: 'super long and hard to guess secret'
};

openpgp.generateKeyPair(options).then(function(keypair) {
    // success
    console.log('ok !');
    var privkey = keypair.privateKeyArmored;
    var pubkey = keypair.publicKeyArmored;
}).catch(function(error) {
    // failure
    console.log('fail !');
});
```

I do not get any console log (neither 'ok !' nor 'fail !').

The only thing displayed in chrome is : 
![image](https://cloud.githubusercontent.com/assets/4950209/12480932/1b353528-c046-11e5-8f21-4d32b882492b.png)

What am I missing ? Thanks for your help.

**Comment by mwthink** [comment]
I don't think options.userId is a valid attribute. 
Change it to options.userIds with an object with a name and email attribute and you should be good to go. 

Like this.
```js
var options = {
	userIds:[{name:'Jon Smith',email:'jon@example.com'}],
	numBits: 2048,
	passphrase: 'password'
};
```

**Comment by maxime1992** [comment]
@mwthink thank you :) I don't have much time to try it right now but it will be useful later !
