### ISSUE TITLE
Evaluate how to monitor memory usage and implement a unit test for it

### ISSUE THREAD

**Issue by evilaliv3** [openpgpjs/openpgpjs#403]
While following the development of the typed array branch i'm thinking that an important nice to have in our re-testing setup is a monitor for the memory usage of openpgp.js in order to be sure that:
- no memory leaks exist in the library and eventually spot them early;
- change in implementations like passing from string to typed array and vice versa does not cause important changes in memory allocations.

I've already thought a little about this and i'm imagining that probably in some unit tests we can simply use `process.memoryUsage()` when test are run using Node
and put some assetions in order to see that the memory allocation is the one that we expect to be.

https://nodejs.org/api/process.html#process_process_memoryusage

**Comment by tanx** [comment]
+1 :)
