### ISSUE TITLE
"This seems to be a pre-built javascript file" while importing the library in Webpack

### ISSUE THREAD

**Issue by pzduniak** [openpgpjs/openpgpjs#408]
Good job with the 2.0 release, I'm impressed :)

It introduced one issue that bugs me quite a bit:

```js
import openpgp from 'openpgp'
```
results in
```
WARNING in ./~/openpgp/dist/openpgp.js
Critical dependencies:
1:480-487 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/openpgp/dist/openpgp.js 1:480-487
```

```
import openpgp from 'openpgp/src/openpgp'
```
results in
```
ERROR in ./~/openpgp/src/openpgp.js
Module parse failed: /Users/pzduniak/gopath/src/github.com/pzduniak/haus/react-redux-starter-kit/node_modules/openpgp/src/openpgp.js Line 35: Unexpected token
You may need an appropriate loader to handle this file type.
| 'use strict';
|
| import * as messageLib from './message.js';
| import * as cleartext from './cleartext.js';
| import * as key from './key.js';
 @ ./src/main.js 37:15-45
```
(which pretty much means that I would need to somehow replicate the building process from OpenPGPjs)

**Comment by pzduniak** [comment]
Oops, I messed up the Webpack configuration. You didn't see that :)

**Comment by tanx** [comment]
:)

So importing via native ES6 works for you? Or are you using an ES5 transpiler like babel?

**Comment by pzduniak** [comment]
Followed up in #409. I got it working with Webpack+Babel6.

**Comment by jsatk** [comment]
@pzduniak I was able to get this working using `import * as openpgp from 'openpgp';`

**Comment by securityvoid** [comment]
@pzduniak Would you be willing to share your Webpack config that got this working? I'm also having issues with Webpack; but I'm not sure if its related.

**Comment by pzduniak** [comment]
@securityvoid IIRC I simply forked it and put the compressed files there. I can't really help with that issue anymore, I migrated to kbpgp, mostly due to project politics.
