### ISSUE TITLE
openpgpjs.org shows a 404 error page

### ISSUE THREAD

**Issue by pzduniak** [openpgpjs/openpgpjs#412]
Not sure what could possibly cause it, might be a issue with GitHub itself.

**Comment by AlexanderWillner** [comment]
Thanks. We're moving the web site to another hoster. @tanx : I assumed that we'll not have any downtime

**Comment by tanx** [comment]
@pzduniak thanks for the report.

@AlexanderWillner it seems cloudflare dropped my configuration because the domain transfer took too long ;) I'll set the DNS settings up again tomorrow. Then we should finally have TLS on the website.

**Comment by tanx** [comment]
Ok. The domain DNS record are now configure via Cloudflare. The website should now be reachable again and automatically upgrade to TLS via HSTS header (where available):

https://openpgpjs.org

@AlexanderWillner I've wired up most of the subdomains and updated the corresponding links on the website. It might take up to 48 hours to propagate all the DNS changes. Please verify that everything works as before. Most important is probably the MX records and the mailing list.

Thanks

**Comment by AlexanderWillner** [comment]
@tanx touché ;)
@tanx my mail alias and the list seem to work - https://openpgpjs.org/contact.html is not working anymore - will send you a mail for this one.

Thanks for the work.

**Comment by tanx** [comment]
Ok thanks 👍🏼
