### ISSUE TITLE
Show stream examples

### ISSUE THREAD

**Issue by piranna** [openpgpjs/openpgpjs#419]
Add some examples using streams usage, specially for sign verification (that's my use case).

**Comment by tanx** [comment]
Streams aren't currently supported and will likely be in a seperate module.

**Comment by piranna** [comment]
Is there a way to update verification progresively using data chunks
instead of need to load all the data in memory on a single TypedArray? If
so, I could be able to create that independent stream module.

**Comment by piranna** [comment]
In fact, [I have already done it](https://github.com/piranna/download-checksum/blob/master/lib/VerifyPGP.js), only that as you can see it's needed to load all the data in memory previously to process the signature. Is there any way to update the signature on each data chunk?

**Comment by fpietrosanti** [comment]
@piranna there's @evilaliv3 that implemented streaming support, check it out the pull request implementing it. For proper integration into OpenPGP.js @tanx require it to be a separate module, if you wish to work on it
