### ISSUE TITLE
[request] Remove boat from OpenPGP

### ISSUE THREAD

**Issue by naturalist** [openpgpjs/openpgpjs#420]
Stop accepting pull requests that introduce bloat-features like localStorage and integration with remote key repositories! Those have no place in the core project. A PGP library should do one thing and do it well - handle crypto.
 
If you think those extra features are useful to someone then consider implementing a plugin system and making them available as optional plugins. Then the larger community can add whatever else they need, for example IndexedDB store, integration with Keybase.io, etc., etc.

Alternatively, you could issue OpenPGP Lite (or Lean) that does only crypto and none of the over-engineered bloat.

I hope you don't take my sharp tone as offensive. OpenPGP has become very popular and being the only JS library that does PGP, it has become very important for the community.

**Comment by bartbutler** [comment]
@tanx has been very vocal about wanting to move to a plugin-based systems for these useful but not 'core' extra features. We are all in agreement on this.

**Comment by naturalist** [comment]
Great! Looking forward to using a modular OpenPGP. Let me know if you need help.

**Comment by tanx** [comment]
I think there actually isn't much involved in moving stuff into modules. We already ise ES6 modules and basically just append a module e.g `hkp` to the default `openpgp` module before exporting it. I suggested a proposal to move optional to their own github repos under this GH organisation e.g `openpgp-hkp` and load that as a seperate npm module if required in a project:

https://github.com/openpgpjs/openpgpjs/pull/321#issuecomment-183903268
