### ISSUE TITLE
Implement AES-GCM proposal (IETF draft)

### ISSUE THREAD

**Issue by tanx** [openpgpjs/openpgpjs#421]
See https://tools.ietf.org/html/draft-ford-openpgp-format-00

The main advantage of AES-GCM for OpenPGP.js would be that it's available natively in both the WebCrypto api and node's native crypto module. Adopting the IETF proposal would put us in a position where we could move away from JS ciphers that are subject to timing attacks and do all crypto natively with safe/modern primitives.

This would also allow us to deprecate old/busted crypto like SHA-1 and AES-CFB (resync mode) which will probably not be implemented by browsers:

https://bugs.chromium.org/p/chromium/issues/detail?id=438393

**Comment by fpietrosanti** [comment]
@evilaliv3 Given that globaleaks PGP operations doesn't need to have third party compatibility other than with GLClient/OpenPGP.js, can be already use only WebCrypto ciphers in our clientside implementation?

**Comment by tanx** [comment]
First implementation here: https://github.com/openpgpjs/openpgpjs/pull/430
