### ISSUE TITLE
RSA asm.js implementation

### ISSUE THREAD

**Issue by tanx** [openpgpjs/openpgpjs#423]
Add asmCrypto's RSA implementation to our asmCrypto-lite build and replace current JSBN based implementation. More details here: https://github.com/openpgpjs/openpgpjs/issues/416#issuecomment-198905138

**Comment by rmhrisk** [comment]
Can you use WebCrypto? It only supports RSA-OAEP, not sure of OpenPGPs requirements

**Comment by tanx** [comment]
Not sure. We currently cheat on keygen for webkit and export only the bignum params:

https://github.com/openpgpjs/openpgpjs/blob/master/src/crypto/public_key/rsa.js#L154

Maybe we can do something similar for encrypt/decrypt, since we already habe a js impl for PKCS1-1_5:

https://github.com/openpgpjs/openpgpjs/blob/master/src/crypto/pkcs1.js

**Comment by mahrud** [comment]
We tried using asmCrypto's RSA implementation, but since it used its own BigNumber implementation, the bundle size grew too much. So instead I refactored their code to use bn.js and added it in `rsa.js`. I think it's fairly optimized in time and code size, so I'll close this.
