### ISSUE TITLE
Move HKP client to its own module

### ISSUE THREAD

**Issue by tanx** [openpgpjs/openpgpjs#424]
As part of an effort to make the core library leaner and meaner we should create a new git-repo/npm-module named `openpgp-hkp` that can be used optionally by users of OpenPGP.js.

This would also remove the `fetch` polyfill as a direct dependency of OpenPGP.js.

**Comment by twiss** [comment]
Moved to https://github.com/openpgpjs/hkp-client in 43f0724aeb1d2e86c3b586a3631672856e428459.
