### ISSUE TITLE
Cannot decrypt data using private key

### ISSUE THREAD

**Issue by Nevernown** [openpgpjs/openpgpjs#429]
Can someone tell me what went wrong, I tried this:

```
sessionOptions = {
                message: openpgp.message.read(key.enc_key),
                privateKey: openpgp.key.readArmored($scope.poc_data.poc_doctor_private_key).keys[0]
            };
            
            options = {
                message: openpgp.message.read(key.enc_key),
                sessionKey: openpgp.decryptSessionKey(sessionOptions)
            };
                
            openpgp.decrypt(options).then(function(plaintext) {
                $scope.poc_data.poc_doctor_private_key_resolved_document_key = plaintext.data;
                console.log("Decrypted document key for doctor: " + $scope.poc_data.poc_doctor_private_key_resolved_document_key);
            }).catch(function(err){
                console.log("Error during decryption process...");
                console.log(err);
            });

```
and I tried this: 
```

options = {
                message: openpgp.message.read(key.enc_key),
                privateKey: openpgp.key.readArmored($scope.poc_data.poc_doctor_private_key).keys[0]
            };
                
            openpgp.decrypt(options).then(function(plaintext) {
                $scope.poc_data.poc_doctor_private_key_resolved_document_key = plaintext.data;
                console.log("Decrypted document key for doctor: " + $scope.poc_data.poc_doctor_private_key_resolved_document_key);
            }).catch(function(err){
                console.log("Error during decryption process...");
                console.log(err);
            });
```

In both cases it tells me:
"error decrypting massage: Invalid session key for decryption."

**Comment by tanx** [comment]
Please see the tests for working examples:

https://github.com/openpgpjs/openpgpjs/blob/master/test/general/openpgp.js

**Comment by ianbelcher** [comment]
Hi @tanx 

I'm getting this same error and I've been over the tests a number of times. I am calling `openpgp.decrypt` and have valid private key and message objects from what I can tell?

This error is appears to be awfully abstract and I've got no clue what might be the issue?

Any pointers as to what might be causing this issue would be great. I've got everything else working fine, its just the decryption which is throwing everything out.

Thanks and appreciate the work you've done on this project!

Cheers!

**Comment by ianbelcher** [comment]
Just for anyone in future, this error was being caused by my private key having its line breaks changed from `\r\n`to `\n` at one point. Fixing the issue with and ensuring that I kept `\r\n` as the line break combination solved my issue.

Hope this helps.

**Comment by Krassmus** [comment]
Thanx, ianbelcher! Helped me a lot. 

My workaround is to remove the `\r` characters all the time with .replace(/\r/, ""). I guess it only needs to be consistent if you use `\r\n`or simply `\n`. But to my experience the server sometimes removes the `\r`character from the string automatically. So the same code works on one machine and on another it fails. Would be great if openpgp.js could ignore this problem in the future.

**Comment by bartbutler** [comment]
With text we convert to network normal line-breaks before encrypting, as it is part of the standard. I don't see I reason not to do this before attempting to read armor as well. @tanx?

**Comment by eric7704** [comment]
> Just for anyone in future, this error was being caused by my private key having its line breaks changed from `\r\n`to `\n` at one point. Fixing the issue with and ensuring that I kept `\r\n` as the line break combination solved my issue.
> 
> Hope this helps.

Hi, I still get "Error decrypting message: Session key decryption failed" error, please help, I been stuck on this for the longest time...

**Comment by tomholub** [comment]
You may be attempting to use the wrong private key, or the message may have been encrypted for a different private key.
