### ISSUE TITLE
Version 1.4.1: TypeError: Cannot read property 'generateKeyPair' of null

### ISSUE THREAD

**Issue by iDuuck** [openpgpjs/openpgpjs#432]
What is this error causing? I am using bower to install the build/

**Comment by henryboldi** [comment]
same issue here

**Comment by henryboldi** [comment]
same issue as #320

**Comment by iDuuck** [comment]
I fixed this. Don't know how, yet. Could you reproduce this on jsfiddle or something?

**Comment by tanx** [comment]
@henryboldi yes. Thanks for pointing it out.
