### ISSUE TITLE
Cloudflare is annoying the use of the website over tor

### ISSUE THREAD

**Issue by dns2utf8** [openpgpjs/openpgpjs#436]
Hi all

I am a regular tor user and Cloudflare is making me angry every day, because they force me to solve capchas all the time.
I would realy like it if I were able to browse your website without having to solve a capcha every time I visit.

Regards

**Comment by tanx** [comment]
We currently use cloudflare to provide TLS/HSTS protection of our website from github pages. Sorry for the inconvenience.

**Comment by TheLastProject** [comment]
You can whitelist Tor in Cloudflare: https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

On 8 April 2016 08:19:23 CEST, Tankred Hase <notifications@github.com> wrote:
>We currently use cloudflare to provide TLS/HSTS protection of our
>website from github pages. Sorry for the inconvenience.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openpgpjs/openpgpjs/issues/436#issuecomment-207235222

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tanx** [comment]
> You can whitelist Tor in Cloudflare: https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

@TheLastProject thanks! I added the whitelist rule for Tor to our cloudflare configuration. @dns2utf8 could you please try again?

**Comment by dns2utf8** [comment]
Thank you, it works like a charm :+1:
