### ISSUE TITLE
Error building as dep with es6 (babelify) + browserify

### ISSUE THREAD

**Issue by exos** [openpgpjs/openpgpjs#438]
Hi, I have the next problem:

```
➜ ⁅ lolxlib ⭠testopenpgp ⬆ ⁆ lolx/lolxlib ▶ gulp build-min
[02:31:24] Using gulpfile ~/alpha/lolx/lolxlib/gulpfile.js
[02:31:24] Starting 'build-min'...

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: module "./config" not found from "/home/exos/alpha/lolx/lolxlib/node_modules/openpgp/dist/openpgp.js"
    at notFound (/home/exos/alpha/lolx/lolxlib/node_modules/browserify/index.js:803:15)
    at /home/exos/alpha/lolx/lolxlib/node_modules/browserify/index.js:754:23
    at /home/exos/alpha/lolx/lolxlib/node_modules/browser-resolve/index.js:185:24
    at /home/exos/alpha/lolx/lolxlib/node_modules/browser-resolve/node_modules/resolve/lib/async.js:36:22
    at load (/home/exos/alpha/lolx/lolxlib/node_modules/browser-resolve/node_modules/resolve/lib/async.js:54:43)
    at /home/exos/alpha/lolx/lolxlib/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:22
    at /home/exos/alpha/lolx/lolxlib/node_modules/browser-resolve/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

My gulp task:

```
gulp.task('build-min', function () {

    var options = {
        //insertGlobals : true,
        debug : argv.debug,
        extensions: [
            'es6'
        ],
        transform: [
            'babelify'
        ]
    };

    return gulp.src([
            'src/index.js'
        ])
        .pipe(sourcemaps.init())
        .pipe(browserify(options))
        .pipe(rename('lolx.js'))
        .pipe(gulp.dest('dist/'))
        .pipe(uglify())
        .pipe(rename('lolx.min.js'))
        .pipe(gulp.dest('dist/'));
});
```

My .babelrc:

```
{
  "presets": ["es2015"]
}
```

versions: 

node:  5.9.1
npm: 3.7.3
openpgp: 2.2.1 
gulp-browserify:0.5.1
     └── browserify: 3.46.1 
babel-preset-es2015: 6.6.0
babelify: 7.2.0
gulp-babel: 6.1.2

**Comment by tanx** [comment]
It builds fine on my machine and in travis. If you are trying to link the sources directly in your project build, we currently do not support that. It's best to just use the provided npm/bower distribution, which can be loaded as an ES6 module.

**Comment by exos** [comment]
> It builds fine on my machine and in travis. 

Yea, not with me. And this don't resolve my problem (why close the thread?)

> If you are trying to link the sources directly in your project build, we currently do not support that. It's best to just use the provided npm/bower distribution, which can be loaded as an ES6 module.

I'm using NPM, In fact, I did wrote the versions.

When I build the node.js version it's works. The problem is with browserify.

If you think my gulp task is wrong, please show me an working example with browserify + babelify, or reopen this thread.

Thanks

**Comment by tanx** [comment]
Sorry, I misread. I also include openpgp.js via es6module/npm/browserify/babelify in hoodiecrow. But with grunt:

https://github.com/tanx/hoodiecrow
