### ISSUE TITLE
jsdoc is wrong message.message.packets.write();

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#441]
https://openpgpjs.org/openpgpjs/doc/index.html

Under 
Encrypt and decrypt Uint8Array data with PGP keys
encrypted = message.packets.write(); // get raw encrypted packets as Uint8Array
this should be:
encrypted = message.message.packets.write(); // get raw encrypted packets as Uint8Array

So its message.message, just as in README.md

**Comment by tanx** [comment]
@barrydegraaff good catch. The docs were outdated. I pushed an update.
