### ISSUE TITLE
Add Key.encrypt(passphrase) to exported API

### ISSUE THREAD

**Issue by NSkelsey** [openpgpjs/openpgpjs#443]
In the API documentation we find [`key.prototype.decrypt`](https://openpgpjs.org/openpgpjs/doc/key.js.html#line373). However, there is no accompanying `key.prototype.encrypt` for [`Key`](https://openpgpjs.org/openpgpjs/doc/module-key-Key.html) objects.

Either this was a specific design choice or it is genuinely missing – please advise.

The current code I use to preform key.encrypt(passphrase) looks like:
```javascript
// lockKeyRing encrypts the private key material of the key using the passed 
// password. The primary key and all subkeys are encrypted with the password.
// { string -> bool }
function lockKeyRing(password) {
  var w = true;
  w = w && keyRing.privateKey.primaryKey.encrypt(password);
  keyRing.privateKey.subKeys.forEach(function(sk) {
      w = w && sk.subKey.encrypt(password);
   });
  return w;
}
```
Note that the keyRing here is a custom data structure.

P.S. Thanks for the library it is fantastic!

**Comment by evilaliv3** [comment]
Thanks @NSkelsey for the suggestion; I've written a pull request that follows the same pattern of the decrypt API and that is already used by various projects like whiteout-io: https://github.com/whiteout-io/mail/blob/master/src/js/crypto/pgp.js#L204

@tanx / @toberndo what do you think?

**Comment by tanx** [comment]
See https://github.com/openpgpjs/openpgpjs/pull/446
