### ISSUE TITLE
npm install not latest version?

### ISSUE THREAD

**Issue by tgregoneil** [openpgpjs/openpgpjs#444]
Following the example presented and after installing with <code>npm install --save openpgp</code>
I then tried the snippets labeled 'setup' and 'Encrypt and decrypt Uint8Array data with a password' and then got the error:  'openpgp.encrypt is not a function'

Details at stackoverflow: http://stackoverflow.com/questions/36805701/error-from-openpgpjs-example-openpgp-encrypt-is-not-a-function

**Comment by tgregoneil** [comment]
After installing version 2.2.1 with <code>npm install --save openpgp@2.2.1</code> 
The example now finds the function openpgp.encrypt, but then shows this error with your password example:
    
    TypeError: Cannot read property 'length' of undefined
    at Packetlist.read (/home/tgrego/.node_modules_global/lib/node_modules/openpgp/dist/openpgp.js:16823:19)
    at Object.read (/home/tgrego/.node_modules_global/lib/node_modules/openpgp/dist/openpgp.js:14939:14)
    at Object.<anonymous> (/home/tgrego/1/Src/Example/Javascript/Node.js/OpenPgp/openpgpPasswordExamp.js:27:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Password example:

    var openpgp = require('openpgp'); // use as CommonJS, AMD, ES6 module or via window.openpgp
    
    openpgp.initWorker({ path:'openpgp.worker.js' }) // set the relative web worker path
    
    openpgp.config.aead_protect = true // activate fast AES-GCM mode (not yet OpenPGP standard)
    
    
    var options, encrypted;
    
    options = {
        data: new Uint8Array([0x01, 0x01, 0x01]), // input as Uint8Array (or String)
        passwords: ['secret stuff'],              // multiple passwords possible
        armor: false                              // don't ASCII armor (for Uint8Array output)
    };
    
    openpgp.encrypt(options).then(function(ciphertext) {
        encrypted = ciphertext.message.packets.write(); // get raw encrypted packets as Uint8Array
    });
    
    options = {
        message: openpgp.message.read(encrypted), // parse encrypted bytes
        password: 'secret stuff',                 // decrypt with password
        format: 'binary'                          // output as Uint8Array
    };
    
    openpgp.decrypt(options).then(function(plaintext) {
        return plaintext.data // Uint8Array([0x01, 0x01, 0x01])
    });

**Comment by tgregoneil** [comment]
Installing with <code>npm install --save openpgp@2.2.1</code> resolved this issue.

**Comment by tanx** [comment]
We backported binary string support to the `v1.x` branch and released `v1.6.0` A few days ago. I did not know npm always delivers the latest not the highest version. I released `v2.2.2` from the master which should fix the issue.

**Comment by tgregoneil** [comment]
I saw that.  Works great now.   Tanx alot!  :-)

**Comment by tgregoneil** [comment]
By the way, I'm now having a problem when browserfying with openpgp.  Test file contains just this one line:
<code>var openpgp = require ('openpgp')</code>

Browserfying on that file reports an error:  Cannot find './config'.

I see that the openpgp package.json file contains the entry:  "directories":{"lib":"src"}.  Shouldn't that be enough for browserify to find the required files in the src hierarchy?  Thanks!
