### ISSUE TITLE
Documentation on passphrase

### ISSUE THREAD

**Issue by tumenor** [openpgpjs/openpgpjs#445]
Might be that I didn't find it, but I couldn't find any specific documentation on how data is encrypted using only passphrase and no key.

**Comment by neoatlantis** [comment]
Passphrase protected encryption is specified in standard, see [RFC 4880](https://tools.ietf.org/html/rfc4880), section 3.7 and 5.3.

Basically a key is derived from the passphrase in a procedure called S2K(String-to-Key), this key is used to encrypt/decrypt the session key, the latter being used for symmetrically encrypting the actual data.

**Comment by tanx** [comment]
See https://github.com/openpgpjs/openpgpjs/blob/master/README.md#encrypt-and-decrypt-uint8array-data-with-a-password
