### ISSUE TITLE
HKP lookup error handler

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#447]
Right now there seem to be no way to catch errors as a result of looking up keys from keyserver.

Could that be added in a similar way as for decrypt:

      hkp.lookup(options).then(function(key) {
      }, function(err) {
         //This is not in de code
      });

Also enclosing with try-catch does not work.

**Comment by tanx** [comment]
hkp.lookup returns a promise. You need to append .catch(function(err) { ... }); to the return value to handle errors.
