### ISSUE TITLE
HKP lookup does not support Internet Explorer 11 on Windows 7 32 bit or Edge on Windows 10

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#448]
When doing the stuff from the readme, the following error is thrown:
SCRIPT 5007 : Object expected
openpgp.js, Line: 12820, Column 3

var hkp = new openpgp.HKP('https://pgp.mit.edu');
var options = {
    query: 'alice@example.com'
};

hkp.lookup(options).then(function(key) {
    var pubkey = openpgp.key.readArmored(key);
});

**Comment by barrydegraaff** [comment]
Updated title: also fails with the same error on Windows 10 with Edge

**Comment by barrydegraaff** [comment]
Version: OpenPGP.js v2.2.1

**Comment by barrydegraaff** [comment]
The problem is probably caused by the interesting code after `return`

  return fetch(uri).then(function (response) {
    if (response.status === 200) {
      return response.text();
    }
  }).then(function (publicKeyArmored) {
    if (!publicKeyArmored || publicKeyArmored.indexOf('-----END PGP PUBLIC KEY BLOCK-----') < 0) {
      return;
    }
    return publicKeyArmored.trim();
  });

**Comment by barrydegraaff** [comment]
While I like nice code as much as the next guy, I will use this, as that works in all Browsers:

               var xmlHttp = null;   
               xmlHttp = new XMLHttpRequest();
               xmlHttp.open( "GET", 'https://sks-keyservers.net/pks/lookup?op=get&options=mr&search='+encodeURIComponent(document.getElementById('barrydegraaff_zimbra_openpgpQuery').value), true );
            
               xmlHttp.onreadystatechange = function (oEvent) 
               {  
                  if (xmlHttp.readyState === 4) 
                  {  
                     if (xmlHttp.status === 200) 
                     {  
                        var pubkey = openpgp.key.readArmored(xmlHttp.responseText);       
                     } 
                     else 
                     {  
                        console.log('Error:' + xmlHttp.status + ' '+ xmlHttp.statusText);  
                     }  
                  }  
               }; 
            
               xmlHttp.send( null );

**Comment by tanx** [comment]
Did you use the fetch polyfill as described in the readme?

**Comment by barrydegraaff** [comment]
Nope, thanks for pointing that out. Using that polyfill is a lot of overhead for my application for something that can be dealt with so easily.
