### ISSUE TITLE
Export preferredAlgoriths as option for the generate() key function

### ISSUE THREAD

**Issue by evilaliv3** [openpgpjs/openpgpjs#450]
Right now OpenPGP.js does internally select the encryption algorithms for the user.

Although it simplify and make more secure the general use case it does prevent the user to obtain the following:
- improve security if a special use case require strict strong cyphers only;
- improve compatibility/performances whenever the openpgp.js library is used on specific terminals/browsers

\cc @toberndo @tanx: i'm opening this ticket for keeping track of this missing possibility; if you are not against this i will take care eventually to implement this patch in some spare time.

**Comment by chesnokovilya** [comment]
Closing this: you could already specify cypher in config.
