### ISSUE TITLE
Add support for detached signatures

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#452]
Hello Devs,

I would like to ask you to consider adding support for PGP detached signatures. Right now OpenPGP.js only supports sign/verify clear signed messages. 

The benefits of detached signatures are:
1. Allows implementations to support for pgp/mime (that uses detached signatures instead of clear signing)
2. Separates the data content and the signature (end users love this)
3. Allows signing binary data (clear-signing works only for plain text and alters the data before signing, remove white spaces)

The usefulness of detached signatures may be debatable, but if any, I guess in the end if it is about email, one also wants to support pgp/mime.

I cannot see the full implication, but building  detached signature support w/o support for binaries may not be very hard (if you are already a seasoned openpgpjs dev)

See also:
https://github.com/Zimbra-Community/pgp-zimlet/issues/173

detached signatures are one of 3 possible ways of making signatures (only 2 are used for email), see:
https://www.gnupg.org/gph/en/manual/x135.html

OpenPGP.js only supports clear-signed signatures:
openpgpjs/openpgpjs#243
https://openpgpjs.org/openpgpjs/doc/module-openpgp.html

The main difference between clear-signed and detached signatures are:
http://www.gossamer-threads.com/lists/gnupg/users/67646
(scroll down)

Thanks for reading! And thanks for the good work.

Barry

**Comment by tanx** [comment]
For PGP/MIME check out:

https://github.com/whiteout-io/pgpmailer

https://github.com/tanx/pgpbuilder

https://github.com/tanx/mailreader

They use the http://emailjs.org libs. Check out https://hoodiecrow.com to see everything wired up and working together.

**Comment by davidlucid** [comment]
I would also love to see OpenPGP.js support regular signatures of binary data! I really like this library and I am very grateful to the developers, but it is not really working for what I need to accomplish.

I am the developer of a standalone webpage built for timestamping documents using the Bitcoin blockchain and also signing files before timestamping. Currently, the way I have implemented this using OpenPGP.js is by allowing the user to encode the file as a cleartext ASCII message (meant for text files) or Base64 (for binary files) before cleartext signing.

This is obviously a hacky way of accomplishing this. It it completely unnecessary to have the signed message before the signature itself (this slows things down too), and it is also makes it confusing and less streamlined for the user. In addition, when we generate a hash of the signature to add to the blockchain, Also, I'm afraid that are other downsides of which I am unaware to doing all of this using cleartext signing.

So for now, I will be switching to Keybase's implementation (https://keybase.io/kbpgp) since this seems to work well for what I am going for here.

Also, thanks to Barry for those helpful links! They helped clear up some things for me.

**Comment by tanx** [comment]
> I would also love to see OpenPGP.js support regular signatures of binary data! I really like this library and I am very grateful to the developers, but it is not really working for what I need to accomplish.

Then feel free to contribute with a pull request to add the feature.

> So for now, I will be switching to Keybase's implementation (https://keybase.io/kbpgp) since this seems to work well for what I am going for here.

Thanks for letting us know that we're loosing a "paying customer". I read that comment on so many open source repos. It's neither helpful nor constructive. This library is mainly maintained by volunteers who work on it mainly in their free time. I recommend this blog post:

http://www.michaelbromley.co.uk/blog/529/why-i-havent-fixed-your-issue-yet

**Comment by davidlucid** [comment]
My goal in writing that comment was not to request that you spend your time writing all that code in order to satisfy my project's needs. I'm sorry if it did.

All I wanted to do was share my story and show my support for Barry's idea for other signature methods since my project seems to have a need for regular binary signing. 

By mentioning that I will use Keybase's library as an immediate solution, I was not in any way attempting to "let you know that you're losing a 'paying customer'." I simply wanted to share my solution with others who may have the same issue.

I did not mean to sound insulting or demanding. I really appreciate the work that the developers have done on this project.

**Comment by wmhilton** [comment]
@davidlucid What did you end up using to compute detached signatures? I'm trying to generate signed git commits in the browser environment, and have discovered to my chagrin that git does not use cleartext signatures, but [detached binary signatures](https://github.com/git/git/blob/661a1806819ca98c446f82b19e6c98fa174d33a4/gpg-interface.c#L168). I've got verifying signed git commits working, I just can't generate them.

**Comment by barrydegraaff** [comment]
Well, just recently someone figured out how to verify detached signatures using openpgp.js, the project is over here (https://github.com/iwayvietnam/openpgp-secure-zimlet).

The dev over there seems to use the decrypt methods to deal with detached signs, but I have not had time yet to reverse engineer it. If someone could provide a simple example and add it to the openpgp.js documentation it would be great.

**Comment by davidlucid** [comment]
@wmhilton I ended up switching to Keybase's implementation (https://keybase.io/kbpgp). Feel free to check out my implementation over here: https://github.com/HardBTC/WorldCitizenIDKit

**Comment by wmhilton** [comment]
@barrydegraaff Hmm... well as I said OpenPGP.js already has a function for *verifying* detached sigs: [openpgp.message.readSignedContent](https://github.com/openpgpjs/openpgpjs/blob/master/test/general/signature.js#L598). I've just been having bad luck trying to reverse the process, LOL.

It seems that all zimlet is doing is popping off the signature from a [`clearsigned` message](https://github.com/iwayvietnam/openpgp-secure-zimlet/blob/4b2c2224e39debed7f745c81c5f6b422721e315a/openpgp_zimbra_secure/js/OpenPGPEncrypt.js#L89) and calling it a detached signature which I've already tried. But I am making some progress, and am convinced I'm only a single newline and/or carriage return and/or a few header bytes away.

@davidlucid I'll take a look at it right now

**Comment by nguyennv** [comment]
@barrydegraaff
This example I've used to attract signature from clearsigned message:
```js
var signatureHeader = '-----BEGIN PGP SIGNATURE-----';
var signature = signatureHeader + signedText.split(signatureHeader).pop();
```
And this example I've used to verify detached signature:
```js
var message = openpgp.message.readSignedContent(content, signature);
var result = message.verify(publicKeys);
```

**Comment by wmhilton** [comment]
Doesn't that only work though if the cleartext being signed is already in `\r\n` `- --dash-escaped` form? What if I want to create a detached signature for a *binary* file?

**Comment by nguyennv** [comment]
@wmhilton 
This is example I've used to create detached signature for a binary:

```js
var bytes = openpgp.util.str2Uint8Array('openpgpjs');
var message = openpgp.message.fromBinary(bytes);
var signedMessage = message.sign(privateKeys);

var signature = signedMessage.packets.filterByTag(openpgp.enums.packet.signature);
var armoredMessage = openpgp.armor.encode(openpgp.enums.armor.message, signature.write());
```

**Comment by wmhilton** [comment]
OOOH! I'll have to try that. I think I was manually grabbing the signature packet instead of the filterByTag function and I think my real mistake is I was trying to use enums.armor.signed instead of enums.armor.message.

**Comment by wmhilton** [comment]
@nguyennv IT WORKS!! Woohoo! Thank you so much.

@tanx Would you be interested in a pull request with an example and/or unit test with the steps for creating detached signatures?

**Comment by bartbutler** [comment]
I think we would be. Also, a PR to make the interface for doing this nicer rather than using primarily internal functions would be nice.

**Comment by wmhilton** [comment]
@bartbutler Baby steps! I'm just going to document how to do it for now. Maybe I'll be able to add a simpler interface to the public API later, but I think an example is probably good enough for now.

**Comment by algv** [comment]
I want sign file. But out always incorrcet. Why?
Code: 
```JS
var fs = require("fs");
var openpgp = require("openpgp");
var content = fs.readFileSync("test.txt", "binary");

var priv_key_arm2 =
    [ '-----BEGIN PGP PRIVATE KEY BLOCK-----',
/////////////
'-----END PGP PRIVATE KEY BLOCK-----'
    ].join('\n');

var privateKeys = openpgp.key.readArmored(priv_key_arm2).keys[0];
var message = openpgp.message.fromBinary(Buffer.from(content));
var signedMessage = message.sign(privateKeys);
var signature = signedMessage.packets.filterByTag(openpgp.enums.packet.signature);
var armoredMessage = openpgp.armor.encode(openpgp.enums.armor.message, signature.write());
armoredMessage = armoredMessage.replace('-----BEGIN PGP MESSAGE-----\r\n', '-----BEGIN PGP SIGNATURE-----\r\n');
armoredMessage = armoredMessage.replace('-----END PGP MESSAGE-----\r\n', '-----END PGP SIGNATURE-----\r\n');
var detachedSig = armoredMessage; // '-----BEGIN PGP SIGNATURE ... END PGP SIGNATURE-----'

fs.writeFileSync("text.txt.sig", detachedSig);
```

text.txt.sig:
> -----BEGIN PGP SIGNATURE-----
> Version: OpenPGP.js v2.3.7
> Comment: http://openpgpjs.org
> 
> 
> =twTO
> -----END PGP SIGNATURE-----

**Comment by wmhilton** [comment]
Don't forget to update the documentation! [The README](https://github.com/openpgpjs/openpgpjs#create-and-verify-detached-signatures-for-binary-data) still show my ugly workaround, the one with `armoredMessage.replace('-----BEGIN PGP MESSAGE-----\r\n', '-----BEGIN PGP SIGNATURE-----\r\n');`
