### ISSUE TITLE
openpgp.js does not work in strict mode environment

### ISSUE THREAD

**Issue by speigg** [openpgpjs/openpgpjs#454]
I'm trying to use `openpgpjs` in nativescript, which uses commonjs modules (but is not a nodejs environment). The nativescript runtime executes all javascript in strict mode.

Unfortunately, openpgp.js does not work when evaluated in a strict mode environment. Specifically, the module `asmcrypto-lite` causes the following error `TypeError: undefined is not an object (evaluating 'global.Float64Array')`. This happens because the `global` variable used in `asmcrypto-lite` is determined with: `function() {return this}`, which returns undefined in strict mode. Ideally, that function should be replaced with an expression that works in strict mode. I believe this is the only thing which is broken when executing in strict mode.

**Comment by tanx** [comment]
Good catch! If you could provide a PR to our asmcrypto fork, I will ask to merge it upstream as well. Thx.

https://github.com/openpgpjs/asmcrypto-lite

**Comment by twiss** [comment]
This should be fixed in v5, I believe. The OpenPGP.js builds now use strict mode themselves.
