### ISSUE TITLE
Change PassPhrase

### ISSUE THREAD

**Issue by rushglen** [openpgpjs/openpgpjs#460]
Using version 2.3
How can I change the passphrase for an existing private key?

**Comment by rushglen** [comment]
OK! should have looked a bit harder! found the answer here:
https://github.com/whiteout-io/mail/blob/master/src/js/crypto/pgp.js#L231

**Comment by neoatlantis** [comment]
For now, just decrypt the private key, and call the `encrypt` method using new passphrase.
https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L372
