### ISSUE TITLE
Some links in the documentation are broken

### ISSUE THREAD

**Issue by NSkelsey** [openpgpjs/openpgpjs#464]
This is a problem I have noticed in a few places.

The link to `crypto.hash.sha` IE: https://openpgpjs.org/openpgpjs/doc/module-crypto_hash_sha.html

Does not appear on the right hand side when you are on another page in the docs. The link simply disappears.

Similarly the link to `module-key.key` as linked in the index on the right https://openpgpjs.org/openpgpjs/doc/module-key.Key.html does not display all of the documented functions.

If the link is changed to https://openpgpjs.org/openpgpjs/doc/module-key-Key.html (notice the '-' instead of the '.') it works as expected.

Anyway, thanks for having great docs in the first place!

**Comment by tanx** [comment]
Thanks for the heads up. Probably the jsdoc annotations in the respective files are broken.

Patch is welcome 😄👍🏼
