### ISSUE TITLE
revoking a public key

### ISSUE THREAD

**Issue by rushglen** [openpgpjs/openpgpjs#465]
Is this possible? I see in openpgp.js

> // TODO
> Key.prototype.revoke = function () {};

so I guess not, 
would be great though if we could create a revocation certificate so a public key could be revoked.

**Comment by MaximilianKrambach** [comment]
I'm working on it this week.

**Comment by MaximilianKrambach** [comment]
So, now we have had three PR in short order. As mine was clearly the least ready one (I have had some local changes ready, but they were similar to #730, so I didn't push them, and closed my PR), there are two remaining that need to be merged/sorted somehow.

On a quick glimpse I see more value in PR #734, as there is also the possibility of Revocation certificates (i.e. not inmediateley revoking the key itself, but preparing some future revoke).

As for code quality, I already proved myself to be in a very early learning stage, so I won't be able to give a quality review.

My goal is mainly to have something by end of next week.

**Comment by sanjanarajan** [comment]
@MaximilianKrambach thank you so much for your contribution. In this case, it looks like each PR built off of the one before it and added more and more helpful features. I agree that #734 is the most advanced, and supports everything in #730 and more, so I will try to review/merge #734 sometime today. 

Thanks to @MaximilianKrambach, @snowyu, and @twiss for working on this feature!
