### ISSUE TITLE
Combine 2 or more privatekeys into a single key object

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#466]
Sorry for tossing another how-to issue in the issue tracker.

Is there a method to combine 2 or more pgp privet keys into a single private key object.

In the documentation is see a lot:
privateKey: openpgp.key.readArmored(privkey).keys[0],

This hardcodes to the first private key

In GnuPG:
gpg2 --armor --export-secret-keys 933E1A2C EB2105A8

This will result in a single armored pgp private key block that has 2 private keys:
privateKey: openpgp.key.readArmored(privkey).keys[0],
privateKey: openpgp.key.readArmored(privkey).keys[1],

Question, how can I make a single armored block from 2 separately armored privatekeys using openpgp.js?

**Comment by neoatlantis** [comment]
I rolled [my own code][CODE] for that purpose:
[CODE]: https://bitbucket.org/neoatlantis/brgp/src/62cce8663b186275823f28ac7ac869459ad54e18/src/openpgp.util.js?at=master&fileviewer=file-view-default

```
function armorMultipleKeysOfSameType(keys, isPrivate){
    var array = [], packetList, exportingKey;
    isPrivate = Boolean(isPrivate);
    packetList = new openpgp.packet.List();
    for(var i in keys){
        exportingKey = keys[i];
        if(!isPrivate) exportingKey = exportingKey.toPublic();
        if(isPrivate ^ exportingKey.isPrivate()) continue;

        exportingKey.toPacketlist().forEach(function(packet){
            packetList.push(packet);
        });
    }
    var type = (isPrivate ? 
        openpgp.enums.armor.private_key : 
        openpgp.enums.armor.public_key
    );
    return openpgp.armor.encode(type, packetList.write()); 
}
```

**Comment by barrydegraaff** [comment]
@neoatlantis thanks, and wow. Did you consider sending this as a PR to @tanx
