### ISSUE TITLE
Not able decrypt the encrypted content

### ISSUE THREAD

**Issue by jyothisjose** [openpgpjs/openpgpjs#469]
Hi

I could able to encrypt the data using pgp public key, but could't decrypt it uisng private key
My sample code is

var openpgp = require('openpgp'); 

var options = {
    userIds: [{ name:'Jon Smith', email:'jon@example.com' }], // multiple user IDs
    numBits: 2048,                                            // RSA key size
    passphrase: 'hello'         // protects the private key
};

openpgp.generateKey(options).then(function(key) {
    var privkey = key.privateKeyArmored; // '-----BEGIN PGP PRIVATE KEY BLOCK ... '
    var pubkey = key.publicKeyArmored;   // '-----BEGIN PGP PUBLIC KEY BLOCK ... '
	
	plaintext = "hi";
	  var pubKeyDE = openpgp.key.readArmored(privkey).keys;
	  var privKeyDE = openpgp.key.readArmored(privkey).keys[0];
	 // privKeyDE.decrypt(passphrase);
	  openpgp.encrypt({
		publicKeys: pubKeyDE,
		data: plaintext
	  }).then(function(encrypted) {

		console.info("encrypted", encrypted);
		console.info( openpgp.decrypt({
		  privateKey: privKeyDE,
		  message: openpgp.message.readArmored(encrypted.data)
		}));
	  }).then(function(plaintext) {
		//expect(encrypted.data).to.exist;
		//expect(encrypted.data).to.equal(plaintext);
		//done();
	  });
});

privKeyDE.decrypt(passphrase); is showing error.

Could you please help me to decrypt the encrypted content?

**Comment by anjaly** [comment]
Can somebody please help to solve the above issue. 
Thanks in advance.

**Comment by tanx** [comment]
It's best to check out the unit tests for working examples.

**Comment by jyothisjose** [comment]
We tried the test in https://github.com/openpgpjs/openpgpjs/blob/master/test/general/openpgp.js. It returns the encrypted value, but while decrypting we are getting
 { _id: 16,
  _state: undefined,
  _result: undefined,
  _subscribers: [] }

Could you please help  us?
Thanks in advance.

**Comment by tanx** [comment]
Sorry. Don't have the time to debug every user's issue. Currently busy doing customer work.

**Comment by bartbutler** [comment]
@jyothisjose @anjaly So, to echo @tanx, please read the docs.

That said, the private key decrypt thing might be a legit bug, as I couldn't get Key.decrypt to work for me either for some reason. I decrypted the private key using:

  privKeyDE.keys[0].decrypt(options.passphrase);
  privKeyDE = privKeyDE.keys[0];

Secondly, openpgp.decrypt returns a promise, and you are outputting the contents of the promise object rather than the actual result of the decryption.

Once I fixed those things your example worked for me.

**Comment by jyothisjose** [comment]
@bartbutler 
We have given privKeyDE.keys[0].decrypt(options.passphrase);in our example. But still we are facing the same problem (not able to decrypt the encrypted content). 

Could you provide the working copy of our example it will be great help for us. 
 Thank you.

**Comment by bartbutler** [comment]
@jyothisjose Did you read my second comment about the promise? I happen to have the example I tried around, so I'll post it, but it really seems like you didn't read the my comment.

`var openpgp = require('openpgp');

var options = {
userIds: [{ name:'Jon Smith', email:'jon@example.com' }], // multiple user IDs
numBits: 2048//, // RSA key size
//passphrase: 'hello' // protects the private key
};

openpgp.generateKey(options).then(function(key) {
var privkey = key.privateKeyArmored; // '-----BEGIN PGP PRIVATE KEY BLOCK ... '
var pubkey = key.publicKeyArmored; // '-----BEGIN PGP PUBLIC KEY BLOCK ... '

plaintext = "hi";
  var pubKeyDE = openpgp.key.readArmored(pubkey).keys[0];
  var privKeyDE = openpgp.key.readArmored(privkey);
  privKeyDE.keys[0].decrypt(options.passphrase);

  privKeyDE = privKeyDE.keys[0];

  return openpgp.encrypt({
    publicKeys: pubKeyDE,
    data: plaintext
  }).then(function(encrypted) {

    var msg = openpgp.message.readArmored(encrypted.data);

    return msg.decrypt(privKeyDE);
  })
})
.then(function (data) { console.log(data.getText()); })
.catch(function (err) { console.error(err); });`

**Comment by jyothisjose** [comment]
@bartbutler 
Thanks for your valuable information.
