### ISSUE TITLE
Keys importing, Encryption and Decryption fail silently.

### ISSUE THREAD

**Issue by hoangan** [openpgpjs/openpgpjs#486]
This problem makes it very hard to debug. It would be good to raise error or exception.

**Comment by bartbutler** [comment]
They don't fail silently, they return ES6 promises: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by hoangan** [comment]
Thanks for the response. Consider this piece of code: 

var pubkey = openpgp.key.readArmored(config.pubkey).keys;

if (!pubkey[0]) {
  throw new Error("Can't load public key");
}

If I remove the check the whole program would proceed to encrypt with an empty pubkey. I think it should raise an error if the key file is not in a proper format.

**Comment by bartbutler** [comment]
I agree, it should. I'll check it out.

**Comment by twiss** [comment]
In the latest version `openpgp.encrypt` rejects when not passed keys.
