### ISSUE TITLE
Loading and armoring the same key subsequently generates a key with invalid 

### ISSUE THREAD

**Issue by acasajus** [openpgpjs/openpgpjs#492]
If I generate a key, serialize it into an armor, load it again, serialize again and load again, the resulting key cannot sign nor encrypt because it has 2 MPIs instead of 6. (I don't really know what I'm talking about, it's just empirical evidence). I just made a test for it:

```javascript
function deleteme() {
	var options = {
		userIds: [{ name: 'asdasd' }], // multiple user IDs
		numBits: 1024,  // RSA key size
		unlocked: true
	};
	var close_key = function(key, pass) {
		var clear_armor = key.armor();
		var c_key = self.openpgp.key.readArmored( clear_armor ).keys[0];
		c_key.encrypt( pass );
		return c_key.armor();
	}
	var load_key= function ( armor_text, pass ) {
		var read = self.openpgp.key.readArmored( armor_text );
		if( ! read.keys[0].decrypt( pass ) ) {
			throw new Error( "Could not open key" );
		};
		return read.keys[0];
	}
	self.openpgp.generateKey(options).then( function(	keyRes ) {
		var key = keyRes.key;
		console.log( "Generated key has MPIs: ", key.getSigningKeyPacket().mpi.length );
		var closed_1 = close_key( key, "pass_1" );
		var key_1 = load_key( closed_1, "pass_1" );
		console.log( "Loaded key 1 has MPIs: ", key_1.getSigningKeyPacket().mpi.length );
		var closed_2 = close_key( key_1, "pass_2" );
		var key_2 = load_key( closed_2, "pass_2" );
		console.log( "Loaded key 2 has MPIs: ", key_2.getSigningKeyPacket().mpi.length );
	});
}
```

The output in the console is:

```
Generated key has MPIs:  6
Loaded key 1 has MPIs:  6
Loaded key 2 has MPIs:  2
```

**Comment by acasajus** [comment]
In the end if I try to sign with the third key I get:

```
Uncaught (in promise) TypeError: Cannot read property 'toBigInteger' of undefined(…)
```

in function sign at 
```javascript
var d = keyIntegers[2].toBigInteger();
```

**Comment by bartbutler** [comment]
Hmmm. They only thing I can think of is that somehow it's losing it's subkeys, as I see nothing wrong with your test from a visual inspection at least. I'll check it out.

**Comment by acasajus** [comment]
Checking the difference between `key` and `key_1` it seems that

`key_1` has defined:
* `primaryKey.encrypted`
* `users[0].selfCertifications[0].unhashedSubpackets`
* `subKeys[0].subKey.encrypted`
* `subKeys[0].bindingSignature.unhashedSubpackets`
while `key has not.

Doesn't make much sense to me. I expected the original `key` to have stuff defined while `key_1` did not, so the serialization and armoring would not include the missing MPIs. :P

**Comment by acasajus** [comment]
Thanks :beers: Works wonderfully
