### ISSUE TITLE
Overflow in four-octet numbers

### ISSUE THREAD

**Issue by toberndo** [openpgpjs/openpgpjs#497]
Time fields are represented by [unsigned four-octet number](https://tools.ietf.org/html/rfc4880#section-3.5).

There seems to be an overflow for values larger than 30 bit:

```
util.readNumber(util.writeNumber(Math.pow(2, 30), 4))
=> 1073741824
util.readNumber(util.writeNumber(Math.pow(2, 31), 4))
=> -2147483648
```

I came across this when implementing the key expiration time in https://github.com/openpgpjs/openpgpjs/pull/458. With the current implementation of write/readNumber the key expiration time is limited to 2080 (which is surely enough).

**Comment by toberndo** [comment]
BTW, sorry for not having the time to port https://github.com/openpgpjs/openpgpjs/pull/458 to OpenPGP.js v2. I hope to get Mailvelope on OpenPGP.js v2 soon.

**Comment by tomholub** [comment]
@bartbutler we should close this
