### ISSUE TITLE
Lookup up verified signature in keyring

### ISSUE THREAD

**Issue by dpjanes** [openpgpjs/openpgpjs#499]
I'm having a lot

I've used `verify()` and it's returning a number of signatures, e.g

```
[ { keyid: Keyid { bytes: 'º<+QQ:' }, valid: true } ]
```

However, when I try to get this from the keyring using `self.keyring.getKeysForId(signatures[0].keyid, true);` it returns `null`

I've traced this all the way down into `keyIdCheck()` which seems to have no case for actually finding this key even though I can see that it's right there! It does either string comparison or a comparison again the fingerprint, neither of which is going to match.

```
PublicKey {
  tag: 6,
  version: 4,
  created: 2016-11-22T18:32:35.000Z,
  mpi: [ MPI { data: [Object] }, MPI { data: [Object] } ],
  algorithm: 'rsa_encrypt_sign',
  expirationTimeV3: 0,
  fingerprint: '72f4e21ea12532e6070a41018aba803c2b51513a',
  keyid: Keyid { bytes: 'º<+QQ:' },
  packets: Packetlist { length: 0 } }
```

**Comment by twiss** [comment]
`getKeysForId` expects a string, e.g. `signatures[0].keyid.toHex()`.
