### ISSUE TITLE
File streaming encryption support for large file

### ISSUE THREAD

**Issue by sonhuytran** [openpgpjs/openpgpjs#501]
Hi, your library is very useful for me. What do you think about merging it with the code from https://github.com/hellais/openpgpjs/tree/feature/streamedEncryption_fixes (which supports streaming for the 0.11.* version) to your 2.* version, for ones who need file streaming support for large file ?
Thanks.

**Comment by evilaliv3** [comment]
@sonhuytran the up to date discussion on this topic is here: https://github.com/openpgpjs/openpgpjs/pull/321.

I've personally worked on the patch is based on the original of hellais but we have still not decided if to integrate it and how.

**Comment by sonhuytran** [comment]
@evilaliv3 Thanks for your response, I'll be following the #321 to keep getting news.

**Comment by roccomuso** [comment]
+1
