### ISSUE TITLE
Any stripped-down versions?

### ISSUE THREAD

**Issue by giftig** [openpgpjs/openpgpjs#502]
I can't see anything about this in your docs but I wanted to check if you have any stripped-down builds for filesize efficiency, or build your library in a way conducive to being cut down to size. We only have a single use-case, for checking the signature of a message client-side to verify its validity, but a 320KB minified js file is quite a lot to load for this feature.

**Comment by avimar** [comment]
... I'm interested in simply encrypting a string when given a public key.

**Comment by bartbutler** [comment]
So, what are your needs? If you need to support the OpenPGP spec, you sort of need all the crypto algorithms, which is one of the reasons the library is large. If you are doing some in-house crypto which does not need interoperability with the outside you can use something like libsodium (https://www.npmjs.com/package/libsodium) for public key crypto. It's about 110K.

**Comment by giftig** [comment]
I was somewhat hoping if I have a single operation I need to do there might be versions or builds of the library which are cut down to individual common uses, like just the underlying algorithms need to verify a signature like I need, or just encrypt a string like @avimar wanted, but if you're saying the core of the library has too many interdependencies to be able to break it down like that, I'll take your word for it.

Libsodium possibly would have suited our needs (we arbitrarily picked openPGP as it's a well-trusted standard) but it'll be too much backpedalling for us to swap now. I guess we'll have to swallow the 320KB pill.
