### ISSUE TITLE
fetch() fails using hkp.lookup in Firefox addon

### ISSUE THREAD

**Issue by m-strasser** [openpgpjs/openpgpjs#504]
I'm trying to use openpgp.js in a Firefox addon, but downloading a public key with hkp.lookup fails with the following error:

> TypeError: 'fetch' called on an object that does not implement interface Window.

I've found out that I can solve the problem by replacing 
`return fetch(uri).then(....)`
on line 57 in [hkp.js](https://github.com/openpgpjs/openpgpjs/blob/master/src/hkp.js) with
`return self.fetch(uri).then(...)`

But I have no idea why this happens. My only guess is that the script is not allowed to access window.fetch() from inside a Firefox extension?

Please help :)

**Comment by evilaliv3** [comment]
My guess is that like inside webworkers in the contexts of a Firefox plugin
you are able to reach the window object by using self. Or maybe you are
really inside a webworker?

**Comment by m-strasser** [comment]
Thanks for your answer!
I didn't start a web worker as far as I know... also I can use "console.log()" inside the openpgp.js script and my other scripts which shouldn't be possible in a web worker (as far as my very limited knowledge on web workers tells me).

The thing is that I'm just not sure how to find out *when* I have to use self.fetch instead of window.fetch. If I knew that I would just change line 35 of [hkp.js](https://github.com/openpgpjs/openpgpjs/blob/master/src/hkp.js):
`this._fetch = typeof window !== 'undefined' ? window.fetch : _dereq_('node-fetch');`

But I don't know what I should check for and if it's safe to change from window.fetch to self.fetch.
