### ISSUE TITLE
Copyleft with jsrsasign

### ISSUE THREAD

**Issue by mrichards-mdsol** [openpgpjs/openpgpjs#506]
Not sure if this is okay or not, but spotted jsrsasign publishes as MIT and wondered if you knew.

https://github.com/kjur/jsrsasign/blob/master/ext/THIRDPARTY_LICENSE.pgp.txt

Best

**Comment by bartbutler** [comment]
Sorry, I'm confused. I don't think we have a problem because MIT has virtually no restrictions. What issue are you pointing out?

**Comment by mrichards-mdsol** [comment]
LGPL has specific restrictions that don't match MIT.

**Comment by bartbutler** [comment]
True, but a LGPL library I think can use a MIT component with no issues, but not the other way around.

**Comment by bartbutler** [comment]
Oh, I see, jsrsasign is using a component of openpgpjs! Sorry, being dense here. Yeah, that is likely a problem.

**Comment by mrichards-mdsol** [comment]
Hopefully an amicable solution can be reached by the authors of the two libraries.

Sorry for any headaches this might raise.

**Comment by emersion** [comment]
jsrsasign has no longer openpgpjs components - I think this issue can be closed.
