### ISSUE TITLE
Error: Error decrypting message: Cannot read property 'toBigInteger' of undefined

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#507]
Can someone point me in the right direction?

```
Error: Error decrypting message: Cannot read property 'toBigInteger' of undefined
```

This happens to some (about 0.5-1%) users, with a private key generated by openpgp.js. Regardless of the message content, they will always get this error when trying to decrypt. 

It seems like the key was somehow wrongly created.

For now, when creating keys, I will probably have to do a cycle of

1. create a new key
2. encrypt message for it
3. try to decrypt it
4. catch  `Cannot read property 'toBigInteger' of undefined` -> go to step 1

Is there any way to debug this, without access to the private keys of these users?

**Comment by bartbutler** [comment]
As these keys are clearly messed up, is there is any way you can obtain one of the broken keys from one of your users? If not I suppose we can try to generate keys on loop until we get a bad one, but that is assuming the issue is not platform or JS-engine specific...

**Comment by tomholub** [comment]
I have run a test loop of my own overnight. Got 1382 keys and all passed my test (create, encrypt, decrypt, try next). 

Based on how often it happens in the field, I should have gotten five or six of them already, so I assume it's platform specific. Although, one user that did report their chrome version had the exact same version as me (probably on a different platform).

I will try to get something back.

**Comment by tomholub** [comment]
So far, I found it happens on all desktop platforms (Windows, Mac, Linux).

When it fails in a certain environment, it will fail again and again reliably. This is code in a chrome extension, and when it detects this issue after creating a key, it will direct the user to a diagnostic web page (non-extension) where it will create a bogus key, test it and report it to me.

The keys from the web page work every single time. They all come out 100% clear.

I will add the same diagnostic/reporting code inside the chrome extension, and see if it can create and report any broken keys to me.

tbc

**Comment by bartbutler** [comment]
That's very bizarre. If it only happens in the extension, it could have to do with the web worker--window vs. self or likewise. It is very strange though that it happens seemingly randomly on all different platforms.

**Comment by tomholub** [comment]
I didn't have anyone complain about this in a while. I will check with people who had these issues before to see if it's good now.

For a change though, I'm seeing some errors during signing:
```
Error signing cleartext message: Cannot read property 'toBigInteger' of undefined
```

Will investigate.

**Comment by tomholub** [comment]
I'll try to ask a few users to give me one such key/pass phrase, as long as they didn't use it for anything sensitive yet.

**Comment by bartbutler** [comment]
Sounds good, it would be good to get to the bottom of this.

**Comment by mahrud** [comment]
@tomholub do you know what type of key they were signing with? If it's RSA, one of these two lines is the culprit:
https://github.com/openpgpjs/openpgpjs/blob/e939d9b1ab6aa44b6eadb525554ab9bf961439e8/src/crypto/signature.js#L113-L114
Which would mean a problem in assigning `key.params`.

**Comment by tomholub** [comment]
These were definitely RSA keys

**Comment by tomholub** [comment]
Woohoo! Can't wait to test this.
