### ISSUE TITLE
Failed verify for cleartext when content has dashed lines

### ISSUE THREAD

**Issue by nnseva** [openpgpjs/openpgpjs#512]
I am trying to use cleartext sign/verify feature. Unfortunately, it looks like is not escaping dashes properly. The applied [test](https://github.com/openpgpjs/openpgpjs/files/703130/0002_openpgp_verify.js.txt) demonstrates some cases when such dash-escaping works, and when doesn't.

First of all, the existent algorithm leaves a dashed first line of the content unescaped. It looks like messing up the unescaping algorithm and conflicts with an [RFC](https://tools.ietf.org/html/rfc4880#section-7.1).

The following is a demonstration result of signing a text consist of one line with dashes.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

-----Hello PGP!-----
-----BEGIN PGP SIGNATURE-----
Version: OpenPGP.js v2.3.5
Comment: http://openpgpjs.org

wsBcBAEBCAAQBQJYeA6WCRCi4kkuZPCsVgAAVKcH/jB8JdzaueExLO2A/pNp
92QnZ98hVAU6500gLZw5lSS1o0HvzJ8In2IJ9kcxY9hiKR3XN+NkzHPOYuM/
ELqho+fAFN/cgOtOQMsyTn82PNstWsRpkDYa9uDUr9+Ry43aDcxXqtSRWesq
db0bJ2iPgCIFqVn12Zf84xSRRhmAuAPtYB1CgX2t3yshABuEyJZoHJH8kLbH
Qyq6PL27B8P5dOjtxv4xheZxpgvqPBcadw8Bt50dHMlT8oIsi3hUSciWzY7F
PWaNGHeGnN0otriLtPDX5lbYwQzoPWQ3mffI3BbWO3ADQFppr6e3IBVPSDgA
tTEF2Vib8X1YeQO9D6M3HgI=
=IDGz
-----END PGP SIGNATURE-----
```

Secondary, it leaves unescaped lines without dashes. It may leave the message consistent but is hard to recognize on the verify stage.

You can see in the [RFC](https://tools.ietf.org/html/rfc4880#section-7.1) that there are two options available for cleartext-escaping: you can escape EVERY line of the content, or the only starting dash and "From" field.

I suggest using a first conservative simple strategy of cleartext escaping when every line of the cleartext content is escaped. It may be unescaped using the simplest algorithm and can be tested by minimal cases.

**Comment by tomholub** [comment]
Oh, same issue here. I haven't inspected it enough and I thought I'm doing something wrong.

In my case, it was an encrypted message (quoted by someone's email client) inside the signed reply.

Many email/pgp clients will quote the previous encrypted message as is including the PGP armor, and put that inside of the signed content, which will I guess trip off openpgp.js.
