### ISSUE TITLE
The very basics for setting up openpgp for website

### ISSUE THREAD

**Issue by ericavijay** [openpgpjs/openpgpjs#515]
Do you have a very basics tutorial on how to setup openpgp.js from ground up using the ./dist folder setup (I suppose the src folder as well)?

Start with a new worker ? 
var x=new Worker("openpgp.js"); 

It will be helpful to have a simple unit setup without "require" and other dependencies.

Vijay

**Comment by bartbutler** [comment]
This might be one of those cases where it was overlooked because it seemed simple.

Step 1: Load up openpgp.js (or openpgp.min.js) from the dist directory
Step 2: Initialize the web worker with something like:

`    openpgp.initWorker({ path: 'openpgp.worker.min.js' });`

Step 3: use the global openpgp object to do what you want!

**Comment by ericavijay** [comment]
Thanks very much.  
My main problem was I was trying to include "openpgp.min.js" script in <head>  tag like I mode with most <script src tags.  This was failing because no DOM and No "worker" could be initiated.  The openpgp.js or openpgp.min.js was failing silently trying to start its "Worker"

Luckily nobody else has faced this issue.  It is worth just mentioning this in your document.

**Comment by bartbutler** [comment]
HI Vijay, I'm glad you solved your issue but I'm still not certain I follow what is was and what fixed it. Sorry.

**Comment by ericavijay** [comment]
Ha ! what I wrote got lost in Git  (probably because of < or > signs) 
I meant the "SCRIPT" tag was inside "HEAD" tag in my HTML.  This caused failure.  I need to put this script tag after the BODY has begun.  As you are initiating a Worker() when the openpgp.js is getting included.  There needs to a DOM for it to work from.


Hope that makes more sense.

**Comment by bartbutler** [comment]
Interesting, thanks for the heads up!

**Comment by stefan-korn** [comment]
I tried to include openpgp.js within a Drupal form, and also needed to put the script down before the closing body tag, since within the head tag it did not initialize properly (Drupal attaching js with scope footer).
