### ISSUE TITLE
Decrypting Non-Armored Files

### ISSUE THREAD

**Issue by threepears** [openpgpjs/openpgpjs#518]
I have set up Openpgp.js to decrypt client files using PGP keys as they come in to my Node application and place the decrypted versions in a folder for me to access, and all seems to be well....as long as the files are armored.  Here are some sample lines of the code showing the order of events:

```
const encryptedData = fs.readFileSync(encryptedFilePath, 'utf8')
openpgp.decrypt({
        message: openpgp.message.readArmored(encryptedData),
        publicKeys,
        privateKey
}).then( (decrypted) => { fs.writeFile(decryptedFilePath, decrypted.data } )
```

When an armored file comes through, all is well and I get the decrypted file in the specified folder.  However, we have clients that encrypt files with the armored option off, so they come in a hexidecimal-type format....

```
7403 436d e6c0 f941 daac 945b 9a81 f066
6cd2 0032 5df0 9ca2 23a0 6eec a7bb f24c
a941 99a8 1053 ae23 f88b 245c f709 c2b2
```

.....or as encoded text files, which look like this:

```
DµÉ‰í+3K€Ð˜PªeZ_|Ò®ó0ãZqRµ3!ŒpuÉWNZrìÚk´
Aˆ›œiêø8Úól:äÎŸ”6‡)
w¬ÌŒWÝÚ¢Qœœ?H¨¿œ//ÃBA´>(%°e
```

(Both of those resemble what I see when I console log "encryptedData" above in my code example.)

Whenever any non-armored files come in, the process fails and I get a couple different errors depending on the type shown above.  I have searched in documentation, but can't seem to find how to decrypt files that are not armored.  (Every single file, however, works fine when using a desktop program like PGP Desktop, so I can't figure out where my discrepancy is.)  Is there a standard way to do this with Openpgp.js, or is this something this module does not do?  I appreciate any kind words of advice that anyone might offer me!

**Comment by vafada** [comment]
try this:

```
const encrypted = fs.readFileSync('foo.pgp');
const message = openpgp.message.read(encrypted);
```

where `foo.pgp` is a binary file.

**Comment by ramlez** [comment]
Hi @threepears, did you figure out how to tackle the missing MDC error? (_"Error decrypting message: Decryption failed due to missing MDC in combination with modern cipher."_)

I'm getting the same error when I try to decrypt a file with `openpgpjs` library in node.js. The worst part is that I'm able to decrypt the same file manually in my terminal with *gpg* tool and also in C# code.

I'd be glad if someone could point me to the right solution.

**Comment by threepears** [comment]
Hello @ramlez ... unfortunately, I did not manage to resolve the "missing MDC" error.  My company discussed just getting the client to send a file that was encrypted with a newer method, and we moved on from the issue.  However, I do plan on revisiting this in the coming weeks to see if I can finally figure it out ... I will certainly post an answer here if I manage to come up with one!  (And I hope you will do the same .... :) )

**Comment by tomholub** [comment]
@ramlez @threepears there is an `ignore_mdc_error` flag in OpenPGP.js settings, you can use that to silence such errors, allowing it to decrypt.

**Comment by tomholub** [comment]
@bartbutler I suggest to close this issue

**Comment by bartbutler** [comment]
Good idea @tomholub

**Comment by FerLuisxd** [comment]
I still face this issue, I am trying to: Encrypt a message in binary -> Save it into a file -> Decrypt the message 

Here is my code:
```js
    const { keys: [privateKey] } = await openpgp.key.readArmored(process.env.PGP_PRIVATE_KEY)
    await privateKey.decrypt(process.env.PGP_PRIVATE_KEY_PASSPHRASE)

    const message = await openpgp.encrypt({
      message: openpgp.message.fromText(`Hello, World!`), // input as Message object
      publicKeys: (await openpgp.key.readArmored(process.env.PGP_PUBLIC_KEY2)).keys, // for encryption
      armor: false
    })
    console.log(message.message.packets.write())
    const hex = Buffer.from(message.message.packets.write())
    fs.appendFileSync('temp/' + 'test', hex + '\r\n')
    const encryptedData = fs.readFileSync('temp/'+ 'test')
    let encryptedMessage = await openpgp.message.read( encryptedData)
    const  {data:decrypted} = await openpgp.decrypt({
      message: encryptedMessage, // parse armored message
      privateKeys: [privateKey] // for decryption,
    })
    console.log(decrypted) // 'Hello, World!'
```
And here is the error: 
```
error PGP Error: Unexpected end of packet
at Object.read (D:\Projects\ligo\core-cashouts\node_modules\openpgp\dist\openpgp.js:39024:21)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at D:\Projects\ligo\core-cashouts\node_modules\openpgp\dist\openpgp.js:39171:22
```

**Comment by twiss** [comment]
> ```js
>     fs.appendFileSync('temp/' + 'test', hex + '\r\n')
> ```

This should probably be something like

```js
    fs.writeFileSync('temp/' + 'test', hex)
```

If you want to store multiple messages, it's better to store them in separate files.

**Comment by FerLuisxd** [comment]
Sadly didn't change anything

**Comment by twiss** [comment]
@FerLuisxd please post on https://gitter.im/openpgpjs/openpgpjs instead to ask for help, old GitHub issues aren't really the right place to discuss this

**Comment by FerLuisxd** [comment]
Ok finally was able to do it! (This program will write a binary file and then read it)
```
    const { keys: [privateKey] } = await openpgp.key.readArmored(process.env.PGP_PRIVATE_KEY)
    await privateKey.decrypt(process.env.PGP_PRIVATE_KEY_PASSPHRASE)

    const message = await openpgp.encrypt({
      message: openpgp.message.fromText(`Hello, World!`), // input as Message object
      publicKeys: (await openpgp.key.readArmored(process.env.PGP_PUBLIC_KEY2)).keys, // for encryption
      armor: false
    })
    console.log(message.message.packets.write())
    const hex = Buffer.from(message.message.packets.write())
    fs.appendFileSync('temp/' + 'test', hex )
    const encryptedData = fs.readFileSync('temp/'+ 'test')
    let encryptedMessage = await openpgp.message.read(new Uint8Array(encryptedData))
    const  {data:decrypted} = await openpgp.decrypt({
      message: encryptedMessage, // parse armored message
      privateKeys: [privateKey] // for decryption,
    })
    console.log(decrypted) // 'Hello, World!'
```

**Comment by PujaR-dev** [comment]
Better use node-gpg instead of opengpg for non-armored files.

const gpg = require("gpg");
gpg.importKey(privateKey, [], (success, err) => {     
                  gpg.decrypt(m_fileBuffer, [], (err, success) => {      //m_fileBuffer: read the buffer data from the encrypted file
          
                    var data = Buffer.from(success);
                    string_data = data.toString();
                    // console.log("Success", data.toString());
                  });
                });

Or in case you want to save the data in some location use method gpg.decryptToFile()
