### ISSUE TITLE
Typo in: invalidate expired primary keys

### ISSUE THREAD

**Issue by NNemec** [openpgpjs/openpgpjs#519]
Commit 344294659efc0 by sanjanarajan in Oct 2016 introduced the line

`if (primaryUser && primaryUser.selfCertificate && !primaryUser.selfCertificate.isExpired &&`

There are parenthesis missing on This should be 'isExpired()'. If I understand correctly, all certificates checked at this point should be considered expired. I'm surprised that nobody else has complained yet...

**Comment by bartbutler** [comment]
Good catch. I guess everyone uses subkeys for encryption. Fixed in head, new version soon.

**Comment by NNemec** [comment]
That would explain it. I found in through an automated test in a different project. May well be that the use-case was somewhat untypical...
