### ISSUE TITLE
How to avoid slow build time during development?

### ISSUE THREAD

**Issue by piec** [openpgpjs/openpgpjs#524]
Hi,
First thank you for this cool project.

I'm trying some changes in the source of openpgpjs (src/*) but I find the build times quite unpleasant especially when I try small modifications. The task `grunt browserify:openpgp_debug` takes more than 10s to execute on my not-so-old PC (core i7 860).
```
$ time node_modules/.bin/grunt browserify:openpgp_debug
Running "browserify:openpgp_debug" (browserify) task
>> Bundle dist/openpgp_debug.js created.
Done.
13.38s user 0.31s system 116% cpu 11.796 total
```
Most of the time is spent in the user process which means the CPU is the blocking factor (not the disk).
I'm pretty sure the babel pass is responsible. How do you guys develop? Do you have a trick to make the build faster?

I've had a quick look at browserify/babelify/babel documentations but I found no way to enable a cache or to make the build parallel. A way to cache the output of babel if the .js hasn't changed would be nice since most of the times changes are located in only a few files - right now every file seem to be re-babeled at every build. babel/babel-loader seems to do that with `cacheDirectory` but this is for webpack.

----
Things if tried but don't help:
* browserify --fast doesn't help
* grunt watch
* I also tried invoking browserify manually with the same result so grunt isn't the cause

Cheers

**Comment by bartbutler** [comment]
Hmm, 10s does sound about right to me. To be honest, with appropriate editor plugins/linters I don't find the build time to be an issue, as I don't rebuild that often usually. I see your point though, and would entertain any suggestions you come up with to speed it up.

**Comment by darkyen** [comment]
How about a watch mode with a cache of pre-built files? This is out of the box supported by watchify https://github.com/substack/watchify

**Comment by piec** [comment]
I just did a quick test with watchify and it seems to work great!
(not integrated in the gruntfile right now)
```
var fs = require('fs');
var browserify = require('browserify');
var watchify = require('watchify');

var b = browserify('src/index.js', {
    standalone: 'openpgp',
    cache: {},
    packageCache: {},
    debug: true,
})
.external('crypto')
.external('buffer')
.external('node-localstorage')
.external('node-fetch')
.transform('babelify', {
    presets: ['es2015'],
    ignore: /.*\.min\.js/
})
.plugin('browserify-derequire')
.plugin('watchify')

b.on('update', bundle);
bundle();

function bundle() {
  console.log('bundle ...')
  b.bundle().pipe(fs.createWriteStream('dist/openpgp_debug.js'));
  console.log('  done')
}
```

**Comment by bartbutler** [comment]
Cool! Can't wait for the pull request!

**Comment by twiss** [comment]
This should be improved a bit by https://github.com/openpgpjs/openpgpjs/commit/78a0ca937ee02214a643a085f25d28045fa22af0.
