### ISSUE TITLE
[Question] How to encrypt a file?

### ISSUE THREAD

**Issue by roccomuso** [openpgpjs/openpgpjs#525]
How to encrypt a binary file from disk?
Will some stream encyption be supported?

**Comment by bartbutler** [comment]
in openpgp.encrypt there is a filename parameter, and you can pass a raw Uint8Array as the data. For decryption, you want to make sure you set the parameter 'format' to binary. We do not have a streaming API at the moment, but the current code works well for files up to maybe 50 MB in the browser without issues.

**Comment by roccomuso** [comment]
So basically I should convert a `fs.readFileSync(file[, options]);` to a Uint8Array?

**Comment by bartbutler** [comment]
Yes. We can think about adding node-native Buffer support, but the Buffer to Uint8Array conversion should not be that expensive.
