### ISSUE TITLE
GPG signature verification generates error

### ISSUE THREAD

**Issue by leonidas61** [openpgpjs/openpgpjs#526]
Thank you for great software. I was trying to use it for the first time and faced follow problem

I signed hello world message with gpg and can not verify this signature in openpgpjs

I get error here:

  this.worker.onerror = function (e) {
    throw new Error('Unhandled error in openpgp worker: ' + e.message + ' (' + e.filename + ':' + e.lineno + ')');
  };

message, filename and lineno are undefined.

here is how I try to do it:

        var publicKey = openpgp.key.readArmored(pubkey).keys[0];
        var clearMessage = openpgp.cleartext.readArmored(encoded);
        openpgp.verifyClearSignedMessage(publicKey, clearMessage).then(function(sigCheck)
        {
            console.log( sigCheck.signatures[0].valid ); // returns true
        });

and this is signed data:

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hello, world
-----BEGIN PGP SIGNATURE-----

iQIcBAEBAgAGBQJYv/pbAAoJENUK34Athih2kScQAJZ2NMhdWFRPi28piw4B5U7A
Gjl3McdVO1fwYOYAzLlJuhu5NTKDqS21xSRtsVohIqx4KSfUhbwhT67uquzcW1km
hhzjf6brdtwbkYXPYDAD9uaz1Sm4jypyfputwlOkN0zAU0d7ndNniXwVWpSCX/PG
+IWZw6YnAi6KjkChzHSEgsDaRYI9FClDIExCdzV4oUIIQaADTdcXIZHI1BCtHl+Q
oPHY8n53aFg14Dd2X/SkbuhDdpTy9dAv2+I1G8XUawht+cLt0JdHuooK/afOpub8
IfSH8+HaYslEwIbJRYbmY9bJnsBFBEAUiGs4BYzmWDryhSGGcgd7a8xO7CiaQeNH
Vk/K5JeGQnGWzAXMhrIWiEY3L9GJ2d3nFmSc4XJte5PAXCSlYdt5a+E4ZklLlOei
i+D6peDEhceddXGzn2WJet3IDFvgLzZbiVEdKC4MSZPMjuehGHVMl+zUfAJafzy+
IIC1lhXZ3nPVkN0oabTWe8drfuSBNYMTCCE198ASdXF/L5jp54LAlvP9y9MGa8L4
CKUADtgYwIqGnjSM3HcFWVuggZeGsHgwFn29wDDKale/iCoe0eO2F4bS/P4jW+sZ
pPrWEFr/zEe62zBYSO8sASChDGVVs08sBpHy0/Z0nyF7ZA/wM0DSJselWqpAb3Uk
if2Iy5sP38dE9VuRks3X
=oyoJ
-----END PGP SIGNATURE-----

and this is public key:

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFi9qvUBEADEc14LvMzcfMwAeiX5B94vyS47zYLvcpDM/1Q97xUdQOe9jMNd
/FJtqDGyzBnwgS4NYofZ484nser368XEeP/Lmm833obRcWxr6chwB065iwoTG73k
/kVbtndLWGYXsLfH0a42EllxmGasgyxxT0a5MBZMmnGwaQDt0srL2GbRxPhF/mK2
KpQrr1eUTiImMpRURXpFbyuWVnCM0OFfnL1XpsL1bZlVyrlk0DGWyE1QCZ7YNuaT
Yom1JZcjyUmTYpjlC9z24gfp1Vq9gs+tQrEn53eVk0nDIR4/HQCpZLChe6ZZWwjS
TTTLJdwYDmI/b1Evhl9XMi3YsApB8zQ1geM5Tq9cxhdpr+GtChq89vj6N7ltK36/
P2YZ7NYLtqECJYX/2H3fqU5ACyNrbJ24Y/agPV9Tv+QtkM9DpSj17b+pn4VSBi7p
V3Lr2SJ3hzcBHqdC7fy/vmZUjsJ/yQucxxouJ5OHZBJUBCxo240EWFW8oa3Vpbu0
odWbpzuwWnxAtzupeoDtsm2CuiU5imjrvLEMj9i+uY4O/zj4uk2Evn6CKFB3q0RH
itYyZEGXjX7yEI+fwrGc4c+F0WpzCVmjTSQyv4+aa4mD2a0m/CQRjypvuYXq/lWt
g71mRrGiHQFtPLex2Wjvtms03EzF8ghe7+Jce2KilHxnblqvEfjlIx4oTQARAQAB
tCdMZW9uaWQgTHVrb21za2l5IDxsZW9uaWRhczYxQGdtYWlsLmNvbT6JAjkEEwEI
ACMFAli9qvUCGwMHCwkIBwMCAQYVCAIJCgsEFgIDAQIeAQIXgAAKCRDVCt+ALYYo
dnedEACUd3hnOAKOfiqc02CRGxLSqYH+flbUM4R68Hxw4C1SDoqyUGyETVFzJZbQ
7fKvkc2ExEQwIDAxK31NYBbrBcXX6W5+aSIz8SWMNK/CIy8nEzqwt6o5AAKKmAp5
934MW+7iwAUBlvFpKNk/VVuaskzHiW2utOVG/k5DfgBT0KfFke/yYh0SZBcAXs+w
k/ghwZZG/dZujBA1DfVDS/nD2Kg+qSClgroPRQcdmnXqlFng6YFs6Qcz9xBYMCJ2
2pgsMTT8+/Ov59X3DBopShMX2GVZskMH57n3hdw9bRYnyzhuKvr9NKHSvXpnFl6B
bPr/RRHFT86/uW5ZJVENLyEhgrkR70QuB0VarwMwl/ZLbFTS4wqHxBlNUNeOYrhO
U+HT8iLV6llD9iJxGGCGpGDykQM4HWOcgr+1x/Dts8q2UXEKcA8RaKZ5kamMUVvp
0oQKGgVd0q0/1YfXggbbv9VD1pNHx7eviZq/oivMsdc30YLMr5vZ+v7Uc5gZXq9y
sNrygtp6Ng5xSRwmd8ueM7I4uSp9CNDm5xAxBwOCne5yoMKAvIrXtyNtf/pBfESg
oR7nocTBFRf+2TverenYeU7wOgI6OZ2uAvgkQ06d8XqxQTcowTKKtFuIjSQsZQP4
kZc/LRuqFuk9Qzf9HjpyhnRhBxVvxkoBVKbY1vah0NCykyRDSLkCDQRYvar1ARAA
kuak3WquaCD/CTQGEAs4Ez2XQ2ZwLevD72wz1g9jbxpyp2pVCeW6Jc8662Y4w3Xr
sB7Tm/xbAbFVl9N6EObkZQ+yZEx03pDlHIUJbHsaE5zczbL/wGeyyeW2rB3cU1ME
7fDbn2fuj1FuSxAZI6Tkrmdn8x2lXJa3ipUQ8qgQIZ7MfBfsWDqf7xKoQpDh9uGP
Q4VtMTBkyDJovn2dTLIL4az5n2jOtZJqJ1ikpGV1nhhVxDvwtmrhxCviDZLUhO+F
OzM57ohQI7NfJH0q0xy29X+XFH+fcAGvaulWOFRt6XHx6egOLm/+1Gd36h6r7sUX
PXTAkkBCtITnl/ciDmevD+6Gyg9O5KXuxjBWlkE2YHO4t/55OdUO56X2km9D2VI+
ATTobu6ef667M3DoEc5bsm17qKF+zKjOcbTjq6WmnA5PcPrE2q2jwT8PJFFtTN3C
SojHdoDyAJuURskBafjWUgTHINql6kF0nZ11UiX8Ld5T7jrMaS6VipoSDl6leegl
7YNBeGa6Ez6hl5oHQ9QBZtnxRU9vKouEZky7+ZPjJ6k07oNGZfxRqplpFvr5Nitk
TkVqGg5AjrZgqnduVd9seAFN+tCHvvwSXd0gt5i2V9f4lR+rMZfRIwHsk7cMWNDh
krKkYyDk2OrthTgw9eOdDppd6jFQNC3gToMdqmAvZt8AEQEAAYkCHwQYAQgACQUC
WL2q9QIbDAAKCRDVCt+ALYYodidBD/sEhCWYk8GXcwM+Pe3qBbazMuvuZfMyp/xT
ZE7LUsVBdPgMCSMMIF3yV+uMb5FAvLXvKG5NAs0cdE9tv/xA8K4LF12doleR2K6V
lkZhlQx0u766SLfTOWZ+9Ef+nkIJH/khxARVF85YPEpyKNIEdPTTGCn90t6uQOMf
iYR05edvxBbi2aaJ6C2GjpK4duBoTWZvGjDY4zjJys1cVnYit/I140XWhGud9JNm
+4Imu+8VT4zYIi6zPACibmckS3rnfcCc3DZ63JaIOsCm9SRBzMvMeP4h2c7rwXXI
2dIawH+bmVj6Zp52qJXp/zq487LZQMm4fhOTACTnJC32bKLpW4m621WJQZRyQAkB
KaBlbE2niNNStMPuzuIr1YljSVNyOuBBens6dxmNaZVhjyW73i6jYYrJWHhrd8uv
j/duXmYKjv36k0u9ld//rB1EOnIvGpxEmWfD/kcSi3uhxAbHFKFI+h4foPlEGyB9
8z0tWA7aER1ADw/nhL52/Z7QvqSXMUIFx+HJAYOGQnNSWEEs6RrtN6zaRKUOjtIF
u8KEuiTMpoqadJeYVgmT5crUME2zH3WWvnRpMXoK0nK5hFMjlIxt0Ojguxf1Fs0x
kEqZxezNTqrn8xaU/ZBUS8O96wS2veS/66VZFL8AaArXb0aIzROhlXbpAczc/90Y
UXgWa9rGig==
=VNsL
-----END PGP PUBLIC KEY BLOCK-----

**Comment by juanmanuelarze** [comment]
+1

**Comment by voronoipotato** [comment]
You might want to include your entire code.

**Comment by tomholub** [comment]
To verify an inline signed message, follow this code:
```js
var publicKey = openpgp.key.readArmored(pubkey).keys[0];
var clearMessage = openpgp.cleartext.readArmored(message);
var result = clearMessage.verify([publicKey]);
```

I tested it with your message above, shows:
```
keyid: Keyid {bytes: "Õ↵ß-(v"}
signature: Signature {packets: Packetlist}
valid: true
```

@bartbutler I suggest to close this unless someone has followup questions / issues
