### ISSUE TITLE
work with multiple binding signatures per subkey

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#527]
I may do a pull request for this one day but it will take me forever to familiarize myself with the code base and establish a work/test flow.

This key:
http://pgp.surfnet.nl:11371/pks/lookup?op=get&search=0x2930100100003344

Has a bunch of of subkeys. The subkeys have 1-3 binding signatures each. Most of them expired, some not.

```
sub  2048R/D3F47501 2010-09-13            
sig sbind  00003344 2010-09-13 __________ 2012-09-12 []

sub  2048R/A81ED221 2012-09-12            
sig sbind  00003344 2012-09-12 __________ 2014-09-12 []

sub  1024D/20D0AAAC 2010-09-13            
sig sbind  00003344 2010-09-13 __________ 2012-09-12 []

sub  1024D/8B985EF9 2012-09-12            
sig sbind  00003344 2012-09-12 __________ 2014-09-12 []

sub  4096R/D22DB38E 2014-08-27            
sig sbind  00003344 2014-08-27 __________ 2016-08-26 []
sig sbind  00003344 2016-08-24 __________ 2017-02-20 []
sig sbind  00003344 2017-03-06 __________ 2017-09-02 []

sub  4096R/92736F3D 2014-08-27            
sig sbind  00003344 2014-08-27 __________ 2016-08-26 []
sig sbind  00003344 2016-08-24 __________ 2017-02-20 []
sig sbind  00003344 2017-03-06 __________ 2017-09-02 []
```

The non-expired signature is always the last and OpenPGP.js ignores it. GPG is happy with it.

A backward compatible fix would be to add `subKey.bindingSignatures = []` next to `subKey.bindingSignature`. Then fill it up like this:

```js
          case _enums2.default.signature.subkey_binding:
            if (!subKey) {
              _util2.default.print_debug('Dropping subkey binding signature without preceding subkey packet');
              continue;
            }
            subKey.bindingSignatures.push(packetlist[i]);
            subKey.bindingSignature = packetlist[i];
            break;
```

Finally,verify it with something like this:
```js
SubKey.prototype.verify = function (primaryKey) {
  ...
  // check V4 expiration time
  if (this.subKey.version === 4) {
    for(i in this.bindingSignatures) {
      if(this.bindingSignatures[i] ... is valid) {
        return _enums2.default.keyStatus.valid;       
      }
    }
    return _enums2.default.keyStatus.expired;
  }
  return _enums2.default.keyStatus.valid;
};
```

The same for getEncryptionKeyPacket, getSigningKeyPacket and so on.

Some guidance as to all the places in need of patching would be appreciated.

**Comment by mahrud** [comment]
@tomholub on this line: https://github.com/openpgpjs/openpgpjs/commit/2bda12731b50223d6515a516688a655e33d30bd9#diff-abf810d5af710449a432d7965d7aea6dR1046
Is there a particular reason why you didn't do this instead?
```this.bindingSignatures = subKey.bindingSignatures;```

In particular, the current code assumes that the first block of binding signatures is the same. What if the new binding signature was the first instead?

**Comment by tomholub** [comment]
@mahrud You do need to verify each of the subkeys before you accept them. But the logic could be improved I think - either always add subkeys without removing the old ones, or replace all old ones (both subject to verification). I wasn't sure which of the two fit better, as the original code wasn't aware of multi-binding signature setup. If we can agree on which behavior is desirable - replace or unique concat - then this can be improved.
