### ISSUE TITLE
Node performance is unacceptably slow.

### ISSUE THREAD

**Issue by darkyen** [openpgpjs/openpgpjs#530]
When I try to generate a keypair in nodejs (7.2.1). The process takes well over 30 seconds and this is for a key of 4096 bits. GPG2 took < 2. This was done on an 2015 MacBook Pro 15", I am wondering if there is anything else I can enable to improve it. 

In my current config, I do have `aead_protect: true` and its using native nodejs.

**Comment by darkyen** [comment]
I appreciate any feedback anyone has on this :)

**Comment by darkyen** [comment]
I just wrote a wrapper of gpg.

**Comment by bartbutler** [comment]
Makes sense, sorry for the delay in response. Some of the crypto primitives use node native functions when available, but I do not think this applies to key generation, as this is typically not something the server does. I'm sure there is a native node function we could use though. In the browser we use webcrypto extensions for key generation, so it's faster.

**Comment by darkyen** [comment]
I know this is not something that the server should be doing. However, this would make an exceptionally good use case for use cases like electron which can benefit from the native performance boost, 7 minutes on node.js / electron is painfully slow ;). 


Although again the simple workaround will work with gpg2 installed for electron too.  Also, I find it amusing how chrome is somehow outperforming node in this case.

**Comment by bartbutler** [comment]
Your point about electron is very good. We should try to accelerate this using native node crypto function.

**Comment by lirbank** [comment]
Another use case is CLI tools, which also is "Node.js on the client" so to speak. Right now we're just sticking with smaller keys (1024 and 2048 are pretty quick, 4096 takes a very long time) and that works fine while we're developing to product.

**Comment by darkyen** [comment]
@bartbutler Can you give us a "oversight" or "guideline" on where to start fiddling with this, I'm interested in contributing but the thing scares the shit out of me :P

**Comment by bartbutler** [comment]
@darkyen I may have someone to do it already (thinking of using it as a dev test)...I'll let you know if it falls through.

**Comment by darkyen** [comment]
@bartbutler thats a great dev-test :P can I apply?

**Comment by darkyen** [comment]
I was looking into the code-structure, I think the best would be to just wrap node's crypto with a 1:1 spec complaint webCrypto implementation then your code can simply rely on one such shim (and it can be another open source project you guys can maintain or someone else can

**Comment by bartbutler** [comment]
You're right, that would be one of the cleaner ways to do it. There are some complications to doing it 'generally' though, in the sense that webCrypto doesn't support all the features node crypto does, so what interface do you use if you want to use these features? I'm mostly thinking of AES-CFB, which we already use with a direct hack. I suppose we can copy the AES-GCM interface for that. That would be a nice way to do it.

P.S. https://protonmail.com/careers :)

**Comment by bartbutler** [comment]
Most of the work appears to be done already: https://www.npmjs.com/package/node-webcrypto-ossl

**Comment by darkyen** [comment]
> You're right, that would be one of the cleaner ways to do it. There are some complications to doing it 'generally' though, in the sense that webCrypto doesn't support all the features node crypto does, so what interface do you use if you want to use these features? I'm mostly thinking of AES-CFB, which we already use with a direct hack. I suppose we can copy the AES-GCM interface for that. That would be a nice way to do it.

If I were to choose the interface then I'd choose the interface which supports more features and is more battle tested. In this case that would be node's crypto. And then shim/polyfill features through injectable adapters that do not exist in browser crypto keeping the same api the adapter pattern has an additional advantages of "stepping-up" on platforms where native performance is available like Cordova, React Native or Ionic and overall results in a smaller core library.

Another approach is taken by [Native-Crypto](https://github.com/calvinmetcalf/native-crypto) which is wrapping both the primitives in an agnostic lowest common denominator way.

node-webcrypto-ossl look very interesting :). I was initially scared off by the 

**At this time this solution should be considered suitable for research and experimentation, further code and security review is needed before utilization in a production application.**

**Comment by ssancheza227** [comment]
@darkyen Hi :) i used > https://github.com/jerson/react-native-fast-openpgp very fast :)

**Comment by tomholub** [comment]
On behalf of FlowCrypt I'm offering a **$750 bounty** for a clean PR that uses native nodejs crypto for RSA keygen on Node.

Usecase: client side apps running Node.

**Comment by tomholub** [comment]
If a ProtonMail employee picks this up, we'll send a crate of beer to PM office of your choosing ¯\\\_(ツ)\_/¯

**Comment by tomholub** [comment]
@twiss  could you please rename the issue for me - maybe "**performance: use native nodejs rsa keygen**"

**Comment by tomholub** [comment]
Never mind, I went ahead and implemented it so it should get closed soon.
