### ISSUE TITLE
Can't generate keys by just using the npm package

### ISSUE THREAD

**Issue by luchoster** [openpgpjs/openpgpjs#531]
I'm creating a web app, and I can Encrypt and Decrypt just fine.
The problem is if I try to Generate a new Key, my browser just crashes completely (no errors or anything to tell me what's wrong).
I'm using React/Redux and if I include the openpgp.js from a CDN in my main index.html, I can generate a key, just fine. But I don't want to depend on any external libraries.

Am I doing something wrong?

Here's the snipped of the Action's code

```
// I've tried with either of these imports
import openpgp from 'openpgp'
import * as openpgp from "openpgp"

openpgp.generateKey(options)
    .then( result => dispatch(receiveKey(result)) )
```

Like I said, this works fine if I include the openpgp.js from a CDN in my html file. But if I don't, it crashes my browser.

Thanks!

**Comment by darkyen** [comment]
why aren't you calling initWorker ?

**Comment by bartbutler** [comment]
Are you browserifying/bundling openpgpjs with your other app code? That's usually a bad idea with openpgpjs specifically because the web worker needs a standalone copy of openpgp.js it can load. If you bundle it, it can't do that.

**Comment by luchoster** [comment]
Yes, I am calling the initWorker but I had it commented out since I was testing things.
I am using Webpack so I guess that wouldn't work.

Would it be enough to have the dist/ folder and just include both the worker and the openpgp.js in my html?

**Comment by luchoster** [comment]
ha!!!
including the dist files and calling the initWorker in my redux actions, works as I want it!!!

Thank you very much for the help!

**Comment by bartbutler** [comment]
Great!
