### ISSUE TITLE
TypeError cannot read property 'byteLength' of undefined

### ISSUE THREAD

**Issue by luchoster** [openpgpjs/openpgpjs#538]
I have a working web app and now I'm working on building a mobile app with React Native.
I'm just starting to encrypt and when I import 'openpgp', I get this error:
 ```
TypeError cannot read property 'byteLength' of undefined
```

Any idea on where should I start looking at?

**Comment by bartbutler** [comment]
Seems like your key is screwed up, or maybe is an ECC key? Though I would expect that case to fail earlier. That function (byteLength) is attached to the key MPI objects, so the message implies there are no MPIs in the key...

**Comment by luchoster** [comment]
I'm not doing anything yet. 
I mean, this error happens as soon as I include the openpgp library into my code.

**Comment by bartbutler** [comment]
What openpgpjs version? Latest?

**Comment by bartbutler** [comment]
These are the only calls/declarations of that function in the codebase:

`
src/crypto/signature.js:        var k = publickey_MPIs[0].byteLength();
src/crypto/signature.js:          data, keyIntegers[0].byteLength());
src/packet/public_key.js:  return this.mpi[0].byteLength() * 8;
src/packet/public_key_encrypted_session_key.js:    key.mpi[0].byteLength()));
src/type/mpi.js:MPI.prototype.byteLength = function () {
`

I do not think any of that should be called on initialization that I know of...

**Comment by luchoster** [comment]
Yes, latest.
I wonder if it has anything to do with the fact that I'm trying to use it with React Native, so maybe some incompatibility with mobile stuff?

**Comment by bartbutler** [comment]
Could be, we that's not one of the environments in our automatic unit tests. If you could track down the problem I'd be glad to get it fixed.

**Comment by luchoster** [comment]
Awesome, I'll keep you posted. 
Thanks!

**Comment by ssancheza227** [comment]
@bartbutler @luchoster i used > https://github.com/jerson/react-native-fast-openpgp :) very fast.
