### ISSUE TITLE
Compression Errors Silent in Decryption

### ISSUE THREAD

**Issue by demitrin** [openpgpjs/openpgpjs#539]
Currently if a message is compressed with an unsupported algorithm, the packet simply returns `null`. This started sometime around major versions >= `2.4.x`. It would be great if you made these not silent again because I've been trying to debug why a message compressed with `bzip2` was simply returning `null` with no error.

**Comment by demitrin** [comment]
If you're at all interested, I've implemented Bzip2 locally and can make a PR.

**Comment by bartbutler** [comment]
@demitrin We certainly are interested, please submit your PR. We'll look at the silent error issue, that is most definitely not intended.
