### ISSUE TITLE
Decrypting multiple entries is very slow

### ISSUE THREAD

**Issue by mchaabouni** [openpgpjs/openpgpjs#545]
Hi,

I'm iterating through an array of encrypted entries and executing the following code:
```
var options = {
	"privateKey": this._privateKeyDesarmored,
	"message": openpgp.message.readArmored(data),
	"sessionKey":null
};
openpgp.decrypt(options).then(function(decryptedContent) {
	callback(null, decryptedContent.data);

}).catch(function(err){
	callback(err, null);
});
```
This process is very slow. I was wondering if there's a way to execute a batch decrypt?
Decrypting the public key (publicKeyDecrypt) takes a lot of time. Is it possible to decrypt it just once? 

Thanks!

**Comment by bartbutler** [comment]
Hi @mchaabouni,

I'm not sure I follow the issue. The public key is never encrypted or decrypted...if you mean the private key decryption, yes, you can do this once and pass it in for every message decrypt.

Also, are you using aead_protect = true? That is theoretically faster but A) it's not strictly OpenPGP compliant and B) will not work as well for decryption in parallel. Verifying signatures also makes decryption slower.

**Comment by mchaabouni** [comment]
I don't see any gain in performance when using aead_protect = true
How do I disable signature verification?
Thanks!
