### ISSUE TITLE
Error decrypting message: No symmetrically encrypted session key packet found

### ISSUE THREAD

**Issue by markus0074** [openpgpjs/openpgpjs#548]
Hi,

Please help me I don't know what's wrong here in my code:

	var openpgp = require('openpgp'); 
	openpgp.initWorker({ path:'../node_modules/openpgp/dist/openpgp.worker.js' }) 
	var passphrase = 'Our hidden passphrase'; 
	
	const fs = require('fs'); 
	var data = fs.readFileSync('./order-file.txt', 'utf8');
	var pubkey = fs.readFileSync('./public.key', 'utf8');
	var privkey = fs.readFileSync('./private.key', 'utf8');
	
	
	var privKeyObj = openpgp.key.readArmored(privkey).keys[0];

    options = {
    	    message: openpgp.message.readArmored(data),     // parse armored message
    	    publicKeys: openpgp.key.readArmored(pubkey),    // for verification (optional)
    	    privateKeys: openpgp.key.readArmored(privkey).keys[0].decrypt(passphrase),
    	    password : passphrase
    	};
    
    console.dir(options.message.packets); //.['0'].SymEncryptedIntegrityProtected.encrypted);
    console.dir(options.publicKeys);
    console.dir(options.privateKeys);
    console.dir(options.password);

    openpgp.decrypt(options).then(function(plaintext) {

    	console.dir(plaintext);
        return plaintext.data; // 'Hello, World!'
    });

I always get this message:
       
	(node:10198) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error decrypting message: No symmetrically encrypted session key packet found.

And this is my code to generate the message:

	
	const openpgp = require('openpgp'); 
	const machineId = require('machine-id');
	const fs = require('fs'); 
	openpgp.initWorker({ path:'../node_modules/openpgp/dist/openpgp.worker.js' }) 
	var options, encrypted;
	var pubkey = fs.readFileSync('./public.key');
	var privkey = fs.readFileSync('./private.key');
	var passphrase = 'Our hidden passphrase';
	var privKeyObj = openpgp.key.readArmored(privkey).keys[0];
	var machine = machineId(true);
	options = {
	    data: machine,                             
	    publicKeys: openpgp.key.readArmored(pubkey).keys,  
	    privateKeys: privKeyObj 
	};
	
	openpgp.encrypt(options).then(function(ciphertext) {
	    encrypted = ciphertext.data; 

	    fs.writeFile("./machine-id.txt", machine, function(err) {
	        if(err) {
	            return console.log(err);
	        }
	        console.log("The machine-file file was saved!");
	    }); 
	    
	    fs.writeFile("./order-file.txt", encrypted, function(err) {
	        if(err) {
	            return console.log(err);
	        }
	        console.log("The order-file file was saved!");
	    });     
	});

Maybe you can give me an advice how to do it right.
Kind regards

Markus

**Comment by bartbutler** [comment]
Stop passing the passphrase in the decryption options object. That is for messages encrypted with a password (symmetric key encryption) not public key encryption, which you are using. Because you are supplying a password it thinks it's using the former mode.

**Comment by markus0074** [comment]
Thanks. I will try.
