### ISSUE TITLE
Error when decrypting binary data with keys?

### ISSUE THREAD

**Issue by baimurzin** [openpgpjs/openpgpjs#551]
I have the following code:
```
//encryption function 
const options = {
        publicKeys: openpgp.key.readArmored(this.user.publicKey).keys,
        data: data //uint8array data
    };
    return openpgp.encrypt(options);
```
And decryption function below: 
```
const privKeyObj = openpgp.key.readArmored(this.user.secretKey).keys[0];
    privKeyObj.decrypt(this.user.passphrase);
    const options = {
        message: openpgp.message.read(data), //data is uint8array 
        privateKey: privKeyObj,
        format: 'binary'
    };
    return openpgp.decrypt(options);
```

but I got an error when trying to decrypt:
-  Invalid session key for decryption(this code above)

Could you tell where an error is?

**Comment by baimurzin** [comment]
UPD:
I got this error because I have no **password or sessionkey**
In function `Message.prototype.decrypt`
We have a code: 
`const keyObj = sessionKey || this.decryptSessionKey(privateKey, password);`

But when I encrypted file I used only public key where I can find a session key to decrypt?

**Comment by bartbutler** [comment]
Hi @baimurzin,

Can you post your entire code example? My guess is that the private key doesn't match the public key.

**Comment by baimurzin** [comment]
Thanks for respond, @bartbutler 
Ok, I make an example:
[Github gist](https://gist.github.com/baimurzin/32d92ff921fd1f44055245585f66da3a)
Also, I used a variety of methods but did not help me

**Comment by sanjanarajan** [comment]
I think that the issue with your code is here on line 49: https://gist.github.com/baimurzin/32d92ff921fd1f44055245585f66da3a#file-test-js-L49

When creating a Message object from encrypted binary data, you should use openpgp.message.read(data) rather than openpgp.message.fromBinary(data). The latter is only used for reading unencrypted data into Message objects, so it creates the wrong type of packet.

I do think this is confusing, so we will improve the documentation for these functions.

**Comment by baimurzin** [comment]
@sanjanarajan Thanks for trying to help. 
As I said I tried a lot of variety of methods to solve this when I trying as you said
 I got `Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.
`
[updated](https://gist.github.com/baimurzin/32d92ff921fd1f44055245585f66da3a)
And trying this:
[3rd revision](https://gist.github.com/baimurzin/32d92ff921fd1f44055245585f66da3a)

**Comment by sanjanarajan** [comment]
Your 3rd revision is correct to set armor to false in the encrypt function, but you should change line 64 to "fs.writeFileSync(encryptedFolder + "1.jpg", cipherText.message.packets.write());"

The changes are because if armor is false, the result of the encrypt function is a full Message object, stored as "message", not "data". And because this is a Message object and not a Uint8Array, you need to use message.packets.write() to write the contents of the message into a Uint8Array. Hope this makes sense!

**Comment by baimurzin** [comment]
@sanjanarajan I still got the same error;(
[4th](https://gist.github.com/baimurzin/32d92ff921fd1f44055245585f66da3a/0628bed8682405248e41c033d40c8540f2cc6fc5)
Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.


But, if I make changes like this I have no errors but have some problem with the result.
[Last changes without saving into a file](https://gist.github.com/baimurzin/32d92ff921fd1f44055245585f66da3a)
All is ok. But I can not open my image after decryption. The image was damaged.
Do you have any idea?

**Comment by sanjanarajan** [comment]
When I run the exact same code from your 4th revision, everything works and I can properly view the decrypted image. Could you double check that you are getting this error in the updated code?

**Comment by baimurzin** [comment]
@sanjanarajan it's very strange, ok I am going to check and then tell you the result...

**Comment by baimurzin** [comment]
@sanjanarajan I don't know, but it still does not work, I added catch and pinned a log of error in revision. Maybe do you have any idea it does not work?
[with logs](https://gist.github.com/baimurzin/32d92ff921fd1f44055245585f66da3a)

**Comment by baimurzin** [comment]
@sanjanarajan Could you tell me about your library version, OS and NodeJS?

**Comment by baimurzin** [comment]
I tested it on:
1. macOS Sierra with node v6.10.0 openpgp@2.5.4
2. windows 7 with node v6.3.1 openpgp@2.5.4
both jpg and png formats

**Comment by Bradcomp** [comment]
@baimurzin Did you ever resolve this? I am having the exact same problem. When I use `read` I get the same error, while I can decrypt it fine using a GUI like Kleopatra.

**Comment by bartbutler** [comment]
I do not think we ever managed to track down the problem because it always worked fine when we tested it.

**Comment by spearmootz** [comment]
This happens to me randomly. I have a a couple of keys that i use to decrypt/encrypt.  and it does so succesfully but eventually, randomly with no changes, I get the following error.

This message / key probably does not conform to a valid OpenPGP format.

**Comment by twiss** [comment]
@spearmootz Is this in the same code as you talked about in #783? If so, it's probably the same issue. It might be that there's some sort of random (memory/data) corruption on your end, which can result in different errors depending on where it happens.

To debug, you could try setting a breakpoint on errors and logging the data that openpgp.js is trying to parse, and then comparing it to the file to see if it matches.

In any event, it's probably not the same issue as this one; if you need more help/hints please ask on https://gitter.im/openpgpjs/openpgpjs or, if you think it's a bug on our end, please open a new issue with more details if you have any.
