### ISSUE TITLE
How to use .skr file and pasphrase to decrypt file?

### ISSUE THREAD

**Issue by karan-jaryal** [openpgpjs/openpgpjs#552]
Need help as i have .skr file and passphrase to decrypt file and there is no method that take these two parameters😔

**Comment by bartbutler** [comment]
If I understand correctly, an SKR file should contain a PGP keyring (armored)? Maybe you can open it and tell me if it starts with '-----BEGIN PGP PRIVATE KEY'. In that case, you should be able to read the contents of this file into a string and then parse it into a key with openpgp.key.readArmored(str).
Then decrypt it with you passphrase and use the decrypted key to decrypt your file.

**Comment by karan-jaryal** [comment]
Hi @bartbutler thanks for answering when i open .skr file it contain some encrypted type of text

**Comment by bartbutler** [comment]
Are there any English words? Does it start with -----BEGIN PGP PRIVATE KEY?

**Comment by karan-jaryal** [comment]
Nop there are special symbols

**Comment by bartbutler** [comment]
In that case SKR files may be binary and you have to do the same thing I suggested before but use openpgp.key.read() I think.

**Comment by karan-jaryal** [comment]
Ok for decrypt it with passphrase which method should i use

**Comment by karan-jaryal** [comment]
openpgp.key.read() is not function  error when using this method

**Comment by bartbutler** [comment]
Try:
var list = new openpgp.packet.List();
list.read(bytes);
var key = openpgp.key.Key(list);

'bytes' is a Uint8Array with the binary data from the SKR file.

**Comment by karan-jaryal** [comment]
Its giving me object containing : {directSignature,primaryKey:null,revocationSignature: null,users:[0],SubKey :[0]}

**Comment by bartbutler** [comment]
Good. Try following the documentation to decrypt the key with your passphrase.

**Comment by karan-jaryal** [comment]
var privKeyObj = openpgp.key.readArmored(list).keys[0];
giving privKeyObj  undefined

**Comment by bartbutler** [comment]
You shouldn't use readArmored, but now that I look at it more closely, it seems your key object is empty? You could try calling 'decrypt' on maybe. Sorry, that's all I can do to help I think.

**Comment by karan-jaryal** [comment]
Ok,thanks for your help,if i find any solution surely i'll post here

**Comment by karan-jaryal** [comment]
We have to convert ".skr" to ".asc" as module do not support ".skr" file.Than everything will run same as mentioned in documentation.
