### ISSUE TITLE
Cannot cleartext sign Uint8Array

### ISSUE THREAD

**Issue by miestasmia** [openpgpjs/openpgpjs#555]
The cleartext signing example in README.md states that `openpgp.sign` accepts a Uint8Array for `data`, however your docs state that `openpgp.sign` only takes a string for `data`. I tried to pass a Uint8Array nonetheless and was greeted by the below error:
```
Error: Parameter [data] must be of type String
    at checkString (.../openpgp/dist/openpgp.js:15923:11)
    at Object.sign (.../openpgp/dist/openpgp.js:15776:3)
```

**Comment by JohnWest29** [comment]
so what do i do
