### ISSUE TITLE
Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by shredding** [openpgpjs/openpgpjs#560]
The encrypt / decrypt funcs do not have a reject function and are therefore throwing a deprecation warning: 

Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bartbutler** [comment]
I do not see any unhandled promise code in those functions. Are you referring to those functions themselves returning rejected promises?

**Comment by shredding** [comment]
Uhm. Sorry, I tried it again today and it was an error in my unit tests :-(

Keep up the great work!
