### ISSUE TITLE
processing armored blocks that miss a checksum

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#563]
Some PGP software will produce armored messages that miss a checksum. Airmail on a Mac does this. gpg2 is happy with it. pgpdump also doesn't seem to mind. OpenPGP.js not so.

```
-----BEGIN PGP MESSAGE-----
Comment: GPGTools - https://gpgtools.org

hQIMAyg0VaJkxjzIAQ//eN8kI4KBQnyi1XD7FiYZtCH80sp7wZjantPmd5u033Sb
...
...
oqK+Ce+axR9hd6rGjf7d+1y85A4rqwZNLXAl0hbM7LGPzGsUkSkEkLem2BTATLjc
ATDq0UkNp+ePND9NGO2E9syzZG+L3lH9VJMuD5p7b5/MjUGTOdMjGFlTSuE=
-----END PGP MESSAGE-----
```

```
(unknown) Uncaught Error: Ascii armor integrity check on message failed: '' should be 'KKUJ'
    at Object.dearmor [as decode] (openpgp.js:12263)
    at <anonymous>:1:19
```

I could fabricate a checksum and have it processed again by OpenPGP.js, then give a warning to the user, but it would be cleaner to allow this on the library level.

Any downsides to allowing OpenPGP to work with messages without a checksum, maybe under a special config flag?

**Comment by bartbutler** [comment]
No, I think with a configuration flag this is probable fine. Feel free to make a PR if you feel so inclined, otherwise we will try to get to it.

**Comment by tomholub** [comment]
I'll take a look at it and potentially do a PR.
