### ISSUE TITLE
To which KeyArray a generated key should be imported?

### ISSUE THREAD

**Issue by CB-Giepa** [openpgpjs/openpgpjs#569]
Hey there,

just wanted to use the keyring feature but came across a confusion. 
When I generate a key with openpgpjs I get an object with a private and a public armor part. Which of those should i store into my keyring? Is it necessary to store private and public part or is it enough to store the private part of it.

This question cam up to me because in my understanding the public key can be computed out of the private key.

Hopefully someone can explain that part to me.

```js
var keyring = new openpgp.Keyring();
var keyOptions = {
  userIds: [{ name: 'Jon Smith', email: 'jon@example.com'}],            
  numBits: 4096,
  passphrase: 'super long and hard to guess secret' // protects the private key
};

openpgp.generateKey(keyOptions).then(function (key) {
  // Both parts or just the private part?
  keyring.privateKeys.importKey(key.privateKeyArmored);
  keyring.publicKeys.importKey(key.publicKeyArmored);
});
```

Best regards,
Christian

**Comment by tomholub** [comment]
You could save only the private key if you wanted to.

You can always recreate the public key from the private one.

In our implementation we save both - for convenience. Often times, we only need the public key - why always recreate it if we can save it along with to the private one.

**Comment by bartbutler** [comment]
@tomholub is right, the private key includes the public key, so technically you only have to save the private key if you want to.
