### ISSUE TITLE
Support minimal key export?

### ISSUE THREAD

**Issue by karissa** [openpgpjs/openpgpjs#570]
In Autocrypt.js, we want to be able to send the users public key in a binary, base64 encoded form. We have done this using the gpg command line tool with the options ` --export --export-options=export-minimal` (example [in python](https://github.com/autocrypt/py-autocrypt/blob/4916584bdce194bc52c826be57327cc1755696af/core/autocrypt/bingpg.py#L287))

I'm wondering if there's a similar way to do this with `openpgpjs`?

Corresponding specification is here: http://autocrypt.readthedocs.io/en/latest/level1.html#type-1-openpgp-based-key-data

**Comment by bartbutler** [comment]
Yes. I did not actually test it but the following should work. Take a Key object and do:

`var bytes = key.toPacketlist().write();`

'bytes' should be a Uint8Array binary representation of the key's OpenPGP packets. If you need it in Javascript binary string form you can use the openpgp.util.Uint8Array2str function to get there. Good luck!

**Comment by bartbutler** [comment]
I missed the base64 part. Just use 'btoa' on the binary string to get base64.
