### ISSUE TITLE
Does decrypt "ignore" signature?

### ISSUE THREAD

**Issue by QAnders** [openpgpjs/openpgpjs#571]
I am running a decrypt on a message that is supposed to have a signature attached, however when I get the decrypted data back from .decrypt() it is the payload only, no signature.
The sender has shown me screenshots of the message as signed prior to them encrypting it but I can't extract the signature it seems...

```
	var message = openpgp.message.readArmored(msg);     // parse armored message
	var privateKey = openpgp.key.readArmored(private_key).keys[0]; // for decryption

	privateKey.decrypt(passphrase);
	
	var decmsg = message.decrypt(privateKey);
	console.log(decmsg.getText());
```

**Comment by bartbutler** [comment]
Use openpgp.decrypt, not message.decrypt, which is a more-or-less internal function which also does not take advantage of the web worker. The signature object should be part of the successful response.

**Comment by QAnders** [comment]
Seems I am on a pretty old version and I don't have `decrypt()`, only `decryptMessage()`.
I'm not able to update because the runtime of Node.js is not supporting ES6 (import).

I've changed to use `openpgp.decryptMessage()` instead of `message` but I am still only getting the message, not the signature.

```
	openpgp.decryptMessage(privateKey, message).then(function(pgpMessage) {
		console.error('PGP Decrypt done:', pgpMessage.slice(0, 100));
		session.output.write(pgpMessage);
	}).catch(function(error) {
		console.error('PGP decryptMessage error:', error);
		session.reject('PGP decryptMessage error: ' + error);
	});
```

**Comment by bartbutler** [comment]
Which version are you using? OpenPGPjs works in pretty much all Node versions newer than 0.12, so you should not have a problem migrating.

**Comment by QAnders** [comment]
The problem is the `import` and `export` mostly... `import * as messageLib from './message.js';` is not working, I must have `require()`.

It runs in a IBM DataPower Appliance so I am not sure about the Node version (and can't check as there is no npm). Some ES6 functions are included (e.g. Promises) but far from all...

Thanks for your help though!

**Comment by QAnders** [comment]
Yeah, this is a annoying (and growing) problem for many "Node-ish" implementation as most packages are moving to using `import/export` over the old fashioned `reqiure()` and `module.exports`.
I just ported a S/MIME package to be supported and it was a pain to get all instances changed and that was only about 20 .js files... Porting of `openpgpjs` would require a script I think (or a lot of patience...).

**Comment by bartbutler** [comment]
Tough to say, OpenPGPjs got refactored in version 2 to use ES6 modules, so in the source files it's all import. The requires appear after babel does its work to get the dist to ES5 compliance.

**Comment by QAnders** [comment]
I'll try a babel stand-alone and see where I end up... Thanks!

**Comment by QAnders** [comment]
I ran a local babel compile for it to bring it down to ES5 but there is some weirdness, e.g. `asmcrypto-lite` goes missing and some other modules as well, e.g. `compression` complains about keyword `in` so it seems to be a lot of manual "clean-up" anyway...
