### ISSUE TITLE
remove ES6 promises polyfill from build

### ISSUE THREAD

**Issue by k2s** [openpgpjs/openpgpjs#572]
When I load Bluebird and then openpgp.min.js the global Promise object set by Bluebird is replaced with https://github.com/stefanpenner/es6-promise.

Wouldn't it be better to make requirement to provide es6 promise responsibility of the user and not to include it in openpgp build ?

**Comment by bartbutler** [comment]
So, the reason for this is that openpgp.js gets loaded as a standalone web worker as well in the browser and relies on ES6 promises in the worker. The way workers are loaded it is tricky to rely on the user to provide an ES6 promise polyfill--the worker script has to be self-contained. So the polyfill has to stay.

We might, however, be able to add some logic which prevents the polyfill from loading if bluebird or other promise implementation already exists. You could also try loading bluebird after openpgpjs.
