### ISSUE TITLE
support rename encrypted files

### ISSUE THREAD

**Issue by acornejo** [openpgpjs/openpgpjs#577]
When encrypting one can specify a filename parameter.

This filename can then be retrieved during decryption.

If I wanted to rename the file, I would have to decrypt the entire thing first (including filename + payload) and then encrypt again using a different filename.

Is there a better way?

**Comment by bartbutler** [comment]
No, there isn't, sorry. The filename is part of the literal data packet:

https://tools.ietf.org/html/rfc4880#section-5.9

The the literal data packet is then encrypted in its entirety. There is no way to access or modify the literal data body without re-encryption.
