### ISSUE TITLE
Signing message returns =twTO every time

### ISSUE THREAD

**Issue by ShishKabab** [openpgpjs/openpgpjs#578]
For the following code, I always get =twTO as a signature

```
const privKeyObj = openpgp.key.readArmored(keyPair.privateKey).keys[0]
if(!privKeyObj.decrypt(seedPhrase)) {
    console.log('Failed to decrypt private key')
    return null
}

const result = await openpgp.sign({
    data,
    privateKeys: [privKeyObj],
    detached: !attached
})
```

I've tried to pass both a single object and an array into privateKeys, with the same result, because of
https://github.com/openpgpjs/openpgpjs/issues/189#issuecomment-36283582
https://github.com/openpgpjs/openpgpjs/pull/232

**Comment by tomholub** [comment]
Is this still happening? Could you create a .html file with a short script that demonstrates this issue? You can include openpgps straight from the github repo: https://raw.githubusercontent.com/openpgpjs/openpgpjs/master/dist/openpgp.min.js

You can either include bogus testing key in the script, or have the script create one and then use it for signing to demonstrate.

**Comment by bartbutler** [comment]
Feel free to correct me if I'm wrong, but as far as I remember PGP signatures are deterministic, so what about this is unexpected?

**Comment by tomholub** [comment]
`=twTO`, if I'm not wrong, is a checksum of no data (empty). I think he's getting no signature + checksum on the empty result, which would end up being empty string + `=twTO`, or always `=twTO` as he mentioned.

**Comment by tomholub** [comment]
Eg `openpgp.message.read(new Uint8Array([])).armor()` will produce:
```
-----BEGIN PGP MESSAGE-----
Version: FlowCrypt 5.1.1 Gmail Encryption flowcrypt.com
Comment: Seamlessly send, receive and search encrypted email


=twTO
-----END PGP MESSAGE-----
```

I'm suspecting he may be using the API in an unexpected way, that will produce something similar to what I just did, except with signatures.

**Comment by bartbutler** [comment]
You're right, that's odd. From that code snippet, it's not clear what 'data' is. What happens if data is null or an empty UInt8Array? I could see that not working but it should reject the promise I'd think.

**Comment by tomholub** [comment]
I see it.
```js
// this
openpgp.sign({
    data,
    privateKeys: [privKeyObj],
    detached: !attached
})

// should probably be
openpgp.sign({
    data: data,
    privateKeys: [privKeyObj],
    detached: !attached
})
```
I suggest to rename this issue to `sign should throw error when no data supplied`, after which someone can do a PR. Maybe myself :)

**Comment by tomholub** [comment]
Actually, either is fine. Just learned something about JS, I had no clue you can do that. Let me test an empty value.

**Comment by tomholub** [comment]
Ok, how about this:
```js
openpgp.sign({data: '1234', privateKeys: [k], detached: true}).then(r => console.log(r));
```
produces {data: xxx, signature: yyy} as follows:
```
data:
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

1234
-----BEGIN PGP SIGNATURE-----
Version: FlowCrypt 5.1.1 Gmail Encryption flowcrypt.com
Comment: Seamlessly send, receive and search encrypted email


=twTO
-----END PGP SIGNATURE-----

signature:
-----BEGIN PGP SIGNATURE-----
Version: FlowCrypt 5.1.1 Gmail Encryption flowcrypt.com
Comment: Seamlessly send, receive and search encrypted email

wsBcBAEBCAAQBQJaJjLLCRANVojr8xAr5wAAsB8H/RmDtql5PaMR6g75REZK
9WodmlKK/TxIvOazDDLFSw7hHokFcmrDoj+HAqDOy86pGCe2MGbEcb6ykYVV
xpkUF0tpM3dZHJcKyrn8hQNJgzudvGjevIlaBeaeSZO27a+J4Nd77mHklvpE
FTyt4ifwnCwv4CPXpAnKBEurmsQeBB3a60KDbgB5dJYNK/pEUHFQQ2tmCG9x
PA0ot2jw4ROiYI8Tp1gZMpzrK1gqkkZXxD7wf8Rbgv+9nenXFQ+VGQZstnpE
et1kp4by7eheY3DAHAzIV+lB10o3eKggzLuESdgUDwQQn+zQNfexd6Mz6K6C
uuxH5dkB1sLf/otyGXUP/mY=
=jipX
-----END PGP SIGNATURE-----
```

The content of `result.data` that we get back seems to always be wrapped unnecessarily. It was probably meant to just return `1234` - the original data.

@ShishKabab check the `signature` part of the result, not `data`, when creating detached signatures.

@bartbutler we could probably improve this

**Comment by bartbutler** [comment]
Yes, this is strange, I'll think about it a bit more and see what can be done to improve it.

**Comment by bartbutler** [comment]
Dropped the 'data'/'message' fields altogether when using detached signatures, no need to echo the data back to the caller. I'll release it soon.

**Comment by ShishKabab** [comment]
Hey @bartbutler , thanks for the fix! Somehow the notification arrived in another e-mail folder, so I only see your response now  :)

**Comment by bartbutler** [comment]
Thank @tomholub , I had missed this issue for some reason.
