### ISSUE TITLE
Explicitly requires string for passphrase in S2K.produce_key

### ISSUE THREAD

**Issue by FocuzJS** [openpgpjs/openpgpjs#579]
https://github.com/openpgpjs/openpgpjs/blob/bc69357ab55d16634dbcbf5e5f7a3643579697ec/src/type/s2k.js#L145

I'm proposing that we should be able pass a `Uint8Array` as the SecretKey passphrase (ex: SecretKey.decrypt) as it will handle it without throwing a String onto the heap.

The library already is ready for this functionality except for this single instance on line 145 that expects string.

One example fix could be:

```js
passphrase = (typeof(passphrase) === 'object') ? passphrase : util.str2Uint8Array(util.encode_utf8(passphrase));
```

Edit: This same line is used during generation of private keys, therefore changing this line allows `Uint8Array` to be passed into .decrypt of a private key **and** as the passphrase when generating key pairs.

**Comment by twiss** [comment]
Closing, see https://github.com/openpgpjs/openpgpjs/pull/1436#issuecomment-965003168.
