### ISSUE TITLE
ECC supported ?

### ISSUE THREAD

**Issue by ThierryIT** [openpgpjs/openpgpjs#580]
Hi,
When is the possibility to use ECC/PGP will be available with Openpgpjs ?
I am using Mailvelope who is depending on OpenPGPjs.
Thx

**Comment by bartbutler** [comment]
Hi Thierry,

This is being actively developed and we hope released within the next couple months.

**Comment by tanx** [comment]
![image](https://user-images.githubusercontent.com/1374174/31190625-e7b5d2c6-a93b-11e7-8bb9-631b85ffc30e.png)

**Comment by rahiparikh** [comment]
@bartbutler That's awesome! Looking forward to it. I came across https://safecurves.cr.yp.to/ and thought it might help you guys when making decisions on curves.

**Comment by bartbutler** [comment]
Thanks @rahiparikh!
