### ISSUE TITLE
Ionic/typescript support.

### ISSUE THREAD

**Issue by jk89** [openpgpjs/openpgpjs#583]
Hi there,

Is there any timeframe for it working on an IPhone? I'm trying to get this lib to work in an ionic app. It works just fine in Android. But not on IPhone, I can't even generate a key. A project I'm working on needs this fixed. If someone is up for a challege, I could pay for this work to be done.

Cheers

**Comment by bartbutler** [comment]
So I've updated the title of your issue to reflect the appropriate level of precision. The library works fine on iPhone in the browser, but apparently it doesn't in Ionic (which could be related to typescript support, something that I think is currently broken). So yes, I think the way forward is probably to look at the type script definitions and fix them.

**Comment by 0815fox** [comment]
I am also affected, just wanted to import this module into typescript and git the message node_modules/openpgp/index.d.ts is not a module.

**Comment by jk89** [comment]
Hi apologies this was a late Friday afternoon frustrated message devoid of any real context/substance. 

I've been able to use openpgpjs from ionic just fine by just declaring it as any type within a page component, I can even generate keys ok. I use dist versions rather than any gulp or npm shenanigans. 

But for my usecase I run many copies of openpgpjs within a set of webworkers matching the clients hardware concurrency. I am not using the openpgp.worker.min.js instead I am using my own based of the remarks from this previous issue: https://github.com/openpgpjs/openpgpjs/issues/472

Unfortunately the way errors emerge when testing for ios leave a lot to be desired. I am going to build an example project that others can follow. I seem to be getting similar errors with Safari as with ionic for ios.

**Comment by twiss** [comment]
`window.crypto` is available in workers nowadays, and `openpgp.initWorker({n: 2})` can be used to init multiple workers.
