### ISSUE TITLE
Question : Is it possible to change the passphrase associated to the private Key ?

### ISSUE THREAD

**Issue by Ne0blast** [openpgpjs/openpgpjs#584]
Hello there,

I'm currently developing an web application that's using openpgp.js. I need to implement a feature where the user can change its passphrase. I know it's possible to decrypt the private key using the passphrase, but is it possible to encrypt it with a new passphrase ?

I'm doing that for the moment : 
```javascript
var privKeyObj = openpgp.key.readArmored(atob(privKey)).keys[0];
privKeyObj.decrypt(atob(current_passphrase));
```

Thanks for your answer.

**Comment by bartbutler** [comment]
Yes, something like:

```            
privKey.primaryKey.encrypt(privKeyPassCode);
privKey.subKeys[0].subKey.encrypt(privKeyPassCode);
```

You probably want to iterate over all subkeys, as there could be more than one.

**Comment by Ne0blast** [comment]
Thanks for your answer :)

**Comment by bartbutler** [comment]
Make sure you see the edit I made, I think it's as simple as called 'encrypt' on the object.

**Comment by Ne0blast** [comment]
Ok, thank you. Is it normal that the "new" private key really looks like the old one ?

**Comment by bartbutler** [comment]
They should not be identical unless the passphrase is identical (I don't think there is randomization in the key encryption).

**Comment by Ne0blast** [comment]
Ok thanks, seems i've found why it's like that :)

Thanks again for your time.
