### ISSUE TITLE
Add SmartCard Support - Upwork job with hourly rate

### ISSUE THREAD

**Issue by adrianduke** [openpgpjs/openpgpjs#585]
I'd like to see SmartCard support added to OpenPGP.js, I've posted a job on Upwork for it to be completed, I'd love to have a core or active contributor take the job:

https://www.upwork.com/job/Crypto-aware-JavaScript-Developer-Open-Source-Project-Contribution-openpgp-mailvelope_~01faf0ce9c4e66b0b1/

**Comment by mhalano** [comment]
@adrianduke A saw a person has been hired. How hiw work is going?

**Comment by adrianduke** [comment]
Unfortunately it didn't pan out :(. We've now had to move on from this with the client we were working with, using mac gpg tools instead. However I will discuss internally with my company and we may be able to make a bountysource contribution on top of the existing $500. I'd like to see smartcard support added to OpenGPG.js in any case!

**Comment by m00nxaild** [comment]
+1 for adding this support. Consider a donation page?
