### ISSUE TITLE
Teach me how decrypt and verify the signature plz

### ISSUE THREAD

**Issue by juanmanuelarze** [openpgpjs/openpgpjs#587]
Hi guys, i have this problem.

```
var secret = "Im String";
var privKeyObj = openpgp.key.readArmored(privKeyString.trim()).keys[0];
privKeyObj.decrypt(secret);

var publicKey = openpgp.key.readArmored(publicKeyString.trim()).keys;

var options = {
       message: openpgp.message.readArmored(PGPMessageString),
       privateKey: privKeyObj, 
       publicKeys: openpgp.key.readArmored(publicKey.trim()).keys
 };

openpgp.decrypt(options).then(function(plaintext){
      console.log(plaintext);  //THIS NEVER HAPPEND
});
```

(node:21499) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error decrypting message: Invalid enum value.

If i comment publicKeys for just decrypt without verify sign, works and i get the decrypted data.

```
var options = {
       message: openpgp.message.readArmored(PGPMessageString),
       privateKey: privKeyObj, 
       //publicKeys: openpgp.key.readArmored(publicKey.trim()).keys
 };
```
Result:

{ data: "DECRYPTED DATA",
  filename: 'INPUT.txt',
  signatures: [ { keyid: [Object], valid: null, signature: [Object] } ] }

------------------------------------------------------------------------------------------

I need verify the signature.

**Comment by bartbutler** [comment]
Without a fully working example I do not think I can help very much. The code looks right, maybe the public keys are damaged or otherwise unsupported?

**Comment by juanmanuelarze** [comment]
ok, thanks, i think you right, i come back with the solution later.

**Comment by juanmanuelarze** [comment]
@bartbutler now, i think, if the problem is the public key, i will have an error here

`openpgp.key.readArmored(publicKey.trim()).keys`

or not?

The key pair are generated with this lib.
If i have an error in the treatment of the keys as text, i will unable to decrypt the message, why my private key have the same treatment.
When i change public key param for other public key, the result is the decrypted message with signature valid null.
But when i try with the correct public key i have the error.

(node:21499) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error decrypting message: Invalid enum value.

PD: when i encrypt and sign the message i use asciiArmor true and withIntegrityCheck false.
Here the message:

-----BEGIN PGP MESSAGE-----
Version: DidiSoft OpenPGP Library for Android

hQIMA0IkdrSdKZ7cAQ//d2uUlG2ti1Q2CSZd4tNNbriXpFecwQflDC10eD48owRj
2m4C/blaU9VlG1nv+xSUy66FQTUGFtV4RGGoFYKPJfHX/VU8dziFXZOYp09er9TF
LkRJntCnIC16Vk1MDfMGoy53FKp68zyS1lGhJquaZpcGXhbCB7HwTyot5PUoMOFS
fLcpzO8/UBRNB0qJIG+DIc5m4HzI++vkmHoYC0S7XdIXz4z3E7IlgGjdjiX49yvW
2+0nI0S1oc+uob0z1Rev5Z6hb1BGzSMXahGwAnbdDOp7scr/gD0ixh+TH7R4M5q6
LcXOW2v5QTe+89vW+ANDnn/jH1uWGQMYV7aY22+M1D+TSlp4qU/Zu0jvhZWgo2VT
s/+I27BMFyMGtgMjSRwUOHHa5gX4DLEtsmDDsz6hIDVl+bSRez2xdib4Q9AB2hvB
7DV7CnlflY+7PXSFRvjrGL5wE1ny9TDfrQ3I0Bw9XJQIR2D9UV6VHFaAgQuZ9Ur7
TxJCHiTsAbrvtkJlLIAgu7vghJhq9f7undfhqB+8Wcv16fS05W4r5enVKHKEacmy
NghCso2JX704045sziZZ7LPc/YonhQooatjNltbGJpi7Cz0Z+z5NzS7Gu04dXUZV
LpMOppZRiEW+6YNLhZulflgxI6QkaZ0lzUSunBxejB3SZLf1UvnddIu6mwEogpfJ
wbpTTpSv0DUIkshCszxIUMaLFjS5L3zD2V4guomzNGUhcHHXd1WUqj2w2WQK25Ek
Fxg1cCzixG6sFgN/PobglPNUTHSGt5TztSccwHWerV4FpsPJGTqbRr1mAJS2wfXA
C++7IyroYPO/+oK+5aqhsSTpQ0jzNqkb9VPR52wPIyE2BZ4hmPWeW/5zsnemreQx
d3HcvyjnPVIn2pL7mn+BZNnf1Z0oMAAOWE1fUcq2a5q1FoIpjhKzU3RsS9G9x9T8
2FLYcV46IIdYAPvN6aKBUo2h/5gTo6RkiwLn66mzX1fh4hBBX/WYxtoGiaMYajbY
8i56q+LSa9Im0t5MbEuDHaO2Ju2/xmhe+U3jjg4kSzmCqHw5Xntoj+9RT0p/dsYj
zno8+irgdvrG+i4b3Rp99xeJrXrIsD7aYYa/S3ZUcroOxwqYsdy/QJEJdPT1LCo3
MbGX4c360IPVyiQE464RreE7PFClJHq/cvXPheXC/7Zvv7nYkKYSLYNB/LhrThds
L+Bbv1tUm8MDMjWudpRrEzLga32E5DDbyhD7CL0oy+vefQj+DLVkvbeSkJrqgvy3
eSEyi14wq8QqOOJ9s1lUJYer4SmIYH5CdDL9DEC2ZzzTg3UjnWMcS6t12N+x6Pm1
gv6ScrNHDfv6a9ku/PvKf23Ip2Bw0kLuTnBBzMhIkmL7gHSeJCjIHXt7oOkfA9Fy
0gDI/w4K/TQpZC0Tg+NnzcbiHNIzWsH0IHMxbPfA9v+j6Be7yjspwPFQ/TKQrbEW
Sbxqodtd/bwUTlYOecurc92AmlHwwRp44nDZkuAWai6cdtKRnQCSl+R4Lft/txEu
k8Ic7FE7wAOTePt9
=boBh
-----END PGP MESSAGE-----


Here the public key:

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v2.5.10
Comment: https://openpgpjs.org

xsFNBFm/Jq8BD/92+yeUJ39nemjgeKoLP8SMh6+GoF2IvwKK85YkAh4ZY+ZN
ZUk0Sk8ypU8mWxsbl87ynThduSuMagDWXkHQKwPfLHwLLPnqvNJoXINod0jl
GDcWeJDt466imtv8wrS186YWxtVjn7x0DOkCVrn3cRjLFTVHD70GHjB6ibby
8/4lKg4HK1es9MWnGeiCUGBY2YleyyRbo9GKJeEmDYFstc4hE1DI6RH7+cPu
u/Zxa29RwxDcIE6xAnvVvP4HwnfzGsjZ5vW4x+EiW9aMOT/QAC9QeL93kpv6
G+vIkRszugTWo0yceEF209/pI/eRoObQufFQeJ3gNXMY4xrk/EewrfIL5Pq7
KGuFqWiEjxREeByA3bmc/9QCPKBiQcStvkQ9Vm7nB6R2k1j7GxxGhjJIU9be
5wbi/aa1loKB+sXpkJGYWTJVV3aVm5RexvUOTPLwFyIh1ancwZ4o+uqtOzCp
r2d9uZZL63m9wfw64sYVcTaVxz+rfT+GqypBeuCppWjPjEa1Vq3GvM3TL1tR
1VzGPRDdN9lj5E185OQxWgPwvLAlGMLeduVrrBadUUamR7PR+iuTnvBNBtiv
Vqfz/YzV8G5pmA+FYAaDghDiG23wd4xsJq7qF4qzPWE1IMzg7FR5EQvIHTGS
Oa0M38UrxlrVIRjZcRGLT5jXE9DGCOsNO6gY0QARAQABzQtGdWtlbmNpbyA8
PsLBdQQQAQgAKQUCWb8m+QYLCQcIAwIJEHbzCW743wNwBBUICgIDFgIBAhkB
AhsDAh4BAAByOA/9HDQsz4BGSFB9InU99ZH1kCw8ch+cSGezc+OBQOaQt6Ni
zmMw0otGIsH6/IoDm1/Z8Tw+ByVviY0NMHu1gm7PA1DcP2mW842m0d3fPhqW
/qHQ0ih/DsNh1B1q+1f1x4EgjI6K6CzeELLC7bSSy7RPdUbjQVNiBXi8PJxl
HStZcTHSQ9JPBJxiN+zOX0m0g5RsdDUOynI+WqK2DIj757CFshSwesH9Lhbo
zjo36frNTXZvZqdaftnKhcpQvcbjgobi08j6pBjxDZguv2Vq3XnSgYAK7jb4
REq7xsrWDqW5hK5/wJ/fjVVnV+DkXet4iU2KNo93vOicwzbSN1QGWMvPJrhV
w0TGcTDhuFgR2UD1qPEYyqbmXAVMW0XvMeJdpnJ8Qvmi2wExAGSsizdYG4yc
BQy5xRXHPGJs/c3h5FFFCblRIgW8f0GRseUQcWnBlMLGLj09bME4H+3oUuIU
mHClPpTyqXjxfnAGTJql+QBL9JHjau4VP7tNfezx86lRIZHWcD2+8E4ridI2
2mANq5pCWby/OvtC1ar+o/9e4Ibbbac9IgZ7f4o3sZkmJVT/kfd6a9GpDSyo
k+Shv/h5FoU71izS9e66hLmUv2egu9PYmNaJOrEkw2bWo1O0ao4c+sl62f9p
AAixn3A1Q3qdGzoFKEu2T84qyF8CfWmNHvIOMvHOwU0EWb8m2gEQANlfb4ld
MCY0Zdr0/5AfWb7iDwkbjiRAN1dWbAgz5HajlNKuWD5gBoyaEGLFToZPFdQs
9kpHIbmGSW8eQlH3csYRdk6/jTFksjifTnKYOzd3BlotBOJFR+JPx5cYMGUB
uR76IONgKApR1gSk73vSvc2+PvisCRPu9UAzomMr+ASxSyhxldXb3CF8oqzj
Rqez79hOlxn/7dMHwC1Antj+jodIAEdhl2ZvjfEY4NseU6KeDAYG82dq1eSU
snHs1eG1nz4oOVh8OJD0p8D/M8nKN3Vwbu1mBKU6GpCpSulhUCeXnu3oZV9p
i74uLry9faDFSFDgzems2u9Y0ZCDokkmaIwjHfti03GKYzblWmSNJrQchBNN
lsqobIiaSWg764X0oSTFdqO215fvtIycKy2htLs4GVl2vx2Y7eIPtP0BqeNT
wWygRZ3jmx0dCg+xzQWengikSd7J1GCbSpDJtDsmbqGzzCoh2JiTlIGxYmRL
URrSYTvcEefVPBm/r/hqaoLwTau3qW0x1Ve1dcNpGU7u5sw4VE+9Pe5kzfp5
Ni1onPcTWy2787I1VSQby8dXZm1MW16kIeHGsMF/T3bWazPkiiVpp5P5u8Tx
Em1AlvVp+r1YLfyMM8XzzEW4KFD6Dmh5oX5S6gcboEK3Jpxp+J+Ly2yccK5g
n/nHcbFrl5FvKQs5ABEBAAHCwV8EGAEIABMFAlm/JvsJEHbzCW743wNwAhsM
AACHHQ/8CJCTcV0vObvfeMe/HHXXYpN8FFuxwavgNTIzeoLbWjawGcZRSxl6
1REWcvG+6ZK/vrtOL7lGPYwxIaUNhYFt3BLnsP4uzNcPEV7gA+yYL1XyyP/e
OvTgZ7w1FFNk8DmY1GFodrcnS3HMJtwg3V4/5LQP+uHCDzLARqlGSXjTLcls
fgo2U8Pufj6q1i3fcAb1p1ZQIo8CfuARBb0or9byoOyQju8qW88y2G6iF3l9
6oO4ojMhttXQ5YtV5/GaVW8CD+fbp4YYSzW7TprAcDZ506lz0EGJdxqcxuw1
E4UcvguU269Sr40OBvqnvB9nRPPzO3CthDzEGoJx3CIRZINBZpBMVBXpp7yU
PQER1JntwWvE0Yykt0XwlgwyFykRpPMSe9RDFkekhiDJVaSl6NP6OrL5KVIQ
ENzDfWmQPNqU8NJ1KNEvHcieU5hSZFoppZumRZG7hoJ2VqItrTYSMuCEQOuU
rd1RBx3LGTFvGdM8igUwFo3Qs4mWJpfbOyz1qa06bvKg8mMqT+Iz+DuowBh1
HJOFV3q0kXyzTTHJYt6wrC7nWUZsEyU5kIiWRc7rBT+fFBobgnTjgvQTjNmu
oU4SV/imIR9Wa8gciZwhCEI81bU1dVT10WohkNKCbtF7ud0Bqe4cfOzErqJc
D1HoOB9iyHem2GjqKZgYWi+crw8zGWg=
=rLwV
-----END PGP PUBLIC KEY BLOCK-----

**Comment by juanmanuelarze** [comment]
ok, the problem was the method with i encrypt and sign messages in android, with "DidiSoft OpenPGP Library for Android" i was encrypt messages with signAndEncryptStream() and when i change it to signAndEncryptStreamVersion3(), works.

thanks for help and for library, nice work
