### ISSUE TITLE
You shouldn't rethrow a different error

### ISSUE THREAD

**Issue by justinmchase** [openpgpjs/openpgpjs#590]
I'm currently experiencing a null reference exception in this library but I'm having a hard time debugging it because the error that is thrown has its callstack nerfed.
```
Error: Error decrypting message: Cannot read property 'isDecrypted' of null
    at onError (.../node_modules/openpgp/dist/openpgp.js:16111:9)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

[This](https://github.com/openpgpjs/openpgpjs/blob/master/src/openpgp.js#L550) line strikes me as an anti-pattern. It should just be:
```js
error.data = message;
throw error;
```

Or if you wanted to get more clever you could create a custom Error type that preserves the callstack of the inner exception and modifies message like you have it here. [Here](https://stackoverflow.com/a/17891099/12958) is an example of doing that. Which may look like this:
```js
function PgpError(message, innerError) {
    var temp = Error.apply(this, arguments);
    temp.name = this.name = 'PgpError';
    this.message = temp.message;
    this.innerError = innerError;
    var stack = temp.stack + (innerError ? '\n\n' + innerError.stack : '')
    if(Object.defineProperty) {
        // getter for more optimizy goodness
        /*this.stack = */Object.defineProperty(this, 'stack', { 
            get: function() {
                return stack
            },
            configurable: true // so you can change it if you want
        })
    } else {
        this.stack = stack
    }
}
//inherit prototype using ECMAScript 5 (IE 9+)
PgpError.prototype = Object.create(Error.prototype, {
    constructor: {
        value: MyError,
        writable: true,
        configurable: true
    }
});
```

After altering my code in my node_modules folder to throw the original error, this is the actual callstack I'm getting:
```
TypeError: Cannot read property 'isDecrypted' of null
    at Message.decryptSessionKey (.../node_modules/openpgp/dist/openpgp.js:15003:26)
    at .../node_modules/openpgp/dist/openpgp.js:14949:38
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Which is [this line](https://github.com/openpgpjs/openpgpjs/blob/master/src/message.js#L157) unminifed:
```js
var privateKeyPacket = privateKey.getKeyPacket(encryptionKeyIds);
if (!privateKeyPacket.isDecrypted) {
  throw new Error('Private key is not decrypted.');
}
```

`privateKeyPacket` is null. I don't know how that is possible yet.

**Comment by justinmchase** [comment]
After debugging they key I can see that I have a primary key and a sub key but neither of their keyId's match the encryptionKeyIds.

Does that mean that I am using a bad key? Or a bad passphrase? I'm not sure. It would be nice if there was a null check and throw here I think:
```js
var privateKeyPacket = privateKey.getKeyPacket(encryptionKeyIds);
if (!privateKeyPacket) {
  throw new Error('Invalid private key or passphrase.');
}
if (!privateKeyPacket.isDecrypted) {
  throw new Error('Private key is not decrypted.');
}
```

Is that a correct interpretation of this error?

**Comment by justinmchase** [comment]
🔔  Ping!

Just wondering about the correct interpretation of this error, if I understand it correctly I can formulate a PR.

**Comment by bartbutler** [comment]
Hi @justinmchase 

Sorry for the radio silence. Yes, that seems to be just the wrong key to decrypt (if the keyIDs do not match), and I agree both that this particular error should be nicer and that throwing a different error is an anti-pattern. I'm not sure we need our own error class, maybe we can just throw the original errors and make them nicer if they are bad, as in this case.

**Comment by justinmchase** [comment]
👍  Thanks for the reply I'll try to make a PR with that feedback.

**Comment by tomholub** [comment]
Also just bumped into this. The following code worked nicely for me:
```js
function onError(message, error) {
  var newError = new Error(message + ': ' + error.message);
  newError.stack += '\n' + error.stack; // append original stack trace
  throw newError;
}
```
This will result in user-friendly message that also contains a relevant stack trace.

Something like this will make debugging errors out in the field a lot easier.

@justinmchase let me know if you still plan preparing a PR, else I may do it.

**Comment by bartbutler** [comment]
For the record, I think this is an excellent idea to both A) make the errors more friendly B) avoiding losing the stack trace for debugging.

**Comment by tomholub** [comment]
@bartbutler this can be closed I think
