### ISSUE TITLE
Webkit and not supported numBits

### ISSUE THREAD

**Issue by laurinenas** [openpgpjs/openpgpjs#592]
Now on Webkit modulusLength needs to be at least 2048 bits, or I get a really cryptic error. That does not really lead to anything. We could log an error when user submits a not supported numBits param to openpgpjs. Is there a better way to deal with it?

Do you think informing the user of the error would be a good idea?

**Comment by bartbutler** [comment]
I would reject the promise with invalid modulus length rather than silently changing key strength. I'm fairly certain that is what already happens though...we could reject with a better error message.

**Comment by laurinenas** [comment]
Great thanks for response @bartbutler . I agree. Let me explain how I got here: my colleague [got this error from webkit](https://github.com/WebKit/webkit/blame/65c3f3df9c1a9cf87fdf49ee73ba0c95b4e22c6a/Source/WebCore/bindings/js/JSCryptoKeySerializationJWK.cpp#L653), and without context it took some time figuring out what is going on. I believe we could do something better, though I am not sure about how and where of the implementation.

This may be trivial, but I thought I would share. Let me know what you think if this is worthwhile to pursue.

**Comment by bartbutler** [comment]
Merged!
