### ISSUE TITLE
tool to parse userid strings into objects

### ISSUE THREAD

**Issue by graingert** [openpgpjs/openpgpjs#595]
eg:

```json
{ "name": "Ham Spam", comment: "This is a test", email: "example@example.com" }
```

**Comment by tomholub** [comment]
I'd personally welcome it as a part of pubkey parsing - I bet every OpenPGP.js user will have a small utility that does exactly that (I know we do).

**Comment by graingert** [comment]
It turns out these user IDs aren't PGP specific they're addresses as defined by RFC2822 there's an npm module to parse them at addressRfc2822

**Comment by tomholub** [comment]
Indeed not part of OpenPGP spec. Still, a very strong convention.

**Comment by bartbutler** [comment]
Not opposed to requiring that npm module and putting a function that does this in util.

**Comment by graingert** [comment]
I think just having it the docs would be good

**Comment by tomholub** [comment]
Personally, I'd say it should either be a part of the api, or not done. If part of the API, it could be one of: 

```js
k.users[0].userId.userid; //current API

// option A) add a function (will not affect performance unless used):
k.users[0].userId.parse(); // returns {email, name, comment}

// option B) add an object (may affect performance, though uids are short strings, so not much):
k.users[0].userId.parsed; // contains {email, name, comment}

// option C) directly integrated
k.users[0].userId.email;
k.users[0].userId.name;
k.users[0].userId.comment;
```
If we don't put it in a visible place, I suggest we don't do it. I don't think many people will notice it in util.

**Comment by tomholub** [comment]
Unless there is a need to also parse strings outside of keys (eg emails).. then we can link it in util too. Not sure.

**Comment by graingert** [comment]
```js
// option A) add a function (will not affect performance unless used): k.users[0].userId.parse(); // returns {email, name, comment}
```

Can't be tree shaken

**Comment by bartbutler** [comment]
@graingert good point.
