### ISSUE TITLE
Deterministically generate a RSA public/private key pair from a passphrase

### ISSUE THREAD

**Issue by rahiparikh** [openpgpjs/openpgpjs#596]
Is it possible to deterministically generate public/private RSA key pairs from passphrases with sufficient entropy?

**Comment by tomholub** [comment]
OpenPGP.js does not have API for that.

You could swap out `getRandomBytes(n)` and feed it your own entropy, eg recursive hashes of the password. I wouldn't recommend it - cooking up your own crypto is usually not a good idea.

**Comment by bartbutler** [comment]
Yeah, I can't really think of a good reason to have this so I'd rather not implement it in the interest of protecting people from themselves, unless someone can think of a good reason for it.
