### ISSUE TITLE
unknown armor headers should be ignored

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#598]
Gettting **Improperly formatted armor header: Independent Reserve Pty. Ltd. 2017: 1.0.0.0** caused by:
```
-----BEGIN PGP SIGNED MESSAGE----- 
Hash: SHA1 

This is to notify you that your Independent Reserve password has been changed. 

If this action was not initiated by you, follow this link https://www.independentreserve.com/Suspend?ChallengeId=a1d94491-d16f-4d23-8011-83ef1328ed1d to suspend your account immediately. Then contact support to resolve this issue. 

View Account / Change Email Preferences: https://www.independentreserve.com 

-----BEGIN PGP SIGNATURE----- 
Version: BCPG C# v1.7.4114.6375 
Independent Reserve Pty. Ltd. 2017: 1.0.0.0 

iQFRBAEBAgA7BQJaCj7lNBxJbmRlcGVuZGVudCBSZXNlcnZlIDxzeXN0ZW1AaW5k 
ZXBlbmRlbnRyZXNlcnZlLmNvbT4ACgkQjvnr0LoSJkALCAf/UdtutV+7u+6OPqhE 
83aMgpiQse6jR3HgLWjmZnOR/mdPBGrCsFrwmsct5XgcCNoO+90WVNBt4M2JxmWS 
62RKY6TdsCxnJTEjSB3r9cfYpO6m8klB6itTkIF7YnqIivWLomMBaS/HuprWNEmL 
pVWQgMQPkmhz6H7vtJwLcoTG6Pw/mIfBo0/WcZC2ZQDr8C0FKwWFanwvZVdTQhke 
iJaM937feiH/BN0KhWAQpelrEktTF2y/JOl+NC4hUtwskRr7gpI2u2IycqZu5Ciq 
i4OOrBvAQ2i7PqW6OVBmrstV0pQDOwel/GSj0RIax8UwJp7Yf7PNw3RdpMDB6GuI 
QQDroA== 
=zqna 
-----END PGP SIGNATURE-----
```

OpenPGP spec is not super clear on this (as far as I can tell), but GPG verifies it with a warning:
```
gpg: unknown armor header: Independent Reserve Pty. Ltd. 2017: 1.0.0.0

gpg: Signature made Mon 13 Nov 2017 04:55:01 PM PST using RSA key ID BA122640
gpg: Good signature from "Independent Reserve <system@independentreserve.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

I propose that this should not be throwing an error when `tolerant: true` is set in config (the default).

**Comment by bartbutler** [comment]
The issue is that the regex as written doesn't like whitespace in the header name:

`    if (!/^[^:\s]+: .+$/.test(headers[i])) {`

I can't really find any basis for this restriction in the spec except that all standard header names do not have any whitespace.

**Comment by tomholub** [comment]
The original author probably wanted to keep it simple, justifiably so. It will take a bit more complicated regex to allow white spaces but still stick to expected format (headers should not start or end with a whitespace).

I'll do a PR this or next week.

**Comment by tomholub** [comment]
Something like this, supposing single-character headers are also ok: 
`^([^\s:]|[^\s:][^:]+[^\s:])+: .+$`

Testing:
```js
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test('A: Hello')
true
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test('Abcd: Hello')
true
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test('Acd 123 5.6.$.8: Hello')
true
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test(' Acd 123 5.6.$.8: Hello')
false
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test('Acd 123 5.6.$.8 : Hello')
false
```

Which also allows some funny headers, but strictly not out of spec?
```js
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test('_: Hello')
true
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test('*: Hello')
true
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test('* & ## ?? ()(): Hello')
true
```

**Comment by tomholub** [comment]
Even some weirder headers like
```js
/^([^\s:]|[^\s:][^:]+[^\s:])+: .+$/.test('(                          ): What is this')
true
```
Anyway, if GPG allows all of these, we can probably proceed with it.

**Comment by bartbutler** [comment]
What about this? Slightly simpler:

`/^([^\s:]+|[^\s:][^:]+[^\s:]): .+$/`

**Comment by tomholub** [comment]
Actually, this is what I really meant: `/^([^\s:]|[^\s:][^:]*[^\s:]): .+$/` (even slightly simpler)

Removed `+` at the end (it was bogus). Also changed `+` in the middle to `*`.

The left part of the OR is there to allow a single-char header name, so it doesn't need a multiplier. Two chars up are taken care of by the right side of the OR (now fixed).

**Comment by bartbutler** [comment]
Works for me, make a PR and I'll merge it.

**Comment by tomholub** [comment]
Sounds good, will do this or next week, including unit tests.
