### ISSUE TITLE
How to configure openpgpjs worker with React/Babel/Webpack?

### ISSUE THREAD

**Issue by rahiparikh** [openpgpjs/openpgpjs#600]
I am using code similar to the following in simple Javascript that uses React/Babel/Webpack.

```
class foo {
  constructor() {
    let config = {
      aead: false,
      [...]
    };

    openpgp = typeof window !== 'undefined' && window.openpgp ? window.openpgp : require('../../../node_modules/openpgp/dist/openpgp.min');

    /*
     * When path is set to '../../../node_modules/openpgp/dist/openpgp.worker.min',
     * there is no difference in the behavior. We still see two requests going out to 
     * http://<server>/node_modules/openpgp/dist/openpgp.min.js and
     * http://<server>/node_modules/openpgp/dist/openpgp.worker.min.js.
     */
    openpgp.initWorker({
      path: 'scripts/openpgp.worker.min.js'
    });
    openpgp.config = config;
   [...]
  }
}
```

While the code works fine, I noticed that the application makes additional requests (when the object of the class is created) to fetch openpgp.min.js (`<server>/scripts/openpgp.min.js`) and openpgp.worker.min.js. (`<server>/scripts/openpgp.worker.min.js`). This could add latency to the code as every client would have to request this code in addition to bundle (bundle.js) file.

Is there anything that I should be doing (that I am missing) to allow openpgp.min.js and openpgp.worker.min.js to become part of bundle file? 

Additionally, if I really have to use standalone files and cannot integrate them into the bundle, can I at least load them from different domain (such as CDN like `https://cdnjs.com/libraries/openpgp`) with Subresource Integrity?

Thanks!

**Comment by bartbutler** [comment]
Hi @rahiparikh 

So the issues is that OpenPGPjs uses web workers to avoid filling up the main JS event loop. The worker is spawned with a small script (openpgp.worker.min.js) which then requests the main library (openpgp.min.js). You might be able to change things so that your worker requests your bundle instead of openpgp.min.js, which would save you a request, but the worker environment is a bit different than the window environment so no guarantees that it would like everything in your bundle. The other option is to leave it and all the files should be cached that next time the user visits. 

If you are concerned about bandwidth, you could try removing just openpgp.min.js from your bundle so that the main thread and the worker thread request the same file and you avoid duplicating OpenPGPjs. This doesn't save you any requests but it does save you bandwidth/size.

**Comment by bartbutler** [comment]
Seeing your last question, I think you can load them from another domain. There's a function (maybe setWorker?) which allows you to pass a custom filename.

**Comment by Dinfyru** [comment]
You can use https://github.com/webpack-contrib/worker-loader for webpack.
And it's work fine.

**Comment by rahiparikh** [comment]
@Dinfyru would you mind providing a working example with webpack and worker-loader? I am running into errors due to ImportScript statement in worker script.

**Comment by steverecio** [comment]
Has anyone figured out how to call `initWorker` inside of a React app?

**Comment by MrXyfir** [comment]
Did you ever find a good solution @steverecio?

**Comment by steverecio** [comment]
@MrXyfir The solution I found required me to serve the worker scripts from the react `public` folder.

```
var openpgp = require('openpgp');
openpgp.initWorker({ path: '/openpgp/compat/openpgp.worker.js', n: 4 });
```

Then copy the [`dist`](https://github.com/openpgpjs/openpgpjs/tree/master/dist) folder to your react public assets folder.

AFAIK there is no way to launch the web workers without serving them statically.

**Comment by descampsk** [comment]
With vuejs and webpack, I put openpgp.min.js and openpgp.worker.js in a static folder.

Then I have a copyWebpackPlugin to copy the static assets : 

```
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      }
    ])
```

Finaly, I load openpgp and the worker like this : 

```
import * as openpgp from '../../static/openpgp/openpgp.min.js' // ../../static/openpgp/openpgp.min.js' 
openpgp.initWorker({ path: '/static/openpgp/openpgp.worker.js', n: 2 }) // set the relative web worker path
```

Not the best way to do but it works pretty well.
Even if you put the vuejs app on a CDN like cloudfront.

**Comment by twiss** [comment]
In the upcoming v5 release, OpenPGP.js should be much easier to use with Webpack/other build systems, but the Worker has been removed. For the rationale, please see #964. It is better to create your own worker, so that you can import only the parts that you need from there.
