### ISSUE TITLE
Unable to decrypt bouncycastle encrypted data

### ISSUE THREAD

**Issue by matteke-games** [openpgpjs/openpgpjs#601]
Hi,

So I have my application in c# which encrypts data using bouncycastle's pgp using the following method

https://pastebin.com/Zx07efeW

and I try do decrypt it like this:

https://pastebin.com/EFrfrgTB

But when I try to decrypt it I get: Error decrypting message: Invalid session key for decryption

First I thought that the error would be with bouncycastle but couldnt find a problem. But in the openpgp.js file the error happens on line 15017. No data to decrypt, in the function Message.prototype.decryptSessionKey. But I'm not really whats going wrong. This is the data I'm trying to decrypt: https://pastebin.com/NZw4Jr14

**Comment by tomholub** [comment]
Were you able to decrypt it in bouncycastle?

**Comment by bartbutler** [comment]
My suspicion is also a screwy file. I haven't used bouncycastle but when I see stuff like this:

`//data is encrypted first, then compressed,`

my impression is that the result is probably not a valid PGP message in some way. Encrypted data is pseudorandom data, so it doesn't compress. If you want to use compression, you do it first, by putting the data inside a literal data packet and compressing that as part of a compressed data packet. Then you encrypt the compressed data packet.

**Comment by matteke-games** [comment]
Thank you for the quick response, I was able to decrypt it using bouncycastle. And hmm I thought PGP used compression by default? When I was trying to debug openpgpjs inbrowser I noticed an object for the message which I thought said something about the compression, but I may have been mistaken. Tried it without compressing the data but it still wasnt able to decrypt the message

**Comment by matteke-games** [comment]
However without compression the error is different. The error is: Error: invalid array length

**Comment by tomholub** [comment]
Looking at your raw pasted data above, it has formatting issues. Newlines have been replaced by spaces.

Instead of

```
-----BEGIN PGP MESSAGE----- Version: BCPG C# v1.8.1.0 owEBWQam+YUBDAOsUAlVZXOljQEH/i0riKEbHtc/DxtpqjPFqWLnormEvUTz7U6R gWV5UanaF8gIzAKsLnp0JnQYKf93MpPOIorlLNkPB09yYkq5DaFboO7dZyNyNaUW 8lqHVQ/GKZNgOqCpIEIylAZwkjIjhlXWSYhmjRQyo8cTo1C+o4jA8E4G8F5TC/3i cQVUcjDHP/9wb7N8IWAi2UJQwovCttc4kZtDpo2/TaqxWBtO4vFAHZJLIyIq9EP9 pOBhOxw7UjLN8yraqeYht/YnFCN9BAqoY0KXXA8VQLBnlAxOVTv45vEU+aLeNjt4 1bvnHL82ZpFnXgXb/NHyYITzzQ9E4tesQLWoks5XDyhT4rCvu6nJxIfOnO8yZ0Hk +N/+Ockr9oiYtChSJwlLMHaqwYCSbCGxIC3K2xnLETFOT6TZ6alY0GYf8msKDh+C T6jeKK3bUu4VvLOQVq7hYHfYVvv760TAL/IKCRTj9zAjcEzj08XJasnozeVXYGcP MrHQasnfmqfuiZxIIXrztqVMImrbG7hVMdfPgg0ybFXtrzWK3EI5IJlrfv/+91fI HKIdJixRtNlq3TRwuGfV4gDpIPpdk5LWJe/S8m1ioTvVoCMxd2GU1UsSNfdUb65h 0xtfk6NGxnskxFqABn+R72XjC4LtEVFb1wksldK891AiN8QzdwhWfdb/OZOTX+t7 tYg0/M6u0ytDEmrpm4xroQ+Ot4tIUaz4UdbjHggZ/7lzL2CFt3CG6SBsQBj4x2Xr VLCJwIrmU4k0PMysNnUip7Q6vecnZleD0w/k4NCGs6jKuSrlL6/3f8CRxXEsXrkg 1HWeNWIRciRguIEOxLFCjwfeb9lyYU2UzO5zPq+YXt8oQP8FsccIuKxkCMBZSgbo K8de1g+s931Ojg6QEplbwjq5ea9AwJ0JaQ3pGVt8AjzHEz5gT60ituSA7S7jQ5+k GalB/QFvYTAOljwRD6MqhquDywQRtcfWPhNjM9/QZFsmE7ZfwvEIAmRHGhB7t5XD WKhK0CnQbqIMonCCpDLFhkFbocrH/B7jSiirYCYASVBNQKLnGzgyeLtkGhXeWYaC +SzVHL8i1n7ImbLuPQAkRNzAHNRvNT+40tNISSZAS1vNZn/lhakS9h6jHoWnEYOW 5WMGK9zvpyt5XdYhcADIK6P/gnlAbzv56YgUu4fqLV4xHnyU/I8oQAR/sTnz91/E 1ot/jeT6p/eJzQcHxjrCzJFhki3vwSrW9POIUow/6KPoUG3Pb/+FtmLOroB3DZzW vwp5IrTymr4XP6DV0+v2xGNIVuElyigJPT//LNpMaoh0vCuJzS3a0a01klMv+T2V wZrm+nV1DBazmBpbYcfibhCf7vRsFVRVmQaQqCjSa0DTQRvKh3lTDjatecn6uHKO CP3JzhEIJ8fP2XiFGc3fUXujYFCJUN4ECT16h3lk2JuPkI4ZNmN0Qpfv4b6HwdHX Xou/PZBEkTnifqrpepwJxAxhLdMUnHGd92lcy+uvF6QkstZ5txBt72xDZHaBGNu0 rdVVjFZtzDvUFUUQCj0gUMVt0Db4JimDAsBmq/9zh94daS/xJWX54J5eSV+mrHrg 95gFUvhoCxza9QRfdul6kIGM9Pk3cUat8fo/mrGkhcpRZZieXB+BDJJRevwiFoAB DWFejKo0NAGP6Seb3ETWIn8EUXh/BHeDcJe1ClTt16ArNnxucwpimmNYh7xJtftb 6y2EDjYZwrrlTnKX9uTDcW6Dn1pzY9Wa6uqMTukSMU796/CistRmnvwz3vOGhPr1 5eg62Z0nRBefKcr6XjpwSrvkm9B3KYuAOImVMBxqwv9NsjYlyQMlt+7P+LV6KeY4 TB6ik4j09DigjGj5X4w8j6Hn5a7ZjQSHl5+jp1ngBziInojd4tkhCFTCeO0cLlJu LWwbFzYsZIdVt9o33jw78maFI3AxMC9u+XAcC+EUpUUKtQftLN9L/sWyeR0qMS66 e0pH1zsPtqrVf6V2W4Oty8j+KxrGBI+pI5guh1uRwx3z3o9nYsLJ/EWuaoIU2vY1 7f3MiylSoR1yxDMb6gKwObEC3nV3iqmIGqZtJ4IAKsQ4Gs9Mga07tT1Vi/KSVGSQ WQPQC3lL/7OSIWJ84tIHKAtloq7roEKvhTgPCWX+gI4XaPxrPayjbhLXwCcqulN/ =k01S -----END PGP MESSAGE-----
```

It should be

```
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.8.1.0

owEBWQam+YUBDAOsUAlVZXOljQEH/i0riKEbHtc/DxtpqjPFqWLnormEvUTz7U6R
gWV5UanaF8gIzAKsLnp0JnQYKf93MpPOIorlLNkPB09yYkq5DaFboO7dZyNyNaUW
8lqHVQ/GKZNgOqCpIEIylAZwkjIjhlXWSYhmjRQyo8cTo1C+o4jA8E4G8F5TC/3i
...
...
7f3MiylSoR1yxDMb6gKwObEC3nV3iqmIGqZtJ4IAKsQ4Gs9Mga07tT1Vi/KSVGSQ
WQPQC3lL/7OSIWJ84tIHKAtloq7roEKvhTgPCWX+gI4XaPxrPayjbhLXwCcqulN/
=k01S
-----END PGP MESSAGE-----
```

I truncated the middle. Also, notice the mandatory blank line right above the data block.

**Comment by tomholub** [comment]
When debugging this, I suggest you try to use GPG to open such messages to make sure it's valid OpenPGP. Once you find a message that you can open with GPG but not with OpenPGP.js, we'll look into it

**Comment by bartbutler** [comment]
Please reread my comment carefully. You can use compression in PGP for sure
but the order you are using is wrong (need to compress then encrypt, not
the other way around) so my suspicion is thst your output file is invalid.

**Comment by matteke-games** [comment]
@tomholub I checked it and it did fail and then when I reread the comment from @bartbutler I changed my code to compress first and then encrypt and then it successfully decrypted. Thank you for helping and thank you for your time

**Comment by bartbutler** [comment]
Great, glad to hear it!
