### ISSUE TITLE
compatibility - support for BZip2 compression (decompress only)

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#607]
It may be difficult to get good performance out of JS compression. However we should look into decompression for compatibility reasons. Decompressing a message slowly is still better than showing an error message to the user when they receive a compressed message.

Thus I'm opening a separate issue for BZip2 decompression in case someone wants to look into it.

```
Error: Error decrypting message: Compression algorithm BZip2 [BZ2] is not implemented.
```

**Comment by bartbutler** [comment]
Completely agree. We should see if there are some reasonably fast BZip2 libraries we can use.

**Comment by konDeichmann** [comment]
Hi, is there any update on this issue?

**Comment by tomholub** [comment]
I'm not aware of anyone working on this atm.

**Comment by bartbutler** [comment]
I'm trying to find someone. As part of this project I would also like to
improve the ship performance but using native code where available. Anyway,
this issue has not been forgotten.
