### ISSUE TITLE
bounties, financial support, etc

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#608]
What is a good contact to coordinate donations or some form of continuous support?

I also have general questions about staffing and project structure, out of curiosity and for accounting.

Lastly, it seems there used to be a bounty system for issues, was it removed? Due to lack of bounties, other reasons?

**Comment by bartbutler** [comment]
Hi @tomholub,

Sorry for the delay in response. I'll try to respond to your questions in order.

1. We can absolutely have a conversation about donations/continuous support. I do not think there is any kind of legal entity in place for this at the moment but there could be.
2. OpenPGPjs was maintained by @tanx of Whiteout.io, who assumed that duty from the original library developer Recurity Labs Gmbh. When Whiteout.io folded, ProtonMail through me and @sanjanarajan  assumed maintainer responsibilities, along with Mailvelope via @toberndo and GlobalLeaks via @evilaliv3. @tanx is also still involved to a degree, though his main focus has moved on to other projects. The maintainers try to oversee and encourage PRs and bug reports from the community and also contribute code themselves. The code we contribute tends to be features that our respective organizations need for obvious reasons (major performance enhancements and detached signature work from ProtonMail, HKP support from Mailvelope, etc). Some of this work has been contracted out on a paid basis, mostly to @tanx and other experienced OpenPGPjs developers. We also try to shepherd community work to the point where it can be merged if it doesn't get there on its own (this is happening right now for ECC support, which we hope to finish testing and merge soon).
3. This might have been before my time. I know ProtonMail offers bounties for security issues in its products, which includes security issues in OpenPGPjs by extension, but I'm not aware of an active OpenPGPjs-specific bounty program.

**Comment by tomholub** [comment]
I'm closing this as asnwered. The info is good for anyone wishing to contribute & know history of the project. I'm hoping that one day @FlowCrypt can afford to dedicate a part time dev to help maintain & improve this. Until then, I will be contributing as time allows.
