### ISSUE TITLE
Calculate/show (in %) how far is key generation process?

### ISSUE THREAD

**Issue by torw4897dfz** [openpgpjs/openpgpjs#61]
This is not really an issue but more support question because I did not see any information about mailing list for users.

2048 key generation takes between 1 and 30 seconds, obviously depending on many factors. Is there a way to/to show in % how far is this process to be able to have a progress bar or something similar where user could be informed how long does he have to wait?

I was looking around BigInteger functions but I did not come very far.

Thanks and sorry for spam if there is a better place for this question.

**Comment by tanx** [comment]
Not relevant anymore as we use native keygen now in most cases.
