### ISSUE TITLE
openpgp incompatible with bluebird

### ISSUE THREAD

**Issue by k2s** [openpgpjs/openpgpjs#614]
related to #572
openpgp overrides global `Promise` object with `es6-promise` in worker and main file.
This is problem if application relays on for example `Bluebird` implementation of global object.

I see two possible solutions for main file:
1. don't use global `Promise` class, but define own `OpenPgpPromise` object and use that where needed
2. check if current global `Promise` doesn't provide all needed extensions and only then load `es6-promise`

**Comment by mahrud** [comment]
This should be fixed in the new release as we only polyfill `Promise` when it's undefined.
@k2s Can you check that the issues is resolved?
