### ISSUE TITLE
decrypting a message in a loop - data packets get wiped during first run

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#617]
If I do something like this:
```
let m = openpgp.message.readArmored(armored_m);

Promise.all([m.decrypt(k1), m.decrypt(k2)]).then(results => {
  console.log(results[0]);
  console.log(results[1]);
})
```
One of the results will always fail, because the first successful result will wipe data packets for the second one (memory optimization?).

Knowing this, I can refactor my code to account for it. I just feel like I can't be the only person trying to follow a pattern where you may attempt to decrypt the same message object several times with different parameters, later checking which one worked.

Solutions:

**Option 1)** respond with the same success result on subsequent decrypt attempts just like PrivateKey.decrypt() does

**Option 2)** Set a flag/parameter on the message object during first successful decrypt just before wiping the data packets. Watch this flag during subsequent attempts, and raise a specific error: "Encrypted data packets were removed during previous successful decrypt attempt"

**Option 3)** Consider it a feature and forget about it. Maybe a warning in a "known limitations" somewhere.

Option 1 is consistent with how PrivateKey.decrypt() behaves. Option 2 is a bit stricter, because Option 1 allows you to supply it a wrong private key on second attempt and it will look like that wrong key has decrypted the message, possibly causing confusion.

**Comment by bartbutler** [comment]
`I just feel like I can't be the only person trying to follow a pattern where you may attempt to decrypt the same message object several times with different parameters, later checking which one worked.`

I'm having a trouble understanding the use case here. Figuring out which/key password is correct out of a bunch of possibilities? Why would one need to do this?

**Comment by tomholub** [comment]
Not all OpenPGP messages advertise which keyids a message is encrypted for. Some people prefer to not include this info for privacy reasons.

Say I receive such message, and I have five private keys available. I want to try different keys until one opens the message, or until all fail.

**Comment by bartbutler** [comment]
Really? How does that work within the spec? The Key ID doesn't appear to be optional in the RFC.

https://tools.ietf.org/html/rfc4880#section-5.1

Or do you mean subkey encryption?

I feel like a better approach would be to to allow an array of decrypted private keys or an array of passwords rather than a single one and have OpenPGPjs handle the loop. We implement this already in our app externally to choose the appropriate private key from a list--it would be good to integrate it. But I still don't understand how these 'stealth' messages you are talking about work.

**Comment by tomholub** [comment]
On the bottom of https://tools.ietf.org/html/rfc4880#section-5.1

> An implementation MAY accept or use a Key ID of zero as a "wild card"
>  or "speculative" Key ID.  In this case, the receiving implementation
>  would try all available private keys, checking for a valid decrypted
>  session key.  This format helps reduce traffic analysis of messages.

This is what `gpg --hidden-recipient` does. Accepting `key | array` when decrypting and looping within openpgp.js would be quite awesome. It's just a matter of figuring out how to handle error output if all fail (different keys may produce different errors, etc).

**Comment by bartbutler** [comment]
Interesting, I've never seen that blurb. Yeah, I think we can do this somewhat easily.

**Comment by sanjanarajan** [comment]
Support for multiple private keys & Key ID wildcard added in https://github.com/openpgpjs/openpgpjs/pull/635
