### ISSUE TITLE
Error decrypting message: privateKeyPacket is null

### ISSUE THREAD

**Issue by nandamerheb** [openpgpjs/openpgpjs#620]
Hi,

I'm trying to load public key from DB and private key from a textbox and try encryption and decryption.
Encryption works fine, but I can't decrypt message because I getting this error:
"Error decrypting message: privateKeyPacket is null"

My code is bellow:

                    $.ajax({
                        url: '/User/GetPublicKey',
                        type: 'POST',
                        data: { device: fpp },
                        success: function (result) {

                            var pubkeyLoad = result;
                            var privkeyLoad = document.getElementById("tbRecoveryKey").value; //encrypted private key

                            var privKeyObj = openpgp.key.readArmored(privkeyLoad).keys[0];
                            privKeyObj.decrypt('@logirani.xce_PasswordHash');

                            options = {
                                data: 'Hello, World!',                            // input as String (or Uint8Array)
                                publicKeys: openpgp.key.readArmored(pubkeyLoad).keys,  // for encryption
                                privateKeys: privKeyObj // for signing (optional)
                            };
                            

                            openpgp.encrypt(options).then(function (ciphertext) {
                                var encryptedTxt = ciphertext.data; // '-----BEGIN PGP MESSAGE ... END PGP MESSAGE-----'

                                alert(encryptedTxt);

                                options = {
                                    message: openpgp.message.readArmored(encryptedTxt),     // parse armored message
                                    publicKeys: openpgp.key.readArmored(pubkeyLoad).keys,    // for verification (optional)
                                    privateKey: privKeyObj // for decryption
                                };

                                openpgp.decrypt(options).then(function (plaintext) {
                                    var temp = plaintext.data; // 'Hello, World!'

                                    alert(temp);
                                });
                            });

                        },
                        error: function (xhr, status) {
                            if (xhr.statusText == "NoKeyDevice") {
                                popWarning2("There is no key for this device. Please generate a new one!");
                            }
                        }
                    });

**Comment by bartbutler** [comment]
Does the private key correspond to one of the public keys? If not, then this definitely doesn't work--you can't encrypt something to a random public key and then decrypt it with your private key--you'd have to have the private key corresponding to the public key, or encrypt with the public key corresponding to your private key.

**Comment by bartbutler** [comment]
I'm going to close this, feel free to reopen if I'm incorrect about the issue.

**Comment by nandamerheb** [comment]
Dear Brat,

 

When I generate a key pair and try encrypt and decrypt it works. After that, I store a PUBLIC key to DB and PRIVATE key to Cookie.

 

When I get back public key from DB and private key from a cookie and try encryption-decryption doesn't work.

Can be a problem if I write a public key to DB as a string?

 

B.R.

Adnan

**Comment by nandamerheb** [comment]
When I generate a key pair and try encrypt and decrypt it works. After that, I store a PUBLIC key to DB and PRIVATE key to Cookie.

When I get back public key from DB and private key from a cookie and try encryption-decryption doesn't work.
Can be a problem if I write a public key to DB as a string?

**Comment by bartbutler** [comment]
Shouldn't be as long as you are armoring it first. Try storing just the public key/just the private key to see which is the issue, and then debug from there.

**Comment by tomholub** [comment]
@nandamerheb were you debugging this on Firefox? It does seem to have something to do with keypair mismatches as Bart mentioned.

We are seeing something related, but only on Firefox - or so it seems.

**Comment by tomholub** [comment]
Indeed, on v2.x.x this error would be thrown on private key mismatch. Chrome would be throwing a different error.

I tested this on v3.x.x and the errors are consistent between browsers now, so this won't be confusing us anymore.
