### ISSUE TITLE
openpgp.encrypt with AES_GCM (aead_protect) = true) on Edge fails with error: 870000b

### ISSUE THREAD

**Issue by jameseggers** [openpgpjs/openpgpjs#624]
Hey, 

When encrypting a string or file with OpenPGP.js on Edge 15/16 with AWS-GCM (aead_protect = on), I continually receive the error `Error encrypting message: Could not complete the operation due to error 8070000b`. However when I disable the flag, it works.

I have done a fair bit of research and found the same error cropping up [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7919579/), but am not 100% sure they're related since from what I have read openpgpjs is supposed to work fine on Edge.

Here's the code I'm using to encrypt:

```
       const options = {
          data: "xxxxx",
          publicKeys: publicKeys
        }
        openpgp.encrypt(options).then(function (ciphertext) {
           console.log(ciphertext.data)
        })
```
It's happening on version 2.6.2 and others I have tried, the same code works fine on Chrome/Safari/Firefox

**Comment by tomholub** [comment]
Which version of OpenPGP.js is that?

**Comment by jameseggers** [comment]
@tomholub 2.6.2, I have tried a lot of other versions too with the same problem :(

**Comment by jameseggers** [comment]
@tomholub narrowed it down to `aead_protect = on` being the issue, updated issue above

**Comment by mahrud** [comment]
Probably not the case, but try setting `openpgp.config.use_native=false`. If this used to work but just started failing, it may be related to #627.

**Comment by jameseggers** [comment]
@mahrud will give that a try, thanks :)

**Comment by twiss** [comment]
This should be fixed in the latest version :)

**Comment by jameseggers** [comment]
@twiss thanks!
