### ISSUE TITLE
ripe-md.js is GPL

### ISSUE THREAD

**Issue by wmhilton** [openpgpjs/openpgpjs#625]
[`src/crypto/hash/ripe-md.js`](https://github.com/openpgpjs/openpgpjs/blob/master/src/crypto/hash/ripe-md.js) is licensed under the GPLv2 not the LGPL. The discrepancy was detected by an automated tool (fossa.io) while scanning one of my own projects.

**Comment by bartbutler** [comment]
Thanks, replaced it with an MIT-license library.
