### ISSUE TITLE
ESLint cleanups

### ISSUE THREAD

**Issue by mahrud** [openpgpjs/openpgpjs#633]
Towards the end of the `.eslintrc.js` file, there are a few ESLint rules that I had to silence because either:
- fixing the issue was easy but the resulting diff would be huge;
- the problem was in a module that we borrowed from somewhere else (e.g. `des.js`);
- took too much effort!
https://github.com/openpgpjs/openpgpjs/blob/fa208e8308ce3c0cec1c99bec60799a97768b055/.eslintrc.js#L351-L361

Just a nice place to start cleaning up stuff.

**Comment by chesnokovilya** [comment]
Closing this as semi-fixed.
