### ISSUE TITLE
Does not support Windows EOL

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [openpgpjs/openpgpjs#636]
https://github.com/openpgpjs/openpgpjs/blob/a57d94072cfbf6e2dd9074a11e315ae34a39b969/src/encoding/armor.js#L44

I have generated my keys with GNUPGP_WIN32_CLI that on Windows add CRLF as line endings which will crash on `Unknown ASCII armor type` due to the strict regex.

I have converted the EOL to LF, but maybe it is an issue you would like to know about.

**Comment by bartbutler** [comment]
Can you provide the public key you were having trouble with for debugging? This should not be an issues as all newlines should be standardized to LF before that step during 'dearmor' calls:

https://github.com/openpgpjs/openpgpjs/blob/a57d94072cfbf6e2dd9074a11e315ae34a39b969/src/encoding/armor.js#L268

**Comment by bartbutler** [comment]
Can you a public key to reproduce the problem? I have not been able to reproduce.

**Comment by alesmenzelsocialbakers** [comment]
Yes. Here you go:
(Just  generated new test keys - had to change the extension to .txt so it could be uploaded to github)

[testPub.txt](https://github.com/openpgpjs/openpgpjs/files/1736062/testPub.txt)

**Comment by bartbutler** [comment]
Thanks! I'll give it a try.

**Comment by twiss** [comment]
That file is encoded as UTF-16 with a Byte Order Mark. In Node.js, the following works for me:

```js
openpgp.key.readArmored(fs.readFileSync('testPub.txt', 'utf16le').replace(/^\uFEFF/, ''))
```
