### ISSUE TITLE
Error generating keypair

### ISSUE THREAD

**Issue by Dinfyru** [openpgpjs/openpgpjs#638]
safari error generating keypair: the operation is not supported.
openpgpjs v2.5.13
safari 11.0.3

**Comment by bartbutler** [comment]
Can you provide the parameters you used for key generation? Safari has issues with generating keys with < 2048 bytes.

**Comment by Dinfyru** [comment]
```
openpgp.generateKey({
      userIds: [{ name: 'test', email: 'test'}],
      numBits: 2048,
      passphrase
})
```

**Comment by Dinfyru** [comment]
This error only in web worker.

**Comment by Dinfyru** [comment]
When upgrade openpgp to 2.6.2, i have new error in safari
```
Unhandled promise rejection – TypeError: Attempted to assign to readonly property.
```

**Comment by Dinfyru** [comment]
error on:
```
function generate(options) {
  var secretKeyPacket, secretSubkeyPacket;
  return Promise.resolve().then(function () {
    options.keyType = options.keyType || _enums2.default.publicKey.rsa_encrypt_sign;
    if (options.keyType !== _enums2.default.publicKey.rsa_encrypt_sign) {
      // RSA Encrypt-Only and RSA Sign-Only are deprecated and SHOULD NOT be generated
      throw new Error('Only RSA Encrypt or Sign supported');
    }
   ...
}
```
on this line `options.keyType = options.keyType || _enums2.default.publicKey.rsa_encrypt_sign;`

**Comment by bartbutler** [comment]
Hmmm, so you have 'use_native' off in your configuration?

**Comment by Dinfyru** [comment]
Error, when i running this code
```
        const contentBlock = htmlToDraft(sanitizeHtml(this.wysiwygHtml.value, sanitizeRules));
        const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
        const newEditorState = EditorState.createWithContent(contentState);
        this.onEditorStateChange(newEditorState);
```

**Comment by Dinfyru** [comment]
i don't disable 'use_native';

**Comment by Dinfyru** [comment]
But it helped for me in safari. As i know, safari is supporting native crypto.

**Comment by Dinfyru** [comment]
I use self made web worker (not openpgp worker).

**Comment by Dinfyru** [comment]
error on this line: (in generate function => generateSecretKey function)
`return secretKeyPacket.generate(options.numBits)`

**Comment by Dinfyru** [comment]
@bartbutler plz update it for this situation.

**Comment by bartbutler** [comment]
Strange, it works in all the tests with Safari 11. We can change that though.

**Comment by bartbutler** [comment]
I reordered the file a bit so that 'webkitSubtle' should never be accessed if 'subtle' exists. Anyway, all the tests already ran on Safari 11, so I could never reproduce your issue. You could try the master branch and see if it helps.

**Comment by Dinfyru** [comment]
The error was with the "use strict" setting. Your commit helped for me.

**Comment by bartbutler** [comment]
Hmmm, okay. Glad it is fixed.
