### ISSUE TITLE
Skipped test in test/crypto.js

### ISSUE THREAD

**Issue by MaximilianKrambach** [openpgpjs/openpgpjs#646]
There is a test that is marked to be skipped (["asmCrypto AES without OpenPGP CFB resync"](https://github.com/openpgpjs/openpgpjs/blob/master/test/crypto/crypto.js#L339-L344)), remaining as "pending" eternally on `grunt browsertest`. 

Is there any information why this test is skipped? (Apart from "Test fails if run")

I still don't know a lot about the background of the different  crypthographic methods, so it is not apparent to me why this test should not be done (anymore?).

**Comment by bartbutler** [comment]
Thanks for the report. Yeah, the test was just to test the binary equivalence of the main AES library to the 'old' AES method. It apparently never worked and was forgotten. I fixed in the master branch and re-enabled it. Thanks!
