### ISSUE TITLE
Importing keys to GNUPGP

### ISSUE THREAD

**Issue by shinmantis** [openpgpjs/openpgpjs#653]
Hello, I am trying import keys generated by openpgpjs (specifically the public key) using GNUPGP.  Ultimately I would like to use PHP's GNUPG module to encrypt messages server side.  My problem is from the CLI GNUPGP will not import the openpgp generated public key to the key ring.  I can import GNUPGP keys just fine into openpgp but not the other way around.  The error I get is, 

"gpg: no valid OpenPGP data found."
"gpg: Total number processed: 0"

I've attached the GNU Public key and the Openpgp generated public key for reference.

Could this be a key output formatting issue?  Any help would be greatly appreciated.

[pubkey_gpg.txt](https://github.com/openpgpjs/openpgpjs/files/1754703/pubkey_gpg.txt)
[pubkey.txt](https://github.com/openpgpjs/openpgpjs/files/1754704/pubkey.txt)

**Comment by sanjanarajan** [comment]
I was able to successfully import both keys into the latest version of GPG in the command line (2.2.5). Could you share which GPG version and command you are using?

**Comment by shinmantis** [comment]
I am using 2.2.4 under OSX EL Capitan.  I just downloaded 2.2.5 and I still get the same error with the pubkey.txt (openpgp) version.  pubkey_gpg.txt (GNUPGP) imports just fine.  They are in the same folder location.

**Comment by shinmantis** [comment]
I tried using GNUPG on ubuntu (which comes pre-installed) to be certain there wasn't an issue in the OSX installation andI still get the same error.  Sanjanarajan, are you using a different command or flag option to successfully import the openpgp version into the GNU?

**Comment by mahrud** [comment]
@shinmantis I also can successfully import it:
```
[mahrud@galois ~]$ /usr/bin/gpg --import pubkey_gpg.txt 
gpg: key E382745A: public key "mikey <mikey@mikey.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
[mahrud@galois ~]$ /usr/bin/gpg2 --import pubkey_gpg.txt 
gpg: key BEA79117E382745A: public key "mikey <mikey@mikey.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
Can you make a gist of the output of `cat pubkey_gpg.txt | gpg2 --list-packets` please?

**Comment by shinmantis** [comment]
Hello Mahrud, here is the  gist

https://gist.github.com/shinmantis/603b4cf42c04ed76bf75e0decaca5747

**Comment by shinmantis** [comment]
Just to be clear, my problem is with importing pubkey.txt (generated from openpgp.js) not pubkey_gpg.txt (generated from gnupg).

**Comment by mahrud** [comment]
Ahh, sorry I didn't read. Then I can confirm the problem.

**Comment by sanjanarajan** [comment]
Could you try after removing the newline at the bottom of the file?

**Comment by mahrud** [comment]
I don't think the new line makes a difference with `--list-packets`. I also tried removing windows ascii characters.

**Comment by shinmantis** [comment]
I have tried removing the new line at the bottom of the pubkey.txt file as well with no success.  GNUPG complains of no valid OpenPGP data.

**Comment by shinmantis** [comment]
@sanjanarajan can you upload the "modified" pubkey.txt file so I can see specifically what you're modifying?  I can't seem to get to your same result removing the new line at the bottom of mine.

**Comment by sanjanarajan** [comment]
[pubkey.txt](https://github.com/openpgpjs/openpgpjs/files/1760159/pubkey.txt)

From a diff between this and the original, @mahrud and I found that the original file has three extra bytes at the beginning (a byte order mark) which is probably causing the issue.

**Comment by shinmantis** [comment]
Saving the file with encoding UTF-8 (no BOM) solved the problem. As a matter of fact, the last two new lines at the bottom of the txt aren't the issue and don't affect importing the file.  Thank you so much @sanjanarajan and @mahrud for helping me with this.

**Comment by sanjanarajan** [comment]
Glad to hear it's working!
