### ISSUE TITLE
Decryption - file content - No symmetrically encrypted session key packet found

### ISSUE THREAD

**Issue by mersed** [openpgpjs/openpgpjs#655]
I am trying to decrypt content of file based on the examples in documentation:

```
let text = require('fs').readFileSync('someKindOfFile.csv');

let options = {
    message: openpgp.message.fromBinary(text),
    password: 'password1234'
};

openpgp.decrypt(options).then(function(plaintext) {
	console.log(plaintext.data);
        return plaintext.data;
});

```
File is encrypted using password. For example above I am getting following error message: "**Unhandled promise rejection (rejection id: 1): Error: Error decrypting message: No symmetrically encrypted session key packet found**".

Not sure am I missing something, or do I need to provide additional parameters?

**Comment by bartbutler** [comment]
openpgp.message.fromBinary is a function to make an unencrypted OpenPGP message object from raw data. It's not the right function for reading an already-encrypted file. Use openpgp.message.read() for binary, openpgp.message.readArmored() for armored.

**Comment by mersed** [comment]
Just wanted to confirm that things are working.

Additionally, adding explanation why it was not working in my case. Before posting a question, i used read and readArmored as well and was not working.

Issue in my case was related with the file by itself. Before encryption I am programatically connecting via sftp and downloading file on my side. During read/write stream encoding was wrong (comparing with original file), hence during the download process encoding messed up original pgp file causing for decryption process to fail.

**Comment by bartbutler** [comment]
Glad to hear it is working and the problem is understood.

**Comment by lfern** [comment]
Take a look here #849

**Comment by electblake** [comment]
@mersed I'm pretty sure I'm experiencing the same issue re: working with sftp.

What did you end up doing on the sftp.get side? encoding?

**Comment by mersed** [comment]
> @mersed I'm pretty sure I'm experiencing the same issue re: working with sftp.
> 
> What did you end up doing on the sftp.get side? encoding?

I dont recall 100%, having in mind that this was posted 3 years ago, and I already moved to another company (dont have access to the old repo to check this for you). However, I remember that, it was the issue with encoding during file download.

If you are downloading file using some kind of sftp client, you should have possibility to specify encoding while writing stream. Try to check/play research those values against pgp and you should find solution.
