### ISSUE TITLE
web worker user facing errors

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#656]
Following from #604 and #590

We have an error log that logs exceptions on user device. I asked the user to send it and this is what I got:
```
Error: Unhandled error in openpgp worker: Uncaught (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.worker.js:23)
at Worker.AsyncProxy.worker.onerror (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:21518:11)
```
Not useful! :)

I will look into getting a reasonable stack trace from web worker errors on Chrome and Firefox.

**Comment by bartbutler** [comment]
Ask the user to dump a property on the Error object called 'workerStack':

https://github.com/openpgpjs/openpgpjs/blob/master/src/worker/async_proxy.js#L69
