### ISSUE TITLE
readSignedContent should also accept uint8

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#657]
Here
https://github.com/openpgpjs/openpgpjs/blob/5fac00eddbb3c8056386731ed7fd3c9268197f27/src/message.js#L623

As API user, we have to first convert our uint8 `content` to a str, then call `readSignedContent`, just to see it converted back to uint8 here:

https://github.com/openpgpjs/openpgpjs/blob/5fac00eddbb3c8056386731ed7fd3c9268197f27/src/message.js#L625

The function should check if `content instanceof Uint8Array` and only convert if needed. I would do the same for `detachedSignature` to keep it convenient.

As it is now, it will fail with **str2Uint8Array: Data must be in the form of a string**

**Comment by bartbutler** [comment]
Hi Tom,

I'm not entirely sure of your use case but after playing around with this function I realized that it duplicates functionality of fromText and fromBinary and didn't do a UTF8 conversion, which while it was documented correctly, could be confusing. I think that the function is too complex and should be removed.

I have replaced it with an 'appendSignature' function which now can take either an armored or Uint8Array signature.

So the procedure would be to use fromText or fromBinary as is appropriate for your data, call appendSignature, and then verify. You can also just call verify directly with the signature unless you have a real need to combine the data and signature together.

Let me know if this breaks your workflow in some way.

https://github.com/openpgpjs/openpgpjs/commit/20a0e76998e964e10811efb2e163a2a390c2ea73

**Comment by tomholub** [comment]
That is quite ok with me, and the docs looks quite clear - sounds good.
