### ISSUE TITLE
Request: Project Review Session

### ISSUE THREAD

**Issue by PCSmith** [openpgpjs/openpgpjs#658]
Hello,

I hit the openpgpjs twitter account a couple times but I'm not sure anyone is monitoring it so forgive me for trying here. I am getting close to a first prod release on a project I've been working on for a while. Would it be possible @bartbutler to do a quick screen share session to go over what I've done to make sure I've implemented this project securely as well as to get a couple recommendations from you in real time?

Thanks! <3

**Comment by bartbutler** [comment]
My apologies, I have been pretty terrible at checking the openpgpjs Twitter account--I plan to change this soon in the run up to release of version 3. While I can't commit a lot of time I'd be happy to chat with you a bit. You can DM me on my personal Twitter handle @BartCButler and we'll schedule something.

**Comment by PCSmith** [comment]
Done. Thank you!
