### ISSUE TITLE
await won't work in demo

### ISSUE THREAD

**Issue by Andrewyg** [openpgpjs/openpgpjs#664]
I've copy the demo for signing detached signature as following:

var privKeyObj = openpgp.key.readArmored(privkey).keys[0];
await privKeyObj.decrypt(passphrase);

```
options = {
    data: 'Hello, World!',                             // input as String (or Uint8Array)
    privateKeys: [privKeyObj],                         // for signing
    detached: true
};

openpgp.sign(options).then(function(signed) {
    detachedSig = signed.signature;
});
```

But as I run it comes the following error:

```
await privKeyObj.decrypt(passphrase);
      ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

And I've look up stackoverflow and I came up with [this](https://stackoverflow.com/questions/42225480/await-unexpected-identifier-on-node-js-7-5) answer which said `await` can only be used in `async`, but I still don't know how to solve it?

Who can help me out?

**Comment by bartbutler** [comment]
Await is ES7 syntax. If you are not running in an ES7-compatible
environment then you can use Babel to convert your code OR just chain
promises ES6-style. Let me know if that isn't clear.

**Comment by Andrewyg** [comment]
@bartbutler  But why ES7 isn't supported if I'm using latest NodeJS (`v8.9.3`)?

**Comment by bartbutler** [comment]
@Andrewyg I don't know (also, I was mistaken, async/await is ES8, not ES7) it should be supported according to this chart:

http://node.green/

If you just need it to work I suggest babel or using promises.

**Comment by mahrud** [comment]
@Andrewyg short answer: use `privKeyObj.decrypt(passphrase).then(() => { ... })`.

Long answer: Node.js supports `await` inside `async` functions, but the core developers can't make up their mind on whether they want to allow `await` in REPL or not. Last I checked, they added this, then they reverted it, and I think now they have it in v10.
There are various tricks to fix it, google "node await repl". Also in modern browser consoles await works out of the box.
