### ISSUE TITLE
Slim version for key generation only

### ISSUE THREAD

**Issue by alecpl** [openpgpjs/openpgpjs#665]
Roundcube Webmail's Enigma plugin uses openpgpjs for key pair generation only. Now, when v3 is 2 times bigger than v2 I'd like to ask if it would be possible that you provide a separate version of the library for key generation purposes? How much smaller in size that could be?

**Comment by mahrud** [comment]
I think making the library tree-shake-able is somewhere on the TODO list. But for now:
### Easy solution:
Modify `src/index.js` to only have one line:
```
export { default as crypto } from './crypto';
```
Then browserify and uglify this to get a ~356KB bundle and use [`openpgp.crypto.generateParams`](https://openpgpjs.org/openpgpjs/doc/module-crypto_crypto.html#.generateParams).

### Optimized solution:
Modify `src/index.js` to only have one line:
```
export { default as public_key } from './crypto/public_key';
```
Modify `src/crypto/public_key/index.js` to be:
```
import rsa from './rsa';
import elliptic from './elliptic';
export default { rsa, elliptic };
```
Modify `src/crypto/public_key/elliptic/index.js` to be:
```
import Curve, { generate } from './curves';
export default { Curve, generate };
```
Now browserify and uglify to get a ~208KB bundle and just replicate what the [`generateParams`](https://openpgpjs.org/openpgpjs/doc/crypto_crypto.js.html#line263) function does in your code.

**Comment by apecranium** [comment]
Is this still a todo item? I'm also interested in this feature, specifically just the encrypt feature. I attempted to follow the instructions above, but my savings were minimal. I could very well be doing something wrong.

**Comment by chesnokovilya** [comment]
This could be fixed in v5. See https://github.com/openpgpjs/openpgpjs/issues/547
