### ISSUE TITLE
Change passphrase from Privatkey on openpgp.js 3.0.x 

### ISSUE THREAD

**Issue by stastka** [openpgpjs/openpgpjs#667]
I try to change passphrase from a PrivateKey. I have solution from openpgp.js 2.6.x [https://github.com/whiteout-io/mail/blob/69387508036ccc443a5cc2f33730ce162c556536/src/js/crypto/pgp.js#L238-L259](url) but does'nt work on 3.0.x.

I found that some function changed: clearPrivateMPIs() to clearPrivateParams() and getAllKeyPackets() to getKeyPackets(), but if I encrypt the subkey and make after then clearPrivateParams() I have error:

Error: If secret key is not encrypted, clearing private params is irreversible.

Dany

**Comment by sanjanarajan** [comment]
The secret key packet encryption function is now an `async` function that returns a Promise (https://github.com/openpgpjs/openpgpjs/blob/master/src/packet/secret_key.js#L182). This means that you need to `await` the result of the packet encryption before attempting to clear the private params. See https://javascript.info/async-await for more information. 

But it looks like what you are doing on lines 252 - 255 is just duplicating the functionality of the Key.prototype.encrypt function (https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L347) so I recommend that you use that instead. Note that this is also an `async` function.

**Comment by stastka** [comment]
Thank you for the hint. I have successfull changed my passphrase from PK.

**Comment by sanjanarajan** [comment]
Glad to hear it :)
