### ISSUE TITLE
Binary gpg2 compatible non-detached output

### ISSUE THREAD

**Issue by ummjackson** [openpgpjs/openpgpjs#676]
Hi there, 

I'm trying to generate a base64 formatted binary output that would match the output of `echo -n "email@test.com" | gpg2 --sign | base64` 

Using the code below, I'm able to output the *signature itself* correctly but it's detached from the message. Running it back through gpg2 it asks for the filename because it's detached. How can I get the code below to output not just the signature but the attached message in binary format?

Appreciate any help.

```
options = {
    data: 'email@test.com',
    privateKeys: privKeyObj,
    armor: false
};

openpgp.sign(options).then(signedData => {
    console.log(Buffer.from(signedData.message.signature.packets.write()).toString('base64'));
});
```

**Comment by ummjackson** [comment]
Ended up figuring this out myself... to get the message + signature together you can't use the code above because it exports in clearText and you just get the detached signature. 

The code below works: 

```
    message = openpgp.message.fromText('email@test.com');

    message.sign([privKeyObj]).then(signedMessage => {
    	console.log(Buffer.from(signedMessage.packets.write()).toString('base64'));
    });
```

**Comment by bartbutler** [comment]
You could also use the high-level API (openpgp.sign) to get the binary detached signature, make a literal data packet with your message:

```
const literalDataPacket = new packet.Literal();
literalDataPacket.setText(text);
```

and then use write() to get the bytes and concatenate it with the signature bytes. It's not particularly clean though.

**Comment by ummjackson** [comment]
Thanks @bartbutler! The solution I landed on ended up being clean enough and seems to work for now... I do recommend the documentation is improved a little to make this more obvious. Can imagine getting the signed message in binary form is a common use case.

**Comment by bartbutler** [comment]
TBH, you're the first I can remember. Most use cases for signing, text or binary, want the data either human-readable in the case of text or usable separate from the signature, in the case of files, so that PGP-ignorant applications and users can still use the data.
