### ISSUE TITLE
Default key expiration 'never'

### ISSUE THREAD

**Issue by MaximilianKrambach** [openpgpjs/openpgpjs#681]
Some confusion about key expiration may soon surface in projects as mailvelope, as I am implementing a javascript API for native gnupg (using nativeMessaging).

*openpgpjs*: keyExpirationTime is set to 0 means "never expire".

*gnupg*: setting/leaving the expiration time at 0  results in ' a reasonable expiration time is chosen', unless explicitly stated that the key does not expire.

**Is the 'never expire' in openpgpjs a default value that was willingly chosen?**

Example for confusion/issues with eternal keys:  https://github.com/mailvelope/mailvelope/issues/545

**Comment by tomholub** [comment]
My two cents, I would say the confusion should be cleared up by UI/UX designers, not at OpenPGP.js API level. I think it's reasonable to assume that if no expiration is provided to the library, key should not expire.

Software that uses OpenPGP.js is free to choose a "reasonable default" as it sees fit, not at the library level - too much magic imho.

**Comment by bartbutler** [comment]
I agree @tomholub . 0 meaning never expire is significantly more logical than 'reasonable expiration time' as well.

**Comment by sanjanarajan** [comment]
RFC 4880 defines a key expiration time of 0 to mean "never expire":

```
5.2.3.6.  Key Expiration Time

   (4-octet time field)

   The validity period of the key.  This is the number of seconds after
   the key creation time that the key expires.  If this is not present
   or has a value of zero, the key never expires. 
```

**Comment by MaximilianKrambach** [comment]
Okay, thank you for the clarification.

(one side note: RFC 4880 only talks about how the expiration date is represented, not which expiration to set on key generation, which is left undefined)
