### ISSUE TITLE
Browser matrix should only show master builds

### ISSUE THREAD

**Issue by KAYLukas** [openpgpjs/openpgpjs#682]
The browser matrix is always showing the latest test that have been done. So as of now, the npm page says that all browsers fail. 

![screen shot 2018-04-09 at 09 57 37](https://user-images.githubusercontent.com/1674504/38486261-c13cf50a-3bdc-11e8-940a-45a2a09bf9a3.png)

We should fix this by creating a different saucelabs account for non master branches.

See also:
https://github.com/canjs/canjs/issues/3134

**Comment by chesnokovilya** [comment]
fixed by #965
