### ISSUE TITLE
Encryption in Firefox tampermonkey crashes

### ISSUE THREAD

**Issue by Muph0** [openpgpjs/openpgpjs#686]
When encrypting string with generated/imported keys, [this userscript](https://pastebin.com/9rpCUv0i) run in Firefox tampermonkey crashes with error

```
Error: Error encrypting message: Could not
find valid key packet for signing in key d713ea674b8e4752
``` 

suggesting that the key is expired, even if the key is newly generated.

However, the same code run in client code works alright. [(see this jsfiddle)](https://jsfiddle.net/toLf6hxh/28/)
I have also tested it in Chrome tampermonkey and the script runs ok. Probably a bug?

**Comment by twiss** [comment]
`window.Symbol` doesn't seem to be available in tampermonkey userscripts. If you set `window.Symbol = unsafeWindow.Symbol` *before* you load openpgp.js, it works.
