### ISSUE TITLE
Is this project's crypto affected by javascripts double implementation?

### ISSUE THREAD

**Issue by tweidinger** [openpgpjs/openpgpjs#689]
Hey, after reading on twitter about problems in Javascripts double implementation I was wondering if this could affect crypto used by this library? (Like are there custom datatypes made for this?)
https://twitter.com/b0rk/status/986424989648936960

![dbb8tm_waaey1mv](https://user-images.githubusercontent.com/28728469/39078135-72138032-4507-11e8-965b-cf66a97c4bc1.jpg)

**Comment by bartbutler** [comment]
Among other reasons, the imprecision of floating point types mean that they don't work for crypto--crypto is done exclusively with integers, and we have specific 'big integer' libraries for use with crypto. Thanks for the question though!
