### ISSUE TITLE
compressjs dependency

### ISSUE THREAD

**Issue by simevo** [openpgpjs/openpgpjs#695]
Him I noticed that you are using a forked compressjs.
Why don't you push your enhancements as PR to [cscott/compressjs](https://github.com/cscott/compressjs) ? You would then be able to depend from `cscott/compressjs` rather than `github:openpgpjs/compressjs` which is cleaner.

**Comment by dkg** [comment]
can you explain what "tree-shakable" means?  how is it a major refactor  of compressjs to move the transpiling stuff into OpenPGP.js directly, while using upstream compressjs?

**Comment by bartbutler** [comment]
I didn't do the work so forgive me if I'm fuzzy on the details of why it was done this way.

Tree-shaking is when you can do `require('compressjs.bzip2')` to import only the bzip2 module into your project and leave the rest of the package out. My impression was that compressjs is not set up for that--it just has a monolithic build script which bundled all algorithms into a JS file. The fork was to modify the build process to be able to only select bzip2. Making it tree-shakable would have been better but would have been a bigger refactor of the library.

**Comment by simevo** [comment]
Tree shaking is also something webpack shines: https://webpack.js.org/guides/tree-shaking/
Would moving from browserify to webpack ease this type of optimization ?

**Comment by chesnokovilya** [comment]
closed by #798
