### ISSUE TITLE
Stop using strings as byte vectors

### ISSUE THREAD

**Issue by dreamingofelectricsheep** [openpgpjs/openpgpjs#71]
Currently the native javascript strings are used everywhere as vectors of bytes. This isn't the best idea, considering that we have Uint8Array available. How about refactoring the codebase to use something like this:

```javascript
openpgp_bytearray = Uint8Array == undefined ? Array : Uint8Array;

var bytes = new openpgp_bytearray(128);
bytes[10] = 16;
```

It would make it explicit when byte arrays are used and get rid of all the ```String.fromCharCode``` littering the codebase.

Does anyone have issues with this?

**Comment by tanx** [comment]
v2.x uses all Uint8Arrays internally
