### ISSUE TITLE
Bug: Unable to verify signed message synchronously

### ISSUE THREAD

**Issue by openpgpjsUser** [openpgpjs/openpgpjs#711]
**Example of Asynchronous Verify**
`openpgp.verify(options).then(function(verified) {
    validity = verified.signatures[0].valid; // true
    if (validity) {
        console.log('signed by key id ' + verified.signatures[0].keyid.toHex());
    }
});`

Most people probably want an ability to return the result synchronously. Currently there is no way to do that. Man functions can utilize await to turn synchronously. An example in the doc is:

`ciphertext = await openpgp.encrypt(options)`

However, this same pattern cannot be used with signature verification. For example:

`verified = await openpgp.verify(options)`

**The above will throw a browser error.**

**Comment by sanjanarajan** [comment]
Yes, as these functions are asynchronous, the only way to simulate synchronous behavior is using `await` as you described. This should work for verify as well - see this example in the test suite: https://github.com/openpgpjs/openpgpjs/blob/master/test/general/brainpool.js#L178
