### ISSUE TITLE
Encrypt and decrypt Uint8Array data with a password

### ISSUE THREAD

**Issue by rushglen** [openpgpjs/openpgpjs#713]
Not really an issue, more like a question!

Is "Encrypt and decrypt Uint8Array data with a password" using AES 256 by default?

(I searched the documentation and google etc but could not find an answer)

and a big thank you to everyone who has helped put this incredible library together.

**Comment by sanjanarajan** [comment]
Yes, encryption uses AES256 by default (see https://github.com/openpgpjs/openpgpjs/blob/master/src/packet/sym_encrypted_session_key.js#L55) and decryption will use whatever session key algorithm was used to encrypt the packet.

**Comment by rushglen** [comment]
Thank you.

**Comment by ZelphirKaltstahl** [comment]
I've been wondering about this for a few hours. _"Where do I specify AES 256 then?"_, _"Where do I specify the decryption algorithm at all?!"_ and similar questions.
This should be mentioned in the examples in the readme. I created a pull request to put the info there.
