### ISSUE TITLE
Get install error when use npm i openpgp at windows

### ISSUE THREAD

**Issue by QTGate** [openpgpjs/openpgpjs#717]
Hi I got error when I install openpgp with NPM at windows.

```
C:\Users\User>npm -v
6.1.0

C:\Users\User>npm i openpgp
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/openpgpjs/compressjs.git

npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```
Thanks.

Peter

**Comment by QTGate** [comment]
Hi
Could you guys make this project's install easy and no need git installed.
Because we looks need face to how to install Git to Android when we try develop our project to Android.
Peter

**Comment by tomholub** [comment]
Download it as a zip then: https://github.com/openpgpjs/openpgpjs/archive/master.zip

**Comment by tomholub** [comment]
This issue could be closed
