### ISSUE TITLE
Help needed. OpenPGP-PHP and openpgpjs

### ISSUE THREAD

**Issue by veldjmaxis** [openpgpjs/openpgpjs#721]
HI,
I'm trying to use key generated by openpgp-php lib, for ex.
`-----BEGIN PGP PUBLIC KEY BLOCK-----

xv8AAAENBFswnYwBCACt/8Mv8kNCP3UAtHT5FSIOdFpqQqQeJbSf8WgAeY2fCEQQ9rOEXy0lcpOUnfvM+wv6hHXhcq4lm6QaYGuAgRUbu97dSt460s5U4nqWfJgF1i+ZMOXBLQvOiSiYwLeodWtOoltbS9mwSbvhPCKvZlpTbydzpLMMdFTSuefhFlgKygq9XfyjW1NSnn4K2D3tjnAmB0E+65ookMSwCBSuQ7uM8fzTEOkRtDjiKxzaYxLCYG51alb9jJ8J5JtcYWZbpX2xXjjXk7cUvGqsFJoeKjC9qT2+ikaG1DtqVv/jGGQbtqK0WaFh2NYkhW0n/p2eI8GVBahdHoat6XoB+SE+LpGfABEBAAHN/wAAABloT25lIDxhc2RqYXNkQGFzZGFzZC5jb20+wv8AAAErBBMBCAAf/wAAAAUCWzCdjP8AAAACGwP/AAAACRBUqXh4JqE9vwAAXqsH/16r3THbfxtuwEP3I3Clg3iyHLdJy0x0szSOMR6ix1JJ/yCUMaG2s3jAj2cs+XfzAqQ+grhMEFs3icJ45ovow+ZnYVnEu4/yN8L4IxGMSh9px5rtQlgTC+Ona8dGp3M6ek5IMEHqIsRg4wQAbm9kNNRi6asZjnud3gR6KzWG2CU1JEFkN0Vu3q28ZVv3Pv/sJeQvntx4ceA3l5cWsStyL1WSSi5WrZCAXsIIfEYueKfMkiqW/LJ7nGicvkued9wP+HTEY3o5W/9UiIRaugpuiKaoFN6EmPmA2B9FU10tyIyZb2YHh0bnsnHxgreJI6qKefNOM5XU9PjfD4ofbZaK9qk=
=z15j
-----END PGP PUBLIC KEY BLOCK-----`

When I'm trying to encrypt message I'm getting
`Error encrypting message: Could not find valid key packet for encryption in key`

What I saw is that, generated key doesn't have any subkey. It might be the reason? Is there any workaround for that?

**Comment by sanjanarajan** [comment]
As you mentioned, this key does not have a subkey, and the primary key's flags indicate that it can only be used to certify other keys and sign data (not encrypt). 

If you need a key for encryption, you should generate a key with an encryption subkey (if you use the default options in this library's `openpgp.generateKey` you will get a key with an encryption-enabled subkey.)

Unfortunately, to add a subkey to an existing primary key is not that simple - you will need to generate a new subkey packet (see https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L1168) and then use `wrapKeyObject` to create a key containing your existing primary key and new subkey.

**Comment by veldjmaxis** [comment]
Thanks for respond,
I generated new key (In theory with subkey and encryption enabled) using openpgp-php lib (https://github.com/singpolyma/openpgp-php).

`-----BEGIN PGP PUBLIC KEY BLOCK-----

xv8AAAENBFswzSgBCADAdtlkiS9jv5V/egLZPg9HYYAzDytKvWqhFaw91EsWwvhC5lCAmU/kc5Je66D9YlMFHfhAxRSsZtO4B0Rlf2VdnFssXl/TOgSgdYaR1YmLtI1jgrN6MgkSAjv9umeLTfQdBh9I7zReR4HXiPNSfx4NwT9jmd9zRWvJBTKTY6isjwmyBNOAZVIncS5ysdQdiD1tpr6h4VmbUoZrUtEG5u4YHnHVZa5go93OumbPJZM805AS0Eres/ROqMRAT2bxO1yrnjvm4vruPTW3B1x7fN1Jp7IMp9/9goCVpWy74UQcMHqiYqgs1NwITnhYGly8DInJNCuPXFE29Ql88ea9fEWbABEBAAHN/wAAABloT25lIDxhc2RqYXNkQGFzZGFzZC5jb20+wv8AAAErBBMBCAAf/wAAAAUCWzDNJ/8AAAACGwP/AAAACRD5MfxPP+B78gAAvO4IALzuYvTolqYmmxng7gV4+f8CiCZ0TB8pzzaRPhvR78tqX4NNYLOabQcczNptgli84z+FU+bNic0oMM9j+AF9ADD9xaGQqW95jBTFbHuhmR1vBTG0OIJMDFlpcSsdTKxewH8UxlMM26RKbCugYkc7aemIDQj09Ev76di/bLcgEpzsBdTBA2/PjcmaPZIQj/J5BVuuFDWz6BSFjp+EDPOXLOp23+C6M87/mvOJaWVQBMxEKmur4j9y0+t6y4VnDyl6RIJAEmrfNLj0aHf3hWp5i/R4G7JhG2tvuocRo6309JLwtrLq49ArEbR9USMuCLxLMbCzvWiaUahegb2mLL5i8mDO/wAAAQ0EWzDNKAEIANiCA1wxoZai3DMCL3GoytTEHMLx2+FSHn6kA0jOqMfaR7H9ReiIhvKV6e4UL1vs5Q/Af4aRNUETLsu7G6eQTelnVrMjR/JrAy/+yHoHJ1xcO4qqEPw6TM+V5do5NMX1CMz0bFOpsfE+yhpFHV82NabuAJ2EOnU/XPiTN30Qgk//4pWjlMWH53Ayz8SBSAH0ufaLbZj4MiUsXmJR08KhouP5y7T97jJBuO5Eof3pBrKgh0rmSYa2mvKIaI5EsSusD8zo3x0XeprIcO2bgdZsKay3eX/Dh4++1pdu+x9X+2LHE2TNSvykJ2Ne0AkEOFkOBaKa0ARIzjmdT2kRDcVLK8MAEQEAAQ==
=5dSr
-----END PGP PUBLIC KEY BLOCK-----`

but now I got error:
`Error encrypting message: Cannot read property 'verified' of undefined
    at Worker.<anonymous>`.

**Comment by sanjanarajan** [comment]
This key is still invalid - it lacks a binding signature from the primary key that indicates that it owns the subkey. See https://tools.ietf.org/html/rfc4880#section-5.2.1

**Comment by sanjanarajan** [comment]
Closing this as it is not an OpenPGP.js bug, but please feel free to reopen if you have any further questions :)
