### ISSUE TITLE
openpgp.generateKey slows/hangs in Edge

### ISSUE THREAD

**Issue by icymaru** [openpgpjs/openpgpjs#722]
I have an Angular 5 app and generateKey execute more than 30 secs in Edge and makes it unresponsive. Chrome and Firefox are ok, which only takes 1-2 secs.

```
    const options = {
      userIds: [{ name: 'username' }],
      numBits: 2048,
      passphrase: '1234567890'
    };
    console.log('start', new Date());
    openpgp.generateKey(options)
      .then(key => {
        console.log('stop', new Date());
        console.log(key);
      });
```

**Comment by sanjanarajan** [comment]
Sorry to hear that :/ 
Are you using the latest version of OpenPGP.js? We have had some reports of this from older versions but they were reported to be resolved in the latest.

**Comment by icymaru** [comment]
might be an Edge issue :(

**Comment by twiss** [comment]
Hi :wave: (Non-Chromium-based) Edge is no longer supported in v5, so I'll close this issue, apologies.
