### ISSUE TITLE
huge strings will cause out of memory errors in util.parseUserId

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#724]
I'm consistently getting out of memory errors when processing one of SKS dump files with `openpgp.key.read`:

http://pgp.key-server.io/dump/current/sks-dump-0155.pgp

This is in Node.

```
<--- Last few GCs --->

[3523:0x3222200]    73337 ms: Mark-sweep 1463.2 (1522.3) -> 1462.7 (1522.8) MB, 1145.4 / 0.0 ms  allocation failure GC in old space requested
[3523:0x3222200]    74436 ms: Mark-sweep 1462.7 (1522.8) -> 1462.6 (1491.8) MB, 1098.6 / 0.0 ms  last resort GC in old space requested
[3523:0x3222200]    75543 ms: Mark-sweep 1462.6 (1491.8) -> 1462.6 (1491.8) MB, 1107.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1bec6fca5501 <JSObject>
    1: findNode(aka findNode) [/home/luke/git/flowcrypt-sks-sponge/node_modules/openpgp/dist/openpgp.js:~17745] [pc=0x1a07ace6d574](this=0xfb211c822d1 <undefined>,name=0x33baba1a31b1 <String[9]: addr-spec>,root=0x33baba1b14d9 <Object map = 0x3970048e2131>)
    2: giveResultMailbox(aka giveResultMailbox) [/home/luke/git/flowcrypt-sks-sponge/node_modules/openpgp/dist/openpgp.js:17858] [bytecode=0x...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x11f155c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0xdf2313 [node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 8: 0x1a07acd042fd
Aborted (core dumped)
```

The other files parse ok. I'm putting it here first to add my notes as I investigate this, if there is a fix needed, we can submit it upstream when we figure it out.

**Comment by twiss** [comment]
`email-addresses` is apparently a dependency of `address-rfc2822`, which we use in `util.parseUserId`.

https://github.com/jackbearheart/email-addresses/blob/6ac72d36d079ccf0f4d02288d7dd44c97f6b4675/lib/email-addresses.js#L31

This function creates a boatload of functions for every parse, that might be the cause.

**Comment by tomholub** [comment]
I did use `util.parseUserId` in my code too - that makes sense. The stack trace didn't make it obvious.

Each of these keydump files had 20k keys in it parsing happily, so there may still be something special about the file it keeps failing on - maybe a super long uid string - looking into it.

**Comment by tomholub** [comment]
Here is the winner:
[too-long-userid.txt](https://github.com/openpgpjs/openpgpjs/files/2151265/too-long-userid.txt)

Parsing this with `util.parseUserId` will cause node OOM. This is a key from sks server containing a 1.4M userid that some kind soul uploaded.

We could do a `userid.length < 5kb` check before attempting to parse it.
