### ISSUE TITLE
a way to get k.getExpirationTime without verifying

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#726]
I would like to be able to process many keys quickly and get expiration time without verifying the sigs, which is slow.

I propose an optional `verify` argument that defaults to true as follows:

```js
Key.prototype.getExpirationTime = async function(verify=true) {
  if (this.primaryKey.version === 3) {
    return getExpirationTime(this.primaryKey);
  }
  if (this.primaryKey.version >= 4) {
    const primaryUser = await this.getPrimaryUser(null, undefined, verify);
    const selfCert = primaryUser.selfCertification;
    const keyExpiry = getExpirationTime(this.primaryKey, selfCert);
    const sigExpiry = selfCert.getExpirationTime();
    return keyExpiry < sigExpiry ? keyExpiry : sigExpiry;
  }
};
```

```js
Key.prototype.getPrimaryUser = async function(date=new Date(), userId={}, verify=true) {
  // ...
  const { user, selfCertification: cert } = primaryUser;
  const { primaryKey } = this;
  const dataToVerify = { userid: user.userId , key: primaryKey };
  // added !verify below
  if (!(!verify || cert.verified || await cert.verify(primaryKey, dataToVerify))) {
    return null;
  }
  // ...
  return primaryUser;
};
```

Would a PR for this be accepted?

**Comment by sanjanarajan** [comment]
I personally don't think something like this is within the scope of the library, as it could cause `Key.prototype.getPrimaryUser` and `Key.prototype.getExpirationTime` to potentially return values that according to the RFC would be completely invalid. For example, it could return an expiration time for the future for a key that cannot even encrypt right now. 

To get the behavior you want, we can export the helper functions `getExpirationTime` and `getLatestSignature` and you can combine them with something like `getExpirationTime(key.primaryKey, getLatestSignature(key.users[key.users.length-1].selfSignatures)` in your implementation. Would that work for you?

**Comment by tomholub** [comment]
Got it. Thanks for the hint, I'll test it.

**Comment by tomholub** [comment]
I would not export them as they seem to technical. I'll just copy/paste them in my code and maintain them if necessary. Thanks again!

**Comment by sanjanarajan** [comment]
No problem :) Keep in mind that if you don't use v3 keys you can already significantly simplify them.
