### ISSUE TITLE
openpgp.key.readArmored not found

### ISSUE THREAD

**Issue by longnp93** [openpgpjs/openpgpjs#727]
I am using openpgp version ^3.0.12 with Create-React-App on Chrome version 67 and Windows 8
I have some issues when I first played around with the library. I follow "Encrypt and decrypt String data with PGP keys" on README: 
- openpgp.key.readArmored function not found
- initiate Worker with error 
Uncaught Error: Unhandled error in openpgp worker: Uncaught SyntaxError: Unexpected token < (http://localhost:3000/openpgp.worker.min.js:1) at Worker.worker.onerror (openpgp.js:51800)
Uncaught SyntaxError: Unexpected token <

I played around by storing the **key** as private key and **key.toPublic()** as public key in callback function after generating key successfully. However when I encrypt the data with 2 keys, no response returns as well as no error.

Hope you can help. Thank you.

**Comment by tomholub** [comment]
Hello, you may need to post larger chunks of your code so that we understand how are you importing the library.

**Comment by longnp93** [comment]
Hi Tom, 
I use Nodejs to install Openpgp as the instruction: npm install --save openpgp
Here is my JS file:
`import {Table, Grid, Button, Form } from 'react-bootstrap';
import React, { Component } from 'react';
import './App.css'; 
import web3 from './web3';
import ipfs from './ipfs';
import storehash from './storehash';
import openpgp from 'openpgp'//'../../node_modules/openpgp';

class App extends Component { 
 constructor(props){
	super(props)
    this.state = {
      privateKey:'',
	  publicKey:'',
	  passphrase :'',
	  key:''
    };
	openpgp.initWorker({ path:'openpgp.worker.js' })
 }
	

encrypt = async(event) => {
	const pubkey = this.state.publicKey;
	const privkey = this.state.privateKey;
	const passphrase = this.state.passphrase;
	var that = this;
	const encryptDecryptFunction = async() => {
		const privKeyObj = openpgp.key.readArmored(privkey).keys[0];// my "customized" way - this.state.key.key;
		privKeyObj.decrypt(passphrase)
		
		const options = {
			data: "my data",                             
			publicKeys: openpgp.key.readArmored(pubkey).keys,  // my "customized" way - this.state.key.key.toPublic(),
			privateKeys: privKeyObj                          
		}
		
		openpgp.encrypt(options).then(ciphertext => {
			// '-----BEGIN PGP MESSAGE ... END PGP MESSAGE-----'
			return ciphertext.data;
		})
		.then(encrypted => {
			const options = {
				message: openpgp.message.readArmored(encrypted),     // parse armored message
				publicKeys: openpgp.key.readArmored(pubkey).keys,    // for verification (optional)
				privateKeys: [privKeyObj]                            // for decryption
			}
			 
			openpgp.decrypt(options).then(plaintext => {
				console.log(plaintext.data)
				return plaintext.data; // 'Hello, World!'
			})
		})
	}
}

generateKey = async (event) => {
	var that = this;
	var options = {
		userIds: [{ name:'Jon Smith', email:'jon@example.com' }], // multiple user IDs
		curve: "ed25519",                                          // ECC curve name
		passphrase: 'super long and hard to guess secret'         // protects the private key
	};
	this.setState({passphrase: options.passphrase});
	openpgp.generateKey(options)
	  .then((key,a,b) => {
		that.setState({privateKey: key.privateKeyArmored});
		that.setState({publicKey: key.publicKeyArmored});
      	that.setState({key: key});
	  })
	  .catch((error) => {
		console.log("Something went wrong on generating key: " + error);
	});
}
render() {
      
      return (
        // HTML code
      );
    } //render
} //App
export default App;`

**Comment by tomholub** [comment]
@longnp93 did this help?

**Comment by twiss** [comment]
See also https://github.com/openpgpjs/openpgpjs/issues/767#issuecomment-419643042.
