### ISSUE TITLE
--sign instead of --clearsign

### ISSUE THREAD

**Issue by tonioknuth** [openpgpjs/openpgpjs#731]
Hi, I am trying to sign an encrypted message, but I am only able to find the options to to clearsign, meaning signing of the cleartext message before encryption and deatached signatures. What I would need is signing the encrypted message, as you would do with pgp --sign. I have already tried just encrypting first and then signing, but then the signature gets lost altogether. Is there something I am missing?

**Comment by tomholub** [comment]
You would pass your private key into the encrypt options. The private key itself has to be decrypted. 

```
  const options = {
        data: 'Hello, World!',                             // input as String (or Uint8Array)
        publicKeys: openpgp.key.readArmored(pubkey).keys,  // for encryption
        privateKeys: [privKeyObj]                          // for signing (optional)
    }
```

**Comment by tonioknuth** [comment]
Works like a charm! Thanks for your help!
