### ISSUE TITLE
git required to install package

### ISSUE THREAD

**Issue by diegolacarta** [openpgpjs/openpgpjs#736]
Is there any chance you could publish compressjs and elliptic to npm to avoid the need for git as a requirement to install this package?

**Comment by tomholub** [comment]
I'd imagine there's an overhead maintaining several npm libraries compared to getting it off git that may not be worth it, unless more people need / request this. Are you using a system that does not make it easy to use git?

**Comment by bartbutler** [comment]
I think the commits are pinned, if they aren't that should be fixed. I think ideally we move all to npm but for several packages we run our own forks so that isn't practical at the moment.

**Comment by Developer-Deep** [comment]
Hi, I'm facing the same issue. I'm trying to configure mailtrain on an architecture that doesn't have public internet access and it stops at trying to install compressjs. Was it published to npm? If not, how could I go about installing it?

**Comment by wiktor-k** [comment]
@Developer-Deep, did you check if #715 would solve your issue?

**Comment by Developer-Deep** [comment]
I did solve it back then by manually downloading it and copy pasting it there, if I remember correctly.
