### ISSUE TITLE
gpg --allow-non-selfsigned-uid equivalent 

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#740]
PR #753

Unfortunately, there are still many pubkeys in use today (mostly coming from Symantec PGP Desktop) that do not have uid self signatures. Naturally, OpenPGP.js is refusing to use these for encryption.

I would like to make a PR that would allow this with a flag. I would like to be able to set an attribute on a `Key` object, eg `requireUidSelfSignature` to `false`. After that, when I do `k.getEncryptionKeyPacket()`, it will return one even if there are no self uid signatures. Same for `k.getPrimaryUser()` etc. This would allow such key to be used in `openpgp.encrypt` and elsewhere.

The flag would have to be set on each key individually, allowing the application know which key requires this and show warnings to the user.

This functionality would allow encrypting for legacy keys. Creation of such keys is deprecated, but using such keys should be possible with a flag / user warning for compatibility reasons. Would a PR for this be accepted?

**Comment by sanjanarajan** [comment]
I looked into this GPG flag a bit, and it's a flag from 1999 that according to GPG's documentation is "not recommended, as a non self-signed user ID is trivial to forge." So it may be worth considering that this is a case where security should trump compatibility. 

About your approach specifically - I don't think it's good idea to add properties to keys that are not preserved through serialization and deserialization. Additionally, your approach would not work with workers with our current method of key cloning. It would require adding hacks into the cloning functions as well.

I think your best option would be to just add a global config flag that allows this (of course, defaulting to false). Let me know what you think :)

**Comment by twiss** [comment]
Additionally, to store the fact that (for example) the owner of `privateKey` believes that `key` belongs to `key.users[0]`, you can do:
```js
await key.users[0].sign(key.primaryKey, [privateKey]);
```
The advantage of that is that you can store that information in the armored key.
It might make sense to require, either in your code or in the library, if you do `openpgp.encrypt({ publicKeys, privateKeys })`, that `publicKeys` have been signed by `privateKeys`.

**Comment by tomholub** [comment]
Thank you both for taking the time to review this.

@twiss If I understood you correctly, you are suggesting we could sign other people's keys with `await someoneElsesKey.users[0].sign(someoneElsesKey.primaryKey, [myOwnPrivateKey])` and have a way to for openpgp library to understand that that makes the other keys trustable, even if that key was missing a self-signature.

> It might make sense to require, either in your code or in the library, if you do openpgp.encrypt({ publicKeys, privateKeys }), that publicKeys have been signed by privateKeys.

Not in the library, or at least not through `openpgp.encrypt({ publicKeys, privateKeys })` because the `privateKeys` option has another meaning - it's meant for signing. What if I want to use such public key, but don't necessarily want to sign the message? Anyway, such requirement would break a whole bunch of people's code - not good.

We could, however, have a way for the library to know our own (ultimately trusted) public keys. I'll try to outline this as `Approach 2` below.

## Approach 1
(inspired by @sanjanarajan)

I could set a global flag as you suggest:
```js
openpgp.config.require_uid_self_signature = true; // defaults to true
```
If I set that to false, I'm able to use the key without self-signatures. Now, for each key I use, I would have to check `k.getPrimaryUser().selfSignatures.length > 1` (plus a few null checks) in order to find out when to show warnings to users. That is workable.

**if require_uid_self_signature = true**
 - Everything behaves exactly the same

**if require_uid_self_signature = false** + at least one key uid has a self signature:
 - Everything behaves exactly the same (will fail if invalid)

**if require_uid_self_signature = false** + no key uid has a self signature:
 - Will skip self-signature checks, key will be usable

## Approach 2:
(inspired by @twiss)

No new config flags. 

Add way to set my own ultimately trusted public keys: eg one of:
```js
openpgp.setUltimatelyTrustedPublicKeys([k, ..]);
openpgp.setTrustedPublicKeys([k, ..]);
openpgp.setMyPublicKeys([k, ..]);
```

Later, when processing other public key, for each key uid:
1) if the uid has a self-signature, verify that as usual
2) if the uid does not have a self-signature, but was signed by one of the keys earlier supplied as trusted, verify it with that key instead
3) uid has no signatures, or the signature does not match any of our trusted keys: fail

I do not know what does the RFC4880 have to say about using keys that are missing a self-signature but were signed by a trusted key. As far as I can tell, not much (undefined).

--------------------

Either approach is ok with me as it does not change previous behavior unless additional action is taken (either setting a config flag or adding trusted keys).

**Comment by twiss** [comment]
I think it would ideally be best to do both. After all, GPG also requires --allow-non-selfsigned-uid to even import the key, and that flag

> only allows import - key validation will fail and you have to check the validity of the key by other means.

I haven't tested it, but this makes me think they require you to use this flag _and_ then certify the key.

I agree that the `openpgp.encrypt({ publicKeys, privateKeys })` idea is bad, but I don't really like having a global list of trusted keys either. Perhaps `openpgp.encrypt({ publicKeys, trustedKeys })`?

---

The way that GPG handles this stuff (certifying keys and then validating them based on other keys when you want to use them) is by operating on keyrings instead of individual keys.

We already have an implementation of keyrings, although it is quite bare-bones at the moment. So you could have something like:

```js
const keyring = new openpgp.Keyring();
keyring.publicKeys.push(someoneElsesKey);
keyring.privateKeys.push(myOwnPrivateKey);
const someoneElsesUserId = { email: 'someone@else' }; // or someoneElsesKey.users[0].userId;
await keyring.certifyKey({ publicKey: someoneElsesKey, userId: someoneElsesUserId });
await keyring.encrypt({ toUserId: someoneElsesUserId, message });
```

And then you could either automatically trust all private keys, or add a method to trust public keys as you propose (or both).

You could additionally have an orthogonal config option that requires that _all_ keys be certified by a trusted key, not just keys without a self-signature.

**Comment by tomholub** [comment]
I would say that keyring management should be outside of the scope of a crypto library, with the exception of establishing key trust where it's otherwise missing (eg the subject of this issue). Outside of that, I feel like keyring management should be done by the app. GPG an app thus it manages a keyring. 

My email app has has 1800 public keys. I sure don't want the app to parse them all and shove them into openpgp.js every time I start it! :) But for private keys, that is quite reasonable.

-------------------

The reason I don't feel like doing ```openpgp.encrypt({ publicKeys, trustedKeys })``` is that you would have to pass that value around a lot, into all of the sub-functions, modifying many of the core components. Whereas a global `openpgp.setTrustedKeys` can be done once and then accessed directly only from functions that really need it. This is a bit of a fringe feature, so it should ideally not involve too many changes.

-------------------

> I think it would ideally be best to do both.

I'd say, if you went ahead and signed a key uid, that shows you trust the uid, and it should not matter to you whether or not the owner of the key certified it. If my own signature was to be taken as a good-enough substitute for someone else's self-certification, that could be made to work without a config flag - I think.

-------------------

Thoughts?

**Comment by tomholub** [comment]
Good point about the server side @twiss . Global trusted keys would not make sense from that perspective. 

I still think that key management is outside of the scope of a crypto library. Either way, if there is a Keyring, the use of it should be voluntary / not required for any of the other standard functionality. If that is true, there would be two options on how to proceed on this issue:

---------------------------------
```js
// option 1: set global config and skip verification when uid self-signature not present

openpgp.config.require_uid_self_signature = true; // defaults to true
```
Advantages:
 - simplicity
 - can check if a key was missing self certs to display user warnings: `k.getPrimaryUser().selfCertifications !== null` 

Disadvantages:
 - global config

---------------------------------
```js
// option 2: when uid self-cert is missing, trust other public key uids we ourselves signed / certified

// first, sign someone else's key with something like
let signedKey = await openpgp.certifyKey({ publicKey: someoneElsesKey, userId: someoneElsesUserId, privateKey: myPrivateKey });
// optionally store signed key in keyring

let result = await openpgp.encrypt({ publicKeys: [signedKey], trustedKeys: [myPrivateKey] })
```
Advantages:
 - feels like a more proper way to solve this - certifying other keys shows I trust them
 - the trust is saved in the key, which can be understood later
 - can also check if a key was missing self certs to display user warnings: `k.getPrimaryUser().selfCertifications !== null` 

Disadvantages:
 - more work
 - the `trustedKeys` option will have to be passed around to possibly many sub-functions, changing the function signatures
 - makes `openpgp.encrypt` user interface more complicated. What are `trustedKeys`? Do I need them? Mine or theirs? What does it mean to be missing self-certification? What is a self-certification? - this would have to be documented, and may be an overkill for the issue at hand

---------------------------------

@twiss if you more or less agree on the value props above, I'd be interested to hear an opinion from one of the package maintainers

**Comment by sanjanarajan** [comment]
@tomholub thank you for the thorough summary!

I think to have something like option 2 eventually would be great, but I agree that it may be overkill for this particular issue. 

I would go for option 1 for a quicker fix (as this flag is anyway required for option 2) and then continue fleshing out ideas around certifying other keys if you are interested in adding this as well.

**Comment by tomholub** [comment]
Thanks @sanjanarajan  for looking into this, sounds good.

**Comment by tomholub** [comment]
Closing, will implement as a fork.
