### ISSUE TITLE
stop decrypting in loop

### ISSUE THREAD

**Issue by mr-smit** [openpgpjs/openpgpjs#741]
How to stop openpgp.decrypt() if I run multiple decrypting process ?

for example:

```
for(var i=0; i<100; i++){
   ...
   openpgp.decrypt()
}
```

now all decrypting process is in background, and I want to stop them all

something like:

`openpgp.stop_all_decrypting_processes(); `

Thanks

**Comment by tomholub** [comment]
Are you not waiting for the results? Try

```js
for(var i=0; i<100; i++){
   let result = await openpgp.decrypt(...);
   ...
}
```
This way you can abort it anytime during the loop.

**Comment by mr-smit** [comment]
SyntaxError: await is only valid in async function

p.s.: I dont want to wait for result every loop i want they all be in background, and if I need I can kill them all.

**Comment by tomholub** [comment]
Without the results, decrypting is meaningless, unless you just want to kill some cpu time.

You cannot abort a promise that has been already started in JavaScript.

Read up on promises and/or the async/await syntax in JavaScript.

Besides, JavaScript runs single-threaded and decrypting is cpu intensive, there is no point in starting them all at once. I don't think you'll get a whole lot of benefits by doing that.

**Comment by mr-smit** [comment]
I have 50 encrypted strings on one web page
When I load that page I read all 50 encrypted messages and in loop decrypting it...

but when I click go to next page with ajax request, the decrypting processes is still in cpu/memory, and I want to kill them all

Can you give me example how can I do it without full page refresh ? (my web page is fully ajax)

**Comment by tomholub** [comment]
You do one by one in a loop, with async/await syntax. When page changes,
you stop decrypting the ones you didn't decrypt yet.

For more performance, use a web worker to do it in the background. I would
still suggest to do it in batches of 5 or so.
