### ISSUE TITLE
openpgpjs Promise interfering with Firefox promises?

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#749]
On Firefox, the OpenPGP.js Promise seems to be used anytime I `new Promise` elsewhere in the code, eg like this:

![image](https://user-images.githubusercontent.com/6306961/43450542-745bd1f6-94a2-11e8-8b47-2bde155a98ce.png)

That red underline above shows `openpgp.js` in the stack where I would have not expected it. I thought it was just a regular promise:

```js
static get_global(keys) {
	return new Promise(resolve => {
		chrome.storage.local.get(... ... resolve(...));
	});
}
```

It also seems to cause some other trouble with Firefox internal promises. All of the errors above went away when I forced `var USE_NATIVE = true;` in openpgp.js dist file:
```js
// var USE_NATIVE = !!function () {
//   try {
//     // correct subclassing with @@species support
//     var promise = $Promise.resolve(1);
//     var FakePromise = (promise.constructor = {})[_dereq_('./_wks')('species')] = function (exec) {
//       exec(empty, empty);
//     };
//     // unhandled rejections tracking support, NodeJS Promise without it fails @@species test
//     return (isNode || typeof PromiseRejectionEvent == 'function') && promise.then(empty) instanceof FakePromise;
//   } catch (e) { /* empty */ }
// }();

var USE_NATIVE = true;
```

Are we declaring/replacing the global Promise object? 

1) Could we use the custom Promise only internally within OpenPGP.js without altering the global `Promise` constructor?
2) If not, can we consider adding a config option `openpgp.config.promise = 'native' | 'custom' | 'auto'` ?

**Comment by tomholub** [comment]
I should note, this only became a problem after upgrading to OpenPGP `2.6.0` to v3.

**Comment by tomholub** [comment]
Related in `polyfills.js`:
```js
// No if-statement on Promise because of IE11. Otherwise Promise is undefined in the service worker.
require('core-js/fn/promise');
```
This could be changed to:
```js
if(typeof Promise === 'undefined' || isIE11())  {
  require('core-js/fn/promise');
}
```

**Comment by tomholub** [comment]
Bump. Do you see any issue with doing the following in `polyfills.js`?
```js
function getVersionIE() {
  if (!window || typeof window !== 'object' || !window.navigator || 
      typeof window.navigator !== 'object' || 
      typeof window.navigator.userAgent !== 'string') {
    return null;
  }
  const agent = window.navigator.userAgent;
  const index = sAgent.indexOf("MSIE");
  if (index > 0) { // return IE version number
    return parseInt(agent.substring(index+ 5, agent.indexOf(".", index)));
  }
  if (agent.match(/Trident\/7\./) !== null) { // IE 11 has an updated UA
    return 11;
  }
  return null;   
}

if(typeof Promise === 'undefined' || getVersionIE() === 11)  {
  require('core-js/fn/promise');
}
```

**Comment by twiss** [comment]
V4 will have a separate dist bundle for modern browsers, which does not include the Promise polyfill, and a compat bundle for IE11+ which does. Is that sufficient for you?

**Comment by tomholub** [comment]
That sounds good! I'll close this for now
