### ISSUE TITLE
Indeterministic error: Could not find valid key packet for encryption in key

### ISSUE THREAD

**Issue by bitcalc** [openpgpjs/openpgpjs#751]
I have a chrome extension that uses openpgpjs. When I click on the button that triggers the call of the openpgp.encrypt() function after loading the extension, I often get this error: 

```Error encrypting message: Could not find valid key packet for encryption in key fa12a29e9c98aa2b```

However, if I wait for some time after loading the extension, around 30 seconds, then I can do the same operation without any problem. I'm confused with this indeterministic bug for a while but still cannot figure out what may cause it.

Can anyone offer me any clue where to look at?

I'm using version v3.x. I didn't have this issue with v2.x.x. My chrome version is 67.0.3396.87.

**Comment by tomholub** [comment]
Do you have your extension available somewhere on github/etc to test? If not, could you create a mini-extension that demonstrates/reproduces the issue?

**Comment by bitcalc** [comment]
Yes, I have it on the extension web store: 

https://chrome.google.com/webstore/detail/trust-encrypt/ghechkjikpllachnokghpmiblodogfpo

However, one needs to receive an invite in order to use it. Can you let me know your Gmail address so that I can send you an invite?

Meanwhile, I'll create a trimmed version with hardcoded RSA keys so that one can test it without an invite.

**Comment by twiss** [comment]
> Meanwhile, I'll create a trimmed version with hardcoded RSA keys so that one can test it without an invite.

Where/how are you generating the keys currently? I suspect there might be some issue with a date mismatch. Specifically, if the time of the computer that generates the key is ahead of the time of the computer that uses it, the latter will reject it as not being valid yet.

E.g., one way to reproduce the error is:

```js
let key = await openpgp.generateKey({
  userIds: [{name: 'Joe'}],
  date: new Date(Date.now() + 30000)
});
await openpgp.encrypt({ publicKeys: [key.key], data: 'bla' }); // Error encrypting message: Could not find valid key packet for encryption in key 09b95a131b97486d
```

If that's indeed the issue, one way to solve it would be to modify the above example to subtract 30 seconds from the generation date.

**Comment by bitcalc** [comment]
Well, the mini-version with hardcoded keys doesn't have the issue. I've re-loaded the extension ten times and triggered the same process. None of them showed the problem.

Now it's painfully fun to figure out what causes it by adding half, half,..., parts back.

**Comment by bitcalc** [comment]
I've found some clues that link to a cache use and possibly abnormal behaviors of the server. I'm checking them first. I'll post my client code if the problem still exists after I fix the cache and possible server issue.

**Comment by bitcalc** [comment]
I traced from the cache use to a server bug where an output stream is not explicitly closed in a try statement written in Java like this:

```
        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        try (ArmoredOutputStream aout = new ArmoredOutputStream(bout)) {
            aout.write(bytes);
            return bout.toString();
        }
        catch (IOException e) {
            throw new RuntimeException("Writing to ArmoredOutputStream", e);
        }
```

I moved the return statement from within the try block to outside of the block, which fixed the problem. The issue was the output stream guarded by the try statement may not be flushed out sometimes and resulted in an invalid key armored string returned, which was, in turn, read in by OpenPGPJS readAormored() function.

I'm sorry to report an issue that is not of OpenPGPJS, but I'm grateful for the nice tips and helps offered here.

Another thought is that if OpenPGPJS, as a library, can check its input and reports invalid PGP data object early, that would make it much more easy to find such type of problems. For example, the issue caused by a future date can be reported as an invalid key.

**Comment by bartbutler** [comment]
That's pretty strange...OpenPGPjs definitely should not happily consume a partially-armored string. Can you provide an example input here that OpenPGPjs accepts?

**Comment by bitcalc** [comment]
This is the example. I could set a breakpoint in Chrome and view its value.

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v@RELEASE_NAME@

mE0EWZ0ASAECAOeKr+MkXRie6Bps4ZD98a4xcZokzcNJTkAH9PtgXO/ws64vjY4P
QeOgpUPb51WirX/y/fDAZxovUA6H1SXCK9cAEQEAAbQUPGxld2lzdXJuQGdtYWls
LmNvbT6IdQQQAQgAKQUCWZ0ASAYLCQcIAwIJEKrnrOLExVFyBBUICgIDFgIBAhkB
AhsDAh4BAABVjQH+NaYfuHP0J0Yqt7WoR88J9p7OLbNUMHy49gB+1sE7bX8RrF9w
sSaCWynXuXy2llSeqjQBDldtFz7570GkDP/PBrhNBFmdAEgBAgDxTsUqimboteCC
bRlhviSR5gbVbx/kWd5ObSdOk1YR2IJvlPNlDS/uvJRWRpQ4n84yOIYqE/03p5xD
jfzLSs5DABEBAAGIXwQYAQgAEwUCWZ0ASAkQques4sTFUXICGwwAAKt3AgCpHXLN
XvWzVTrU6boYOefejBlu0/CDAlpAYGggGyY+v1eb4+dQ0V+TcL8TFBjfd3rCTl1H
DWYZoPjHRac3

```

The entire key string is:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v@RELEASE_NAME@

mE0EWZ0ASAECAOeKr+MkXRie6Bps4ZD98a4xcZokzcNJTkAH9PtgXO/ws64vjY4P
QeOgpUPb51WirX/y/fDAZxovUA6H1SXCK9cAEQEAAbQUPGxld2lzdXJuQGdtYWls
LmNvbT6IdQQQAQgAKQUCWZ0ASAYLCQcIAwIJEKrnrOLExVFyBBUICgIDFgIBAhkB
AhsDAh4BAABVjQH+NaYfuHP0J0Yqt7WoR88J9p7OLbNUMHy49gB+1sE7bX8RrF9w
sSaCWynXuXy2llSeqjQBDldtFz7570GkDP/PBrhNBFmdAEgBAgDxTsUqimboteCC
bRlhviSR5gbVbx/kWd5ObSdOk1YR2IJvlPNlDS/uvJRWRpQ4n84yOIYqE/03p5xD
jfzLSs5DABEBAAGIXwQYAQgAEwUCWZ0ASAkQques4sTFUXICGwwAAKt3AgCpHXLN
XvWzVTrU6boYOefejBlu0/CDAlpAYGggGyY+v1eb4+dQ0V+TcL8TFBjfd3rCTl1H
DWYZoPjHRac3p2tj
=nV7P
-----END PGP PUBLIC KEY BLOCK-----

```

**Comment by twiss** [comment]
Openpgp.js is indeed quite lenient currently when parsing keys, neither throwing for missing `-----END PGP PUBLIC KEY BLOCK-----` nor when packets are shorter than expected. The streams branch fixes both of those, though.

> For example, the issue caused by a future date can be reported as an invalid key input.

I don't really agree with that one though, it can be useful to distribute keys ahead of time that may not be used yet.

**Comment by bitcalc** [comment]
What's the streams branch? I don't see similar names in branches.

**Comment by twiss** [comment]
https://github.com/openpgpjs/openpgpjs/pull/709. Should get released next week.
