### ISSUE TITLE
\r\n is being normalized to \n in the decrypted file content

### ISSUE THREAD

**Issue by dwjft** [openpgpjs/openpgpjs#752]
If I'm decrypting a file, I want the original file contents, not a normalized version of the content. I can't imagine why that would be an agreed upon pattern for the library.

Anyway, the use-case I'm having trouble with is a file is based on a fixed-width file format.

Say for example someone sends me an encrypted file that is sending me strings of n bytes in length, and new lines are not a guarantee of a line ending.

For example, a file may look like this:

```
THIS IS 16 BYTES                             \r\n
THIS IS THE NEXT \r\n
16 BYTES .  \r\n
THIS IS THE THIRD SET OF BYTES \r\n
```

Obviously the above is not an accurate representation of a fixed length set of strings, but it illustrates the point perfectly. By normalizing the `\r\n` character to `\n` you are effectively shortening a line by 1 character and invalidating the entire schema of the fixed-width file.

I found the following two issues for reference:
https://github.com/openpgpjs/openpgpjs/issues/636
https://github.com/openpgpjs/openpgpjs/issues/211

**Comment by tomholub** [comment]
Does this still happen when you do:
```js
let m = openpgp.message.read(...);
let decrypted = await let m.decrypt(...);
let data = decrypted.getLiteralData();
```
This will use binary representation, and should not fiddle with your data.

**Comment by dwjft** [comment]
I am using `.readArmored` which has no `getLiteralData()` function on the return result.

The file itself isn't armored but I get a different error when trying to just use `.read` which reads `.input.subarray is not a function`. I pre-armorize non-armored content because I am never sure whether it is armored or not.

**Comment by tomholub** [comment]
I see a little bit on in the readme, this one works for wrapped `openpgp.decrypt` function:

js
```
options = {
    message: openpgp.message.read(encrypted), // parse encrypted bytes
    passwords: ['secret stuff'],              // decrypt with password
    format: 'binary'                          // output as Uint8Array
};

openpgp.decrypt(options).then(function(plaintext) {
    return plaintext.data // Uint8Array([0x01, 0x01, 0x01])
});
```
In general, my expierence with OpenPGP.js is that the `openpgp.decrypt(...)` function adds a tad-bit too much magic, so I'd personally recommend using `message.decrypt(...)` where you get to tightly control the whats and hows.

I think improvements to docs are always welcome.

**Comment by tomholub** [comment]
Just to add, `read` and `readArmored` should result in the same Message object, they only differ in how the data is read initially - unless I'm mistaken.

**Comment by bartbutler** [comment]
So, the rationale here is that if you are treating text data, the implication is that you want the input and output to be Javascript strings. Javascript strings have \n as newline and are in UCS-2. OpenPGP canonical text format is UTF-8, network normal line endings (\r\n). So this conversion to and from is performed automatically.

Binary mode is provided for exactly the purpose you want, to ensure no formatting or processing to the data whatsoever. But a general purpose Javascript OpenPGP library absolutely needs to be able to interface with standard Javascript strings to be useful, and that is what 'text' mode, or default mode, does. I hope that helps explain why the library does what it does.

**Comment by tomholub** [comment]
That does make sense. I guess OP was displeased that it wasn't obvious from documentation. So the question is whether the docs need to be improved or not. If not, the issue can be closed, else we could talk about how to improve it.

One way to force API users to think about this would be to make it a requirement to supply `format` to `decrypt()`, but that would be for v4, if ever, if even desired.

**Comment by tomholub** [comment]
If I get around to it, I'll submit a PR that improves the JSDoc anywhere format is used. Current form:
```
format | String | (optional) return data format either as 'utf8' or 'binary'
```
Updated doc should mention how to get the data results back from the return value, as this differs based on format used, and that `utf8` format may alter the literal data, treating it as a string.
