### ISSUE TITLE
Cannot decrypt data with password

### ISSUE THREAD

**Issue by mnchapel** [openpgpjs/openpgpjs#758]
Hello,

I try to use the "Encrypt and decrypt Uint8Array data with a password" example on my github pages but it doesn't work.

My index.html code below:

`
\<!DOCTYPE html\>
\<html\>
\<body\>
\<script src="js/openpgp.min.js"\>\</script\>
\<script type="text/javascript"\>

	var options, encrypted;

	// Encrypt
	options = {
		message: openpgp.message.fromBinary(new Uint8Array([0x01, 0x01, 0x01])), // input as Message object
		passwords: ['secret stuff'],                                             // multiple passwords possible
		armor: false                                                             // don't ASCII armor (for Uint8Array output)
	};
	openpgp.encrypt(options).then(function(ciphertext) {
		encrypted = ciphertext.message.packets.write(); // get raw encrypted packets as Uint8Array
		console.log("encryped: " + encrypted);
	});

	//Decrypt
	options = {
		message: await openpgp.message.read(encrypted), // parse encrypted bytes
		passwords: ['secret stuff'],              // decrypt with password
		format: 'binary'                          // output as Uint8Array
	};

	openpgp.decrypt(options).then(function(plainText) {
		console.log("contenu du fichier : " + plainText.data);
	});
\</script\>
\</body\>
\</html\>
`

And I got that error on the console: 
`Uncaught SyntaxError: Unexpected identifier`
on the line:
`message: await openpgp.message.read(encrypted)`

If I remove the "await" I got that error:
`Uncaught Error: Parameter [message] needs to be of type Message
    at h (openpgp.min.js:2)
    at Object.r.decrypt (openpgp.min.js:2)
    at index.html:29`
On the line: 
`openpgp.decrypt(options).then(function(plainText) {`

And I also got:
`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at u.readBytes (openpgp.min.js:2)`

Am I forgetting something ?

Thanks
MN

**Comment by twiss** [comment]
`await` needs to be inside an `async` function. Try wrapping the JS in:

```
(async function() {

  ...

})();
```
