### ISSUE TITLE
Unable to decrypt long messages from GPG

### ISSUE THREAD

**Issue by irigi** [openpgpjs/openpgpjs#76]
Recently, I started using mailvelope, software dependent on opengpgjs, and I run into this issue: messages encrypted in GPG under Linux 64bit, which are too long, cannot be decrypted. I send example into the comment to this thread. I tried the issue in the decryption window http://openpgpjs.github.io/openpgpjs/test/encryption.html . The message to be decrypted can be found here: https://www.dropbox.com/s/9pvc7abj3k2oa0w/failedPGPMessage.asc

**Comment by tanx** [comment]
Try again with v2.x. It's much faster.
