### ISSUE TITLE
Missing verification of signatures in getLatestSignature

### ISSUE THREAD

**Issue by toberndo** [openpgpjs/openpgpjs#762]
I'm currently migrating from OpenPGP.js 2 to 4 and checking how certificates are handled internally and it looks to me like the current procedure is suboptimal in some places and can lead to false negatives.

In `Key.prototype.getPrimaryUser` the primary user is found as follows:
1. only the latest signature of a user is considered: https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L515
`getLatestSignature` returns the latest signature, but does not verify before returning that signature. I think __in general only valid signatures should be considered__, so `getLatestSignature` should be more a 'getLatestValidSignature'. In the current implementation the latest self certificate of a user id could be invalid or expired, which would render the complete user id invalid although the user id might have other valid self certificates.
2. In https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L532 users are sorted by primary user id flag and created date. At that point in time the self certificates have not been verified, so what we get as most relevant user id might not have a valid self certificate and will lead to returning null after verification here: https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L541

I would consider the procedure in OpenPGP.js v2 as more accurate: https://github.com/openpgpjs/openpgpjs/blob/v2.6.2/src/key.js#L511
First you build objects for every user id - self signature combination, sort, return the first valid combination.

The missing signature verification in `getLatestSignature` also affects the following methods:
```
Key.prototype.getSigningKey
Key.prototype.getEncryptionKey
Key.prototype.getRevocationCertificate
SubKey.prototype.verify
SubKey.prototype.getExpirationTime
```

Pinging @AndreHeinecke and @dd9jn for feedback on how this is implemented in GnuPG

**Comment by toberndo** [comment]
> and section 5.2.3.3:

Yeah, I quoted that section myself in https://github.com/openpgpjs/openpgpjs/issues/266#issuecomment-369607858 and had the same interpretation.

But I think "self-signature" always implies a valid signature. If you don't check validity then anyone can insert a signature packet in a key where `issuerKeyId.equals(primaryKeyId)` and it would be considered as a self-signature.

**Comment by sanjanarajan** [comment]
To be clear, the validity of the self-signature **is** always checked before the key is used, including in the functions that you enumerated in your first comment. First, we choose which primary user and self-signature to consider by looking for the most recent self-signature. Then, we check the validity of the chosen self-signature in order to determine the validity of the key. 

Yes, this does mean that in the case you described, if somebody inserts a fake self-signature into a key, the key will fail to encrypt. But this seems like reasonable behavior when handling a key that has clearly been tampered with.

I'm not sure if by "valid" you are just referring to signature verification, or if you also consider valid to mean "not expired and not revoked." When additionally considering expiration and revocation, I think there are even more compelling reasons to only consider the last signature, because this allows people to reduce the expiration time and revoke users for their keys without having to remove older signatures.

**Comment by toberndo** [comment]
> To be clear, the validity of the self-signature is always checked before the key is used, including in the functions that you enumerated in your first comment. First, we choose which primary user and self-signature to consider by looking for the most recent self-signature. Then, we check the validity of the chosen self-signature in order to determine the validity of the key.

It's not critical in the sense that it currently does not produce false positives when evaluating self certificates. Still I think it should be good practice to not let a unverified self certificate have any impact in the decision tree of a crypto system. `Key.prototype.getEncryptionKey` directly influences which key packet is used for encryption of a message. Let's say someone has a PGP key with two subkeys (RSA and ECC): an attacker that can modify the key is able to shut down the ECC subkey, it will never be used for encryption, although my application will show it as a valid subkey. This should not be acceptable.

Btw, I'm wondering if `Key.prototype.getEncryptionKey` should prioritize subkeys by "latest valid binding certificate". That way if I add a new shiny ECC key to my existing RSA key, it would have priority. But that is a separate discussion.

> I'm not sure if by "valid" you are just referring to signature verification, or if you also consider valid to mean "not expired and not revoked." When additionally considering expiration and revocation, I think there are even more compelling reasons to only consider the last signature, because this allows people to reduce the expiration time and revoke users for their keys without having to remove older signatures.

Removing older signatures is not an option as key servers for example are append only data structures. So we have to deal with the fact that there are self certificates and binding signatures that make contradicting assertions.

The way to evaluate this is to sort all certificates by creation date and then take the first that is valid, not-expired and not revoked.
So for example take these subkey binding signatures:

1. creation 2018-09-01, expires 2d, verifies correctly, key expires after 4d
2. creation 2017-01-01, expires never, verifies correctly, key expires never

This subkey is still valid as 2. is valid and sets the expiration time of the key to never.

**Comment by toberndo** [comment]
@sanjanarajan sounds great. Thanks for looking into this. I'm currently not working on a PR.
