### ISSUE TITLE
npm install --save openpgp

### ISSUE THREAD

**Issue by vadymsem** [openpgpjs/openpgpjs#764]
It only happens when I try to install openpgp package.

npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone -q git://github.com/openpgpjs/elliptic.git /Users/me/.npm/_cacache/tmp/git-clone-f500dfd8
npm ERR! /Users/me/.npm/_cacache/tmp/git-clone-f500dfd8/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-09-04T14_19_47_378Z-debug.log

**Comment by twiss** [comment]
Perhaps related to https://github.com/openpgpjs/openpgpjs/pull/715? (Which doesn't seem like the right solution, although I don't know what is, but it might be the same problem.)

**Comment by vadymsem** [comment]
Is it so hard to change http instead of ssh for developers?

**Comment by wiltshirek** [comment]
hello folks.  any word on this?  I'm having the same issue.  Is there a work around for this?

**Comment by vadymsem** [comment]
Hello!
I don’t know man;)
I think there is only way to solve it it’s contact with developers.

пт, 5 окт. 2018 г. в 17:59, wiltshirek <notifications@github.com>:

**Comment by tripodsan** [comment]
hmm, the problem persists, that some of the dependencies are referenced by git-urls. which is really a pain when installing this package.

**Comment by twiss** [comment]
Does `npm install --only=production` work?

> why not use proper npm package releases instead of using the git references? this would also speed up npm install afaik. this would also stabilize the releases, since you would have a version reference to those libraries instead of just using the master....

The git URLs have commit hashes in them, so the last point at least doesn't apply.

Given how many dependencies we fork, and how often we add or remove one, we'd prefer not to have to publish all of them to npm.

**Comment by tripodsan** [comment]
we have a similar complex project, and use https://github.com/semantic-release/semantic-release and https://greenkeeper.io/. usually, releasing a dependency happens automatically and adding it to the parent project is then 1 click away. 

this also forces us to create proper issues, pull requests and tests for all packages, which gives a transparent CI/CD flow....
