### ISSUE TITLE
Missing compat from latest release (4.0.1)

### ISSUE THREAD

**Issue by gfortaine** [openpgpjs/openpgpjs#770]
Hello,

Thank you for the great work 👍 

However, it seems that the compat folder is missing from the latest release. And this is particularly annoying for people who need to support legacy browsers (IE11...). Would you be able to spin up a new release fixing this bug, please ?

**Comment by twiss** [comment]
It seems to be there for me: https://github.com/openpgpjs/openpgpjs/tree/v4.0.1/dist/compat

**Comment by gfortaine** [comment]
@twiss It is in the sources, but it isn’t in the published package : https://unpkg.com/openpgp@4.0.1/dist/
