### ISSUE TITLE
Encrypting any file type using pgp keys

### ISSUE THREAD

**Issue by Vasista-22** [openpgpjs/openpgpjs#775]
I've tried to encrypt files using openpgp.js in this way:
`const options = {
                message: openpgp.message.fromText(this.state.buffer),
               publicKeys: (await openpgp.key.readArmored(pubkey)).keys, // for encryption (((await)))
        }

        console.log(options);     
        let encrypted = "";
        await openpgp.encrypt(options).then(ciphertext =>{          //await
          encrypted = ciphertext.data;
          console.log(encrypted); 
        })`

I've defined the pubkey in the code. I've not included all my code.
While this is working, Decryption of the encrypted content is working only for text files that are encrypted.
When I tried to decrypt the contents of a file of any other format other than text files, decryption isn't happening.
I'm using RSA 4096 for encryption and decryption.
I'm downloading the encrypted contents and decrypting using OpenPGPstudio software.

Kindly suggest how to encrypt and decrypt files of any format using pgp keys.

@AlexanderWillner

**Comment by bartbutler** [comment]
Use fromBinary() rather than fromText(). Please reopen if this does not solve your issue.
