### ISSUE TITLE
Deterministic key generation

### ISSUE THREAD

**Issue by djvs** [openpgpjs/openpgpjs#780]
I'd like to use this library for deterministic key generation from a preexisting string.  If I write a PR to accomplish this, is there any possibility it could be merged?  Or better yet, is there any existing way to do this?

**Comment by sanjanarajan** [comment]
No, there is not an existing way to do this. We could consider a PR, but it would probably make sense to settle on the implementation details in this issue first. 

Could you please explain what you would use this feature for? I imagine that it would be mainly useful for key recovery, so in that case it might be best to have a separate recovery function that accepts this data, a public key, and a passphrase, and returns a private key encrypted with that passphrase. This could potentially mitigate the concerns brought up in #596 about misuse of this type of feature. 

Other questions: What format for this string did you have in mind? What data would the string contain for RSA keys vs. ECC keys? Would you pass in a separate string for each subkey?

**Comment by djvs** [comment]
In our case, the idea is to have deterministic key generation based on a 512 bit secp256k1 signature provided by Metamask, in order to form a chain of keys based on the original key, when the original key isn't accessible by a library like openpgp.js but the user does provide a signature.    Our only alternative was instead using the signature as a passphrase on a known and shareable (?) public key.  This is still kind of investigatory phase, so topics like whether or not there's sufficient entropy in that signature (for a given representation of it), whether or not it needs to go through some kind of transformation or hash function, etc., aren't totally resolved.  For a given input string to be mapped to an entropy input for a given function, I guess any function that's deterministic and increases or doesn't reduce entropy would work.

**Comment by chesnokovilya** [comment]
out of scope for this library
