### ISSUE TITLE
openpgp.message.fromText(...) does not work with openpgp.sign(...)

### ISSUE THREAD

**Issue by emilmuller** [openpgpjs/openpgpjs#785]
openpgp.sign(...) returns an unsigned message when used with openpgp.message.fromText(...). Readme.md states that a CleartextMessage or Message object can be passed, but the latter does not seem to work.

**Comment by twiss** [comment]
It works for me. Why does it seem unsigned to you? What's the output of `gpg --list-packets <file-with-returned-armor>`?

**Comment by twiss** [comment]
Feel free to let me know if it still doesn't work for you or the above is not what you expected.
