### ISSUE TITLE
openpgp.sign extremely slow for 3 MB long byte array

### ISSUE THREAD

**Issue by emilmuller** [openpgpjs/openpgpjs#786]
I recently upgraded from version 3 something, to 4.1.1.
openpgp.sign now seems extremely slow and doesn't ever seem to finish (for that byte array). Also, it is eating my memory.

```
var bytes = new Uint8Array(3255425);
var options = {
    userIds: [{ name:'Jon Smith', email:'jon@example.com' }], // multiple user IDs
    curve: "ed25519",                                         // ECC curve name
    passphrase: 'super long and hard to guess secret'         // protects the private key
};

var key = await openpgp.generateKey(options);
var privkey = key.privateKeyArmored; // '-----BEGIN PGP PRIVATE KEY BLOCK ... '

var privKeyObj = (await openpgp.key.readArmored(privkey)).keys[0];
await privKeyObj.decrypt(options.passphrase);

console.log(await openpgp.sign({ message: openpgp.message.fromBinary(bytes), privateKeys: privKeyObj, detached: true })); // Have a coffee
```

![image](https://user-images.githubusercontent.com/16109123/47167371-a5346280-d2fe-11e8-8b71-6ee5acbdf3c4.png)

**Comment by twiss** [comment]
I can't reproduce for some reason. In fact your code runs faster in v4.1.1 than in v3.1.3 for me, at roughly 800ms instead of 1200ms.

I tried both Chrome 69 and 70. What version are you using?

**Comment by emilmuller** [comment]
@twiss Just confirmed this on my end. If I call the initWorker, it is 20x slower on my machine. At my work computer (I'm currently at home) I didn't expect it to finish, so I terminated.

**Comment by emilmuller** [comment]
@twiss At work now and experimenting. I don't have the worker enabled now, and this code does not work (fills 2 GB og memory until it crashes):

```
(async function () { var bytes = new Uint8Array(3255425);
var options = {
    userIds: [{ name:'Jon Smith', email:'jon@example.com' }], // multiple user IDs
    curve: "ed25519",                                         // ECC curve name
    passphrase: 'super long and hard to guess secret'         // protects the private key
};

var key = await openpgp.generateKey(options);
var privkey = key.privateKeyArmored; // '-----BEGIN PGP PRIVATE KEY BLOCK ... '

var privKeyObj = (await openpgp.key.readArmored(privkey)).keys[0];
await privKeyObj.decrypt(options.passphrase);
var message = openpgp.message.fromBinary(bytes);
console.log(await openpgp.sign({ message: message, privateKeys: privKeyObj, detached: true }));
console.log(bytes.length);
bytes = (await openpgp.encrypt({ message: message, passwords: "CI,I96#=N71F'$6psW.=RSqgad%P9)N7", armor: false })).message.packets.write();
console.log("will never get here")
})()
```


Google Chrome | 69.0.3497.100 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 8920e690dd011895672947112477d10d5c8afb09-refs/branch-heads/3497@{#948}
OS | Windows
JavaScript | V8 6.9.427.23

**Comment by twiss** [comment]
@emilmuller Thanks for investigating! The above PR should fix this.

**Comment by emilmuller** [comment]
@twiss That seems to have done the trick! :) Thanks :+1:
