### ISSUE TITLE
accidentally including GPL code

### ISSUE THREAD

**Issue by wmhilton** [openpgpjs/openpgpjs#791]
compressjs is GPL and this library is LGPL.

This fun fact brought to my attention by https://fossa.io/ ...again.

**Comment by sanjanarajan** [comment]
Thank you for bringing this to our attention! We will address this by using a fork of this library: https://github.com/cscott/seek-bzip for decompression and removing bzip2 compression support (it is a "MAY" in the RFC and very slow)
