### ISSUE TITLE
compatibility of Node api  and native signatures

### ISSUE THREAD

**Issue by officefish** [openpgpjs/openpgpjs#803]
I noticed that node Api produced signatures are not compatibility with native ones and vise versa. Node signed only node verified, native signed only native verified. Is it possible to convert one signature to another to let compability with each other?

Other thing is that node sign and verify much faster than native so you can use static methods with no curve and key pair production for node sign/verify processes.

**Comment by twiss** [comment]
Hi @officefish! Could you post some example code of creating and verifying a signature that doesn't work?

**Comment by twiss** [comment]
It sort of sounds like you're trying to mix openpgp.js with `require('crypto').createVerify`, which is not possible. Let me know if you have a different issue.
