### ISSUE TITLE
Compat version contains a single arrow function, tripping up IE11

### ISSUE THREAD

**Issue by Epskampie** [openpgpjs/openpgpjs#804]
If you open up dist/compat/openpgp.min.js and search for `=>`, you'll find 1 match. 

This doesn't work in IE11, which is one of the reasons for the compat version to exists.

**Comment by gfortaine** [comment]
cc @twiss Could it be possible to merge the associated PR in a 4.2.2 release, please ? Because we are confronted to this pretty annoying bug to support correctly IE11.

**Comment by Epskampie** [comment]
Please don't forget to build and release a new version in de `dist` directory as well.

**Comment by mmso** [comment]
@sanjanarajan For some reason the newest released version at https://raw.githubusercontent.com/openpgpjs/openpgpjs/master/dist/compat/openpgp.js still contains the ` => ` at
```
function bufToHex(buf) {
  return Array.prototype.map.call(buf, x => ('00' + x.toString(16)).slice(-2)).join('');
}
```

However when I build locally I don't get that, I get the correctly transpiled version. Could you try making another build?
