### ISSUE TITLE
Google Scripts

### ISSUE THREAD

**Issue by kenman345** [openpgpjs/openpgpjs#806]
Hi!

I am trying to get my github bot Google Script to be able to sign its commits. It appears that this library might be the best shot I have at being able to accomplish this.

Given I have very little knowledge about your library, do you have any advice or instructions that might help me with my efforts? Google Scripts are a bit weird but its handling everything I've wanted to do with it so far and it really would be nice to incorporate this functionality to its capabilities.

**Comment by twiss** [comment]
The README contains instructions for creating detached signatures, which is what you need:

https://github.com/openpgpjs/openpgpjs#create-and-verify-detached-signatures

Alternatively, isomorphic-git is a pure JS git library which seems to have support for signing commits:

https://isomorphic-git.org/docs/en/sign
https://isomorphic-git.org/docs/en/plugin_pgp

Let me know if you have any other questions. Good luck!
