### ISSUE TITLE
OpenPgpJs version 4.2.1 Decrypt fails on verify signature with error 'Error decrypting message: Corresponding signature packet missing at OnePassSignature.verify (node_modules/openpgp/dist/openpgp.js:35786:11)'

### ISSUE THREAD

**Issue by LukeMcCarthy-TW** [openpgpjs/openpgpjs#807]
When trying to decrypt a message I get the following error

Error: Error decrypting message: Decryption failed due to missing MDC.
  at SymmetricallyEncrypted.decrypt (node_modules/openpgp/dist/openpgp.js:38899:11)
at <anonymous>

If I set
```
  openpgp.config.ignore_mdc_error = true
```
I get the following error

  Error: Error decrypting message: Corresponding signature packet missing
at OnePassSignature.verify (node_modules/openpgp/dist/openpgp.js:35786:11)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)

If I remove the public key from the options then the file decrypts correctly, however, I then don't know who sent the message

The file is sent from another organisation and it would be very difficult to change anything on their side

Any help would be greatly appreciated

Sample code below

```
const expect = require('chai').expect;
const openpgp = require('openpgp')

const pgpKeys = require('./pgp_keys_decrypt_unit_test');

const encryptedText = `-----BEGIN PGP MESSAGE-----
Version: SDS E-Business Server - 64 Bit - v9.0.1 - Full License

hQEMA1Fa0FFyaYAZAQgAouMX/4Vd0JWrWsmR6mzT/RLyK16Sd449R6r0H74msyas
sX6YI5Qu+inIJxWQhLF5fgaxr7+N9mwKM/G2FrErG2MDT/XTwjH9WOH4AudK9lcX
NWO2ELJyxwOJhqBlxL0bzjpmL83uufIjfEA7+QsTzGnMgg122aExVs2CVacxQob1
mouEpA7hp3HHBosrO/zIX773sVrOknlYNbzB6lX/+5l14FN19HRXCI7vQIX0G/D1
lF+kKmOodIZFD+5k/J1FDBwwOuHXai86Nv/l0ktvUG18yXrAxq96sTFgZ6xI8Yh0
4mUlZ2Pr2o82Vr5hBbyuLLmD7FMnyg+lubDwxkJXhtLAswHWpzrQ3gMlZVdrneN/
fZmp1yVJWSCTo0KguUZ7OZfjBMOrFPIwk02934EdZ0jP73OMVYS0/06vavRSFDIl
9ysC0UjVyCZABA04TLjf6JlleFdls7hQVEf80LPUvLrHpMA+ZueW8/rJFuruFvJk
1J7M5FmLZuaeeg7DjZ4+dbZug7F+tuQFUcSO10gBVSgUFGAAgljnKhTZG8Ml3ysB
91GiVzfTmOtXUIx3gAqU2I/8JApoxxINuZTZZ4uUBvQ0I2IPBtqcM7XNp68CveR0
jyKUeK1vHn5UZUp2JPFUNxyJQYOYVARP7Sv+YiP+jbqQPxNyKiYXlWay/HaUPGdQ
kfruIznX/hDKTxKrvvB+LtFcsnSwzM54TlqHa4PkfuUcjD/2yCdyjLsy9QeC6Ttv
HK6z8nr93+gqUxmf19fH1zh0J3+fSU8SB7owcG+yabZs/MaG7JngHS3RrRtACUBr
p9wdjv/B21G8vl/qlHnFYW11CPa6
=k3nV
-----END PGP MESSAGE-----`;

const expectedDecryptedMessage = `hello world!`

openpgp.initWorker({ path:'openpgp.worker.js' })
openpgp.config.ignore_mdc_error = true;

const decrypt = async (encryptedText) => {
  const privKeyObj = (await openpgp.key.readArmored(pgpKeys.privkey)).keys[0];
  await privKeyObj.decrypt(pgpKeys.passphrase);

  const options = {
    message: await openpgp.message.readArmored(encryptedText),    // parse armored message
    publicKeys: (await openpgp.key.readArmored(pgpKeys.pubkey)).keys, // for verification (optional)
    privateKeys: [privKeyObj]                                 // for decryption
  }

  return await openpgp.decrypt(options).then(plaintext => plaintext.data);
};

describe('', () => {
  it('given an unencrypted string when the unencrypted string is passed to encryptString then the string returned should be encrypted', async () => {

    const result = await decrypt(encryptedText)

    expect(result).to.equal(expectedDecryptedMessage);
  });
});
```

**Comment by twiss** [comment]
Hey! Could you perhaps import the private key in GPG and post the output of `gpg --list-packets <filename>`?

**Comment by thelukemccarthy** [comment]
Unfortunately I can't import the private key. The file was encrypted by someone else. I doubt they will provide me the private key. I can ask them to run the command but the best case scenario is it will take a long time, the wrote case is the process is automated and no one knows where the key is.

**Comment by twiss** [comment]
I meant your private key, which you use to decrypt it, not the one that was used to sign it. Do you have that?

What it sounds like from the error message is that your message is missing a signature packet. If that is indeed the case, there's not much we can do other than ignore it. You could still find out who claims to have created the message, by looking at the `issuerKeyId` of the one-pass signature packet. However, there's no way to verify that the owner of that key actually created it.

**Comment by thelukemccarthy** [comment]
I can run it for our private key, I'll do that when I'm at my computer

**Comment by LukeMcCarthy-TW** [comment]
The output from the the command ``` $ gpg --list-packets ./file_to_decrypt.txt ``` 
I have reducted some of the info (email address and names)
``` 
:marker packet: PGP
:pubkey enc packet: version 3, algo 16, keyid 4B3FF8565265D493
        data: [2048 bits]
        data: [2048 bits]
:pubkey enc packet: version 3, algo 1, keyid B54831854848485B
        data: [2047 bits]

You need a passphrase to unlock the secret key for
user: "PublicTest (Test Env Key) <*************@gmail.com>"
2048-bit RSA key, ID 4848485B, created 2018-10-15 (main key ID 83669E20)

:encrypted data packet:
        length: 360
gpg: encrypted with 2048-bit ELG-E key, ID 5265D493, created 2016-06-08
      "Private TEST 2048 PGP Key <test2048@*************.com>"
gpg: encrypted with 2048-bit RSA key, ID 4848485B, created 2018-10-15
      "PublicTest (Test Env Key) <*************@gmail.com>"
:compressed packet: algo=2
:onepass_sig packet: keyid C416A52150F77D20
        version 3, sigclass 0x01, digest 8, pubkey 17, last=1
:literal data packet:
        mode t (74), created 0, name="PGP8Encode_Temp_006a6c0000000167154a51680009b575.tmp",
        raw data: 861 bytes
:signature packet: algo 17, keyid C416A52150F77D20
        version 3, created 1542250451, md5len 5, sigclass 0x01
        digest algo 8, begin of digest a3 69
        data: [222 bits]
        data: [224 bits]
gpg: WARNING: message was not integrity protected
```

**Comment by twiss** [comment]
Ah, ok. The signature packet is in fact not missing, it's just a version 3 signature, which we no longer support since OpenPGP.js v4. You could try OpenPGP.js v3. It unfortunately had a slightly different API than v4, so it might be helpful to look through the "High-Level API Changes" section of https://github.com/openpgpjs/openpgpjs/releases/tag/v4.0.0 and apply them in reverse.

As a sort of general warning though, OpenPGP.js v3 has a number of security vulnerabilities that have only been fixed in v4. `openpgp.config.ignore_mdc_error = true` is also not advisable. Please don't put any trust in the data or signatures in these messages.

**Comment by LukeMcCarthy-TW** [comment]
Thanks, @twiss, I will see if I can get the sender to update to version 4 of PGP, if not I guess I will have to use version 3.

Thanks again for your speedy replies

**Comment by LukeMcCarthy-TW** [comment]
@twiss will moving to OpenPGP v3 mean I don't need to use ``` openpgp.config.ignore_mdc_error = true ```
Currently when I don't use it I get the error
```
Error: Error decrypting message: Corresponding signature packet missing
at OnePassSignature.verify (node_modules/openpgp/dist/openpgp.js:35786:11)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by twiss** [comment]
No, you'll still need that. And I think you meant this error, right?

```
Error: Error decrypting message: Decryption failed due to missing MDC.
at SymmetricallyEncrypted.decrypt (node_modules/openpgp/dist/openpgp.js:38899:11)
```

Basically OpenPGP.js is telling you the same thing here as GPG when it said

```
gpg: WARNING: message was not integrity protected
```

but instead of a warning we have an error plus a config option to ignore it.

**Comment by LukeMcCarthy-TW** [comment]
Yeah I did mean 
```
Error: Error decrypting message: Decryption failed due to missing MDC.
at SymmetricallyEncrypted.decrypt (node_modules/openpgp/dist/openpgp.js:38899:11)
```
I copy pasted the wrong error message.

So I take it the solution is for the sender to sign the message with a PGP key that is certified?

**Comment by twiss** [comment]
I assume you're referring to the

```
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

part? No, that's something different. That just basically means you haven't told GPG that you believe that test2048@***.com owns the public key you imported. If you believe they do, you can certify the key yourself to make that warning go away.

`ignore_mdc_error = true` is more like "I know the data in this message shouldn't be trusted, stop yelling at me about it".

Essentially what the sender needs to do to make the other warnings go away is to use newer software to encrypt & sign the message (and possibly for generating the keys too).

Although.. the message claims to have been generated by `SDS E-Business Server - 64 Bit - v9.0.1 - Full License`, which seems to be almost the latest version. Maybe that software just doesn't support v4, or maybe it uses v3 by default but does support v4. Hard to tell without documentation. But since they have a Full License, maybe they can ask that company's support ;)

One other thing: if you can't get them to upgrade and must use these v3 messages, it's best to

- Only ever do something with the data if there are valid signatures. This ameliorates the `ignore_mdc_error` issue slightly. If the signatures don't verify, don't show the message to the user, etc (or whatever you were going to do with it)
- Not use OpenPGP.js v3, since OpenPGP.js v3 had some bugs in signature validation, but instead use GPG or some other library (or revert 4e749965f22bae822510d33ee5f894107aba9b3d ;))

**Comment by twiss** [comment]
No problem! And thanks, I'll let you know if I'm ever on that side of the globe :)

**Comment by toberndo** [comment]
@twiss Currently the exceptions in `OnePassSignature.prototype.verify` will abort the encryption process at https://github.com/openpgpjs/openpgpjs/blob/master/src/openpgp.js#L382. I'm wondering if this is required as the integrity of the message content seems not affected by a corrupted or outdated (v3) signature. So we could also decrypt such messages correctly and just flag the signatures as invalid?

**Comment by twiss** [comment]
Hmm, yeah. The final place where this error is thrown is https://github.com/openpgpjs/openpgpjs/blob/92ba73402a1c9a99260d491fec47ee7ef2090df5/src/openpgp.js#L676

It might make sense to add a try/catch there and set `signature.error` in the catch, perhaps, so that it remains possible to debug this.

**Comment by briancuppmittera** [comment]
I was working with someone sending PGP files with the same problem. They upgraded SDS E-Business Server to version 9.0.2, which fixed the problem.
