### ISSUE TITLE
Error unpacking decrypted Tar file

### ISSUE THREAD

**Issue by bartvollebregt** [openpgpjs/openpgpjs#811]
Hi there,

I'm using below code to try and decrypt an encrypted tar file.
The file gets created without any errors but why I try to unpack the tar with: `tar xopf testifle.tar`
 I get: `tar: Damaged tar archive`

When I decrypt the file with `gpg -o testfile.tar -d testfile.tar.gpg` (and enter password), it does produce a tar file that I'm able to unpack. 

I noticed that openpgpjs produces a 2.4MB file while the gpg command produces a 1.3MB file.

Any help would be much appreciated.

```javascript
const openpgp = require('openpgp');
const fs = require('fs'); 

 openpgp.key.readArmored(privkey).then(privKeyData => {
    const privKeyObj = privKeyData.keys[0];
    privKeyObj.decrypt(passphrase).then(() => {

      openpgp.key.readArmored(pubkey).then(pubKeyData => {
        const pubKeyObj = pubKeyData.keys;
        
        const encryptedData = fs.readFileSync('testfile.tar.gpg');
        let encryptedMessage = openpgp.message.read(encryptedData);

        encryptedMessage.then(result => {

          const options = {
            message: result,
            // passwords: [passphrase],
            publicKeys: pubKeyObj,
            privateKeys: [privKeyObj],
          };

          openpgp.decrypt(options).then(decrypted => {
            fs.writeFileSync('testfile.tar', decrypted.data);
          });
        })

      });

    });
  });
```

**Comment by twiss** [comment]
I think `format: 'binary'` in your decrypt `options` object should fix this. Let me know if it doesn't,

**Comment by bartvollebregt** [comment]
@twiss It worked! Thanks a lot!
