### ISSUE TITLE
Public Key fingerprint is a Uint8Array instead of a hex string

### ISSUE THREAD

**Issue by ecamellini** [openpgpjs/openpgpjs#826]
I just updated to version 4.4.1 from version 2.6.2 and it seems that the fingerprint of a public key is not represented as a hex string anymore, but as a Uint8Array, even though the documentation still says that it is a hex string: https://github.com/openpgpjs/openpgpjs/blob/b1b19946d83da39969fdc22340e32b1d58a3f047/src/packet/public_key.js#L81

I wrote the following test to trigger such behavior:

```js
  test('fingerprint extraction works correctly', async () => {
    const publicKey = `-----BEGIN PGP PUBLIC KEY BLOCK-----

xo0EXCUDJgEEAIw9LTM1WUP9TgCjEul0yj4uYrEDXfKtKxYlGH3hltkTmvhy
8O3J4rGoiNNrSK7LM0lHUndOH1AXkWw4AVAEcXS0CZeyv9cVSt/4F1mTQF5p
XKOf6Ghl9FnGAsep5A1YQ0yCpFIA9dWyVIETj9w1HHndSXJHY3nQmU0+OZhC
WpYPABEBAAHNAjw+wrUEEAEIACkFAlwlAzoGCwkHCAMCCRApzwDY+0vmZAQV
CAoCAxYCAQIZAQIbAwIeAQAAXlID/0ObLJ6Rr7A+ECrW9u5r1k1rau/Zj2bz
8djgPdesdYbzOyvzUcI4aZCt9XclyKPJWTiodUrPkxukJSj4S3ryu1fyiz8j
0bPwW0il7MOPGJjIRCv1qjTMPpuLcfc69v352K1BfDji+nOGAG0bZVtSU3EA
0nkYS64B1t25jmltvxihzo0EXCUDNQEEAJPkwhZz7Rw4iHropBmtT+OdHiwF
YlohR4Cqn+mBXDhE/2GeaRGrEawctgProXh1PF1KuLxgjSsZPgiWfGCpQuHq
3HdlxuGWQ1hNB9e/V0ewHSt8qxMuhrn/eXby68pknVGAeqaIUcSOTId6odyF
hxrIfJzbMvCWVmsA0DJpx9+HABEBAAHCnwQYAQgAEwUCXCUDOwkQKc8A2PtL
5mQCGwwAAJ0NA/9RiAj9j4ceaqkaox0vzB7GdQGbkhYa13lF9X6lT4+AJnZp
D+SCS9vdcztjgU7P5gROoVrzBcLtLiYQyv3fqESMBaHErV3nsI7QTa5dNqWh
btlZf5VzDl+hLwraiiFlqCjnYfsuicR6tIB3c8sEP2bKPgXegHmfByqNd8A5
gyCirQ==
=pxpp
-----END PGP PUBLIC KEY BLOCK-----`;

    const key = await openpgp.key.readArmored(publicKey);
    const fingerprint = key.keys[0].primaryKey.fingerprint;
    expect(fingerprint).toBe('2fb52320034248aeafbaac6329cf00d8fb4be664');
  });
``` 

This test was working correctly before the update: I just added `await` to match the new API.

![image](https://user-images.githubusercontent.com/6418684/50511404-cdbea280-0a8d-11e9-8079-7103b085794b.png)

**Comment by twiss** [comment]
You can use `.getFingerprint()`. You're right that that line of documentation should be updated, though.

**Comment by ecamellini** [comment]
@twiss thanks, `getFingerprint()` returns the correct value converted to hex.
