### ISSUE TITLE
TransformStream not available in Thunderbird

### ISSUE THREAD

**Issue by pbrunschwig** [openpgpjs/openpgpjs#832]
I'm trying to apply v4.3.0 to Enigmail. However, if I use for example `openpgp.key.readArmored()` then the following error is thrown:

`ReferenceError: TransformStream is not defined`

The error appears on both Thunderbird 60 and Thunderbird 65b1. Any ideas why this could happen?

**Comment by tomholub** [comment]
Try the compat version, in case Thunderbird js api is dated.

**Comment by pbrunschwig** [comment]
The Thunderbird API is not dated. It's identical to Firefox, in other words 65b1 contains the API of the next Firefox release.

**Comment by twiss** [comment]
openpgp.js contains a polyfill setting `TransformStream` on the global object if `typeof TransformStream === 'undefined'`.
This is sort of a stab in the dark, but I've previously had weird edge cases in Firefox (when using `document.open`) where `window.somevar` would be set whereas `somevar` was undefined. Could you check whether `window.TransformStream` exists after loading openpgp.js? (Also try `this.TransformStream` in global scope perhaps.) There might be some weird issue where the global scope the code is executing in is not the global object that `window`/`this` points to.

**Comment by pbrunschwig** [comment]
There is indeed a weird issue, but it's not related to openpgp.js. Depending on how far Thunderbird is with starting up, `window.TransformStream` is available or not. It's definitely something on my side. Thanks for the hints.

**Comment by pbrunschwig** [comment]
I finally solved this issue on my side. The problem is that the polyfill loads TransformStream to `window.TransformStream`. But under the circumstances that I load the library in Thunderbird, that won't make TransformStream a global object, therefore `new TransformStream()` fails.

**Comment by juanpaucar** [comment]
@pbrunschwig How did you solve to avoid the polyfill? Right now I'm getting this error since I upgraded jsdom on a project with frontend and backend tests (including some test for pgp custom helpers)

**Comment by pbrunschwig** [comment]
My problem was not to _avoid_ the polyfill, but that it was not loaded. I solved it by extracting the polyfill and loading it explicitly before loading openpgp.js
