### ISSUE TITLE
clarify error messages: Invalid enum value.

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#833]
Some of our users get an `Invalid enum value.` when working with their legacy key. Because these are private keys, we don't get to investigate exactly what enum value that is, or even which type of enum is it trying to get.

I suggest that in 
```js
  /** Converts from an integer to string. */
  read: function(type, e) {
    if (!type[byValue]) {
      type[byValue] = [];
      Object.entries(type).forEach(([key, value]) => {
        type[byValue][value] = key;
      });
    }

    if (type[byValue][e] !== undefined) {
      return type[byValue][e];
    }

    throw new Error('Invalid enum value.');
  }
```
it could throw something like `Invalid enum value 123 for type s2k`

**Comment by sanjanarajan** [comment]
I agree this would be useful. If you would like to make a quick PR we can add this to the next release.

**Comment by tomholub** [comment]
I'll take a look, if I can get it done today, then I will.

Note: do the same thing for 
```
Error: Unknown s2k type.
at S2K.read (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:40048:15)
at SecretKey.decrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:37217:14)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:31411:29
at Array.map (<anonymous>)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:31409:35
at Array.map (<anonymous>)
at Key.decrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:31406:57)
```

**Comment by twiss** [comment]
> `Invalid enum value 123 for type s2k`

This seems potentially risky. Let's say an attacker can modify a non-MDC encrypted message, ask an oracle to decrypt it, doesn't have access to the decrypted text, but does get these error messages back. Then, this error message will tell them the last 5 bits of the first decrypted byte due to the call to `enums.read` when parsing the decrypted packets. The `enums.read` in literal.js could tell them the second byte, etc.

Even the type could leak some information, since the code path for packet parsing differs depending on the value of the first byte, and different packets involve different calls to `enums.read`. In most cases, the stack trace should be able to tell you which type the code was trying to read.

**Comment by tomholub** [comment]
Does this only seem to be an issue with on non-MDC messages?

Eg when MDC is in use, it seems we would need to make sure that such modification will throw MDC error before it throws `Invalid enum` error, and not the other way around, and there would have to be a test specifically for that.

**Comment by twiss** [comment]
There's other places an attacker could, in some cases, learn something — for example, when decrypting a message with a password, the call to `enums.read` in sym_encrypted_session_key.js could reveal a byte of data. There's also a call in public_key_encrypted_session_key.js, but only if the 2-byte checksum there is correct, which seems potentially brute-forceable.

> Eg when MDC is in use, it seems we would need to make sure that such modification will throw MDC error before it throws `Invalid enum` error

That's indeed the case. So the only thing an attacker could learn there is if e.g. a message is encrypted with an algorithm we don't support, and things like that, which doesn't seem too sensitive.

**Comment by tomholub** [comment]
Let's leave this open, and I'll hold off on this until the risks are better understood. Thanks for feedback @twiss

**Comment by twiss** [comment]
It may make sense to enable this only when `openpgp.config.debug` is set, add a warning not to set that option in production, and then provide a way for your users to temporarily enable it, perhaps? (There's other cool things you could do with a debug mode, like show stack traces in the UI, modify `util.print_debug_error` to show errors in the UI, etc.)

**Comment by tomholub** [comment]
Enabling this with a debug flag would work for us. I'll take this on. 

@sanjanarajan Please don't delay your upcoming release waiting for this

**Comment by tomholub** [comment]
@twiss is there a way to assign issues to me even though I'm not a member? I noticed I'm starting to lose track of issues I've taken on, being able to filter the issues by my name would help :)

**Comment by emilmuller** [comment]
> Some of our users get an `Invalid enum value.` when working with their legacy key. Because these are private keys, we don't get to investigate exactly what enum value that is, or even which type of enum is it trying to get.
> 
> I suggest that in
> 
> ```js
>   /** Converts from an integer to string. */
>   read: function(type, e) {
>     if (!type[byValue]) {
>       type[byValue] = [];
>       Object.entries(type).forEach(([key, value]) => {
>         type[byValue][value] = key;
>       });
>     }
> 
>     if (type[byValue][e] !== undefined) {
>       return type[byValue][e];
>     }
> 
>     throw new Error('Invalid enum value.');
>   }
> ```
> 
> it could throw something like `Invalid enum value 123 for type s2k`

**Comment by tomholub** [comment]
I'm closing this as not-so-improtant.
