### ISSUE TITLE
Keys with non-ASCII user Ids do not work 

### ISSUE THREAD

**Issue by az82** [openpgpjs/openpgpjs#845]
Handling of keys with user Ids containing non-ASCII UTF-8 characters is broken. 

## How to reproduce
```js
const key = (await openpgp.key.readArmored(unicode_key)).keys[0];

const primUser = await key.getPrimaryUser();
expect(primUser).to.exist;
```
You can use the key at https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0F96D906EF3359CB for testing. 

If you inspect `key.users`, you can see that the user Id is there, but `getLatestValidSignature` in`getPrimaryUser` fails. The string content seems broken, as if the string was parsed with a different encoding. Also, please note that [haraka/node-address-rfc2822](https://github.com/haraka/node-address-rfc2822) will quote names containing non-ASCII unicode characters, which might break signature verification. 

## See also
- Downstream issue in Mailvelope https://github.com/mailvelope/mailvelope/issues/623

**Comment by twiss** [comment]
This should probably still be fixed, but the user ID in that key seems to be Windows-1252 encoded, not UTF-8 encoded. (It contains the byte 0xF6 for "ö" instead of 0xC3 0xB6.)

The spec [says](https://tools.ietf.org/html/rfc4880#section-5.11):

> 5.11.  User ID Packet (Tag 13)
>
>   A User ID packet consists of UTF-8 text that is intended to represent
   the name and email address of the key holder.

**Comment by az82** [comment]
Thanks for pointing that out, I wasn’t aware of that. I’ll check how the offending keys were created.

**Comment by az82** [comment]
The keys were created with GnuPG using a Windows-1252 encoded settings file. Apparently GnuPG creates invalid keys in this case. I've raised an issue with GnuPG: [dev.gnupg.org/T4360](https://dev.gnupg.org/T4360).

In my opinion, this is not an issue with OpenPGP.js as the keys are clearly invalid. Of course, it would be nice if the keys worked anyway as they do with GnuPG.

**Comment by twiss** [comment]
Closing this, as it's indeed not a valid key. There's perhaps an argument to be made that we should be throwing on invalid UTF-8 when parsing keys (and messages), though - that's something we could do fairly easily by adding `{ fatal: true }` here: https://github.com/openpgpjs/openpgpjs/blob/038d8466fecb4299d21b68bd280ba419acede2f1/src/util.js#L338 That's a discussion for another issue, though.
