### ISSUE TITLE
Help with streaming decrypt, session keys error

### ISSUE THREAD

**Issue by nlfiedler** [openpgpjs/openpgpjs#849]
Neither the README nor the tests have exactly what I'm trying to do, which is encrypt a file using a stream, and then decrypt the file using a stream. The encrypted file decrypts just fine with `gpg` so I'm sure the output is valid. But when I try to decrypt using `openpgp`, I get an error about the session keys:

```
     Error: Error decrypting message: Session key decryption failed.
      at Message.decryptSessionKeys (node_modules/openpgp/dist/openpgp.js:33317:22)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm going to assume the encrypt code is fine, and just paste the decrypt here (I'm using Node v10):

```javascript
  const input = fs.createReadStream(infile)
  const readableStream = nodeToWeb(input)
  const options = {
    message: openpgp.message.fromBinary(readableStream),
    passwords: ['keyboard cat'],
    format: 'binary'
  };
  const plaintext = await openpgp.decrypt(options)  // << blows up here
```

Thanks for any help you can offer. I'd be happy to turn this into an example, once it's working, if that is helpful.

**Comment by lfern** [comment]
Take a look here: #655

**Comment by twiss** [comment]
@nlfiedler It shouldn't matter, but did you try passing the node stream to `fromBinary` directly (without the `nodeToWeb` in between)? That should be supported too. Other than that your code looks fine, so if it doesn't work it might just be a bug.

**Comment by nlfiedler** [comment]
The difference between `read()` and `fromBinary()` was _really_ hard to see in the API docs. Thank you for explaining, it's working now. And thanks @twiss for the tip on the stream, that is good to know.

**Comment by twiss** [comment]
Ah yeah I missed that, so I guess you're right that the API is confusing :/
