### ISSUE TITLE
Intermittent sign+verify failure

### ISSUE THREAD

**Issue by twiss** [openpgpjs/openpgpjs#854]
Two test failures that each happened once:

```
Brainpool Cryptography
  Encrypt and sign message:
      AssertionError: expected false to be true      
      at Context.<anonymous> (test/general/brainpool.js:213:45)
```

~and Unit Tests Crypto API functional testing Sign and verify DSA~ (fixed by #938)

**Comment by chesnokovilya** [comment]
I will try to investigate this, since it prevents travis test builds from successfully passing sometimes.

**Comment by twiss** [comment]
I think the brainpool one might have something to do with https://github.com/openpgpjs/openpgpjs/blob/6d626ea70ca080af410e1dfb1c4a9f0dda99bec3/src/crypto/public_key/elliptic/key.js#L225 stripping leading zeroes or some such.

**Comment by chesnokovilya** [comment]
example non-working signed + encrypted data for brainpool is here https://gist.github.com/chesnokovilya/accb5138bd077616067eff10ea35c1f6
