### ISSUE TITLE
How to change key's password?

### ISSUE THREAD

**Issue by torw4897dfz** [openpgpjs/openpgpjs#86]
As I see there is no code to change password for the key.  Or is it there?

I would like to try that today but maybe already someone did it?

Edit:
There are actually two problems here but they can probably be solved with the same code:
1. Set password for key without password (unencrypted key)
2. Change password for key which already has password (encrypted key)

**Comment by origliante** [comment]
@tanx I looked into it for an hour or so, key does have decrypt() and armor, and does not have encrypt(). How the reencryption is of the key is doable? Thanks

**Comment by tanx** [comment]
@origliante here is the code from [Whiteout Mail](https://whiteout.io/)

https://github.com/whiteout-io/mail-html5/blob/69387508036ccc443a5cc2f33730ce162c556536/src/js/crypto/pgp.js#L238-L259

**Comment by fpietrosanti** [comment]
Which is the keystore format? Is this something OpenPGP standard?

**Comment by origliante** [comment]
Thank you @tanx ;)
