### ISSUE TITLE
functions of openpgp not stubbed with sinon

### ISSUE THREAD

**Issue by jochenonline** [openpgpjs/openpgpjs#860]
I am trying to test my application and for that have to stub the functions of openpgp. Unfortunately it does not work:

```js
const openpgp = require("openpgp");
const sinon = require("sinon");
sinon.stub(openpgp, "generateKey");
// after the last statement openpg.generateKey stays the original version
```
This explicitely does not work with openpgp. I don't habe this problem with other libraries. Any hints what I am doing wrong?

**Comment by twiss** [comment]
This seems to have something to do with the way browserify defines exports using `Object.defineProperty`.

You can try something like

```js
Object.defineProperty(openpgp, "generateKey", { value: openpgp.generateKey, writable: true, configurable: true });
sinon.stub(openpgp, "generateKey");
```

or, alternatively, use `defineProperty` to set `openpgp.generateKey` to the stub after you create it.

**Comment by jochenonline** [comment]
I used you first solution. Works like a charm. Thank you!
