### ISSUE TITLE
gpg signature vs openpgpjs signature

### ISSUE THREAD

**Issue by rininove** [openpgpjs/openpgpjs#861]
I try make xep-0027 in xmpp, and can't sign status
Psi plus don't start encrypt

i check console in psi, and see what psi send sing status with some privkey
`<x xmlns="jabber:x:signed">iQEzBA...`
but then i try send with openpgp sign it send 
`<x xmlns="jabber:x:signed">wsDcBAEB...`

I check what i sign:
created key by
 `gpg --generate-key
`
with
qwerty
qwerty@gmail.com
without password

then sign blank file to check
`gpg -a --clear-sign -r qwerty 1.txt`

I make it 5 times. All 5 time file 1.txt.asc contains "iQ...."

> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA512
> 
> 
> -----BEGIN PGP SIGNATURE-----
> 
> iQEzBAEBCgAdFiEEbABL40Zn3aYfOvMtDmLEayTpxUAFAlxrwNsACgkQDmLEayTp
> xUDAUQf9Gc8uPL8twQuhudoL1mwkVWowx4RGBREVsRH1UvA2PRwvKzGlc/88LrPP
> een7cjBZ1IVH8243JAzH1l5ymBEtu+SuHwPyRV1w9k1A7RdzNFFalEJ2imgB+iNv
> YH+rglsssDqTQwsRbG77ZSoKGI2bukbYHKe01kTiuo9SLxH6F1/p4Od8JGVOJkRh
> L6PZ5j1UjA0PqjcZtwIQvIUsIQy3kJBpFHAZqaJi0oH4EWCTqCGcol+tXekRx1fS
> btsnSkQrha6eTEEyzUD3RU+Bek+xTOac2cmxkgQj+ApRHv4PWz6lrBB6yP/Ou+Rd
> dUoV6Dqc865098jP6m81/9pTkxNHug==
> =7krS
> -----END PGP SIGNATURE-----
> 
> 

Then i export keys
` gpg -a --export-secret-keys qwerty\n
 gpg -a --export qwerty\n
`

And put it to nodejs code

> const openpgp = require("openpgp");
> openpgp.initWorker({ path: "openpgp.worker.js" });
> 
> async function x() {
>   pubkey =`-----BEGIN PGP PUBLIC KEY BLOCK-----
> 
> mQGNBFxrv8kBDADdlkaHqCOQXhnhV+ALCYztwZv25CA8cIo9CXRPgsvnRJBvpjdy
> vW5euvkLMGAUTFAB3rks4OSZc+4v227bYQmjGJKtgSKJbQz3TWqoTio5kLqc27ya
> ZUBYey9KsAY2xM9THKpI6ZmBh1ts9CfhVSnehvnUtk41phWV4u9Vqu5pqpXr0V2b
> mMGDveRnFEl5F+rfmDgueAokEo0fxsr7GgM5s4cg8MSFZZV74bR1fU8jkPDzynQ3
> yDO7NZTl1Vh0YqsDybbPe78+OXRtMbEML0VUalGmreH8bXilbXSfkf0FPznhpXmR
> swnaQOGdBSHVxiB9J6pO0iJlqvOqODlFplEqTo/G2UfJiupNLus8R5PUci8ZzI6A
> dtMA7X6hLtdEQHONDSbq84VY6887iZkdXGcBTzh8FP2SbzLOXv/5VLPzd7DJbwVW
> pCnNAE4sfKW+OuygjEu5J1iBSmsHTOF73fQL8JGBquQJgYaWCaAsBIwF/i2+uOxG
> swVl3pNf/Z2lYW8AEQEAAbQZcXdlcnR5IDxxd2VydHlAZ21haWwuY29tPokB1AQT
> AQoAPhYhBK65u1tNEl03eObgjKcEOv+Wmig6BQJca7/JAhsDBQkDwmcABQsJCAcC
> BhUKCQgLAgQWAgMBAh4BAheAAAoJEKcEOv+Wmig6B5sMAMw2SUUBuVgCyc5QcJ9F
> TgFt21qPl1cir3GcITVe1Ui5P5Usd6UM1wl8YvQslsYCWVCFroBWJx6fwmAP7c7u
> 8HKwZ3RTr/Nx+rwFlYmXB9WJcLNxHh5b5iM4UHTdjlaajc9Shhs5kq7HqQH3sibr
> LbghVFMsGIiD818appHlrrVAlJbemtwcNtwWEH/1gN0Z2pHFpzQHIAiik8bNFYqR
> XHceqt4daNMsTaVRo4U/4u71pcKfkYzm6RlkBhSmiuV7ahnBFjHUojZhiKbax5cQ
> Qv/IY7kYY8lMd1vQ04gbewawPbC9HAWxMMn51EFQnVFR+RHzTIUtBGYpY9JcWFY6
> akFhFxPHQDqSeMFQQOAsCSHSWCY24pD1aopRSYYDiJectwXiyURI+v7a7tKlRB+O
> GzD5cBMz2ftZgPxSE8ZM3VhRxLUG9h1khrBEEKHd2xBwiMFTudwivOSkpW9z9fyu
> EroFAshYiMx1x0dX8ZUjL2vlkCW17ObmxdQUJp7ku0jNirkBjQRca7/JAQwA83oJ
> 6FhDMiCgHrxu+uCbiX/JBaR4qupd+iEXkK1oY206OqCQ1AVbZ7p48D3RQf0UawY6
> tu71VyzCBH+e2YiUCyEUYLba6e2W0r0K2Sj1OITvmJOwih0AB9JyIPlDiHkRbYuu
> KYn7GAdQyGOluN2jfXvdJjBKd7qgpV3lkNNhDQwPghtaWcoU/6RvPbo62Bibjzg6
> +USf4ANRJErjrEk7U9JwvlodZTs1CRLEfQ130hgfSVTSZiJAc50M/QuU+SyhHmuB
> 0+VHoNYJwM+/gyVxLrAi3Cul+L93+UgZfOBx69GMN52pbkAH17P1WHhJLMgpf0xZ
> HzQ8oo65/Hz+0QA8DU8uER5B9fP6PWRe05K6u1OkaTwkbcvqWfMqY7Ql5lR8eQqK
> eerPCOX75fyg/qvMstnSOZUjLpe60fFhX6g4AjPU8D0Hgh5M2WykrUmk6m9xy/hE
> 17Wf6jnwSiJ02JW2DuLCDOIKs+CSww9Xmtml8Vf+XfTNoxF+xiIqbBcCwPAxABEB
> AAGJAbwEGAEKACYWIQSuubtbTRJdN3jm4IynBDr/lpooOgUCXGu/yQIbDAUJA8Jn
> AAAKCRCnBDr/lpooOrHrC/9EvxalkJ8Y45aLBPCM79f30ThWlz897PTO4+Dq28ef
> qJwkXtktqq4t0eglAQn1uStxz/niPGbvOwtOqbV7UVp6XPNZXOWhqJ74UjGOuM0E
> hsIl6fyW4brHixeI1Mzlhjx8n9jSn5RiqlO2tqZv+lLwUmagVFGO+b8AaBSY1pKn
> CEX7OaJ2W9F41Q70QSR72T0HvBlikzqrP4x5vp1ixitGEZKs2culjdKwgtt1DgJi
> NEyHsPxoPVK2vD7QFmNcYq2N1mIu6/c8iYMnJbHDLQOuxvkySi91iM1xt1MxlYh3
> EzDYVP04m0+ggtx5/YgEE/7EtXhGXn3cuYq5nalUZDYt6eZoZloGYR8iLa+sO1pt
> sZFvR010H7wZdHQDg2vM/GDJoiN/6C5qQv7QukdAlHQnNOeJOjHfSWVwZIvVr9yf
> utxaRVbsM7iIc4xnCT7PfY9CJBxSpWBCNXhIxfrOUozifVx9t3jaYBb6P008UJgp
> MpML9YmxiJY1uXk5KJAA7C4=
> =9tDo
> -----END PGP PUBLIC KEY BLOCK-----`;

>   const privKeyObj = (await openpgp.key.readArmored(
>     `-----BEGIN PGP PRIVATE KEY BLOCK-----
> 
> lQVYBFxrv8kBDADdlkaHqCOQXhnhV+ALCYztwZv25CA8cIo9CXRPgsvnRJBvpjdy
> vW5euvkLMGAUTFAB3rks4OSZc+4v227bYQmjGJKtgSKJbQz3TWqoTio5kLqc27ya
> ZUBYey9KsAY2xM9THKpI6ZmBh1ts9CfhVSnehvnUtk41phWV4u9Vqu5pqpXr0V2b
> mMGDveRnFEl5F+rfmDgueAokEo0fxsr7GgM5s4cg8MSFZZV74bR1fU8jkPDzynQ3
> yDO7NZTl1Vh0YqsDybbPe78+OXRtMbEML0VUalGmreH8bXilbXSfkf0FPznhpXmR
> swnaQOGdBSHVxiB9J6pO0iJlqvOqODlFplEqTo/G2UfJiupNLus8R5PUci8ZzI6A
> dtMA7X6hLtdEQHONDSbq84VY6887iZkdXGcBTzh8FP2SbzLOXv/5VLPzd7DJbwVW
> pCnNAE4sfKW+OuygjEu5J1iBSmsHTOF73fQL8JGBquQJgYaWCaAsBIwF/i2+uOxG
> swVl3pNf/Z2lYW8AEQEAAQAL/1X8FVxYw4wm59YIunit+RDdmz7f4R5y8UGkJI0i
> DSut8HpSvpt4pJZ/6VoNKItX3YgMPEEM98gQM3JArTDV4951D53iSVuYhHqGgQfU
> ZRA3eCKcJgCnn6N2EbDiw1aHYog2zGFEvHuF4dVSnRMUcA3YxKNlJs4sp52lFQhi
> Luez+T8r3C4fxZ/wlOvm9GfX/x1KvSpTDGRZCog1JNjxjCTc5GfE5g15kNskh1k8
> CfScLtP7UMPAnUpdDW1uL0fibQ8nnsPS++Y16dUZM4z2BTO9kdzYFnpJdJHYybKg
> ybSB6z4JdrxdIzwfj1mQNakken3wjrWxEx/b9+bIgLKqUfQqf07gHmgKIcKY2Qla
> G2BXVy9yfs6wvUiBTdkoznx63gHjK+AA7P4vx6VzN2kgZ5a3XfB/3Am0VbDjfYLC
> ODxt3qcXOZBvbbCXGHFosBP1geAhuM1WHpYmsPggo109Rb+dTyQk19zauQSAn8jR
> ERhfs+LHpqvi/16UStd8tIacoQYA5ISojIxwadZtKP9N25kYsaF9dr6jZNcxmf/P
> L1ZvJb/Y2gEBCcNB77mgHjR9XsWq5Q8v/phgT8ywJi5o5D78X61rKCsAaQ4VsMR/
> zrzBSjXk6/mR1boeTdVPO1S8J3XgjoIpcyou21d3BOy4xcF4w35LdX+Qw4T4/jK+
> z3E71+sp82725L94JvH/kJIozcF9SyQv73BU4ILHXRNt0FFG6In6mae/zwfDQfiq
> 9zyThhhLmiQLgL/LejVR3GXTgp0/BgD4PDptuEHcsYvZ/tIPYbdng/feYGscvys8
> 8QxaiNdQnjw3n0TNHVXuWHjmX4DYn/dL0lQEoPODKzlkNEJmyfx+ZtfrdqDtLlgp
> gtWggd2y/MPf320yrdkY8OHUxxgMpCK0ml/BSJ4+O8qqpnNwmiDQahIAS091eILc
> +b9Deu3ZMJbFgznN9hE/5MMxkpfKRr3tEmnaS444Y05F5WHF7/Y99Jly1C5y7COs
> Eh9mexBaSBv1slkaK11CEJ/EujoPv9EF/iJ4EBtYKdG0TzMUkuKRLqyhoWDtGM35
> ophzfYzahEQCBUE68Xl5y2Qsa/UcsoaPDdWoV4s6vCmtNSZl7YKZaU6Y+ptEVh/J
> bPNkCvTt8dGrZJPH7GR9QXZHIIbQ04loAEUutE3jauh9f95jHuDlCR06ujVcDwEK
> To+OSwM40PL+TeBPZiv9jLFM572hOZW5S6sr1yDVa0AmnYByUEb37p5pn4CBuUq8
> dOD7ipGWyBYt2ThmmqCpKciWStCJQFU6SeqLtBlxd2VydHkgPHF3ZXJ0eUBnbWFp
> bC5jb20+iQHUBBMBCgA+FiEErrm7W00SXTd45uCMpwQ6/5aaKDoFAlxrv8kCGwMF
> CQPCZwAFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQpwQ6/5aaKDoHmwwAzDZJ
> RQG5WALJzlBwn0VOAW3bWo+XVyKvcZwhNV7VSLk/lSx3pQzXCXxi9CyWxgJZUIWu
> gFYnHp/CYA/tzu7wcrBndFOv83H6vAWViZcH1Ylws3EeHlvmIzhQdN2OVpqNz1KG
> GzmSrsepAfeyJustuCFUUywYiIPzXxqmkeWutUCUlt6a3Bw23BYQf/WA3RnakcWn
> NAcgCKKTxs0VipFcdx6q3h1o0yxNpVGjhT/i7vWlwp+RjObpGWQGFKaK5XtqGcEW
> MdSiNmGIptrHlxBC/8hjuRhjyUx3W9DTiBt7BrA9sL0cBbEwyfnUQVCdUVH5EfNM
> hS0EZilj0lxYVjpqQWEXE8dAOpJ4wVBA4CwJIdJYJjbikPVqilFJhgOIl5y3BeLJ
> REj6/tru0qVEH44bMPlwEzPZ+1mA/FITxkzdWFHEtQb2HWSGsEQQod3bEHCIwVO5
> 3CK85KSlb3P1/K4SugUCyFiIzHXHR1fxlSMva+WQJbXs5ubF1BQmnuS7SM2KnQVY
> BFxrv8kBDADzegnoWEMyIKAevG764JuJf8kFpHiq6l36IReQrWhjbTo6oJDUBVtn
> unjwPdFB/RRrBjq27vVXLMIEf57ZiJQLIRRgttrp7ZbSvQrZKPU4hO+Yk7CKHQAH
> 0nIg+UOIeRFti64pifsYB1DIY6W43aN9e90mMEp3uqClXeWQ02ENDA+CG1pZyhT/
> pG89ujrYGJuPODr5RJ/gA1EkSuOsSTtT0nC+Wh1lOzUJEsR9DXfSGB9JVNJmIkBz
> nQz9C5T5LKEea4HT5Ueg1gnAz7+DJXEusCLcK6X4v3f5SBl84HHr0Yw3naluQAfX
> s/VYeEksyCl/TFkfNDyijrn8fP7RADwNTy4RHkH18/o9ZF7Tkrq7U6RpPCRty+pZ
> 8ypjtCXmVHx5Cop56s8I5fvl/KD+q8yy2dI5lSMul7rR8WFfqDgCM9TwPQeCHkzZ
> bKStSaTqb3HL+ETXtZ/qOfBKInTYlbYO4sIM4gqz4JLDD1ea2aXxV/5d9M2jEX7G
> IipsFwLA8DEAEQEAAQAL/RVDMNbO0G1x/nG4tHtpvoODOo+o1ZXdekAEAE4U6rMW
> IJnqmEM/xYP5O6MFTv8zhgMzq9B6bUgD41yntXxbSkxvgttQVK1Nn5h/RFGDG2ko
> aNEbArWJA03rkaZyBjUGl6BIrLi5cUlfqC0b0KbkiijE9qLlYDd0/575ZHkhkI3m
> YftTfrAtLujFWCacmxNwkLMw7quCk/Co8X7ZIGlVCt6O1+Qzs/H5ee/1KN4f3Tkm
> fKL3ipk7QAQosK/vgT7CaBMHrDZwYrb7Fn1AfCAal24M6b4cBqRfah/qJSBhB1pk
> KpS8EwWLV4iWQg4JgV4UAd6S8BOzeDQw7+gvW4zm0YWscDEubXzJw+BUsEUoxh/8
> qK3Y09YSsEBzZWj/jtYVTrQD9HbakWqol6cif0jUXMWTYYg8aKkoox2SJrqFr3cR
> BLB026zlMllFCZp436gLtP+MwRjsRcLfiPGgU8UjbOkQkDPZIx2y3tqgRQokuZ3Z
> NjFHcAqefQ6SihXwwIVp0QYA9yVy/lCWseIJSIKqmBFJQVzKkNsSgMtDrptGE296
> SOjf/eXtnX1J+IY2hCEFoMrWStk5Iay1BU0JPmEA43Tt7gGPfj+GOZe7sqqyW07s
> Liub5Um0PrImS/aiLf6Bsauewu0nT/cll0AynjKNxSmhnUZYB2UqBksz5RfVbMFs
> dXnB7OM/KVf0j25rViI9t42a/NjqLLsmUatjvhjCOOLwyY6SijakY2qBK6lPUKpU
> Q3g5uF1jw9e/FWTBDAvuko1ZBgD8Mu+vqB6Pns3U7TKXsVAN9odQv6PgtWo1wHi4
> mE7aF+t9MmephDHZJkTqkaP7CXXYMR6Ngz1sNDvHotpeBe92j8rC7UkMzotFiVmM
> KA/HNtTXTP8q1spu/7Py+VvN3TLF6JWu/84cvSHp4jAmdUryJKpgQwKrsM9sRezC
> QCHg0dY0OiQ7nd1ZwRWAD3Sqgc1cDgxfH1izqTo0EIYQMj+YnfG+E/IxGy/AKg2v
> AVYaqis2dy68kd6veNKRx2eBZpkF/jVMP6hWVf9YBI50EaY34t76IF3CieWJnTDo
> SCa4zjrqmSuz5BntNxSm+4UwWn317bcUlsbEjRFi/ukCUprdwT+gxbetj2XCXrO5
> XtaAMK45oHkAOaHe6aEmq3DaRrmsUqrvlKuQTxUstGH+aEOpczQHtIZJupj9QDIY
> NPjfaMs/nBnSzMreqZHpV+pNh5YuuLd0vtvvHagS5/KE6zPkuop1W8GW0dA9AYiX
> dZVE3BvCFE9Ilj9FrFqJc07G8Sw2yeOjiQG8BBgBCgAmFiEErrm7W00SXTd45uCM
> pwQ6/5aaKDoFAlxrv8kCGwwFCQPCZwAACgkQpwQ6/5aaKDqx6wv/RL8WpZCfGOOW
> iwTwjO/X99E4Vpc/Pez0zuPg6tvHn6icJF7ZLaquLdHoJQEJ9bkrcc/54jxm7zsL
> Tqm1e1FaelzzWVzloaie+FIxjrjNBIbCJen8luG6x4sXiNTM5YY8fJ/Y0p+UYqpT
> tramb/pS8FJmoFRRjvm/AGgUmNaSpwhF+zmidlvReNUO9EEke9k9B7wZYpM6qz+M
> eb6dYsYrRhGSrNnLpY3SsILbdQ4CYjRMh7D8aD1Strw+0BZjXGKtjdZiLuv3PImD
> JyWxwy0Drsb5MkovdYjNcbdTMZWIdxMw2FT9OJtPoILcef2IBBP+xLV4Rl593LmK
> uZ2pVGQ2LenmaGZaBmEfIi2vrDtabbGRb0dNdB+8GXR0A4NrzPxgyaIjf+guakL+
> 0LpHQJR0JzTniTox30llcGSL1a/cn7rcWkVW7DO4iHOMZwk+z32PQiQcUqVgQjV4
> SMX6zlKM4n1cfbd42mAW+j9NPFCYKTKTC/WJsYiWNbl5OSiQAOwu
> =cUHb
> -----END PGP PRIVATE KEY BLOCK-----
> `
>   )).keys[0];
> 
>   cleartext = "";
> 
>   options = {
>     message: openpgp.cleartext.fromText(""),
>     privateKeys: [privKeyObj]
>   };
> 
>   await openpgp.sign(options).then(function(signed) {
>     cleartext = signed;
>   });
> 
>   if (cleartext.data) console.log(cleartext.data);
>   else if (cleartext.signature) console.log(cleartext.signature);
>   else console.log(cleartext);
> }
> 
> x();

And try again 5 times, all output has "ws.."

> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA512
> 
> 
> -----BEGIN PGP SIGNATURE-----
> Version: OpenPGP.js v4.4.7
> Comment: https://openpgpjs.org
> 
> wsDcBAEBCgAGBQJca8F8AAoJEKcEOv+Wmig6OVMMAI0qE8I2+JPLQbXZDvbK
> zfgOLpsVlG0hEfXAvGXdUp9lCJY6w+0Sfnad05pre+vkkj8wSKneMDEBI2fT
> FaJz3318BgdMStwX2civFm55nyKjLTpu3MHBp2mOFwS4T2vlSR1usKiUudnH
> gaMjJpZOwz2dgyBw9ZZRH7oRjfkqsbiBdGBiZahR1sxJZ2UTKqdUUd43GAEN
> 304myB1lTnItrtKNah7QqHSRb6i86Bvog+TteEcNeX0VdnJQzodCCvqc6pJL
> ZLa5Dl3xBmfdT3PXcbVXqCTB75L7VbSk471h+3tWav+qqfvnAm5GxKO939DN
> 8JhWmsWhNnM6FYzxKPblhHq14mX/4DY9cc9B1h3hyuR0VFol+YZtbpmoHfes
> 973+RU4wya9/ftLOb5F4jHtzAdagCtbNmOSoxAZpkvZzXQqqlk6nuxpu6FgJ
> FNsqkN1WVrU91biZMhcd6SnpyHOuEVLM8pP1882T9bH+p6LtVN6+DTwAAC8H
> W3DezU/+0o4Ysg==
> =zBUg
> -----END PGP SIGNATURE-----

Why in gpg sign start with "iQ.." and openpgpjs start with "ws..."

**Comment by twiss** [comment]
The start of the signature contains a length, which is different based on the encoding of the rest of the signature. That's why it starts with "ws" instead of "iQ". This by itself shouldn't be a problem, but another difference in the encoding could be.

Do you have another problem, or error?

**Comment by twiss** [comment]
Actually, you exported a different key than you used to sign with. The `-r` parameter is to choose the _recipient_, not which key to sign with. You can use `--local-user qwerty` for that.

Or, if the GPG signature is signed with the correct key, you need to export that (and not `qwerty`).
