### ISSUE TITLE
can encrypt/decrypt or signe message with another key ???

### ISSUE THREAD

**Issue by arsenal120496** [openpgpjs/openpgpjs#872]
I wonder if i can use another key (key generate by CA , self create key, .... ) or what ever external key to encrypt/decrypt???

**Comment by twiss** [comment]
Hi @arsenal120496, OpenPGP.js is compatible with other PGP software, so yes, you can use keys you generated yourself with other software. GnuPG is one example of such software. CAs use a different system of certificates and are not compatible.
