### ISSUE TITLE
Problem with the await command

### ISSUE THREAD

**Issue by BloggoDoggo** [openpgpjs/openpgpjs#873]
I have been working on an auto role embed with reactions. It will not let me use await. There are no errors but the await issue. I need major help! This is all my code:

const { RichEmbed} = require('discord.js');
const { prefix } = require('../config');

exports.run = async (client, message, args) => {

    await message.delete().catch(O_o=>{});

    const a = message.guild.role.get(`556479251428278282`) // Member
    const b = message.guild.role.get(`556479444810727444`) // Memers

    const filter = (reaction, user) => ['a', 'b', 'c'].includes(reaction.emoji.name) && user.id === message.author.id;

    const embed = new RichEmbed()
        .setTitle('Available Roles')
     .setDescription(`
    
        🇦 ${a.toString()}
        🇧 ${b.toString()}
        🇨 ${c.tostring()}
    
        `)
        .setColor('RANDOM')
        .setFooter(`ID : ${message.author.id}`)

    message.channel.send(embed).then(msg => {

        await msg.react('🇦');
        await msg.react('🇧');
        await msg.react('🇨');

        msg.awaitReaction(filter, {
            max: 1,
            time: 30000,
            error: ['time']
        }).then(collected => {

            const reaction = collected.first();

            switch (reaction.emoji.name) {
                case '🇦':
                    if (message.member.roles.has(a)) {
                        msg.delete(2000)
                        return message.channel.send('You already have this role!');
                    }
                    message.member.addRole(a).catch(err => {
                        console.log(err);
                        return message.channel.send(`Error adding you to this role: **${err.message}**.`);
                    });
                    message.channel.send(`You have been added to the **${a.name}** role!`).then(m => m.delete(3000));
                    msg.delete();
                    break;
                case '🇧':
                if (message.member.roles.has(b)) {
                    msg.delete(2000)
                    return message.channel.send('You already have this role!');
                }
                message.member.addRole(b).catch(err => {
                    console.log(err);
                    return message.channel.send(`Error adding you to this role: **${err.message}**.`);
                });
                message.channel.send(`You have been added to the **${b.name}** role!`).then(m => m.delete(3000));
                msg.delete();
                    break;
                case'🇨':
                if (message.member.roles.has(c)) {
                    msg.delete(2000)
                    return message.channel.send('You already have this role!');
                }
                message.member.addRole(c).catch(err => {
                    console.log(err);
                    return message.channel.send(`Error adding you to this role: **${err.message}**.`);
                });
                message.channel.send(`You have been added to the **${c.name}** role!`).then(m => m.delete(3000));
                msg.delete();
                    break;
            }

        }).catch(collected => {
            return message.channel.send(`I couldn't add you to this role!`)
        });

    });

 };

 exports,help = {
     name: 'roles'
 };

**Comment by twiss** [comment]
Not sure if you closed it because you figured it out, or because it doesn't seem to have anything to do with openpgp.js 🙃 but:

```diff
-message.channel.send(embed).then(msg => {
+message.channel.send(embed).then(async msg => {
```

should do the trick.

**Comment by BloggoDoggo** [comment]
Yea sorry about that. I closed it because I got it but a new problem has appeared in my code

I'm continuing my auto role with reactions, but it will not work and I'm so confused on where I'm messing up

**Comment by twiss** [comment]
No worries, however, since I don't know much about react and this still doesn't seem to have anything to do with openpgp.js I can't help you further, unfortunately. Good luck!

**Comment by BloggoDoggo** [comment]
Ok, thanks for your help. Hopefully I can get more help.
