### ISSUE TITLE
"npm install --save openpgp" errors when git is not installed (minor issue)

### ISSUE THREAD

**Issue by verysimplyms** [openpgpjs/openpgpjs#877]
Extremely minor issue, but the docs should make a small note saying that git should be installed when attempting to use "npm install --save openpgp." I tried installing openpgp by accident without git installed and wasted more time than I'd like to admit.

**Comment by twiss** [comment]
Good idea :+1: Would you like to open a PR for this? Perhaps it should also mention that you need to be logged in (https://github.com/openpgpjs/openpgpjs/issues/764) if that issue still applies?
