### ISSUE TITLE
OpenPGP should not rely on global polyfills - can’t decode keys

### ISSUE THREAD

**Issue by natesilva** [openpgpjs/openpgpjs#878]
When running under Node.js, OpenPGP polyfills `global.TextEncoder` and `global.TextDecoder`.

If another module loads the `fast-text-encoding` polyfill first, then OpenPGP fails to decode keys with this error:

`Error: Invalid key: need at least key and user ID packet`

One such module is the current version of `@google-cloud/speech`.

**Workaround:**

Ensure OpenPGP loads first. Or polyfill `global.TextEncoder` and `global.TextDecoder` with a working implementation before any other module tries to polyfill.

_this still might fail if either OpenPGP’s or a 3rd party polyfill does not perfectly implement the spec as required by the other module_

**Suggestion:**

The `TextEncoder` and `TextDecoder` APIs are only used once each, in `src/util.js`. Why not use a [ponyfill](https://github.com/sindresorhus/ponyfill) or something that doesn’t depend on global namespace.

**Comment by natesilva** [comment]
This may be fixed on Google’s side soon: https://github.com/googleapis/google-auth-library-nodejs/issues/626

But it could break at any time if some other module uses a bad polyfill. OpenPGP should avoid depending on the global namespace.

**Comment by twiss** [comment]
Hey @natesilva! I agree that OpenPGP.js writing to `global` is bad. However, since Node.js 11, TextEncoder and TextDecoder are already available on the global object by default. So reading them from the global object should not normally be an issue - and since that version, OpenPGP.js doesn't write to the global object anymore either. Neither does `fast-text-encoding`, it looks like. Does using Node 11+ fix your issue?

**Comment by natesilva** [comment]
We’re on Node 10 (LTS). It’s more that OpenPGP.js shouldn’t _read_ from global since it was getting a bad version of `TextEncoder`/`TextDecoder`. For us, we’ll keep an eye on the issue until we can switch to the next Node.js LTS that has global versions of those APIs.

**Comment by twiss** [comment]
Reading TextEncoder/TextDecoder from the global object really shouldn't be an issue - it's the only place they exist in the browser, and they exist there in Node 11+. If someone overwrites them with a broken version, that's not our fault. There's even legitimate use cases for overwriting the TextEncoder that OpenPGP.js uses, e.g. see https://github.com/openpgpjs/openpgpjs/issues/821#issuecomment-449544822. Even if we change our behavior to use a ponyfill but default to the native (global) version for performance, which would be reasonable, that still wouldn't fix your issue.

**Comment by twiss** [comment]
Closing - feel free to, if you feel like it, open another issue to not write polyfills to global though, we should fix that.

**Comment by ruipimentel** [comment]
For anyone else suffering from this problem on Node 10, installing `text-encoding` package (`npm install text-encoding`) and then inserting the following lines at the beginning of my code solved for me:

```js
const { TextDecoder, TextEncoder } = require('text-encoding');
global.TextDecoder = TextDecoder;
global.TextEncoder = TextEncoder;
```

For `TextEncoder` specifically, MDN has a [working polyfill](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#polyfill).

**Comment by jomel** [comment]
> For anyone else suffering from this problem on Node 10, installing `text-encoding` package

Actually, you can avoid the extra dependency, as Node 8 & 10 actually already include those functions in the bundled `util` package, you just need to hoist them to global...
```
    // polyfill stuff for openpgp in Node 8 and 10 
    global.TextDecoder = require('util').TextDecoder; 
    global.TextEncoder = require('util').TextEncoder; 
```
See my other comment: https://github.com/openpgpjs/openpgpjs/issues/900#issuecomment-1285445728
