### ISSUE TITLE
About Passphase

### ISSUE THREAD

**Issue by arsenal120496** [openpgpjs/openpgpjs#881]
I'm a newbie. I wonder if i can change or customize the passphase

The default passphase in words: "super long and hard to guess secret". I know i can change the position of any words. But I want to change these 7 words to others. Can i??????

Somebody can help me this situation????? Tks a lot.

**Comment by tomholub** [comment]
This library is meant for developers with a decent knowledge of the basics of programming and cryptography. 

I would recommend to start with software meant for end users to familiarise yourself, like gnupg or mailvelope or others. 

You can, and should, be choosing a completely different pass phrase, yes.
