### ISSUE TITLE
Generating a key in Electron causes an infinite loop.

### ISSUE THREAD

**Issue by claunia** [openpgpjs/openpgpjs#883]
Hi,

When trying to generate a new key it enters a catch() loop in `dist/openpgp.js` lines 289, then catch at 277, then catch at 720, then back at 289 and repeat, infinitely.

OpenPGP.JS version: 4.4.10
Electron version: tried with 3, 3.1 and 4.0
IDE: WebStorm

Example code:
```javascript
    const pgpGenerationOptions =
              {
                  userIds:    [{name: "REDACTED", email: "REDACTED"}],
//                  numbits: 4096,
                  curve:    "brainpoolP512r1",
// Changing the algorithm makes no difference
                  passphrase: ""
              };

    // Generate a new key
    var keys = await openpgp.generateKey(pgpGenerationOptions);
    // Never gets out. Using .then() makes no difference.
```

EDIT: The exception message is `Writer was released and can no longer be used to monitor the stream's closedness`

**Comment by twiss** [comment]
Hi @claunia! Could you post a full stack trace of that error?

Also, as a workaround, you could try using the streams polyfill rather than the built-in version, by setting:

```js
window.TransformStream = undefined;
```

before loading openpgp.js.

**Comment by chesnokovilya** [comment]
closing as stale
