### ISSUE TITLE
How to check if browser is supported

### ISSUE THREAD

**Issue by dabit1** [openpgpjs/openpgpjs#890]
Hi! I don't find any way to check whether the user browser is supported by openpgpjs or not. I would need it in order to alert to the user that its browser will not encrypt messages.

Does anyone know how to do it?

Thanks!

**Comment by twiss** [comment]
Hey :wave: First off, there's a list of browsers supported by both of the builds at https://github.com/openpgpjs/openpgpjs#platform-support. The compat build has fairly wide browser support. Furthermore, if you don't use the worker, that should fix various compat issues with old Safari.

I think the easiest way to check whether a browser can encrypt though, is to just try it. Encrypt a tiny message in a try/catch and show a warning if it fails.

Alternatively, one browser API that OpenPGP.js depends on, and that you could check for (although I'm not sure that its existence alone guarantees that OpenPGP.js will work, it's pretty likely that it will), is [getRandomValues](https://caniuse.com/#search=getrandomvalues). This is how we check for its existence:

https://github.com/openpgpjs/openpgpjs/blob/cc4a9119a3e1577e36fdb5a72a25fc8c6d7e3163/src/crypto/random.js#L40-L55

So you could either do something like that and alert if it doesn't exist, or call that function (`await openpgp.crypto.random.getRandomBytes()`) and see if it throws.

**Comment by twiss** [comment]
(Let me know if you still have questions)

**Comment by dabit1** [comment]
I did not do it yet, but I'll let you know in that case. Thank you so much!
