### ISSUE TITLE
OpenPGP should not write polyfills to global

### ISSUE THREAD

**Issue by jpreynat** [openpgpjs/openpgpjs#900]
Following of #878 to prevent openpgp to write polyfills to global.
We are using Node 8 on Google Cloud Functions and cannot switch to Node 11+ yet since Node 10 is still in beta there.

We encounter the same issue while reading an otherwise totally valid key: `Error: Invalid key: need at least key and user ID packet`.

**Comment by twiss** [comment]
Hi! As you know I agree with the title of this issue, however, I don't see how it could cause the issue you're having. Since this is about *writing* polyfills to global, that should if anything be causing issues for *other* modules, not for openpgp.js itself.

Does the workaround in the other issue work for you? Does your code work when running locally in Node 11?

**Comment by jpreynat** [comment]
Hi @twiss, thanks for your quick answer.

I understand your point, and that I've been confused by the proposed solution.
I didn't have the chance to test the code locally, since it is designed to run on a serverless environment and cannot easily be emulated with Node 11.

To give a little more context, we are using `openpgp` through another module of ours, `github-api-signature`, that automatically generates a PGP signature for GitHub commits given its content.
The implementation of the method we are using can be found [here](https://github.com/GitbookIO/github-api-signature/blob/master/src/createSignature.ts).
We were initially using `openpgp@^2.6.2`, which works perfectly. I recently updated our `github-api-signature` module to switch to TypeScript and updated the code to use the latest version of `openpgp@^4.4.4`.

After deploying the update in production, all signatures failed to generate with the `Error: Invalid key: need at least key and user ID packet` error in the Cloud Functions environment, while testing it locally works like a charm.

After testing a few things, here are two of my results:
- I first tried adding a simple homemade polyfill in our webpack build to define `global.TextEncoder` and `global.TextDecoder` using native `util.TextEncoder` and `util.TextDecoder` from Node 8, only if they weren't defined. This didn't work, I still got the same error. Note that we are using `@babel/polyfill` and the homemade polyfill was placed after babel in the build.

- I then removed the condition to unconditionally use native Node utils.
`openpgp` didn't fail in this case, but the commit was created with an `Unverified` status, while with the older version using `openpgp@^2`, the signature is always verified.

We are also using `@google-cloud/storage` which requires `fast-text-encoding`, and this module most likely already hacks the global scope and makes the version of `TextEncoder` and `TextDecoder` available to `openpgp` invalid. So this might be a first issue.

However, there might be another problem with key validations, since when forcing the use of native Node modules, the created signature seems invalid to GitHub with version 4 of `openpgp`.

**Comment by twiss** [comment]
> I then removed the condition to unconditionally use native Node utils.
openpgp didn't fail in this case

Alrighty. If you want another way to do this without monkey-patching openpgp.js, you could do something like `global.TextEncoder = undefined` before loading openpgp.js.

> but the commit was created with an Unverified status, while with the older version using openpgp@^2, the signature is always verified.

This is a bit of a guess based on your mention of v2, but probably you need to use `openpgp.cleartext.fromText` instead of `openpgp.message.fromText`?

**Comment by jpreynat** [comment]
Thanks for the answer @twiss.
I will try switching to `cleartext` instead of `message` to see if that fixes my specific issue.

However, I don't think that users of the module should have to worry about setting `global.TextEncoder` to `undefined`.
Since `openpgp` is only compatible with NodeJS >= 8, `TextEncoder` and `TextDecoder` should never have to be polyfilled in a Node environment, and can always be required from the `util` native module when the module is used with Node.

**Comment by twiss** [comment]
> However, I don't think that users of the module should have to worry about setting global.TextEncoder to undefined.

This is a workaround for something that `fast-text-encoding` is doing, not something that openpgp.js is doing.

> Since openpgp is only compatible with NodeJS >= 8, TextEncoder and TextDecoder should never have to be polyfilled in a Node environment, and can always be required from the util native module when the module is used with Node.

We're not polyfilling them in this case, we're simply reading them from global. Please see https://github.com/openpgpjs/openpgpjs/issues/878#issuecomment-477286883. Yes, your specific case would be fixed by always using the version from `util`, but it also has issues, so that might break stuff for other people.

Closing this issue, however, everyone feel free to open another issue or PR addressing the writing of polyfills to global (as opposed to reading them), if you like.

**Comment by jomel** [comment]
@twiss
I get the whole "we did not cause this problem, complain to those who did" logic,
BUT from my perspective, you guys should really improve your documentation & version enforcement.

### **openpgp >= v5.0.0 won't work with Node < 11** (out of the box)
V5 is what you get when you simply try adding openpgp to your project (`npm install openpgp`).

Yes, it's (relatively) easy to make it work, by 

- manually polyfilling
simplest by adding the below before using openpgp:
```
    // polyfill stuff for openpgp in Node 8 and 10 
    global.TextDecoder = require('util').TextDecoder; 
    global.TextEncoder = require('util').TextEncoder; 
```

- or use an older version
`npm install openpgp@4.10.10`
(the polyfills [were removed in the 5.0.0 release](https://github.com/openpgpjs/openpgpjs/commit/ab419179bcc37b1dd598b3cf041b7b200d6f9208))


I think the node version (in)compatibility **should be made clear in the docs** / getting started / examples. (a [note on node versions was removed in 5.0.0 release](https://github.com/openpgpjs/openpgpjs/commit/4edd85be69b782bce10a9ec74ddd8fd3acf7339e#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L41))

I would also suggest the addition of ["engines" declaration](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines) in your package.json set to ">=8" in v4 branch (& do a 4.10.11 bugfix release) and ">=11" in v5 branch - this will **warn people when attempting to 'install' an incompatible package version**.




And before someone asks: no, I cannot move my legacy project (where I attempted to use openpgp) to a newer version of Node, as management have refused to allocate the time for this.

**Comment by twiss** [comment]
Hi @jomel, this is not the right issue for that discussion, since it's completely unrelated to *writing* polyfills to global. Could you open a new issue for that? And, feel free to open a PR with your suggestion, as well.
