### ISSUE TITLE
Encrypt inputed files in Electron based app 

### ISSUE THREAD

**Issue by jose123455587** [openpgpjs/openpgpjs#904]
Hi,
I'm trying to make a electron app that you can encrypt and decrypt files.
But i'm having a problem with fuction in js and html. In debug console say that I don't have a function called encrypt(), but it is not true.
Here is my code.
html
`<form method="post">
    <div>
      <div>
        <h6>Public Key</h6>
        <input type="file" id="pubkey"/>
        </div>
          <div>
            <h6>File to Encrypt</h6>
            <input type="file" id="file"/>
            </div>
              <button type="submit" value="Submit" onclick="Encrypt()" >Encrypt</button>
      </div>
    </form>`

and js 
`var openpgp = require("openpgp");
 
function Encrypt(){

  //get inouted files in html
  const pubkey = document.getElementById("pubkey");
  const filetoencrypt = document.getElementById("file");

  openpgp.initWorker({});// initialise openpgpjs
  const file = fs.readFileSync(filetoencrypt);
  const fileForOpenpgpjs = new Uint8Array(file);

  //get public key
  const pubkeypgp = fs.readFileSync(pubkey);
  const pubkeyForOpenpgpjs = new Uint8Array(pubkeypgp);
  const openpgpPublicKey = openpgp.key.readArmored(pubkeyForOpenpgpjs);

  //encrypt
  const options = {
    data:  fileForOpenpgpjs,
    publicKeys: openpgpPublicKey.keys,
    armor: false
  };

  const encryptionResponse = await openpgp.encrypt(options); // note the await here - this is async
  const encryptedFile = encryptionResponse.message.packets.write();

  fs.writeFileSync('/tmp/file-encryped', encryptedFile);
}`

what should I do?

**Comment by twiss** [comment]
`await` can only be used in `async` functions, so try `async function Encrypt`.

If you have any other questions (that aren't about bugs 🙂) please post them in https://gitter.im/openpgpjs/openpgpjs instead.
