### ISSUE TITLE
Decrypt Uint8Array data with PGP keys

### ISSUE THREAD

**Issue by zjzeit** [openpgpjs/openpgpjs#906]
The examples show the following:

- Encrypt and decrypt Uint8Array data with a password
- Encrypt and decrypt String data with PGP keys

But not `Encrypt and decrypt Uint8Array data with PGP keys` which is my goal. Below is the code. If I omit `sessionKeys` and use `privateKeys` in the options, I get an error:

>Error decrypting message: Session key decryption failed.

This led me to using `sessionKeys` without knowing what is really happening. When I view `plaintext`, it is the exact same thing as `fileToDecrypt` (my input file I'm trying to decrypt). Please let me know the proper way to decrypt a file using PGP keys. The closest issue I found was [429](https://github.com/openpgpjs/openpgpjs/issues/429) which did not resolve my issue.

```
var privateKey = $('#inputfield').val();
const privateKeyObj = openpgp.key.readArmored(privateKey).keys[0];
var keyPassphrase = $('#inputfield2').val();

reader.onload = function(e){
   var fileToDecrypt = new Uint8Array(e.target.result);
   console.log(e);
   var options = {
      message: openpgp.message.fromBinary(fileToDecrypt),
      //message: openpgp.message.read(fileToDecrypt),
      //privateKeys: [privateKeyObj],
      sessionKeys: [privateKeyObj],
      format: 'binary', // output result as Uint8Array
      armor: false // Don't ASCII-armor, just keep it as a binary blob
   };
   
   openpgp.decryptKey({
      privateKey: privateKeyObj,
      passphrase: keyPassphrase
   }).then(function(){
      openpgp.decrypt(options).then(plaintext => {
         console.log(plaintext); // plaintext.data contains the same data as fileToDecrypt -> not desired
         var blob = new Blob([plaintext.data], {type: "application/octet-binary;charset=utf-8"});
         var url = URL.createObjectURL(blob);
      })
   }).catch(error => {
      console.log(error);
   });
```

**Comment by twiss** [comment]
Hi! It's probably easiest to start with the "Encrypt and decrypt String data with PGP keys" example, remove the first options object and call to `openpgp.encrypt()`, and (as you did) add `format: 'binary'` to the second options object.

Then, for the input, if you open the encrypted file locally, is it a text file or a binary file? If it's text, you need to convert the Uint8Array to string with `openpgp.util.Uint8Array_to_str` and keep using `openpgp.message.readArmored`. If it's binary, you should pass the Uint8Array to `openpgp.message.read` (not `fromBinary`).
