### ISSUE TITLE
Error when encrypting: Could not find valid key packet for encryption in key

### ISSUE THREAD

**Issue by Pietro89** [openpgpjs/openpgpjs#910]
have a error when trying to encrypt a string with a pgp public key: 'Could not find valid key packet for encryption in key 9ae788ff8eec0b31'

This error doesn't appear with every key but with most of them. Here one of the keys that errors:

`-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.43

mI0EXQJU0gEEAKZKsTmlR71mPgzQR6hyGJXR4tuoH/RgJPnZGCKPlJqCj8GCvlTa
Jqy5gUZQJItwS4ssFU56+fI1a47oe08covHWgLAsGRWCxsD/oneFhddPhhZkHOui
s1CW3CNDQ8hhl/DykhUoegKCmvNDzRVsD4y7ueLkzAisu3MH3ShQWDB/ABEBAAG0
CUxJTlhPIFNBU4icBBABAgAGBQJdAlTSAAoJEPa8OTh7Vcnz4kID/0KL7RBA5Z83
WuirfaVXF+Kqi4QXQO4EBUUknSbO+igRSJ/MLV4NROuhn2AZ3YWXK9B8rLsaZy9Q
49/rr1lPn648Wq2lAoN7uLwtycspFQscjLT76hDMnoOvJGzjrpi+xC7n0W7ggLRN
TkCUB8b+OBvwPhptny8kS6DASwew0Fp7
=2Sis
-----END PGP PUBLIC KEY BLOCK-----`

Here is the function im using to encrypt

`async function pgpEncrypt(pubkey, message) {`
    `await openpgp.initWorker({ path: 'openpgp.worker.js' })`
    `const options = {`
        `message: await openpgp.message.fromText(message), // input as Message object`
        `publicKeys: await openpgp.key.readArmored(pubkey).keys, // for encryption`
    `}`
    `const cipherText = await openpgp.encrypt(options)`
    `return cipherText.data`
`}`

openpgp.js version is 4.5.2

What's wrong with this? how can i ensure the key works with this library?

**Comment by tomholub** [comment]
We use OpenPGP.js too and this key works just fine when I run it through our compatibility check:

```
(1) Primary keys found: 1  
(2) PK 0 > Is Private? [-] false  
(3) PK 0 > Primary User: [-] LINXO SAS  
(4) PK 0 > Fingerprint: [-] C7AB 85A1 EC31 7837 79DE 756B F6BC 3938 7B55 C9F3  
(5) PK 0 > Subkeys: [-] 0  
(6) PK 0 > Primary key algo: [-] rsa_encrypt_sign  
(7) PK 0 > Primary key verify: [-] 3  
(8) PK 0 > Primary key expiration? [-] Infinity  
(9) PK 0 > Encrypt/Decrypt test: Encryption with key was successful  
(10) PK 0 > Encrypt/Decrypt test: Skipping decryption because isPrivate:false isDecrypted:null  
```

Maybe you copied another key. Try to find specifically the one with longid `9ae788ff8eec0b31`.

**Comment by Pietro89** [comment]
This one too:
Error encrypting message: Could not find valid key packet for encryption in key 26459c97e4c91294

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.43

mI0EXQs/VwEEAPTlK3xYFbzruJhv+XY979aIyZKRiEYz+/NRLJHlkrSoXjh5XHxD
6syoyiLHDqVPCsuhBkdfKIaPsxlOyRZczHAENng40RZ+6pe/7MNM9BnJoD3tN2YQ
rnIAgiLxf19S5vsHS8DFDgr+S5cn+WHggyKibrV11eFQl6mHXdBqBToDABEBAAG0
CUxJTlhPIFNBU4icBBABAgAGBQJdCz9XAAoJECZFnJfkyRKU0bED/1JsMWwLK3Xu
tfgJ3PWtP8ddaRag8iVBj30EZK8hDCVP7M/0GxD5TlHZLsAMFkweIPHyi+M3jP0l
Ua7VThGq57ypHTdHDAe1BnNbHYO4gySPbQnCP/jdiqVZsbhzQJ/jAVaG72wXmx6V
CUP7IXEQ/jNfzJpry0jxkTI6owTma1C9
=Me3W
-----END PGP PUBLIC KEY BLOCK-----

**Comment by twiss** [comment]
Hi :wave: I can't reproduce your error either, but there is a small syntax issue in your code:

```diff
-publicKeys: await openpgp.key.readArmored(pubkey).keys, // for encryption
+publicKeys: (await openpgp.key.readArmored(pubkey)).keys, // for encryption
```

That would lead to a different error than the one you're seeing, though.
