### ISSUE TITLE
Session key decryption failed when attempting to decrypt plain text

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#913]
I managed to write the following:
```js
const m = openpgp.message.fromBinary(encryptedData);
await m.decrypt(undefined, [pwd]); // Error: Session key decryption failed.
```
That took some head-scratching to fix, considering I've worked with the library for a while:
```js
const m = await openpgp.message.read(encryptedData);
await m.decrypt(undefined, [pwd]); // success
```
In this situation a better error may be appropriate, eg `Error: Cannot decrypt plain data`. That would still be weird, but at least I would not need to double check the password 10 times? A better error may be `Error: Cannot decrypt plain data. Use openpgp.message.read() or openpgp.message.readArmored()` though not sure if that is too much guessing.

**Comment by twiss** [comment]
I agree, I've seen the same mistake made before. I think fixing #907 would already improve the error message a bit. PR welcome, if you like :)

**Comment by larabr** [comment]
After merging #1289  , the thrown error is now `Session key not found`, which is more accurate than before, and should be clearer.
