### ISSUE TITLE
openpgp.initWorker is not a function

### ISSUE THREAD

**Issue by shawndewet** [openpgpjs/openpgpjs#915]
Please help...I am trying to get this working in an existing ASP.Net MVC Web Application.

I first started by adding the following html script tags:
```
<script src="@Url.Content("~/Scripts/openpgp.min.js")"></script>
<script src="@Url.Content("~/Scripts/openpgp.worker.min.js")"></script>
```

and I got this error on loading my page:

> ReferenceError: importScripts is not defined

So I did some research and added RequireJS to my page, like so:
```<script data-main='@Url.Content("~/Scripts/openpgp.min.js")'  src="@Url.Content("~/Scripts/require.js")"></script>```

Then in the event handler in which I intend to run my decryption logic, I have the following code:
```
async function decryptBBRecording(commId) {
        var openpgp = require(['openpgp']);
        await openpgp.initWorker({ path: 'openpgp.worker.js' }) // set the relative web worker path
...
...
...
}
```

and it is on that "await" line that I am getting 

> TypeError: openpgp.initWorker is not a function

I'm thinking this is because I have not loaded the openpgp.worker.min.js file.  But when I do so via script tag, I get the following errors:

> ReferenceError: importScripts is not defined

and when I do so via `require(["@Url.Content("~/Scripts/openpgp.worker.min.js")"]);` I get this:

> Error: Script error for "openpgp"
> ReferenceError: importScripts is not defined

Please can you provide me with guidance on how to get this working?

**Comment by twiss** [comment]
Hi! You don't have to include `openpgp.worker.min.js` on the page directly. You also shouldn't need require.js and the call to `require`. Just include `openpgp.min.js` on the page, it will globally define `openpgp`, and then call `openpgp.initWorker` as you are doing.

**Comment by shawndewet** [comment]
@twiss great that did it thanks a mil!

**Comment by twiss** [comment]
:+1: No problem!
