### ISSUE TITLE
Revoke a key - revocationCertificate not revocationSignature

### ISSUE THREAD

**Issue by rushglen** [openpgpjs/openpgpjs#929]
docs are wrong at https://openpgpjs.org/openpgpjs/doc/

when generating a key pair
`openpgp.generateKey(options).then(function(key) {
    var privkey = key.privateKeyArmored; // '-----BEGIN PGP PRIVATE KEY BLOCK ... '
    var pubkey = key.publicKeyArmored;   // '-----BEGIN PGP PUBLIC KEY BLOCK ... '
    //var revocationSignature = key.revocationSignature; // '-----BEGIN PGP PUBLIC KEY BLOCK ...'  
    //should be:

    var revocationCertificate = key.revocationCertificate;
});`

also when revoking a key substitute revocationSignature with revocationCertificate
var options = {
    key: openpgp.key.readArmored(pubkey).keys[0],
    //revocationSignature: revocationSignature
    revocationCertificate: revocationCertificate
};`

**Comment by twiss** [comment]
Thanks, good catch, I'll update them. In the meantime, the examples in the [readme](https://github.com/openpgpjs/openpgpjs#examples) should be more up to date.

**Comment by twiss** [comment]
(The documentation at https://openpgpjs.org/openpgpjs/ has been updated for v5.)
