### ISSUE TITLE
NojoJs: Generate Keys returns  Error: Error generating keypair: Failed to encode: the 'stream' option is unsupported

### ISSUE THREAD

**Issue by lugaliguori** [openpgpjs/openpgpjs#934]
Hello I'm trying to generate a new key pair but im gettin " Error: Error generating keypair: Failed to encode: the 'stream' option is unsupported"

this here is my code 

var openpgp = require('openpgp')
await openpgp.initWorker({ path:'../node_modules/openpgp/dist/openpgp.worker.js' })
    var options = {
        userIds: [{ name:'Jon Smith', email:'jon@example.com' }], // multiple user IDs
        numBits: 512,                                            // RSA key size
        passphrase: 'super long and hard to guess secret'         // protects the private key
    };
    openpgp.generateKey(options).then(function(key) {
        var privkey = key.privateKeyArmored; 
        var pubkey = key.publicKeyArmored;   
        var revocationCertificate = key.revocationCertificate; 
    });

it just the example code but I can't get it to work.

tried it with both initworker and without init worker

nodejs version 9.8.0

**Comment by twiss** [comment]
Your code works fine for me using Node 9.8.0. It seems that this error is thrown by `fast-text-encoding`, which we don't use by default. It's possible that you're using a package that includes it (and writes it to global scope), such as `googleapis/google-auth-library-nodejs`; see previous discussion and various workarounds in #878.

**Comment by lugaliguori** [comment]
thank you, yes the error was exactly, that I was using calling the package
googlecloud/storage, changing the order of the packages solved the issue
