### ISSUE TITLE
RSA secret key param coefficient u: RFC3447 vs RFC4880 inconsistency

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#936]
Today I learned something. Since I spent all this effort writing up what ended up being a non-bug, I'll go ahead and post it, in case someone hits the same roadblock and can google this.

TL;DR

- RFC3447 PKCS RSA defines a coefficient `u` equal to `(inverse of q) mod p`
- RFC4880 has RSA coefficient `u` be `the multiplicative inverse of p, mod q`

The spec does differ. Read the (correct) spec, Luke.

----------------------

Original version:

I'm exporting openpgp-nodejs generated RSA private key in a base64 encoded [DER format per RFC3447](https://tools.ietf.org/html/rfc3447#appendix-A.1.2):

```
      RSAPrivateKey ::= SEQUENCE {
          version           Version,
          modulus           INTEGER,  -- n
          publicExponent    INTEGER,  -- e
          privateExponent   INTEGER,  -- d
          prime1            INTEGER,  -- p
          prime2            INTEGER,  -- q
          exponent1         INTEGER,  -- d mod (p-1)
          exponent2         INTEGER,  -- d mod (q-1)
          coefficient       INTEGER,  -- (inverse of q) mod p
          otherPrimeInfos   OtherPrimeInfos OPTIONAL
      }
```
I was doing this in `publicKeyDecrypt`, because I was going to extract the private key & encrypted session key and pass that to a faster native RSA implementation to decrypt.

The parameters are spelled out nice and tidy (copying from dist OpenPGP.js lib):
```js
          const c = data_params[0].toBN();
          const n = key_params[0].toBN(); // n = pq
          const e = key_params[1].toBN();
          const d = key_params[2].toBN(); // de = 1 mod (p-1)(q-1)
          const p = key_params[3].toBN();
          const q = key_params[4].toBN();
          const u = key_params[5].toBN(); // q^-1 mod p
```
I use asn1 to format them as DER, based on the RFC linked above:
```js
            // structure
            const RSAPrivateKey = asn1.define('RSAPrivateKey', function() {
              this.seq().obj(
                this.key('version').int(),
                this.key('modulus').int(),
                this.key('publicExponent').int(),
                this.key('privateExponent').int(),
                this.key('prime1').int(),
                this.key('prime2').int(),
                this.key('exponent1').int(),
                this.key('exponent2').int(),
                this.key('coefficient').int(),
              );
            });

            // two lines copied from RSA decrypt implementation elsewhere in the lib
            const dq = d.mod(q.subn(1)); // d mod (q-1)
            const dp = d.mod(p.subn(1)); // d mod (p-1)

            // data
            var derRsaPrv = RSAPrivateKey.encode({
              version: 0,
              modulus: n,
              publicExponent: e,
              privateExponent: d,
              prime1: p,
              prime2: q,
              exponent1: dp, //         INTEGER,  -- d mod (p-1)
              exponent2: dq, //        INTEGER,  -- d mod (q-1)
              coefficient: u, //       INTEGER,  -- (inverse of q) mod p
            }, 'der');

            // export
            console.log(derRsaPrv.toString("base64"))
```
So far so good, but the exported key is unusable. I read RFCs, stare at the code, double check everything.

Out of desperation I run the exported key through openssl. Error:
```bash
$ openssl rsa -check -in node-exported-rsa.key -noout
error:04FFF07E:rsa routines:CRYPTO_internal:iqmp not inverse of q
```
Here `iqmp` refers to the `coefficient`, or `u` as we name it - the last param.

I dig into the BN library and write something like:
```js
console.log("coefficient 'u' (iqmp) supposed to be (inverse of q) mod p or 'q^-1 % p'")
console.log(`current        : ${u.toString(10)}`)
console.log(`newly computed : ${q.invm(p).toString(10)}`)
```
The numbers differ.

I export the rsa key using the newly computed coefficient instead of the one parsed from the key:
```js
            // data
            var derRsaPrv = RSAPrivateKey.encode({
              version: 0,
              modulus: n,
              publicExponent: e,
              privateExponent: d,
              prime1: p,
              prime2: q,
              exponent1: dp, //         INTEGER,  -- d mod (p-1)
              exponent2: dq, //        INTEGER,  -- d mod (q-1)
              coefficient: q.invm(p), //       INTEGER,  -- (inverse of q) mod p
            }, 'der');

            // export
            console.log(derRsaPrv.toString("base64"))
```

Run this modified version through openssl, works:

```bash
$ openssl rsa -check -in node-exported-rsa-3.key -noout
RSA key ok
```

The exported key now works in my native code, too. I can decrypt the session key with it fine.

Trying to look for the culprit, I start looking into key parsing, etc, and finally I'm looking at RSA `generate`:

```js
    return {
      n: p.mul(q),
      e: E,
      d: E.invm(phi),
      p: p,
      q: q,
      // dp: d.mod(p.subn(1)),
      // dq: d.mod(q.subn(1)),
      u: p.invm(q)
    };
```
Notice the last line:
```js
      u: p.invm(q)
```
Based on the spec
```js
          coefficient       INTEGER,  -- (inverse of q) mod p
```
this sounds like it should be:
```js
      u: q.invm(p)
```
Switching it does break the tests.

I headed instead to [OpenPGP RFC4880](https://tools.ietf.org/html/rfc4880#section-5.5.3) and re-read it carefully:

> MPI of u, the multiplicative inverse of p, mod q.

vs [RFC3447](https://tools.ietf.org/html/rfc3447#appendix-A.1.2):

> (inverse of q) mod p

Opposite, which explains the mystery.

**Comment by tomholub** [comment]
To my excuse, the library does feature an incorrect comment:
```js
          const u = key_params[5].toBN(); // q^-1 mod p
```
Wrong as per the PGP spec, unless my mind got corrupted, it should be:
```js
          const u = key_params[5].toBN(); // p^-1 mod q
```

**Comment by twiss** [comment]
Interesting. The first note on https://tools.ietf.org/html/rfc3447#page-8 explains:


      for compatibility with the representations of RSA private keys in PKCS
      #1 v2.0 and previous versions, the roles of p and q are reversed
      compared to the rest of the primes.  Thus, the first CRT
      coefficient, qInv, is defined as the inverse of q mod p, rather
      than as the inverse of R_1 mod r_2, i.e., of p mod q.

**Comment by twiss** [comment]
To follow up on this - I think you could just reverse the two primes; i.e. do something like
```
        p: prv.prime2,
        q: prv.prime1,
        dp: prv.exponent2,
        dq: prv.exponent1,
        u: prv.coefficient
```
and then you wouldn't have to recompute `u`? I haven't tried this though, maybe there's some issue with it I'm missing.

**Comment by tomholub** [comment]
Interesting, that will be worth taking a look. You may be right.

**Comment by twiss** [comment]
Swapping `p` and `q` has now been done in #999, so I'll take that as an excuse to close this issue 🙂
Thanks for bringing it up, since it helped find that performance improvement ^.^

**Comment by tomholub** [comment]
Thanks!
