### ISSUE TITLE
Cannot verify the signature - Error: No cleartext signed message.

### ISSUE THREAD

**Issue by wisecat57** [openpgpjs/openpgpjs#942]
I have a signature and public key I want to verify it but code doesn't work. It says "No cleartext signed message."

`function verifySign(pubkey,signature){
    let sync = true;
    let result;
    const verifySomething = async() => {
        options = {
            message: await openpgp.cleartext.readArmored(signature), // parse armored message
            publicKeys: (await openpgp.key.readArmored(pubkey)).keys // for verification
        };
        
        openpgp.verify(options).then(function(verified) {
            validity = verified.signatures[0].valid; // true
            if (validity) {
                console.log('signed by key id ' + verified.signatures[0].keyid.toHex());
                result = true;
                sync = false;
            }else {
                result = false;
                sync = false;
            }
        });
    }
    verifySomething();

    while(sync){ require('deasync').sleep(100);}
    return result;
}`

**Comment by twiss** [comment]
Could you post an example signature? It's most likely that your issue is pretty much what the error says, i.e. "your signature is not a cleartext signed message" :) Maybe it's a regular signed message (in which case you need `message.readArmored`) or perhaps it's a detached signature.

**Comment by wisecat57** [comment]
> 
> 
> If you have a regular signed message, you probably need `message.readArmored` instead of `cleartext.readArmored`. If that doesn't work either, could you post an example signature?

thanks it worked.
