### ISSUE TITLE
key.encrypt(passphrase): MPI.toUint8Array: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#943]
What could possibly cause the situation below? We're seeing a bunch of these, but could not reproduce ourselves.
```
TypeError: Cannot read property 'length' of null
	at MPI.toUint8Array (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:41380:32)
	at MPI.write (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:41367:48)
	at write_cleartext_params (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:38726:24)
	at SecretKey.encrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:38820:21)
	at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:33020:5
	at async Promise.all (index 0)
        // our code below just calls key.encrypt(passphrase). We check that pp is a truthy string
        //      and the key should be decrypted at the point we're calling it
	at <async> openpgpKeyEncrypt (/extension/js/common/settings.ts:65:29)
	at <async> <anonymous> (/extension/chrome/settings/modules/change_passphrase.ts:89:75)
```
My best guess is maybe if we called the encrypt method second time while the first one is still at work? Could that possibly cause this?

Or is it a bug in openpgp? Or wrong usage?

Thanks for taking a look :100:

**Comment by twiss** [comment]
> My best guess is maybe if we called the encrypt method second time while the first one is still at work? Could that possibly cause this?

Yeah, I think you would get this error simply by calling `key.encrypt` twice in a row, even. The reason is that that function calls `clearPrivateParams`. So the intention is that the key can no longer be used as a private key after encrypting it; that includes encrypting it again.

If you don't want this behavior, you could pull out some of that function and do something like:

```js
await Promise.all(key.getKeys().map(key => key.keyPacket.encrypt(passphrase)));
```

**Comment by tomholub** [comment]
Actually, it doesn't (seem to) behave the way you descibe. That's why it got my attention.
```js
let = { privateKeyArmored } = await openpgp.generateKey({userIds: [{email: "hello@user.com"}], passphrase: "my pp"});
let {keys: [k]} = await openpgp.key.readArmored(privateKeyArmored);
await k.decrypt('my pp')
await k.encrypt('my pp')
await k.encrypt('my pp') // fine
await k.encrypt('my pp') // fine
await k.encrypt('my pp') // fine
```

**Comment by tomholub** [comment]
Another test, could not get it to fail when attempting to encrypt concurrently either:
```js
(async() => {
	let = { privateKeyArmored } = await openpgp.generateKey({userIds: [{email: "hello@user.com"}], passphrase: "my pp"});
	let {keys: [k]} = await openpgp.key.readArmored(privateKeyArmored);
	console.log(`isDecrypted: ${k.isDecrypted()}`);
	await k.decrypt('my pp')
	console.log(`isDecrypted: ${k.isDecrypted()}`);
	await Promise.all([k.encrypt('my pp'), k.encrypt('my pp'), k.encrypt('my pp'), k.encrypt('my pp')])
	console.log(`isDecrypted: ${k.isDecrypted()}`);
	await k.encrypt('my pp');
	console.log(`isDecrypted: ${k.isDecrypted()}`);
})().then(() => console.log('success')).catch(console.error)
```
![image](https://user-images.githubusercontent.com/6306961/62933941-deb8eb80-bdb2-11e9-9167-74ab9e769045.png)

**Comment by tomholub** [comment]
Not that I would necessarily want/need it to fail when re-encrypting. Although that's also a fine thought. I'm more interested it why could have it failed above ¯\\\_(ツ)\_/¯

**Comment by twiss** [comment]
Right, you're right that it doesn't throw right away. But trying to use the key after that does throw:

```js
let = { privateKeyArmored } = await openpgp.generateKey({userIds: [{email: "hello@user.com"}], passphrase: "my pp"});
let {keys: [k]} = await openpgp.key.readArmored(privateKeyArmored);
await k.decrypt('my pp')
await k.encrypt('my pp')
await k.encrypt('my pp')
// At this point, the key is "broken"
await k.decrypt('my pp') // Still doesn't throw, though
// Using the key for anything at this point (decrypting, signing) will throw
await k.encrypt('my pp') // Error
```
Perhaps that's what's happening?

Arguably this is a bug and should be fixed in one way or another, perhaps by throwing in the second call to `encrypt`.

**Comment by tomholub** [comment]
Whoa, I'm super glad I brought it up. Because I think a similar bug has haunted me in the past, where somewhere in the middle of the process, I would `.armor()` and save the broken key, and next time pull my hair, not understanding what's going on.

It would be great if we could throw just before the key would have otherwise gotten into a broken state. Then we can catch the issue wherever it's actually happening.

**Comment by twiss** [comment]
> Because I think a similar bug has haunted me in the past, where somewhere in the middle of the process, I would .armor() and save the broken key, and next time pull my hair, not understanding what's going on.

Hmhm :/ I agree, what it's doing currently is super dangerous behavior because of that.

**Comment by tomholub** [comment]
For the time being, I'll work around it as follows:
```js
  static openpgpKeyEncrypt = async (key: OpenPGP.key.Key, passphrase: string) => {
    if (!passphrase || passphrase === 'undefined' || passphrase === 'null') {
      throw new Error(`Encryption passphrase should not be empty:${typeof passphrase}:${passphrase}`);
    }
    const privateKeyPackets = key.getKeys().filter(k => k.keyPacket.tag === openpgp.enums.packet.secretKey);
    const encryptedPackets = privateKeyPackets.filter(p => !p.isDecrypted());
    if (!privateKeyPackets.length) {
      throw new Error(`No private key packets in key to encrypt. Is this a private key?`);
    }
    if (encryptedPackets.length) {
      throw new Error(`Cannot encrypt a key that has ${encryptedPackets.length} of ${privateKeyPackets.length} still encrypted`);
    }
    await key.encrypt(passphrase);
  }
```
Which should mimic the intended future behavior.

**Comment by tomholub** [comment]
Actually, working on this, I think I may have a solution to the earlier `isDecrypted` dilemma when only some packets are decrypted. I think we should have two methods:

```js
// every dev needs to know one of the two, based on context - better be explicit
prv.isFullyDecrypted();
prv.isFullyEncrypted();
```
In this case, `isEncrypted` would be removed from documentation, but still functional. In v5 one day, the implementation could be replaced with exception: `isEncrypted deprecated: Use isFullyDecrypted or isFullyEncrypted`

I'll make another issue for this, and would be happy to contribute the PR. I'd be thrilled to have a way to be very explicit about this, for easier security reviews.

**Comment by twiss** [comment]
So I think `isFullyDecrypted` / `isFullyEncrypted` is not a bad idea, but shouldn't be needed just to fix this issue. The above PR fixes it at a slightly lower level.

**Comment by tomholub** [comment]
Absolutely, that is an unrelated observation I had.
