### ISSUE TITLE
Error decrypting message: Session key decryption failed.

### ISSUE THREAD

**Issue by wisecat57** [openpgpjs/openpgpjs#944]
That's the code that I'm using.
`function decryptData(encryptData){
        let result;
        let sync = true;
        const encryptDecryptFunction = async() => {
            console.log('working');
            var privKeyObj = (await openpgp.key.readArmored(current_secret)).keys[0];
            await privKeyObj.decrypt(current_pass);
            const options = {
                message: openpgp.message.fromText(encryptData),       // input as Message object
                privateKeys: [privKeyObj]
            }
        
            openpgp.decrypt(options).then(plainText => {
                result = plainText.data // '-----BEGIN PGP MESSAGE ... END PGP MESSAGE-----'   
                sync = false;
            }).catch((err) => {
                console.log(err);
                result = false;
                sync = false;
            })
        }`

**Comment by twiss** [comment]
You probably need `message.readArmored` instead of `message.fromText` - please see the examples in the README ;)

**Comment by wisecat57** [comment]
> 
> 
> You probably need `message.readArmored` instead of `message.fromText` - please see the examples in the README ;)

I did that now I get this error ' Parameter [message] needs to be of type Message or CleartextMessage'

**Comment by twiss** [comment]
You probably need to add an `await` before it ^.^

**Comment by wisecat57** [comment]
> 
> 
> You probably need to add an `await` before it ^.^

const options = {
                message: await openpgp.message.readArmored(encryptData),       // input as Message object
                privateKeys: [privKeyObj]
            }
that's my finale code and it stills give me the ' Parameter [message] needs to be of type Message or CleartextMessage'

**Comment by twiss** [comment]
That's.. strange. I'm not sure how that could happen. And that code works for me. I'm tempted to say, are you sure you're running the new code?

If it still doesn't work, could you post the full code with an example message and key?

**Comment by wisecat57** [comment]
Can you send the function that you have been using ?

**Comment by twiss** [comment]
See e.g. https://github.com/openpgpjs/openpgpjs#encrypt-and-decrypt-string-data-with-pgp-keys
