### ISSUE TITLE
reformat code whitespaces, add linter

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#949]
Here's what happens when I paste that into vscode (default settings):

```js
const test = function (a, b = 1) { // "function (" also appears quite often
  if (a + 1 === b) {
    try {
      someFn(b);
    } catch (e) { }
  }
  const arr = [a];
  const obj = { b };
};
```
That's really close, maybe except for spaces around `=` in args. But if the above is cool with you, the advantage is that it's the default of a very popular JS IDE. I can contribute the auto-format whitespace-only-PR to bootstrap some consistency. Thoughts?

_Originally posted by @tomholub in https://github.com/openpgpjs/openpgpjs/pull/947#issuecomment-521984523_

**Comment by tomholub** [comment]
> Hmhm +1 The only downside / argument for keeping it the way it is is to keep `git blame` clean. But that spacing does make a bit more sense so I think it's OK. Perhaps wait a bit until #931 is merged to make a PR, though, since that PR is rather large?
> 
> Also, if we're talking about ideals, it would be nice to make `npm lint` enforce this spacing at some point :)

> Yeah, I think we should switch to `const test = function(a, b = 1) ` since this is airbnb style. There is eslint rule for it `space-infix-ops=error`.

**Comment by chesnokovilya** [comment]
Hey! My point is about spaces inside function  `function(a, b = 1) `. In the codebase we have a lot of  `function(a, b=1) `. So I think I could fix it. Other than that I do not have any preferences.

**Comment by twiss** [comment]
I think you two were in agreement :)

@tomholub I'll leave this open in case you want to make a PR changing the other stuff at some point (`function (`, `catch (`...)
