### ISSUE TITLE
refactor with ES6 classes?

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#952]
Throughout the codebase, there are things like:

```js
function SecretKey(date = new Date()) {
  PublicKey.default.call(this, date);
  this.xxx = yyy;
}

SecretKey.prototype.someMethod = function () {
  // ...
};
```
These represent classes, but are quite awkward to look at & use.

Proposed alternative:
```js
class SecretKey extends PublicKey {

  constructor(date = new Date()) {
    super(date);
    this.xxx = yyy;
  }

  someMethod() {
    // ...
  }

}
```
Is there any known downside to this, other than the amount of work it will involve?

**Comment by chesnokovilya** [comment]
We would need to include poly-fills for the `class`. It seems there is support for it in core-js, so it could be done.

**Comment by chesnokovilya** [comment]
Hey @tomholub, do you want to try implementing it?

**Comment by tomholub** [comment]
@chesnokovilya my time availability is super unreliable. I could get to this in 3 months, or in 2 years. But as long as this stays open, there is some chance I'll one day make a PR for it :) ..

**Comment by tomholub** [comment]
But what I'd recommend is to make this incremental, eg maybe just refactor one tiny class somewhere in the periphery of the library. It it turns out well, then the "ES6" classes could slowly nibble away at the rest of the codebase over time.

**Comment by chesnokovilya** [comment]
Yeah, you could mark this issue as `help wanted`, or `good first contribution`.

**Comment by chesnokovilya** [comment]
will be closed by https://github.com/openpgpjs/openpgpjs/pull/1047
