### ISSUE TITLE
Use camelCase for the object and functions, and PascalCase for constructors.

### ISSUE THREAD

**Issue by chesnokovilya** [openpgpjs/openpgpjs#955]
There are mixed naming such as `des_addPadding` or `Uint8Array_to_MPI`. I propose to switch to the camelCase everywhere: `desAddPadding`, `Uint8ArrayToMPI`. 

This would help with constructor naming, for example, use `new TypeMPI`. Now we have  `new type_mpi` which is not standard and require rules exception.

**Comment by twiss** [comment]
Hmhm :+1: `des_addPadding` is an internal function, so we can easily change that, but `Uint8Array_to_MPI` is a public function, so we'd probably have to wait until v5 if we want to rename that (even if that specific function is probably not used much, but e.g. `Uint8Array_to_str` probably is).

**Comment by chesnokovilya** [comment]
ok, could you create a milestone v5 than, and add this issue to it?
