### ISSUE TITLE
Encrypt with multiple keys

### ISSUE THREAD

**Issue by wisecat57** [openpgpjs/openpgpjs#957]
Hi, I'm trying to encrypt string with multiple keys but I get that error;
`TypeError: Error encrypting message: key.getPrimaryUser is not a function
`
Here is my code;
https://gist.github.com/wisecat57/8a1f55ed9b129c3c1154180e5398e263

**Comment by tomholub** [comment]
You have to read/parse each pubkey first. So you run `const k = await openpgp.key.readArmored('----BEGIN...')` on each of the keys, then pass array of key objects, not the strings.

**Comment by wisecat57** [comment]
> You have to read/parse each pubkey first. So you run `const k = await openpgp.key.readArmored('----BEGIN...')` on each of the keys, then pass array of key objects, not the strings.
I used that code to do that, is that wrong ? 
`pubkeys = pubkeys.map(async (key) => {
            return (await openpgp.key.readArmored(key))
        });`

**Comment by tomholub** [comment]
I missed that, sorry.

Anyway, your map returns promises. You need to await these, eg `publicKeys: await Promise.all(pubkeys)`

**Comment by wisecat57** [comment]
> I missed that, sorry.
> 
> Anyway, your map returns promises. You need to await these, eg `publicKeys: await Promise.all(pubkeys)`

Thanks it worked.
