### ISSUE TITLE
Find Email from Public Key

### ISSUE THREAD

**Issue by wisecat57** [openpgpjs/openpgpjs#958]
Hi, I couldn't see on the documentation, but is there a way to find email from someone's public key ?

**Comment by tomholub** [comment]
Yes, look at `key.users`

**Comment by wisecat57** [comment]
> Yes, look at `key.users`
Can you send me an example ? I couldnt find it

**Comment by chesnokovilya** [comment]
You could look at tests, for example https://github.com/openpgpjs/openpgpjs/blob/master/test/general/key.js#L1750
