### ISSUE TITLE
\r\n addheader() not required

### ISSUE THREAD

**Issue by mr-smit** [openpgpjs/openpgpjs#960]
If you disable version and comments with:

window.openpgp.config.show_version = false;
window.openpgp.config.show_comment = false;

then function "addheader()" will return \r\n, which is not required anymore.

`function addheader(customComment) {
  let result = "";
  if (config.show_version) {
    result += "Version: " + config.versionstring + '\r\n';
  }
  if (config.show_comment) {
    result += "Comment: " + config.commentstring + '\r\n';
  }
  if (customComment) {
    result += "Comment: " + customComment + '\r\n';
  }
  result += '\r\n';   <-- here
  return result;
}`

Then all encrypted stuff looks like this:
-----BEGIN PGP MESSAGE-----

WPAa7EVtWWdzKQ+QvOjburKfnU6Do7YL8pNiI0ukBGjQst5FgKAnjMewQ1zd
zGiFSk7Qt0mQcAY8N08EjBTlRVfJgSZDODc7dGzshtkRXDtpwH1xqzZ9o4LK
qi2urFaxl8llHSxObQ6eFeAM+LdtGwJDQLvu6HbWmLcM4m8e3bpi3T68/XdL
0JhK8fu4ehLP9hguoqAYJHgj3gW4D97GvUvdm6KE5MU=
=qnej
-----END PGP MESSAGE-----

must look like this:

-----BEGIN PGP MESSAGE-----
WPAa7EVtWWdzKQ+QvOjburKfnU6Do7YL8pNiI0ukBGjQst5FgKAnjMewQ1zd
zGiFSk7Qt0mQcAY8N08EjBTlRVfJgSZDODc7dGzshtkRXDtpwH1xqzZ9o4LK
qi2urFaxl8llHSxObQ6eFeAM+LdtGwJDQLvu6HbWmLcM4m8e3bpi3T68/XdL
0JhK8fu4ehLP9hguoqAYJHgj3gW4D97GvUvdm6KE5MU=
=qnej
-----END PGP MESSAGE-----

**Comment by twiss** [comment]
The blank line is required. See https://tools.ietf.org/html/rfc4880#section-6.2.
