### ISSUE TITLE
Simplify `openpgp.key.readArmored`

### ISSUE THREAD

**Issue by twiss** [openpgpjs/openpgpjs#962]
My guess is that most uses of `openpgp.key.readArmored` are (or should be) something like:
```js
const { keys, err: [err] = [] } = await openpgp.key.readArmored(armor);
if (err) throw err;
```
So I propose that's what we make
```js
const keys = await openpgp.key.readArmored(armor);
```
do. (Probably most uses in fact use only the first key, which is fine, but it seems cleaner to stay symmetric with the `privateKeys` and `publicKeys` parameters of various other functions. The first key is only a `const [key]` away anyway.)

Then, if you do need multiple keys from a single armor, we could expose a function `readAll` that returns `Array<Promise>` instead of `Promise<Array>` (with `read = (armor) => Promise.all(readAll(armor))`).

Feedback welcome :)

**Comment by tomholub** [comment]
I assume you meant
```js
const key = await openpgp.key.readArmored(armor); // not `keys`
```
I agree that it would be more convenient to have it throw (reject) errors instead of returning them. But since you can always `const [key] = ...`, maybe it's not necessary to have a special function return just the first key?

So my proposal would be to just
```
const keys = await openpgp.key.readArmored(armor); // may throw
// or
const [key] = await openpgp.key.readArmored(armor); // may throw
```
Without another `readAll` function. Maybe this is what you meant - I'm not sure.

**Comment by twiss** [comment]
I did in fact mean that :) The only reason why you might want another function, and why the current API is even the way it is, is that you might have an armored key block with two keys, _one_ of which is broken, and you might want to still have access to the other key.

Or maybe nobody needs that, not sure, but that was the rationale.

**Comment by tomholub** [comment]
That's a fair rationale, actually. It's useful to be able to read all / skip errors.

Now the question is.. does having two methods, one simpler and one original, actually result in overall improvement in simplicity? (maybe)

But I have to admit, we do have a convenience method like that in our code, too.. (reading a single key).. so it's fair.

**Comment by twiss** [comment]
Done in #1047 / #1236.
