### ISSUE TITLE
Remove the Worker

### ISSUE THREAD

**Issue by twiss** [openpgpjs/openpgpjs#964]
It is better to have a worker in the application, than in a library, for a variety of reasons:
- Currently, an application that uses the worker has to load OpenPGP.js twice, once in the main thread and once in the worker. This is unnecessary and inefficient. (#839)
- Having the worker inside OpenPGP.js prevents tree shaking, since the worker script does not know in advance which functions of OpenPGP.js it will be asked to call. Having the application's workers script call OpenPGP.js directly makes that information known.
- Having only the application import OpenPGP.js (rather than having our worker script import it as well) would allow the application to use their own build process and treat OpenPGP.js as a normal ES6 module.
- Parsing and storing keys inside the worker (instead of in the main thread as is currently done) would allow us to cache certain information that we currently have to calculate in the worker each time the key is used. It would also avoid having to copy the key to the worker each time, and further offload work from the main thread while parsing.
- Similarly, the application could fetch keys and messages from their server directly inside the worker, further reducing copying. This is particularly useful when stream-decrypting a message.
- It would allow us to add callback hooks, or allow the application to monkey-patch functions in OpenPGP.js.

There are also some challenges:
- Obviously, application developers have to create this worker. Removing it from OpenPGP.js makes it more difficult for developers to get started with the library in the most efficient way possible. We could write some "getting started" example code that creates a worker.
- When stream-decrypting a message; OpenPGP.js currently passes the data to the main thread chunk by chunk. Applications might have to re-implement this, due to https://github.com/whatwg/streams/issues/276. Alternatively, applications could use OpenPGP.js inside a Service Worker; and rely on Response's streaming support to pass the data to the application (or a file).  
For stream-encrypting, the most common use case is probably encrypting a `File` object, which _can_ be passed using `postMessage`.

**Comment by tomholub** [comment]
Thanks for the writeup. Having OpenPGP.js come without a worker will be a loss, but.. I guess the benefits are worth it. Particularly ability to tree-shake and monkey-patch functionality would be super useful.. and possibly worth the hassle to have to implement our own worker.

I wonder if there could be another repo, like openpgp-worker-example, that would implement common functionality, and let people adapt it their way. That one should probably be under a more permissive license, eg MIT/Apache2/BSD, because that code would be expected to be actually incorporated into app devs' codebase.

**Comment by twiss** [comment]
Done in #1072 / #1047.
