### ISSUE TITLE
Rename `numBits` and `bits` to `rsaBits`

### ISSUE THREAD

**Issue by twiss** [openpgpjs/openpgpjs#969]
It would be nice to be consistent between `generateKey`'s `numBits` and `getAlgorithmInfo`'s `bits`. `numBits` is redundant with its type. `bits` is fine. `rsaBits` would indicate that it only applies to RSA keys, which is nice and makes it so that `openpgp.generateKey({ rsaBits: 4096 })` contains an explicit indication that RSA is being used.

We might want to do this in a backwards compatible way (not just so that we can perhaps do this before v5, but also so that `openpgp.generateKey({ numBits: 4096 })` doesn't silently start generating 2048-bit keys for people who don't read the release notes), e.g.

```js
export function generateKey({ userIds = [], passphrase = "", numBits = 2048, rsaBits = numBits, keyExpirationTime = 0, curve = "", date = new Date(), subkeys = [{}] }) {
```

(And `Key.prototype.addSubkey`, depending on how long we wait with this :) And maybe `key.generate` as well? E.g. @tomholub do you use the low-level API for this?)

**Comment by tomholub** [comment]
I'm happy to fix our use of the api to follow the new names if that helps consistency. Consistency is key :+1: thanks for checking!
