### ISSUE TITLE
Doesn't work with Angular 5 on Chrome 77.0.3865.90

### ISSUE THREAD

**Issue by thanapongp** [openpgpjs/openpgpjs#973]
Hi, it appears that this library doesn't work with Angular 5 on Chrome 77.0.3865.90 (JavaScript V8 7.7.299.11), because when I try to call `openpgp.key.readArmored(privateKey)`, it always throws this error:

```
Uncaught (in promise) TypeError: Method Promise.prototype.then called on incompatible receiver [object Object] 
at ZoneAwarePromise.then (<anonymous>)

Promise.then (async) 
pipe @openpgp.js:22949
transformPair @openpgp.js:23057
```

But, when I try calling the same code on the previous version of Chrome (69.0) and Firefox (69.0.1) everything works as expected.

**Comment by chesnokovilya** [comment]
Hello, could you create a gist with code that produce this error? Have you tried to run unit tests:
 `grunt browsertest`.
I have not detected any issues with chrome 77 during quick testing.

**Comment by chesnokovilya** [comment]
Issue in Angular repository https://github.com/angular/angular/issues/32802

**Comment by twiss** [comment]
As a workaround, you could try using the streams polyfill rather than the built-in version, by setting:

```js
window.TransformStream = undefined;
```

before loading openpgp.js.

**Comment by codesandnotes** [comment]
If after nullifying `window.TransformStream` one gets errors, remember to add a web streams polyfill afterwards; such as:
`<script src="https://unpkg.com/web-streams-polyfill/dist/polyfill.min.js"></script>`

For me that did the trick on a Ionic 3-based app (Angular 5.2.11) using openpgp.js

**Comment by chesnokovilya** [comment]
closed as fixed in Angular repository.
