### ISSUE TITLE
[QUESTION] Streaming large file into message

### ISSUE THREAD

**Issue by PhilippHomann** [openpgpjs/openpgpjs#981]
Hi there,

I'm trying to read an encrypted file into `Message` using `openpgp.message.read`:
```js
const encryptedData = fs.readFileSync("file.gpg")
let message = await openpgp.message.read(encryptedData)
// do something with message
```
Everything worked fine using this code until I had to decrypt a large file (> 2GB), which causes `readFileSync` to fail with ERR_FS_FILE_TOO_LARGE.
But when using fs.createReadStream and `read(encryptedData, true)` the message is not being parsed properly.

Could you give me any hint how to use `openpgp.message.read` in conjunction with large files from filesystem?
I want to work with the packets in side message, so I can't use decrypt as I don' want to decrypt the file.

Thanks!

**Comment by twiss** [comment]
Hi! You shouldn't have to pass `true` to message.read, have you tried it without? (Or pass 'node'.)

**Comment by PhilippHomann** [comment]
@twiss Worked with "node". Is this written down somewhere in the docs?
