### ISSUE TITLE
 Linking failure in asm.js: Unexpected stdlib member

### ISSUE THREAD

**Issue by batuhansozer** [openpgpjs/openpgpjs#985]
(node:8760) V8: /home/zelos/Desktop/Kedi/kedichat/chat/node_modules/openpgp/dist/openpgp.js:2491 Linking failure in asm.js: Unexpected stdlib member

I get this error every time I use openpgp

**Comment by chesnokovilya** [comment]
Hello, could you please include node version, openpgp version, and a way to replicate this bug? It does not happen on other systems.

**Comment by twiss** [comment]
From the error message, it sounds like this could happen if you're extending a built-in object (of the standard library) with a new function or property (member). Are you writing anything to `global`, or perhaps the `prototype` of a built-in function?

**Comment by twiss** [comment]
Let me know if you still have this issue.

**Comment by dan-turner** [comment]
I'm seeing this too

**Comment by twiss** [comment]
Hey @dan-turner :wave: Thanks! That looks perfectly normal.

I'm assuming you're using OpenPGP.js in a larger Node.js project, though? Could you run the same two `console.log` lines just before calling OpenPGP.js? One of your other dependencies might be messing with the built-in `Uint8Array`.

If you still get the same result, could you try to create a minimal reproducible example?

For what it's worth, openpgp works fine for me in that version of Node:

```
$ node
Welcome to Node.js v12.16.1.
Type ".help" for more information.
> const openpgp = require('openpgp')
undefined
> openpgp.encrypt({ message: openpgp.message.fromText('hi'), passwords: 'test' }).then(console.log, console.error)
Promise { <pending> }
> {
  data: '-----BEGIN PGP MESSAGE-----\r\n' +
    'Version: OpenPGP.js v4.10.1\r\n' +
    'Comment: https://openpgpjs.org\r\n' +
    '\r\n' +
    'wy4ECQMIGlkVb2cEWZ3gNg4uusRwkPb26fM5FahTT4HjJMQULb3s7woNnCZg\r\n' +
    'ALXd0joBbjdz0db3CFkiC7f5P5xdf4d9IFrBJy+OMbt9nXZxUFCgdn42T9Rx\r\n' +
    'phomGifIs4kMFmrQBwEaF9bJ\r\n' +
    '=B/0x\r\n' +
    '-----END PGP MESSAGE-----\r\n'
}
```

**Comment by subha-sfcu** [comment]
> From the error message, it sounds like this could happen if you're extending a built-in object (of the standard library) with a new function or property (member). Are you (or a package you're importing) writing anything to `global`, or perhaps the `prototype` of a built-in function?
> 
> In particular, the global object that's passed to the asm function at that line is `Uint8Array`. Could you run
> 
> ```js
> console.log(Uint8Array.toString());
> console.log(Object.getOwnPropertyDescriptors(Uint8Array.prototype));
> ```
> 
> and post the output here?

> console.log(Uint8Array.toString());
function Uint8Array() { [native code] }
undefined
> console.log(Object.getOwnPropertyDescriptors(Uint8Array.prototype));
{
  constructor: {
    value: [Function: Uint8Array],
    writable: true,
    enumerable: false,
    configurable: true
  },
  BYTES_PER_ELEMENT: { value: 1, writable: false, enumerable: false, configurable: false }
}
undefined
>

**Comment by nottoseethesun** [comment]
Getting this exact error (`node_modules/openpgp/dist/openpgp.js:2491 Linking failure in asm.js: Unexpected stdlib member`) as well; test given above works fine as expected (see below).   What are ideas as to how to fix, or is this an actual bug in this project, the NodeJS `openpgp`?

```bash
$ node --version
v14.11.0
```

```typescript
console.log(Uint8Array.toString());
console.log(Object.getOwnPropertyDescriptors(Uint8Array.prototype));
```
yields:

```
   function Uint8Array() { [native code] }

   {
      constructor: {
        value: [Function: Uint8Array],
        writable: true,
        enumerable: false,
        configurable: true
      },
      BYTES_PER_ELEMENT: { value: 1, writable: false, enumerable: false, configurable: false }
    }
```

Also the repl test works fine:

```
$ node
Welcome to Node.js v14.11.0.
Type ".help" for more information.
> const openpgp = require('openpgp');
undefined
> openpgp.encrypt({ message: openpgp.message.fromText('hi'), passwords: 'test' }).then(console.log, console.error);
Promise { <pending> }
> {
  data: '-----BEGIN PGP MESSAGE-----\r\n' +
    'Version: OpenPGP.js v4.10.4\r\n' +
    'Comment: https://openpgpjs.org\r\n' +
    '\r\n' +
    'wy4ECQMIVnCjm+2GQhLg0T2Cun09/wp284sd7bJ206ewRDtec0u0VCI7ayJD\r\n' +
    'xVi20joBRD8rFaQQvAtlJe2jeLnCUPq4AHAoLQV3/SNLzIOQRxtC2s9q9qIQ\r\n' +
    'JT/LCjIC/U/h0KJgxAAJ3YuT\r\n' +
    '=Dmhy\r\n' +
    '-----END PGP MESSAGE-----\r\n'
}


```

**Comment by twiss** [comment]
Hey :wave: If it works in the REPL but not in your application, then my best guess is that there's something about the environment you're running the application in that makes the globals different from the expected ones. E.g. just a wild guess but are you using Jest? The issue could be https://github.com/facebook/jest/issues/2549.

Alternatively, maybe there's another dependency of your application that's messing with the globals, or somehow interacting badly with OpenPGP.js?

**Comment by Janaka-Steph** [comment]
I tried using `https://www.npmjs.com/package/jest-environment-node-single-context` as suggested in facebook/jest#2549 but didn't work for me
