### ISSUE TITLE
Setup algorithm on signing for JWT generation 

### ISSUE THREAD

**Issue by yelichi** [openpgpjs/openpgpjs#986]
I want to use openpgp to generate a signature which is in a JWT. So can I setup a specific algorithm on a signature ?

**Comment by chesnokovilya** [comment]
Hello, this library does not support JWT standard, so probably it would be better to find another one with JWT support.

**Comment by twiss** [comment]
Here's one that seems promising, but I haven't looked at the code so I can't vouch for it: https://www.npmjs.com/package/webcrypto-jwt.
