### ISSUE TITLE
Is it possible to add a recipient without re-encrypting the entire message?

### ISSUE THREAD

**Issue by mailbee** [openpgpjs/openpgpjs#989]
My encrypted files can be quite big. And the list of recipients can change frequently for the same file.

I have no problems with adding/removing recipients from scratch, by re-encrypting the whole file. However, this is far from being efficient. I'm wondering if it's possible to just alter the header of the PGP message by adding a recipient (the session key encrypted with their public key) while reusing the same session key which was used to encrypt the file contents?

Ideally, I want to store an encrypted file as two files, actually. One is the header (which can change often, when recipients are added/deleted) and another one is just the encrypted contents itself (and this part never changes). Upon download, I'll send the contents of the header and then the encrypted file contents to the output stream.

This would spare me from a quite CPU-consuming (re-encryption) and disk I/O consuming (reading/writing file contents) task.

Is it possible with this library?

**Comment by bartbutler** [comment]
Short answer -- yes. Store the key packets separately from the data packets and use the encryptSessionKey() and decryptSessionKey() API to add or remove key packets as you see fit.

**Comment by mailbee** [comment]
Thanks! I will close the issue for now.
