### ISSUE TITLE
Streaming decryption support

### ISSUE THREAD

**Issue by nwtgck** [openpgpjs/openpgpjs#990]
Hi, developers. Thank you very much for your wonderful project!

I'd like to ask you whether streaming decryption is supported. I confirmed streaming-encryption is supported on browser. However, I could not do streaming decryption in the following script.

```js

// Plain data
let limit = 8000;
const plainStream = new ReadableStream({
    async pull(controller) {
    if (limit === 0) controller.close();
    const value = new Uint8Array([1, 2, 3]);
    controller.enqueue(value);
    // console.log(`plain: ${value}, limit: ${limit}`);
    console.log('plain');
    limit--;
    }
});


// Encrypt
const encrypted = await openpgp.encrypt({
    message: openpgp.message.fromBinary(plainStream),
    passwords: ['secret stuff'],
    armor: false,
    streaming: true,
});
const encryptedStream = encrypted.message.packets.write();


// Decrypt
const decrypted = await openpgp.decrypt({
    message: await openpgp.message.read(encryptedStream),
    passwords: ['secret stuff'],
    format: 'binary',
    armor: false,
    streaming: true,
});
console.log('after decrypted');
const decryptedStream = decrypted.data;
console.log(decryptedStream);

// Read
const reader = decryptedStream.getReader();
while(true) {
    const {done, value} = await reader.read();
    if (done) break;
    // console.log(`read: ${value}`);
    console.log('read');
}
```
(Online demo: <https://codepen.io/nwtgck/pen/KKKVmYz?editors=1011>)

In my expectation, console.log of "plain" and "read" are outputted alternately. However, actual output is many "plain"  are outputted and then some "read" are outputted.

**Comment by twiss** [comment]
Hi! Please see https://github.com/openpgpjs/openpgpjs/releases/tag/v4.0.0. It should explain why decrypted data arrives delayed, and what you could do to fix that.

**Comment by nwtgck** [comment]
@twiss Thank you very much!

Now I understand why the decryption is not streamed by default: the authentication data are attached at the end of data. And the problem was solved by two solutions: AEAD in draft-stage or allowing unauthenticated data. Thanks!

**Comment by twiss** [comment]
No problem, glad it helped!
