### ISSUE TITLE
How to import the build file

### ISSUE THREAD

**Issue by PauloPatoleia** [openpgpjs/openpgpjs#991]
Hi, i want to use openpgp in a Rhino environment therefore i dont have node, import / require etc. The only way i can use it is if i can call the js file and use it that way. Giving an example of how i did it with moment.js :

var momentjs = moment();

Is openpgp.js able to be called like this? Thanks

**Comment by twiss** [comment]
Hi :wave: The openpgp.js dist file tries to write `openpgp` to the global scope. So if you can run the file, `openpgp` should be available after that. If that doesn't work, you might have to define e.g. a `window` or `global` variable that points to the global scope. Good luck!
