### ISSUE TITLE
Testing: add ability to specify config options in node command line

### ISSUE THREAD

**Issue by chesnokovilya** [openpgpjs/openpgpjs#992]
We need to be able to modify config from node command line, without use of gruntfile, similiar to web browser testing  `http://localhost:3000/test/unittests.html?use_native=false`.

This would enable travis to run automatic testing for some important config options: use_native,  AEAD mode, elliptic.

**Comment by larabr** [comment]
Since we removed the option to disable native crypto in v5, and we implemented custom configuration, I don't think global flags are needed anymore -- we should aim to keep comprehensive test coverage instead.
