### ISSUE TITLE
Openpgp.message.fromBinary doesn't work with Nodejs.ReadableStream

### ISSUE THREAD

**Issue by descampsk** [openpgpjs/openpgpjs#994]
Hello,

I'm trying to encrypt a File in a browser in a streamable way.

I use a <input> HTML tag to retrieve a file from a user.

Then I create a NodeJS.ReadableStream from this file with the following code : 

```
import from2 from 'from2'
import toBuffer from 'typedarray-to-buffer'

export default function (file, options) {
    options = options || {}
    var offset = options.offset || 0
    var chunkSize = options.chunkSize || 1024 * 1024 // default 1MB chunk has tolerable perf on large files
    var fileReader = new FileReader(file)
    
    var from = from2(function (size, cb) {
        if (offset >= file.size) return cb(null, null)
        fileReader.onloadend = function loaded (event) {
        var data = event.target.result
        if (data instanceof ArrayBuffer) data = toBuffer(new Uint8Array(event.target.result))
        cb(null, data)
        }
        var end = offset + chunkSize
        var slice = file.slice(offset, end)
        fileReader.readAsArrayBuffer(slice)
        offset = end
    })
    
    from.name = file.name
    from.size = file.size
    from.type = file.type
    from.lastModified = file.lastModified
    
    fileReader.onerror = function (err) {
        from.destroy(err)
    }
    
    return from
}
```

It creates a NodeJS.ReadableStream and I pass it to the function openpgp.message.fromBinary like this: 

```
const encryptFile = async function (file, publicKeyReceiverList) {
  const fileStream = FileReaderStream(file)

  const publicKeyObjList = []
  for (const publicKey of publicKeyReceiverList) {
    const publicKeyObj = (await openpgp.key.readArmored(publicKey)).keys[0]
    publicKeyObjList.push(publicKeyObj)
  }

  const options = {
    message: openpgp.message.fromBinary(fileStream), // input as Message object
    publicKeys: publicKeyObjList, // for encryption
    // privateKeys: [privKeyObj], // for signing (optional)
    armor: false
  }
  const ciphertext = await openpgp.encrypt(options)
  return ciphertext.message.packets.write()
}
```

But I got the following error:

Error: Data must be in the form of a Uint8Array or Stream
    at Object.r.fromBinary

Do you know what i'm doing wrong ?
How can I encrypt files with openpgp ?
Nodejs.ReadableStream - https://nodejs.org/api/stream.html#stream_class_stream_readable is different thant ReadableStream - https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams ?

Thank you !

**Comment by twiss** [comment]
Hey :wave: Could you try the workaround described here: https://github.com/openpgpjs/openpgpjs/pull/824#issuecomment-451177117?
If that works, you probably have the same issue.

**Comment by descampsk** [comment]
Thanks for the advice but it doesn't work. I have the same issue.

I tried this : 

```
  const fileStream = FileReaderStream(file)
  // eslint-disable-next-line
  console.log(fileStream)
  
  const newStream  = fileStream.pipe(new stream.PassThrough())
  // eslint-disable-next-line
  console.log(newStream)

  const options = {
    message: openpgp.message.fromBinary(newStream), // input as Message object
    publicKeys: publicKeyObjList, // for encryption
    // privateKeys: [privKeyObj], // for signing (optional)
    armor: false
  }
  const ciphertext = await openpgp.encrypt(options)
  return ciphertext.message.packets.write()
```

What is strange, is that my first stream is already Readble: 

![image](https://user-images.githubusercontent.com/22590202/67205268-ae737600-f40f-11e9-9ed7-d368aa9c4a41.png)

**Comment by descampsk** [comment]
Ok i found the issue I think.

Openpgpjs use web-stream-tools and this library https://github.com/openpgpjs/web-stream-tools/blob/master/lib/util.js.

In this library, there is the function isStream to determine if the object is a stream or not. In my case, this function returns false.

Here is the implementation:

```
const isNode = typeof global.process === 'object' &&
  typeof global.process.versions === 'object';

const NodeReadableStream = isNode && require('stream').Readable;

/**
 * Check whether data is a Stream, and if so of which type
 * @param {Any} input  data to check
 * @returns {'web'|'node'|false}
 */
function isStream(input) {
  if (ReadableStream.prototype.isPrototypeOf(input)) {
    return 'web';
  }
  if (NodeReadableStream && NodeReadableStream.prototype.isPrototypeOf(input)) {
    return 'node';
  }
  return false;
} 
```

However, in my case, my object is a NodeReadableStream. And require('stream').Readable.prototype.isPrototypeOf(input) return true.

The issue is: with webpack I can use NodeReadableStream, but because i'm on a web application, openpgpjs has the NodeReadableStream  to false.

I'm pretty sur if we change the code to:

```
const isNode = typeof global.process === 'object' &&  typeof global.process.versions === 'object'
// eslint-disable-next-line
console.log('isNode', isNode)

const NodeReadableStream = stream.Readable

function isStream(input) {
  if (ReadableStream.prototype.isPrototypeOf(input)) {
    return 'web'
  }
  if (NodeReadableStream.prototype.isPrototypeOf(input)) {
    return 'node'
  }
  return false
}
```
It will work.

What do you think ?

**Comment by descampsk** [comment]
It seems to work when I change isStream to : 

```
function isStream(input) {
  if (ReadableStream.prototype.isPrototypeOf(input) || input.readable) {
    return 'web';
  }
  if (NodeReadableStream && NodeReadableStream.prototype.isPrototypeOf(input)) {
    return 'node';
  }
  return false;
}
```

**Comment by twiss** [comment]
Hey :wave: I see. If you're in a web app, it's probably better to use the Web ReadableStream instead of Node's Readable (to answer your original question, they're different, yeah). It's possible to create a Web Stream from a File, as well.

Alternatively, if you need to stick with Node streams for some reason, I would trick the code you quoted into thinking it's running in Node by defining an appropriate `global.process` - but that may have other side effects as well.

As for your proposed replacement, you're using a global `stream` - that doesn't exist on the web, and I believe it doesn't by default in Node either, when not in a repl, so I believe that wouldn't work.

**Comment by descampsk** [comment]
I looked for many hours how to create a Web Readable Stream from a File but I didn't found anything.

Could you help me or point me some resources ?

**Comment by twiss** [comment]
In Chrome, that functionality is now built-in: https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream.

For other browsers, you could try https://www.npmjs.com/package/from2-blob. I think I've seen others that are simpler but this one should work fine.

(The main imporant information to know that might help googling is that a File is also a Blob: https://developer.mozilla.org/en-US/docs/Web/API/File.)

**Comment by descampsk** [comment]
Thanks for your help. I will check your docs and post here my solution when found. Can maybe help some others people.

**Comment by twiss** [comment]
> I looked for many hours how to create a Web Readable Stream from a File but I didn't found anything.

In Chrome, that functionality is now built-in: https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream.

For other browsers, I can't immediately find a library although I thought I'd seen one. You could look at https://github.com/maxogden/filereader-stream/blob/master/index.js for inspiration for how to use a FileReader to read a File chunk by chunk, and then see https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream for how to create a ReadableStream from it.

(The main imporant information to know that might help googling is that a File is also a Blob: https://developer.mozilla.org/en-US/docs/Web/API/File.)

**Comment by descampsk** [comment]
Here is the first solution with the new resource you pointed me : Blob.stream() Thanks !

```
const encryptFile = async function (file, publicKeyObjList, progressJson) {
  const stream = file.stream()

  const options = {
    message: openpgp.message.fromBinary(stream), // input as Message object
    publicKeys: publicKeyObjList, // for encryption
    // privateKeys: [privKeyObj], // for signing (optional)
    armor: false
  }
  const ciphertext = await openpgp.encrypt(options)
  const encrypted = ciphertext.message.packets.write()
  // You can use the ReadableStream to pipe to do other things

  // Here I read the encrypted stream to create a encrypted File and sent it through https
  const reader = openpgp.stream.getReader(encrypted);
  let encryptedFileData = []
  while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (progressJson) {
        progressJson.loaded += value.length
      }
      encryptedFileData.push(value)
  }

  return new File(encryptedFileData, file.name, { type: file.type, lastModified: file.lastModified })
}
```

But it works only on Chrome.

I will test today some others solutions to make it work on all browsers

**Comment by descampsk** [comment]
Ok found it.

Here is my function to create a ReadableStream:

``` fileReadableStream.js
export default function (file, options) {
    options = options || {}
    let offset = options.offset || 0
    let chunkSize = options.chunkSize || 1024 * 1024 // default 1MB chunk has tolerable perf on large files
    let fileReader = new FileReader(file)

    let readableStream = new ReadableStream({
        start(controller) {
            fileReader.onload = () => {
                const data = new Uint8Array(fileReader.result)
                controller.enqueue(data)
                if (offset >= file.size) {
                    controller.close()
                } else {
                    let end = offset + chunkSize
                    let slice = file.slice(offset, end)
                    fileReader.readAsArrayBuffer(slice)
                    offset = end
                }
            }
            let slice = file.slice(0, chunkSize)
            fileReader.readAsArrayBuffer(slice)
            offset = chunkSize
        }
    })
    
    return readableStream
}
```

And then to encrypt the stream:

```
const encryptFile = async function (file, publicKeyReceiverList, progressJson) {
  const stream = fileReadableStream(file)

  const options = {
    message: openpgp.message.fromBinary(stream), // input as Message object
    publicKeys: publicKeyObjList, // for encryption
    // privateKeys: [privKeyObj], // for signing (optional)
    armor: false
  }
  const ciphertext = await openpgp.encrypt(options)
  const encrypted = ciphertext.message.packets.write()
  const reader = openpgp.stream.getReader(encrypted);
  let encryptedFileData = []
  while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (progressJson) {
        progressJson.loaded += value.length
      }
      encryptedFileData.push(value)
  }

  return new File(encryptedFileData, file.name, { type: file.type, lastModified: file.lastModified })
}
```

Thanks @twiss for your help !

**Comment by drzraf** [comment]
I'm adding here that we now have some Stream support in browsers and that a `ReadableStream` can be fetched in a `Response`, but by no way can we **send** a Steam as part of a **Request** (`fetch/POST`) what makes *upload* of heavy encrypted payloads impossible (at least, using `fetch`)
- https://github.com/whatwg/fetch/pull/425 
- https://www.chromestatus.com/feature/5274139738767360 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1469359

**Comment by drzraf** [comment]
More specifically on that topic, once I `<script src="openpgp@4.10.4/dist/openpgp.min.js"></script>`, then:
`ReadableStream.prototype.isPrototypeOf(new File([1,2], "foo").stream())` == **false**
(probably because of `web-streams-polyfill`)
The consequence is that `web-stream-tools` `utils.isStream()` fails (the above `isPrototypeOf` test) if I try to `message.fromBinary()` a native `File`'s `stream()` (eg: from `<input type="file">`.

= The ReadableStream polyfill bundled by openpgp.js keeps the ReadableStream-tester library from succeeding.
I don't know how complete is `File.stream()` on Firefox 76, but that's prone to confusion.

**Comment by twiss** [comment]
>  `ReadableStream.prototype.isPrototypeOf(new File([1,2], "foo").stream())` == **false**

Interesting. I guess this means `stream()` is using `global.ReadableStream` instead of the native `ReadableStream`.

>  (probably because of `web-streams-polyfill`)

Yeah. We're indeed overwriting `global.ReadableStream`. This is however fixed in the v5 branch, where we use web-streams-po**n**yfill instead.

It should be installable from GitHub if you do:

```
    "openpgp": "github:twiss/openpgpjs#90d83ffaea110e4eefb76f91e237bbfc4d43d15b",
```

There are however API changes in v5 as well, documented here: https://github.com/openpgpjs/openpgpjs/wiki/V5-Changelog.
There will probably be further API changes before we release v5, but if you wish, you could try it already.
