### ISSUE TITLE
Own Webworker and encryption: No secure Random number generator available

### ISSUE THREAD

**Issue by descampsk** [openpgpjs/openpgpjs#996]
Hello,

Thanks the advice of @twiss, I tried to use my own WebWorker with openpgp.
At the moment, it works well with String decryption but didn't work with string encryption.

Here is the simplified code I use : 

Here is the code in the main thread:

```
import PgpWorker from './pgp.worker.js'
const sendMessage = async function (message) {
  return new Promise((resolve, reject) => {
    let sharedPgpWorker = new SharedWorker((fn=>fn.match(/"(.*?)"/)[1])(""+PgpWorker))
    sharedPgpWorker.onerror = function(event) {
      reject(event)
    }
    sharedPgpWorker.port.onmessage = function (event) {
      if (event.data.err) {
        reject(event.data.err)
      } else {
        resolve(event.data)
      }
    }
    sharedPgpWorker.port.postMessage(message)
  }) 
}
const encryptMessageAndSign = async function (publicKeyReceiverList, message) {
  const workerMessage = {
    method: 'encryptMessageAndSign',
    arguments: {
      publicKeyReceiverList: publicKeyReceiverList,
      message: message
    }
  }
  return sendMessage(workerMessage)
}
```

Here is the worker code: 

```
import * as openpgp from 'openpgp'
const encryptMessageAndSign = async function (publicKeyReceiverList, message) {
  const publicKeyObjList = []
  for (const publicKey of publicKeyReceiverList) {
    const publicKeyObj = (await openpgp.key.readArmored(publicKey)).keys[0]
    publicKeyObjList.push(publicKeyObj)
  }
  const options = {
    message: openpgp.message.fromText(message), // input as Message object
    publicKeys: publicKeyObjList, // for encryption
    privateKeys: [pgpData.decryptedPrivateKey] // for signing (optional)
  }
  const cypertext = await openpgp.encrypt(options)
  return cypertext.data
}

self.onconnect = async function(event) {
  var port = event.ports[0]

  port.onmessage = async function (event) {
    try {
      const method = event.data.method
      switch (method) {
        case 'encryptMessageAndSign': {
          const { publicKeyReceiverList, message } = event.data.arguments
          const encryptedMessage = await encryptMessageAndSign(publicKeyReceiverList, message)
          port.postMessage(encryptedMessage)
          break
        }
        default: {
          throw new Error(`This method ${method} is unknow by the worker.`)
        }
      }
    } catch (err) {
      port.postMessage({ err: err })
    }
  }
}
```

And the error is: 
![image](https://user-images.githubusercontent.com/22590202/67391553-389e1480-f59f-11e9-87f2-02a6915c87d3.png)

Do you have an idea ?

**Comment by twiss** [comment]
Hey :wave: Probably the issue is that OpenPGP.js is trying to look at `window.crypto.getRandomValues`:

https://github.com/openpgpjs/openpgpjs/blob/c7a65ccd163d7bd640a53b5fad423ceb1e8ada4c/src/crypto/random.js#L42-L43

Whereas in a worker, `window` is not available.

Probably this should be replaced by simply:

```js
if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
  crypto.getRandomValues(buf);
```

There are probably other places in the codebase that have the same issue. If you'd like to send a pull request fixing these, that would be very welcome.

**Comment by descampsk** [comment]
Ok i tried and it works. I will open a pull request.

**Comment by descampsk** [comment]
@twiss How can i do a pull request ? ^^'

remote: Permission to openpgpjs/openpgpjs.git denied to descampsk. when i try to push on a new branch.

**Comment by twiss** [comment]
You can make a fork, in the top right corner, then push to that, and then make a pull request :)

See https://help.github.com/en/github/getting-started-with-github/fork-a-repo and https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.
